#!/usr/bin/env python3
import json

at03_answers = {
    1: 'C', 2: 'B', 3: 'D', 4: 'D', 5: 'C', 6: 'C', 7: 'D', 8: 'D', 9: 'C', 10: 'D',
    11: 'A', 12: 'A', 13: 'D', 14: 'C', 15: 'A', 16: 'E', 17: 'A', 18: 'A', 19: 'A', 20: 'C',
    21: 'C', 22: 'D', 23: 'D', 24: 'D', 25: 'A', 26: 'D', 27: 'D', 28: 'C', 29: 'C', 30: 'C',
    31: 'A', 32: 'A', 33: 'A', 34: 'D', 35: 'C', 36: 'C', 37: 'D', 38: 'A', 39: 'A', 40: 'C',
    41: 'A', 42: 'C', 43: 'C', 44: 'B', 45: 'B', 46: 'A', 47: 'B', 48: 'D', 49: 'C', 50: 'C',
    51: 'B', 52: 'B', 53: 'C', 54: 'A', 55: 'B', 56: 'D', 57: 'B', 58: 'C', 59: 'B', 60: 'D',
    61: 'A', 62: 'C', 63: 'A', 64: 'C', 65: 'B'
}

at03_explanations = {
    1: "Auditing standards are the minimum standards of auditor's performance that must be achieved on each audit engagement. Failure to meet these standards means the auditor is negligent.",
    2: "The term 'should' equates to 'compliance'. Hence, the auditor must with the requirements unless the auditor demonstrates and documents that alternative actions that were sufficient to achieve the objectives of the standards.",
    4: "Audits do not provide absolute assurance, only reasonable assurance.",
    5: "Reasonable care is the highest level of professional care an auditor can provide.",
    6: "GAAS are the guidance for measuring the quality of the auditor's performance.",
    8: "An audit is connected with reasonable assurance, errors in judgement can be waived provided the audit was conducted in compliance to the PSAs.",
    13: "Choice D pertains to independence.",
    15: "Standards of field work are the standards or criteria for planning and evidence-gathering (PIE): 1. Planning and proper supervision, 2. Internal control consideration, 3. Evidence should be sufficient and appropriate. Choice A pertains to general standards, not standards of fieldwork.",
    16: "Standards of reporting are the standards on auditor's expression of audit opinion (SHOW): 1. Standards in accordance with GAAP/PFRS, 2. Historical and consistent application of GAAP/PFRS, 3. Opinion regarding the financial statements taken as a whole, 4. While also having adequate disclosure of information.",
    18: "PSAs are intended to clarify the meaning of 'generally accepted auditing standards.'",
    24: "Risks cannot be eliminated in any circumstances. It can only be reduced.",
    26: "Applying PSQM means that the firm adheres to the components of quality management, compliance to the PSQM means that the firm would comply with reasonable assurance that the necessary requirements of the standard to conduct the audit in accordance to professional standards.",
    27: "Noncompliance with the PSAs is acceptable provided that the departure is immaterial or explained, and in all cases documented in the audit working paper.",
    30: "Requirement of the code of ethics is that Auditors must be objective, this means that the auditor must be independent in both Mind and Appearance.",
    31: "The SQM has eight components: 1. Risk assessment process, 2. Governance and leadership, 3. Relevant ethical requirements, including independence, 4. Acceptance and continuance of engagements, 5. Engagement performance, 6. Resources, 7. Information and communication, 8. Monitoring and remediation process.",
    36: "To maintain proper quality of the performance of the audit, audit firms are expected to provide training to their employees and staff that conduct the audit.",
    37: "The financial and operational priorities of the firm do not lead to inappropriate judgments about whether to accept or continue a client relationship.",
    41: "A declaration of independence by every auditor in the firm is required at least annually to provide reasonable assurance that individuals that are part of the audit team is independent from the client they are assigned to.",
    52: "The human resource department is part of the PSQM, and that one of their main objective is to assign individuals in the Engagement team to clients that do not pose a threat to their independence as well as being competent in conducting the audit.",
    55: "Choice A is incorrect because seniors should not primarily focus on advising throughout the engagement. Choice C is incorrect because academic-related matters are the minimum requirement for the competence of the staff. Choice D is incorrect because it pertains to accepting or rejecting the client.",
    57: "The level of competence of the audit assistant dictates the necessity to supervise the audit assistant.",
    59: "The signature of the engagement partner is affixed in the audit report, and that he/she must maintain the overall quality of the particular engagement, he/she also must adhere to the requirements of the quality standards.",
    60: "Choice D pertains to consultation.",
    65: "If the person being appointed as an engagement quality reviewer is an engagement partner, a cooling-off period of at least two (2) years is required before the engagement partner can assume the role of engagement quality reviewer."
}

at03_raw = [
    (1, "Generally Accepted Auditing Standards (GAAS)", "In the auditing environment, failure to meet auditing standards is often:",
     [("A", "An accepted practice."), ("B", "A suggestion of negligence."), ("C", "Conclusive evidence of negligence."), ("D", "Tantamount to criminal behavior.")]),
    (2, "Generally Accepted Auditing Standards (GAAS)", "When a statement of an auditing standard uses the word \"should\" relating to a requirement, it means that the auditor:",
     [("A", "Must fulfill the responsibilities under all circumstances."), ("B", "Must comply with requirements unless the auditor demonstrates and documents that alternative actions that were sufficient to achieve the objectives of the standards."), ("C", "Should consider whether to follow the advice based on the exercise of professional judgment in the circumstances."), ("D", "May choose to change responsibilities relating to various professional standards that remain under consideration.")]),
    (3, "Generally Accepted Auditing Standards (GAAS)", "Audit standards require an auditor to:",
     [("A", "Issue an unmodified opinion only when the auditor is satisfied that no instances of fraud have occurred."), ("B", "Design the audit program to meet financial statement user's expectations concerning fraud."), ("C", "Perform procedures that are designed to detect all instances of fraud."), ("D", "Provide reasonable assurance that the financial statements are not materially misstated.")]),
    (4, "Generally Accepted Auditing Standards (GAAS)", "An audit performed in accordance with generally accepted auditing standards generally should:",
     [("A", "Be expected to provide absolute assurance that illegal acts will be detected where internal control is effective."), ("B", "Be relied upon to disclose violations of truth in lending laws."), ("C", "Encompass a plan to actively search for all illegalities which relate to operating aspects."), ("D", "Not be relied upon to provide absolute assurance that all illegal acts will be detected.")]),
    (5, "Generally Accepted Auditing Standards (GAAS)", "While performing audit services for their clients, professional accountants have a duty to provide a level of care which is:",
     [("A", "Greater than average"), ("B", "Guaranteed to be free from error."), ("C", "Reasonable"), ("D", "Superior")]),
    (6, "Generally Accepted Auditing Standards (GAAS)", "Which of the following best describes what is meant by generally accepted auditing standards (GAAS)?",
     [("A", "Audit objectives generally determined on audit engagements."), ("B", "Acts to be performed by the auditor."), ("C", "Measures of the quality of the auditor's performance."), ("D", "Procedures to be used to gather evidence to support financial statements.")]),
    (7, "Generally Accepted Auditing Standards (GAAS)", "The GAAS require that the CPAs:",
     [("A", "Assume responsibility for any losses to the client from fraud which existed during the audit but was not detected by the auditors."), ("B", "Follow accounting principles adopted by the SEC."), ("C", "Not accept as audit clients' companies which compete directly with one another."), ("D", "Exercise due professional care in the performance of the examination and the preparation of the report.")]),
    (8, "Generally Accepted Auditing Standards (GAAS)", "Which of the following is not a requirement of the generally accepted auditing standard which states that due professional care is to be exercised in the performance of the audit?",
     [("A", "Observance of the standards of field work and reporting."), ("B", "Critical review of the audit work performed at every level of supervision."), ("C", "Degree of skill commonly possessed by others in the profession."), ("D", "Responsibility for losses because of errors of judgment.")]),
    (9, "Generally Accepted Auditing Standards (GAAS)", "The general standards of the generally accepted auditing standards (GAAS) include a requirement that:",
     [("A", "The fieldwork to be adequately planned."), ("B", "The auditor to obtain sufficient, competent evidential matter."), ("C", "Due professional care be exercised by the auditor."), ("D", "The auditor's report to state whether the financial statements are presented in conformity with PFRS.")]),
    (10, "Generally Accepted Auditing Standards (GAAS)", "The standard of due professional care requires the auditor to:",
     [("A", "Make perfect judgment decisions in all cases."), ("B", "Ensure that the financial statements are free from error."), ("C", "Possess skills clearly above the average for the profession."), ("D", "Apply judgment in a conscientious manner, carefully weighing the relevant factors before reaching a decision.")]),
    (11, "Generally Accepted Auditing Standards (GAAS)", "Requirements for training, independence and professional care are included in which group of the generally accepted auditing standards (GAAS)?",
     [("A", "General"), ("B", "Fieldwork"), ("C", "Reporting"), ("D", "Quality management")]),
    (12, "Generally Accepted Auditing Standards (GAAS)", "What is the general character of the generally accepted auditing standards classified as general standards?",
     [("A", "Criteria for competence, independence, and professional care of individuals performing the audit."), ("B", "The requirements for the planning of the audit and supervision of assistants, if any."), ("C", "Criteria of evidence gathering."), ("D", "Criteria for the content of the auditors' report on financial statements and related footnote disclosures.")]),
    (13, "Generally Accepted Auditing Standards (GAAS)", "Under GAAS, which of the following reflects a concept from general group?",
     [("A", "The confirmation of accounts receivable."), ("B", "Completing an internal control questionnaire."), ("C", "The initial planning of the audit with the audit partner, manager, senior, staff and client personnel."), ("D", "The assignment of audit personnel to an engagement where they have no financial interest.")]),
    (14, "Generally Accepted Auditing Standards (GAAS)", "What is the general character of the generally accepted auditing standards classified as standards of field work?",
     [("A", "The competence of persons performing the audit."), ("B", "Criteria for the content of the auditor's report on financial statements and related footnote disclosures."), ("C", "The criteria of audit planning and evidence-gathering."), ("D", "The need to maintain an independence in mental attitude in all matters relating to the audit.")]),
    (15, "Generally Accepted Auditing Standards (GAAS)", "Which of the following does not pertain to the standards of fieldwork?",
     [("A", "Technical training and proficiency."), ("B", "Adequate planning and supervision."), ("C", "Proper study and evaluation of internal control as a basis for reliance thereon."), ("D", "Obtaining sufficient competent evidential matter.")]),
    (16, "Generally Accepted Auditing Standards (GAAS)", "The generally accepted standards of reporting in auditing refer to:\nA. Whether financial statements are presented in conformity with GAAP.\nB. Whether accounting principles have been consistently observed.\nC. Adequacy of disclosures.\nD. An expression of opinion on the financial statements taken as a whole.\nE. All of these.",
     [("A", "A only"), ("B", "B only"), ("C", "C only"), ("D", "D only"), ("E", "All of these.")]),
    (17, "Generally Accepted Auditing Standards (GAAS)", "The generally accepted standards of reporting encompass all of the following except:",
     [("A", "Consideration of an entity's internal control."), ("B", "Consistent application of accounting principles."), ("C", "Informative disclosures."), ("D", "Conformity of financial statements with GAAP.")]),
    (18, "Philippine Standards on Auditing (PSA)", "The Philippine Standards on Auditing (PSAs) issued by the Auditing and Assurance Standards Council (AASC) are:",
     [("A", "interpretations of generally accepted auditing standards."), ("B", "interpretations of generally accepted accounting principles."), ("C", "the criteria used in evaluating the fair presentation of the financial statements."), ("D", "optional guidelines which an auditor may choose to follow or not follow when conducting an audit.")]),
    (19, "Philippine Standards on Auditing (PSA)", "Which of the following is responsible for establishing auditing standards that will become generally accepted in the Philippines?",
     [("A", "Auditing and Assurance Standards Council."), ("B", "Commission on Audit."), ("C", "Financial and Sustainability Reporting Standards Council."), ("D", "Securities and Exchange Commission.")]),
    (20, "Philippine Standards on Auditing (PSA)", "Which of the following best describes the functions of Auditing and Assurance Standards Council (AASC)?",
     [("A", "To establish and promulgate generally accepted accounting principles in the Philippines."), ("B", "To investigate violations of the Philippine Accountancy Law."), ("C", "To promulgate auditing standards, practices, and procedures that shall be generally accepted by the accounting profession in the Philippines."), ("D", "To determine the minimum requirements for admission in the accounting profession.")]),
    (21, "Philippine Standards on Auditing (PSA)", "The Philippine Standards on Auditing (PSA) can be described as:",
     [("A", "Providing very specific guidance about the specific activities an auditor must perform on each engagement."), ("B", "Similar to Philippine Financial Reporting Standards (PFRS)."), ("C", "Defining the minimum standards of performance for an auditor."), ("D", "Providing assurance that an auditor will not issue an inappropriate audit opinion.")]),
    (22, "Philippine Standards on Auditing (PSA)", "According to Philippine Standards on Auditing (PSA); because there are inherent limitations in an audit that affect the auditor's ability to detect material misstatements, the auditor is:",
     [("A", "A guarantor but not an insurer of the statements."), ("B", "An insurer but not a guarantor of the statements."), ("C", "Both a guarantor and an insurer of the financial statements."), ("D", "Neither a guarantor nor an insurer of financial statements.")]),
    (23, "Philippine Standards on Auditing (PSA)", "An auditor need not abide with a specific requirement of PSA if the auditor believes that:",
     [("A", "The amount is insignificant or immaterial."), ("B", "The requirement of the PSA is impractical to perform."), ("C", "The requirement of the PSA is impossible to perform."), ("D", "Any of the given three choices is correct.")]),
    (24, "Philippine Standards on Auditing (PSA)", "The risk that an auditor will fail to uncover a material misstatement is eliminated:",
     [("A", "If client has good internal control."), ("B", "If auditor observes the Code of Professional Ethics."), ("C", "When the auditor complies with PSA."), ("D", "Under no circumstances.")]),
    (25, "Philippine Standards on Auditing (PSA)", "The auditor's best defense when material misstatements are not uncovered is to have conducted the audit:",
     [("A", "In accordance with PSA."), ("B", "As effectively as reasonably possible."), ("C", "In a timely manner."), ("D", "Only after an adequate investigation of the management team.")]),
    (26, "System of Quality Management (SQM)", "A firm of independent auditors must establish and follow quality management policies and procedures because these standards:",
     [("A", "Are necessary to meet increasing requirements of auditors' liability as insurers."), ("B", "Are required by the SEC for auditors of all firms."), ("C", "Include formal filing of records of such policies and procedures to a regulatory agency."), ("D", "Give reasonable assurance that the firm as a whole will comply with professional standards.")]),
    (27, "System of Quality Management (SQM)", "The main purpose of implementing a system of quality management is to provide the firm with reasonable assurance that: (Choose the incorrect statement)",
     [("A", "The firm and its personnel will comply with PSA, Ethical and legal requirements to enable the firm to issue an appropriate report."), ("B", "The audit will be performed in accordance with the requirements PSA."), ("C", "The firm will issue a report that is appropriate in the circumstances."), ("D", "All of the PSA standards would be complied with no exception.")]),
    (28, "System of Quality Management (SQM)", "Which of the following is not an essential component of quality management?",
     [("A", "Policies to ensure that personnel maintain their independence in fact and in appearance."), ("B", "Policies that ensure that monitoring activities are effectively applied."), ("C", "Policies and procedures to ensure that firm personnel are actively engaged in marketing strategies."), ("D", "Policies and procedures to ensure that the work performed by firm personnel meet applicable professional standards.")]),
    (29, "System of Quality Management (SQM)", "Which of the following is an element of a CPA firm's quality management system that should be considered in establishing its quality control policies and procedures?",
     [("A", "Complying with laws and regulations."), ("B", "Using statistical sampling techniques."), ("C", "Independence."), ("D", "Consideration of audit risk and materiality.")]),
    (30, "System of Quality Management (SQM)", "To comply relevant ethical standards in conducting a quality audit, the auditor must:",
     [("A", "have already accumulated at least five years of audit experience."), ("B", "use statistical sampling techniques."), ("C", "be independent."), ("D", "Always consider audit risk and materiality.")]),
    (31, "System of Quality Management (SQM)", "Elements of a CPA firm's quality management that should be considered in establishing its quality management policies and procedures must include:\nMonitoring and Remediation | Ethical Requirements | Engagement Performance\nA. Yes | Yes | Yes\nB. Yes | Yes | No\nC. Yes | No | Yes\nD. No | Yes | Yes",
     [("A", "Yes, Yes, Yes"), ("B", "Yes, Yes, No"), ("C", "Yes, No, Yes"), ("D", "No, Yes, Yes")]),
    (32, "System of Quality Management (SQM)", "Which of the following is not an element of quality management?",
     [("A", "Documentation."), ("B", "Engagement performance."), ("C", "Information and communication."), ("D", "Relevant ethical requirements.")]),
    (33, "System of Quality Management (SQM)", "The objective of the quality management policies to be adopted by an audit firm will ordinarily incorporate all of the following except:",
     [("A", "Risk and return process"), ("B", "Governance and leadership"), ("C", "Engagement performance"), ("D", "Human resources")]),
    (34, "System of Quality Management (SQM)", "The engagement partner should be satisfied that appropriate procedures regarding the acceptance and continuance of client relationships and specific audit engagements have been followed, and that conclusions reached in this regard are appropriate and have been documented. Acceptance and continuance of client relationships and specific audit engagements include considering:\nI. The integrity of the principal owners, key management, and those charged with governance of the entity.\nII. Whether the engagement team is competent to perform the audit engagement and has the necessary time and resources.\nIII. Whether the firm and the engagement team can comply with ethical requirements.",
     [("A", "I only"), ("B", "I and II only"), ("C", "II and III only"), ("D", "I, II, and III")]),
    (35, "System of Quality Management (SQM)", "The primary purpose of establishing quality management policies and procedures for deciding whether to accept a new client is to:",
     [("A", "Enable the CPA firm to attest to the integrity of the client management."), ("B", "Satisfy the CPA firm's duty to the public concerning the acceptance of new clients."), ("C", "Minimize the likelihood of association with clients whose management lacks integrity."), ("D", "Anticipate before performing any field work whether an unmodified opinion can be expressed.")]),
    (36, "System of Quality Management (SQM)", "Within the context of quality management, the primary purpose of continuing professional education and training activities is to enable a CPA firm to provide its personnel with:",
     [("A", "Technical training that assures proficiency as a valuation expert."), ("B", "Professional education that is required in order to perform with due professional care."), ("C", "Knowledge required to fulfill assigned responsibilities."), ("D", "Knowledge required to perform a peer review.")]),
    (37, "System of Quality Management (SQM)", "Which of the following quality management objectives would be least important to the auditor?",
     [("A", "Independence."), ("B", "Acceptance and continuance of audit engagements."), ("C", "Engagement performance."), ("D", "Determination of audit fee.")]),
    (38, "System of Quality Management (SQM)", "A quality management policy that requires personnel in the firm to adhere to independence, integrity, objectivity, confidentiality and professional behavior, relates to:",
     [("A", "Ethical requirements"), ("B", "Governance and leadership"), ("C", "Information and communication"), ("D", "Monitoring and remediation")]),
    (39, "System of Quality Management (SQM)", "In pursuing a firm's quality management objectives, a firm should adopt policies and procedures to enable it to identify and evaluate circumstances and relationships that create threats to independence, and to take appropriate action to eliminate those threats or reduce them to an acceptable level by applying safeguards, or, if considered appropriate, to withdraw from the engagement. Which quality management element would this be most likely to satisfy?",
     [("A", "Ethical requirements"), ("B", "Monitoring"), ("C", "Resources"), ("D", "Governance and leadership")]),
    (40, "System of Quality Management (SQM)", "In pursuing a CPA firm's quality management objectives, a CPA firm may maintain records indicated which partners or employees of the CPA firm were previously employed by the CPA firm's clients. Which quality control element would this be most likely to satisfy?",
     [("A", "Monitoring"), ("B", "Assignment"), ("C", "Independence"), ("D", "Skills and competence")]),
    (41, "System of Quality Management (SQM)", "The firm shall obtain written confirmation of compliance with its policies and procedures on independence from all firm personnel required to be independent by relevant ethical requirements:",
     [("A", "At least annually."), ("B", "At least monthly."), ("C", "At least semi-annually."), ("D", "At the completion of each engagement.")]),
    (42, "System of Quality Management (SQM)", "Which of the following quality management procedures relates to engagement performance?",
     [("A", "Advancement"), ("B", "Hiring"), ("C", "Direction"), ("D", "Professional development")]),
    (43, "System of Quality Management (SQM)", "In connection with the element of engagement performance, a CPA firm's system of quality management should ordinarily provide that all personnel:",
     [("A", "Have the knowledge required to enable them to fulfill responsibilities assigned."), ("B", "Review and test compliance with the firm's quality control policies and procedures."), ("C", "Seek assistance from persons having appropriate levels of knowledge, judgment, and authority."), ("D", "Appropriately maintain independence when providing assurance services.")]),
    (44, "System of Quality Management (SQM)", "Which of the following is a policy that must be established to comply with the quality management engagement performance?",
     [("A", "The firm is to be staffed by personnel who have attained and maintained the technical standards and professional competence required to enable them to fulfill their responsibilities."), ("B", "There is a sufficient direction, supervision, and review of work performed at all levels to provide reasonable assurance that the work performed meets appropriate standards of quality."), ("C", "The firm should assign responsibility for each engagement to an engagement partner."), ("D", "The continued adequacy and operational effectiveness of quality control policies and procedures are to be observed.")]),
    (45, "System of Quality Management (SQM)", "This quality management element requires a firm to establish policies and procedures to provide it with reasonable assurance that engagements are performed in accordance with professional standards and regulatory and legal requirements, and that the firm or the engagement partner issue reports that are appropriate in the circumstances.",
     [("A", "Ethical requirements"), ("B", "Engagement performance"), ("C", "Monitoring"), ("D", "Human resources")]),
    (46, "System of Quality Management (SQM)", "Which of the following is one of the elements of a CPA firm's quality management system?",
     [("A", "Governance and leadership"), ("B", "Computer assisted audit techniques."), ("C", "Control activities."), ("D", "Control environment.")]),
    (47, "System of Quality Management (SQM)", "Which of the following quality control elements is most closely associated with the requirement to promote a culture of quality?",
     [("A", "Monitoring and remediation"), ("B", "Governance and leadership"), ("C", "Engagement performance"), ("D", "Information and communication")]),
    (48, "System of Quality Management (SQM)", "The firm should establish policies and procedures designed to promote an internal culture with the commitment to competence based on the recognition that quality is essential in performing engagements. Such policies and procedures should require the firm's chief executive officer (or equivalent) or, if appropriate, the firm's managing board of partners (or equivalent), to assume ultimate responsibility for the firm's system of quality control.",
     [("A", "Ethical requirements"), ("B", "Monitoring"), ("C", "Human resources"), ("D", "Leadership and governance")]),
    (49, "System of Quality Management (SQM)", "In connection with the element of resources, a CPA firm's system of quality management should ordinarily establish procedures that:",
     [("A", "Provide adequate supervision at all levels, considering the training, ability and experience of the personnel assigned."), ("B", "Encourage personnel to use authoritative sources on complex or unusual matter."), ("C", "Require preparation of time budgets to properly schedule the audit work."), ("D", "Establish qualifications deemed necessary for various levels of responsibility within the firm.")]),
    (50, "System of Quality Management (SQM)", "Which element of a system of quality management is addressed by the establishment of policies and procedures designed to provide the firm with reasonable assurance that it has sufficient personnel with the competence, capabilities, proper training and commitment to ethical principles?",
     [("A", "Monitoring and remediation."), ("B", "Governance and leadership."), ("C", "Human resources."), ("D", "Engagement performance.")]),
    (51, "System of Quality Management (SQM)", "In compliance with the element of human resources, the firm should address issues relating to:",
     [("A", "Engagement performance"), ("B", "Assignment of engagement teams"), ("C", "Governance"), ("D", "Differences of opinion")]),
    (52, "System of Quality Management (SQM)", "In compliance with the element of resources, the firm should address issues relating to:",
     [("A", "Engagement performance"), ("B", "Assignment of engagement teams"), ("C", "Consultation"), ("D", "Difference of opinion")]),
    (53, "System of Quality Management (SQM)", "The statement, \"Quality management policies and procedures should be relevant, adequate, effective, and complied with\" is most closely associated with what element of quality management?",
     [("A", "Engagement performance"), ("B", "Governance and leadership"), ("C", "Monitoring"), ("D", "Relevant ethical requirements")]),
    (54, "System of Quality Management (SQM)", "This PSQM element is concerned with providing reasonable assurance that policies and procedures related to the other elements are suitably designed and being effectively implemented by the firm.",
     [("A", "Monitoring"), ("B", "Engagement performance"), ("C", "Human resources"), ("D", "Ethical requirements")]),
    (55, "System of Quality Management (SQM)", "In pursuing the firm's quality management objectives with respect to assigning personnel to engagements, the auditors may use policies and procedures such as:",
     [("A", "Designating senior qualified personnel to provide advice on accounting or auditing questions throughout the engagement."), ("B", "Requiring timely identification of the staffing requirements of specific engagements so that enough qualified personnel can be made available."), ("C", "Establishing at entry levels a policy for recruiting that include minimum standards of academic preparation and accomplishments."), ("D", "Evaluate clients upon occurrence of specified events to determine whether the relationships ought to be continued.")]),
    (56, "System of Quality Management (SQM)", "The work performed by the assistants should be reviewed by personnel of at least equal competence to consider all of the following except:",
     [("A", "Whether the conclusions expresses are consistent with the results of the work performed."), ("B", "Whether the work was adequately performed and documented."), ("C", "Whether the objectives of the audit have been achieved."), ("D", "Whether the engagement personnel maintained independence.")]),
    (57, "System of Quality Management (SQM)", "The primary factor that should be considered in determining the extent of supervision needed by an assistant is the assistant's:",
     [("A", "Willingness to exercise due care."), ("B", "Competence."), ("C", "Professional certification."), ("D", "Independence.")]),
    (58, "System of Quality Management (SQM)", "In connection with the element of monitoring, a CPA firm's system of quality management should ordinarily provide for the maintenance of:",
     [("A", "A file of minutes of staff meetings."), ("B", "Updated personnel files."), ("C", "Documentation to demonstrate compliance with its policies and procedures."), ("D", "Documentation to demonstrate compliance with peer review directives.")]),
    (59, "System of Quality Management (SQM)", "The person responsible for the audit engagement and its performance, and for the auditor's report that is issued in behalf of the firm is the",
     [("A", "Quality control reviewer"), ("B", "Engagement partner"), ("C", "Client's management"), ("D", "Those charged with governance")]),
    (60, "System of Quality Management (SQM)", "The engagement partner should take responsibility for the direction, supervision, and performance of the audit engagement in compliance with professional standards and regulatory and legal requirements, and for the auditor's report that is issued to be appropriate in the circumstances. Supervision includes the following except:",
     [("A", "Tracking the progress of the audit engagement."), ("B", "Addressing significant issues arising during the audit engagement, considering their significant, and modifying the planned approach appropriately."), ("C", "Informing the members of the engagement team of their responsibilities."), ("D", "Identifying matters for consultation or consideration by more experienced engagement team members during the audit engagement.")]),
    (61, "System of Quality Management (SQM)", "It is an objective evaluation of the significant judgments made by the engagement team and the conclusions reached thereon.",
     [("A", "Engagement quality review"), ("B", "Engagement partner review"), ("C", "Peer review"), ("D", "Management review")]),
    (62, "System of Quality Management (SQM)", "Which of the following is incorrect about engagement quality review under PSQM 2?",
     [("A", "Engagement quality review is performed by the engagement quality reviewer and completed on or before the date of the engagement report."), ("B", "An engagement quality review is not intended to be an evaluation of whether the entire engagement complies with professional standards and applicable legal and regulatory requirements, or with the firm's policies or procedures."), ("C", "An engagement quality review can only be done by an engagement partner."), ("D", "All of these are correct about engagement quality review under PSQM 2.")]),
    (63, "System of Quality Management (SQM)", "For audits of financial statements of listed entities, the engagement partner should not issue the auditor's report until the completion of the:",
     [("A", "Engagement quality review"), ("B", "Management review"), ("C", "Engagement team review"), ("D", "Engagement partner review")]),
    (64, "System of Quality Management (SQM)", "Which of the following is incorrect about the engagement quality reviewer?",
     [("A", "An engagement quality reviewer is a partner, other individual in the firm, or an external individual, appointed by the firm to perform the engagement quality review."), ("B", "The engagement quality reviewer's evaluation of significant judgments is performed in the context of professional standards and applicable legal and regulatory requirements."), ("C", "The engagement quality reviewer may be one of the members of the engagement team."), ("D", "All of these are correct about the engagement quality reviewer.")]),
    (65, "System of Quality Management (SQM)", "If the person being appointed as an engagement quality reviewer is an engagement partner, a cooling-off period of at least how many years is required before the engagement partner can assume the role of engagement quality reviewer?",
     [("A", "1 year"), ("B", "2 years."), ("C", "3 years."), ("D", "5 years.")])
]

chapter03 = {
    "id": "at-03",
    "code": "AT-03",
    "title": "The Professional Standards and System of Quality Management",
    "description": "Generally Accepted Auditing Standards (GAAS), Philippine Standards on Auditing (PSAs), and the System of Quality Management (PSQM 1 and PSQM 2).",
    "objectives": [
        "Generally Accepted Auditing Standards (GAAS)",
        "Philippine Standards on Auditing (PSA)",
        "System of Quality Management (SQM)"
    ],
    "totalQuestions": 65,
    "questions": []
}

for num, obj, qtext, opts in at03_raw:
    correct = at03_answers[num]
    expl = at03_explanations.get(num, f"Suggested Answer: {correct}. In accordance with PSQM and Philippine Standards on Auditing.")
    chapter03["questions"].append({
        "id": f"at03-{num}",
        "number": num,
        "chapterId": "at-03",
        "chapterCode": "AT-03",
        "chapterTitle": "The Professional Standards and System of Quality Management",
        "objective": obj,
        "question": qtext,
        "options": [{"key": k, "text": t} for k, t in opts],
        "correctAnswer": correct,
        "explanation": expl
    })

with open("src/data/chapters/at03.ts", "w", encoding="utf-8") as f:
    f.write(f"import {{ Chapter }} from '../../types/quiz';\n\nexport const chapter03: Chapter = {json.dumps(chapter03, indent=2)};\n")

print("Created at03.ts with 65 questions")
