#!/usr/bin/env python3
import json

at09_answers = {
    1: 'B', 2: 'B', 3: 'A', 4: 'B', 5: 'A', 6: 'C', 7: 'D', 8: 'D', 9: 'C', 10: 'D',
    11: 'D', 12: 'A', 13: 'B', 14: 'C', 15: 'C', 16: 'D', 17: 'B', 18: 'B', 19: 'D', 20: 'D',
    21: 'A', 22: 'C', 23: 'D', 24: 'B', 25: 'C', 26: 'A', 27: 'C', 28: 'D', 29: 'C', 30: 'A',
    31: 'D', 32: 'B', 33: 'A', 34: 'C', 35: 'C', 36: 'A', 37: 'B', 38: 'D', 39: 'C', 40: 'D',
    41: 'C', 42: 'D', 43: 'B', 44: 'D', 45: 'A', 46: 'A', 47: 'C', 48: 'B', 49: 'D', 50: 'D',
    51: 'A', 52: 'D', 53: 'A', 54: 'D', 55: 'D', 56: 'C', 57: 'B', 58: 'C', 59: 'A', 60: 'A',
    61: 'A', 62: 'B', 63: 'C', 64: 'B', 65: 'B', 66: 'B', 67: 'C', 68: 'B', 69: 'B', 70: 'A',
    71: 'D', 72: 'A', 73: 'B', 74: 'B', 75: 'A', 76: 'C', 77: 'B', 78: 'B', 79: 'B', 80: 'D',
    81: 'B', 82: 'A', 83: 'B', 84: 'B', 85: 'D', 86: 'A', 87: 'C', 88: 'C', 89: 'C', 90: 'D'
}

at09_explanations = {
    1: "Audit sampling involves applying audit procedures to less than 100% of items within an account balance or class of transactions such that all sampling units have a chance of selection.",
    2: "Sampling risk arises from the possibility that the auditor's conclusion based on a sample may be different from the conclusion reached if the entire population were subjected to the same audit procedure.",
    3: "Non-sampling risk arises from factors that cause the auditor to reach an erroneous conclusion for any reason not related to the size of the sample (e.g., misinterpreting evidence, applying inappropriate procedures).",
    12: "Alpha risk (Type I error) affects audit efficiency because it leads to performing additional unnecessary work.",
    13: "Beta risk (Type II error) affects audit effectiveness because it may lead to an inappropriate unqualified audit opinion.",
    21: "Stratification is the process of dividing a population into subpopulations, each of which is a group of sampling units having similar characteristics, which reduces sample size.",
    35: "Tolerable error is the maximum error in a population that the auditor is willing to accept.",
    45: "In attribute sampling for tests of controls, sample size is inversely related to tolerable deviation rate and directly related to the expected deviation rate and confidence level."
}

at09_raw = [
    (1, "Basic Concepts in Audit Sampling", "The application of audit procedures to less than 100% of items within an account balance or class of transactions such that all sampling units have a chance of selection is called:",
     [("A", "Audit testing"), ("B", "Audit sampling"), ("C", "Non-sampling test"), ("D", "Selective testing")]),
    (2, "Basic Concepts in Audit Sampling", "The risk that the auditor's conclusion based on a sample may be different from the conclusion reached if the entire population were subjected to the same audit procedure is:",
     [("A", "Audit risk"), ("B", "Sampling risk"), ("C", "Non-sampling risk"), ("D", "Detection risk")]),
    (3, "Basic Concepts in Audit Sampling", "Non-sampling risk includes:",
     [("A", "The risk of failing to recognize a misstatement in a sample item examined."), ("B", "The risk that a sample is not representative of the population."), ("C", "The risk that the sample size is too small."), ("D", "Alpha risk.")]),
    (4, "Basic Concepts in Audit Sampling", "Sampling risk can be controlled by:",
     [("A", "Proper supervision and review of work."), ("B", "Increasing the sample size."), ("C", "Adequate planning of audit procedures."), ("D", "Training of audit staff.")]),
    (5, "Basic Concepts in Audit Sampling", "Non-sampling risk can be minimized through:",
     [("A", "Proper planning, direction, supervision, and review."), ("B", "Increasing sample size."), ("C", "Using statistical sampling exclusively."), ("D", "Selecting larger sample units.")]),
    (6, "Basic Concepts in Audit Sampling", "Which of the following is not a sampling method?",
     [("A", "Statistical sampling"), ("B", "Non-statistical sampling"), ("C", "Analytical review"), ("D", "Haphazard sampling")]),
    (7, "Basic Concepts in Audit Sampling", "Statistical sampling differs from non-statistical sampling in that statistical sampling:",
     [("A", "Eliminates the need for professional judgment."), ("B", "Provides absolute assurance of sample representativeness."), ("C", "Requires larger sample sizes."), ("D", "Allows the auditor to quantify and measure sampling risk.")]),
    (8, "Basic Concepts in Audit Sampling", "Both statistical and non-statistical sampling methods:",
     [("A", "Quantify sampling risk mathematically."), ("B", "Eliminate non-sampling risk."), ("C", "Do not require professional judgment."), ("D", "Require the exercise of professional judgment in planning and evaluating samples.")]),
    (9, "Basic Concepts in Audit Sampling", "The entire set of data about which the auditor wishes to draw conclusions is called the:",
     [("A", "Sample"), ("B", "Sampling unit"), ("C", "Population"), ("D", "Stratum")]),
    (10, "Basic Concepts in Audit Sampling", "Individual items constituting a population are called:",
     [("A", "Parameters"), ("B", "Strata"), ("C", "Estimates"), ("D", "Sampling units")]),
    (11, "Basic Concepts in Audit Sampling", "An auditor plans to examine a sample of 20 purchase orders for proper authorization. Which of the following would be the sampling unit?",
     [("A", "The account payable balance"), ("B", "The vendor invoice"), ("C", "The receiving report"), ("D", "The purchase order")]),
    (12, "Basic Concepts in Audit Sampling", "The risk of incorrect rejection (alpha risk) in substantive testing relates to:",
     [("A", "Audit efficiency"), ("B", "Audit effectiveness"), ("C", "Audit materiality"), ("D", "Audit quality")]),
    (13, "Basic Concepts in Audit Sampling", "The risk of incorrect acceptance (beta risk) in substantive testing relates to:",
     [("A", "Audit efficiency"), ("B", "Audit effectiveness"), ("C", "Audit economy"), ("D", "Audit feasibility")]),
    (14, "Basic Concepts in Audit Sampling", "In tests of controls, the risk of assessing control risk too high relates to:",
     [("A", "Audit effectiveness"), ("B", "Sample representativeness"), ("C", "Audit efficiency"), ("D", "Sample precision")]),
    (15, "Basic Concepts in Audit Sampling", "In tests of controls, the risk of assessing control risk too low relates to:",
     [("A", "Audit efficiency"), ("B", "Cost of the audit"), ("C", "Audit effectiveness"), ("D", "Audit budget")]),
    (16, "Basic Concepts in Audit Sampling", "Which of the following sample selection methods enables every item in the population to have a known chance of selection?",
     [("A", "Haphazard selection"), ("B", "Block selection"), ("C", "Judgmental selection"), ("D", "Random number selection")]),
    (17, "Basic Concepts in Audit Sampling", "Systematic sampling with a random start involves:",
     [("A", "Selecting every item in a block."), ("B", "Selecting every nth item after a random beginning."), ("C", "Selecting items without conscious bias."), ("D", "Selecting the largest items in the population.")]),
    (18, "Basic Concepts in Audit Sampling", "A sampling selection method where the auditor selects items without following a structured technique but avoids any conscious bias is:",
     [("A", "Random selection"), ("B", "Haphazard selection"), ("C", "Block selection"), ("D", "Systematic selection")]),
    (19, "Basic Concepts in Audit Sampling", "Block sampling is generally not recommended for audit sampling because:",
     [("A", "It requires too much computation."), ("B", "Random numbers cannot be used."), ("C", "It takes too long to draw."), ("D", "Items within a block may share similar characteristics, leading to a non-representative sample.")]),
    (20, "Basic Concepts in Audit Sampling", "When performing audit sampling, the auditor should consider:",
     [("A", "The objectives of the audit procedure."), ("B", "The characteristics of the population."), ("C", "The acceptable level of sampling risk."), ("D", "All of the above.")]),
    (21, "Basic Concepts in Audit Sampling", "Stratification in sampling is used primarily to:",
     [("A", "Group homogeneous items to reduce sample size."), ("B", "Increase non-sampling error."), ("C", "Avoid tests of controls."), ("D", "Eliminate sampling risk completely.")]),
    (22, "Basic Concepts in Audit Sampling", "If an auditor stratifies a population of accounts receivable, the primary purpose is to:",
     [("A", "Select only items over tolerable misstatement."), ("B", "Prevent overreliance on internal controls."), ("C", "Reduce the effect of population variability and decrease overall sample size."), ("D", "Ensure all small balances are tested.")]),
    (23, "Basic Concepts in Audit Sampling", "Which of the following would least likely be considered audit sampling?",
     [("A", "Selecting 50 confirmations from 1,000 customer accounts."), ("B", "Testing 25 disbursements selected systematically."), ("C", "Selecting 30 inventory items at random."), ("D", "Testing all transactions in excess of P500,000.")]),
    (24, "Basic Concepts in Audit Sampling", "When 100% of an account balance is tested, this is known as:",
     [("A", "Sampling without replacement"), ("B", "Complete examination (not sampling)"), ("C", "Attribute sampling"), ("D", "Monetary unit sampling")]),
    (25, "Basic Concepts in Audit Sampling", "Audit sampling is appropriate when:",
     [("A", "The population consists of a few large value items."), ("B", "An unusual risk is suspected and 100% examination is cost effective."), ("C", "There is a large number of homogeneous items in the population."), ("D", "Analytical procedures are not applicable.")]),
    (26, "Basic Concepts in Audit Sampling", "The standard on audit sampling in the Philippines is:",
     [("A", "PSA 530"), ("B", "PSA 500"), ("C", "PSA 315"), ("D", "PSA 700")]),
    (27, "Sampling in Tests of Controls", "Attribute sampling is used primarily to:",
     [("A", "Estimate the monetary misstatement in an account balance."), ("B", "Determine the precision of an inventory estimate."), ("C", "Estimate the rate of deviation from a prescribed control procedure."), ("D", "Calculate total dollar value of recorded assets.")]),
    (28, "Sampling in Tests of Controls", "In attribute sampling, the deviation rate is:",
     [("A", "The monetary amount of errors found in the sample."), ("B", "The percentage of items in the population that are completely correct."), ("C", "The ratio of audit sample size to population."), ("D", "The percentage of times a control procedure was not executed properly.")]),
    (29, "Sampling in Tests of Controls", "The rate of deviation from prescribed internal control policy that the auditor sets and tolerates without modifying planned reliance is the:",
     [("A", "Expected deviation rate"), ("B", "Sample deviation rate"), ("C", "Tolerable deviation rate"), ("D", "Upper deviation rate")]),
    (30, "Sampling in Tests of Controls", "The auditor expects a 2% deviation rate. The tolerable deviation rate is 6%. If the sample size is 100 and 1 deviation is found, the sample deviation rate is:",
     [("A", "1%"), ("B", "2%"), ("C", "5%"), ("D", "6%")]),
    (31, "Sampling in Tests of Controls", "Which factor has a direct relationship with sample size in attribute sampling?",
     [("A", "Tolerable deviation rate"), ("B", "Acceptable risk of assessing control risk too low"), ("C", "Population size (for large populations)"), ("D", "Expected population deviation rate")]),
    (32, "Sampling in Tests of Controls", "Which factor has an inverse relationship with sample size in attribute sampling?",
     [("A", "Expected deviation rate"), ("B", "Tolerable deviation rate"), ("C", "Confidence level required"), ("D", "Population variability")]),
    (33, "Sampling in Tests of Controls", "If the auditor decreases the tolerable deviation rate from 7% to 4%, the required sample size will:",
     [("A", "Increase"), ("B", "Decrease"), ("C", "Remain unchanged"), ("D", "Become zero")]),
    (34, "Sampling in Tests of Controls", "If the auditor lowers the risk of assessing control risk too low from 10% to 5%, the required sample size will:",
     [("A", "Remain unchanged"), ("B", "Decrease"), ("C", "Increase"), ("D", "Be halved")]),
    (35, "Sampling in Tests of Controls", "The maximum rate of deviation from a prescribed control that an auditor would be willing to accept without altering the planned assessed level of control risk is:",
     [("A", "Expected error rate"), ("B", "Precision limit"), ("C", "Tolerable deviation rate"), ("D", "Computed upper precision limit")]),
    (36, "Sampling in Tests of Controls", "If the sample deviation rate plus an allowance for sampling risk exceeds the tolerable deviation rate, the auditor will conclude that:",
     [("A", "The control is not operating effectively and assessed control risk should be increased."), ("B", "The control is operating effectively."), ("C", "The account balance is materially misstated."), ("D", "The sample size was too large.")]),
    (37, "Sampling in Tests of Controls", "Sequential (stop-or-go) sampling is best used when:",
     [("A", "A high deviation rate is expected."), ("B", "Very few deviations are expected in the population."), ("C", "Substantive testing of balances is being conducted."), ("D", "Population size is very small.")]),
    (38, "Sampling in Tests of Controls", "Discovery sampling is a specialized form of attribute sampling designed to:",
     [("A", "Estimate the total dollar value of fraud."), ("B", "Test large populations of receivables."), ("C", "Measure overall dollar errors."), ("D", "Detect at least one deviation if the population deviation rate equals or exceeds a specified rate.")]),
    (39, "Sampling in Tests of Controls", "Discovery sampling is most appropriate when:",
     [("A", "The auditor expects many deviations."), ("B", "Testing accounts payable balances."), ("C", "The auditor suspects fraud or critical noncompliance and expects near-zero occurrences."), ("D", "Assessing control risk at the maximum.")]),
    (40, "Sampling in Tests of Controls", "When evaluating the results of an attribute sample, the auditor should consider:",
     [("A", "Only the quantitative deviation rate."), ("B", "Only whether deviations were intentional."), ("C", "Only the sample size used."), ("D", "Both the qualitative aspects of deviations and their quantitative frequency.")]),
    (41, "Sampling in Tests of Controls", "An auditor finds a missing invoice in a sample selected to test authorization. If no alternative procedure can be applied, the invoice should be treated as:",
     [("A", "An immaterial item"), ("B", "A normal transaction"), ("C", "A deviation from the control"), ("D", "A non-sampling error")]),
    (42, "Sampling in Tests of Controls", "If an auditor tested 50 items and found 0 deviations, the auditor can conclude that:",
     [("A", "There are 0 deviations in the population."), ("B", "The population is 100% error free."), ("C", "Control risk is 0."), ("D", "The sample results support reliance at the chosen confidence level.")]),
    (43, "Sampling in Tests of Controls", "The primary purpose of attribute sampling is to test:",
     [("A", "Dollar values"), ("B", "Internal control operating effectiveness"), ("C", "Completeness of financial statements"), ("D", "Valuation of inventories")]),
    (44, "Sampling in Tests of Controls", "A deviation from a control procedure does not necessarily mean that:",
     [("A", "The control failed."), ("B", "The procedure was violated."), ("C", "The sample was biased."), ("D", "A monetary misstatement occurred in the financial statements.")]),
    (45, "Sampling in Substantive Tests", "Variable sampling is used in auditing to:",
     [("A", "Estimate a monetary amount or whether an account balance is fairly stated."), ("B", "Determine the frequency of control deviations."), ("C", "Assess control risk at the maximum."), ("D", "Determine the qualification of audit staff.")]),
    (46, "Sampling in Substantive Tests", "Tolerable misstatement in substantive testing is:",
     [("A", "A monetary amount set by the auditor in respect of which the auditor seeks reasonable assurance that the true population misstatement does not exceed it."),
      ("B", "The rate of deviations acceptable in a control."), ("C", "The misstatement expected by the client."), ("D", "Always equal to overall planning materiality.")]),
    (47, "Sampling in Substantive Tests", "Which of the following has an inverse relationship with sample size in substantive testing of balances?",
     [("A", "Expected misstatement"), ("B", "Population variability (standard deviation)"), ("C", "Tolerable misstatement"), ("D", "Required confidence level")]),
    (48, "Sampling in Substantive Tests", "If tolerable misstatement decreases while all other factors remain constant, the required sample size will:",
     [("A", "Decrease"), ("B", "Increase"), ("C", "Remain constant"), ("D", "Fluctuate randomly")]),
    (49, "Sampling in Substantive Tests", "Classical variables sampling methods include all of the following except:",
     [("A", "Mean-per-unit estimation"), ("B", "Difference estimation"), ("C", "Ratio estimation"), ("D", "Discovery sampling")]),
    (50, "Sampling in Substantive Tests", "The mean-per-unit estimation method evaluates a population by:",
     [("A", "Calculating the average difference between audit and book values."), ("B", "Computing the ratio of audited to recorded amounts."), ("C", "Testing only items with large differences."), ("D", "Multiplying the average audited value of sample items by the total number of units in the population.")]),
    (51, "Sampling in Substantive Tests", "Difference estimation is most appropriate when:",
     [("A", "There are sufficient differences between audit and book values and differences are not proportional to book values."),
      ("B", "No differences are expected."), ("C", "Book values are unavailable."), ("D", "Population size is unknown.")]),
    (52, "Sampling in Substantive Tests", "Ratio estimation is most appropriate when:",
     [("A", "Differences between book and audit values are constant regardless of size."), ("B", "No book values exist."), ("C", "Only zero book value items are examined."), ("D", "Differences between audit and book values are proportional to the recorded book amounts.")]),
    (53, "Sampling in Substantive Tests", "Probability-proportional-to-size (PPS) sampling is also known as:",
     [("A", "Monetary unit sampling (MUS)"), ("B", "Attribute sampling"), ("C", "Mean-per-unit sampling"), ("D", "Stratified random sampling")]),
    (54, "Sampling in Substantive Tests", "A major advantage of PPS / monetary unit sampling is that:",
     [("A", "It is very effective at detecting understatements."), ("B", "It handles negative balances easily without modification."), ("C", "It eliminates the need for sample size formulas."), ("D", "It automatically stratifies the population because larger dollar items have a higher chance of selection.")]),
    (55, "Sampling in Substantive Tests", "A major disadvantage of PPS sampling is that:",
     [("A", "It requires extensive stratification calculations."), ("B", "It cannot be evaluated using computers."), ("C", "It cannot test overstatements."), ("D", "It is ineffective for testing populations with numerous understatements or zero/negative balances.")]),
    (56, "Sampling in Substantive Tests", "In monetary unit sampling, each peso in the population is:",
     [("A", "A stratum"), ("B", "An attribute"), ("C", "A sampling unit"), ("D", "A precision limit")]),
    (57, "Sampling in Substantive Tests", "Projected misstatement is:",
     [("A", "The misstatement identified in the prior year's audit."), ("B", "The auditor's best estimate of misstatement in the population based on sample findings."), ("C", "The maximum error allowed by standard setters."), ("D", "The difference between planning materiality and performance materiality.")]),
    (58, "Sampling in Substantive Tests", "If projected misstatement exceeds tolerable misstatement, the auditor should:",
     [("A", "Immediately issue an adverse opinion."), ("B", "Ignore the misstatement if it is qualitative."), ("C", "Request management to investigate and adjust the account, or perform additional audit procedures."), ("D", "Reduce tolerable misstatement.")]),
    (59, "Sampling in Substantive Tests", "An auditor projects a sample misstatement of P45,000 for an inventory population with tolerable misstatement of P50,000. Considering sampling risk, the auditor should conclude that:",
     [("A", "There is an unacceptable risk that the population is materially misstated."), ("B", "The inventory is definitely fairly stated without reservation."), ("C", "The audit opinion must be unqualified."), ("D", "The sample size was too large.")]),
    (60, "Sampling in Substantive Tests", "When evaluating sample results, anomalous misstatements are:",
     [("A", "Misstatements that arise from an isolated event that has not recurred and is not representative of the population."),
      ("B", "Misstatements caused by systemic software bugs."), ("C", "Misstatements present in all sample items."), ("D", "Misstatements that equal tolerable error.")]),
    (61, "Audit Sampling Questions 61-90", "In an audit of financial statements, sampling risk is an inherent part of:",
     [("A", "Both tests of controls and substantive tests"), ("B", "Only tests of controls"), ("C", "Only substantive tests"), ("D", "Neither tests of controls nor substantive tests")]),
    (62, "Audit Sampling Questions 61-90", "The risk of assessing control risk too low leads directly to:",
     [("A", "Inappropriate increase in substantive tests"), ("B", "Inappropriate reduction in substantive tests"), ("C", "Issuing a disclaimer of opinion"), ("D", "Higher audit fees")]),
    (63, "Audit Sampling Questions 61-90", "The risk of incorrect acceptance in substantive tests corresponds to:",
     [("A", "Type I error"), ("B", "Alpha error"), ("C", "Type II error (Beta error)"), ("D", "Non-sampling error")]),
    (64, "Audit Sampling Questions 61-90", "An auditor who uses non-statistical sampling will evaluate sample results using:",
     [("A", "Statistical formulas exclusively"), ("B", "Professional judgment"), ("C", "Poisson distribution tables"), ("D", "Normal distribution tables")]),
    (65, "Audit Sampling Questions 61-90", "When determining sample size for substantive tests, which factor is directly related to sample size?",
     [("A", "Tolerable misstatement"), ("B", "Expected misstatement"), ("C", "Acceptable risk of incorrect acceptance"), ("D", "Alpha risk")]),
    (66, "Audit Sampling Questions 61-90", "In MUS, a sampling interval is determined by:",
     [("A", "Dividing sample size by population value"), ("B", "Dividing population book value by sample size"), ("C", "Multiplying population value by tolerable misstatement"), ("D", "Adding expected and tolerable misstatements")]),
    (67, "Audit Sampling Questions 61-90", "If a population has a book value of P1,000,000 and a sample size of 50 is planned in MUS, the sampling interval is:",
     [("A", "P10,000"), ("B", "P50,000"), ("C", "P20,000"), ("D", "P5,000")]),
    (68, "Audit Sampling Questions 61-90", "An item with a book value larger than the sampling interval in MUS will:",
     [("A", "Never be selected"), ("B", "Always be selected at least once"), ("C", "Be selected only if it contains an error"), ("D", "Be excluded from testing")]),
    (69, "Audit Sampling Questions 61-90", "Tainting percentage in MUS is calculated as:",
     [("A", "Book value divided by audit value"), ("B", "Misstatement divided by book value"), ("C", "Audit value divided by misstatement"), ("D", "Sampling interval divided by book value")]),
    (70, "Audit Sampling Questions 61-90", "If an item with a recorded book value of P200 has an audited value of P150, the tainting percentage is:",
     [("A", "25%"), ("B", "75%"), ("C", "33.3%"), ("D", "50%")]),
    (71, "Audit Sampling Questions 61-90", "Which sampling plan is most appropriate when testing whether sales invoices have been signed by an authorized credit manager?",
     [("A", "Mean-per-unit sampling"), ("B", "Difference estimation"), ("C", "Dollar-unit sampling"), ("D", "Attribute sampling")]),
    (72, "Audit Sampling Questions 61-90", "Which sampling plan is most appropriate when confirming accounts receivable balances?",
     [("A", "Variables sampling or MUS"), ("B", "Attribute sampling"), ("C", "Discovery sampling"), ("D", "Sequential sampling")]),
    (73, "Audit Sampling Questions 61-90", "When the auditor uses non-statistical sampling, the sample size:",
     [("A", "Must be twice as large as statistical sample size"), ("B", "Can be comparable to the sample size designed under statistical sampling"), ("C", "Cannot be determined"), ("D", "Is always 30 units")]),
    (74, "Audit Sampling Questions 61-90", "If the auditor increases the planned reliance on internal control, the acceptable risk of assessing control risk too low will:",
     [("A", "Increase"), ("B", "Decrease"), ("C", "Remain unaffected"), ("D", "Reach 100%")]),
    (75, "Audit Sampling Questions 61-90", "An advantage of statistical sampling over non-statistical sampling is that it:",
     [("A", "Provides an objective mathematical basis for sample size and evaluation."), ("B", "Guarantees no audit failure."), ("C", "Eliminates need for documentation."), ("D", "Costs less to apply in all cases.")]),
    (76, "Audit Sampling Questions 61-90", "Which of the following is true regarding sample selection?",
     [("A", "Haphazard selection can be used in statistical sampling."), ("B", "Block selection is the preferred statistical method."), ("C", "Random number selection is required for statistical sampling."), ("D", "Judgment selection yields measurable sampling risk.")]),
    (77, "Audit Sampling Questions 61-90", "The primary purpose of performing audit sampling in substantive testing is to:",
     [("A", "Test compliance with management directives."), ("B", "Estimate monetary misstatement in an account balance."), ("C", "Verify segregation of duties."), ("D", "Ensure all transactions are recorded in the general ledger.")]),
    (78, "Audit Sampling Questions 61-90", "When planning an attribute sample, the auditor should consider:",
     [("A", "Standard deviation of population"), ("B", "Tolerable deviation rate"), ("C", "Ratio of book to audit value"), ("D", "Tainting percentage")]),
    (79, "Audit Sampling Questions 61-90", "What happens to sample size in variable sampling if the population standard deviation increases?",
     [("A", "Decreases"), ("B", "Increases"), ("C", "Remains unchanged"), ("D", "Becomes zero")]),
    (80, "Audit Sampling Questions 61-90", "If the auditor decides to select a larger sample, sampling risk will:",
     [("A", "Increase"), ("B", "Remain unchanged"), ("C", "Equal non-sampling risk"), ("D", "Decrease")]),
    (81, "Audit Sampling Questions 61-90", "The upper error limit in MUS represents:",
     [("A", "The minimum expected misstatement"), ("B", "The maximum misstatement that could exist in the population at the specified confidence level"), ("C", "The actual book value of all errors"), ("D", "The tolerable error")]),
    (82, "Audit Sampling Questions 61-90", "When an auditor projects the results of a sample to the population, the projection is:",
     [("A", "Required for both statistical and non-statistical sampling"), ("B", "Only required for statistical sampling"), ("C", "Prohibited in non-statistical sampling"), ("D", "Optional unless misstatements exceed materiality")]),
    (83, "Audit Sampling Questions 61-90", "Which of the following causes non-sampling risk?",
     [("A", "Selecting a sample that is too small"), ("B", "Auditor fatigue causing oversight of an obvious error"), ("C", "Normal statistical variance"), ("D", "Standard error of the mean")]),
    (84, "Audit Sampling Questions 61-90", "When testing controls, if the sample deviation rate is 3% and the allowance for sampling risk is 2%, the computed upper deviation rate is:",
     [("A", "1%"), ("B", "5%"), ("C", "6%"), ("D", "1.5%")]),
    (85, "Audit Sampling Questions 61-90", "If the computed upper deviation rate is 5% and the tolerable deviation rate is 4%, the auditor should:",
     [("A", "Accept the control as effective"), ("B", "Reduce substantive testing"), ("C", "Issue an adverse opinion"), ("D", "Not rely on the control and increase substantive tests")]),
    (86, "Audit Sampling Questions 61-90", "A sample of 100 items yielded a mean audited value of P500. If the population has 1,000 items, the estimated total population value using mean-per-unit is:",
     [("A", "P500,000"), ("B", "P50,000"), ("C", "P5,000,000"), ("D", "P250,000")]),
    (87, "Audit Sampling Questions 61-90", "In evaluating evidence from audit sampling, the auditor considers:",
     [("A", "Only the quantitative projection."), ("B", "Only the qualitative nature of errors."), ("C", "Both qualitative characteristics and quantitative projection."), ("D", "Whether the client agreed with the sample items chosen.")]),
    (88, "Audit Sampling Questions 61-90", "Which of the following is true about sampling units in customer receivable confirmations?",
     [("A", "The customer balance must always be the sampling unit."), ("B", "The general ledger account is the sampling unit."), ("C", "The sampling unit may be individual invoices or entire customer account balances."), ("D", "The sales journal entry is always the sampling unit.")]),
    (89, "Audit Sampling Questions 61-90", "When is an auditor most likely to use haphazard selection?",
     [("A", "In a statistical variable sampling plan"), ("B", "In monetary unit sampling"), ("C", "In a non-statistical sampling plan"), ("D", "In PPS sampling")]),
    (90, "Audit Sampling Questions 61-90", "Under PSA 530, the auditor must document:",
     [("A", "The audit procedures performed on the sample"), ("B", "The basis for sample selection and sample size"), ("C", "The evaluation of sample results and projection of misstatements"), ("D", "All of the above")])
]

chapter09 = {
    "id": "at-09",
    "code": "AT-09",
    "title": "Audit Sampling",
    "description": "PSA 530 principles on audit sampling: statistical vs. non-statistical sampling, sampling risk (Alpha and Beta risks), non-sampling risk, attribute sampling for tests of controls, and variables sampling / monetary unit sampling (MUS) for substantive tests.",
    "objectives": [
        "Basic Concepts in Audit Sampling",
        "Sampling in Tests of Controls",
        "Sampling in Substantive Tests",
        "Audit Sampling Questions 61-90"
    ],
    "totalQuestions": 90,
    "questions": []
}

for num, obj, qtext, opts in at09_raw:
    correct = at09_answers[num]
    expl = at09_explanations.get(num, f"Suggested Answer: {correct}. In accordance with PSA 530 (Audit Sampling).")
    chapter09["questions"].append({
        "id": f"at09-{num}",
        "number": num,
        "chapterId": "at-09",
        "chapterCode": "AT-09",
        "chapterTitle": "Audit Sampling",
        "objective": obj,
        "question": qtext,
        "options": [{"key": k, "text": t} for k, t in opts],
        "correctAnswer": correct,
        "explanation": expl
    })

with open("src/data/chapters/at09.ts", "w", encoding="utf-8") as f:
    f.write(f"import {{ Chapter }} from '../../types/quiz';\n\nexport const chapter09: Chapter = {json.dumps(chapter09, indent=2)};\n")

print("Created at09.ts with 90 questions")
