#!/usr/bin/env python3
import json

at12_answers = {
    1: 'B', 2: 'C', 3: 'A', 4: 'C', 5: 'D', 6: 'B', 7: 'C', 8: 'A', 9: 'C', 10: 'D',
    11: 'B', 12: 'A', 13: 'B', 14: 'C', 15: 'C', 16: 'C', 17: 'B', 18: 'B', 19: 'A', 20: 'D',
    21: 'B', 22: 'C', 23: 'D', 24: 'B', 25: 'A', 26: 'A', 27: 'C', 28: 'D', 29: 'D', 30: 'B',
    31: 'D', 32: 'B', 33: 'A', 34: 'C', 35: 'D', 36: 'B', 37: 'A', 38: 'D', 39: 'B', 40: 'D',
    41: 'A', 42: 'B', 43: 'B', 44: 'C', 45: 'A', 46: 'A', 47: 'C', 48: 'C', 49: 'D', 50: 'C',
    51: 'C', 52: 'D', 53: 'A', 54: 'A', 55: 'B', 56: 'B', 57: 'C', 58: 'C', 59: 'A', 60: 'C',
    61: 'A', 62: 'B', 63: 'C', 64: 'B', 65: 'B', 66: 'B', 67: 'C', 68: 'B', 69: 'B', 70: 'A',
    71: 'D', 72: 'A', 73: 'B', 74: 'B', 75: 'A', 76: 'C', 77: 'B', 78: 'B', 79: 'B', 80: 'D',
    81: 'B', 82: 'A', 83: 'B', 84: 'B', 85: 'D', 86: 'A', 87: 'C', 88: 'C', 89: 'C', 90: 'D',
    91: 'A', 92: 'B', 93: 'C', 94: 'D', 95: 'A', 96: 'B', 97: 'C', 98: 'A', 99: 'B', 100: 'C'
}

at12_explanations = {
    1: "Under PSA 700 (Revised), the auditor's report has the Opinion section placed first, immediately followed by the Basis for Opinion section.",
    2: "The auditor expresses an unmodified (clean) opinion when the auditor concludes that the financial statements are prepared, in all material respects, in accordance with the applicable financial reporting framework.",
    31: "PSA 705 (Revised) governs modifications to the opinion: qualified opinion, adverse opinion, and disclaimer of opinion.",
    32: "A qualified opinion is expressed when misstatements are material but not pervasive, or when unable to obtain sufficient appropriate evidence where possible effects are material but not pervasive.",
    33: "An adverse opinion is expressed when misstatements, individually or in aggregate, are both material and pervasive to the financial statements.",
    34: "A disclaimer of opinion is expressed when the auditor is unable to obtain sufficient appropriate audit evidence and the possible effects could be both material and pervasive.",
    66: "An Emphasis of Matter paragraph refers to a matter appropriately presented or disclosed in the financial statements that is fundamental to users' understanding (PSA 706).",
    81: "Key Audit Matters (KAM) under PSA 701 are those matters that, in the auditor's professional judgment, were of most significance in the audit of the financial statements of the current period."
}

at12_raw = [
    (1, "Nature and Elements of the Auditor's Report", "Under PSA 700 (Revised), which section of the independent auditor's report appears first?",
     [("A", "Basis for Opinion"), ("B", "Auditor's Opinion"), ("C", "Management's Responsibility"), ("D", "Auditor's Responsibilities")]),
    (2, "Nature and Elements of the Auditor's Report", "An unmodified opinion states that the financial statements:",
     [("A", "Are accurate in all respects."),
      ("B", "Are guaranteed by the auditor to be free from error."),
      ("C", "Present fairly, in all material respects, in accordance with the applicable financial reporting framework."),
      ("D", "Have been approved by the Securities and Exchange Commission.")]),
    (3, "Nature and Elements of the Auditor's Report", "The auditor's report shall have a title that clearly indicates that it is the report of a(n):",
     [("A", "Independent auditor"), ("B", "Certified internal auditor"), ("C", "Management consultant"), ("D", "Government examiner")]),
    (4, "Nature and Elements of the Auditor's Report", "The auditor's report is normally addressed to:",
     [("A", "The audit manager"), ("B", "The chief accountant"), ("C", "The shareholders and/or those charged with governance of the entity"), ("D", "The general public")]),
    (5, "Nature and Elements of the Auditor's Report", "The Basis for Opinion section in an unmodified auditor's report shall:",
     [("A", "State that the audit was conducted in accordance with Philippine Standards on Auditing (PSAs)."),
      ("B", "Refer to the section that describes the auditor's responsibilities under PSAs."),
      ("C", "Include a statement that the auditor is independent and has fulfilled other ethical responsibilities."),
      ("D", "All of the above.")]),
    (6, "Nature and Elements of the Auditor's Report", "Management's responsibility for the financial statements includes:",
     [("A", "Assessing audit risk and setting detection risk."),
      ("B", "The preparation and fair presentation of the financial statements and internal control necessary to enable free from material misstatement."),
      ("C", "Expressing an independent opinion on the financial statements."),
      ("D", "Reviewing the working papers of the external auditor.")]),
    (7, "Nature and Elements of the Auditor's Report", "The auditor's report shall be dated as of:",
     [("A", "The end of the fiscal year."),
      ("B", "The date the fieldwork started."),
      ("C", "No earlier than the date on which the auditor has obtained sufficient appropriate audit evidence to support the opinion."),
      ("D", "The date the annual stockholders' meeting takes place.")]),
    (8, "Nature and Elements of the Auditor's Report", "The auditor's report must include the auditor's signature, which may be:",
     [("A", "In the name of the audit firm, the personal name of the auditor, or both."),
      ("B", "In the name of the client company only."),
      ("C", "Signed by the client's internal audit department."),
      ("D", "An anonymous digital key.")]),
    (9, "Nature and Elements of the Auditor's Report", "In the Philippines, the auditor's report requires disclosure of the following professional credentials:",
     [("A", "TIN and SSS numbers only."),
      ("B", "Voter's registration and passport details."),
      ("C", "CPA Certificate No., PRC/BOA Registration No., BIR Accreditation, and PTR No."),
      ("D", "High school diploma and college transcript.")]),
    (10, "Nature and Elements of the Auditor's Report", "The auditor's responsibilities section states that the auditor's objectives are to:",
     [("A", "Obtain reasonable assurance about whether the financial statements as a whole are free from material misstatement."),
      ("B", "Issue an auditor's report that includes an opinion."),
      ("C", "Exercise professional judgment and maintain professional skepticism throughout the audit."),
      ("D", "All of the above.")]),
    (11, "Nature and Elements of the Auditor's Report", "Reasonable assurance is defined as:",
     [("A", "Absolute assurance that all misstatements will be detected."),
      ("B", "A high level of assurance, but not a guarantee that an audit conducted in accordance with PSAs will always detect a material misstatement."),
      ("C", "Negative assurance that nothing came to the auditor's attention."),
      ("D", "A moderate level of assurance.")]),
    (12, "Nature and Elements of the Auditor's Report", "The entity's financial statements identified in the opinion paragraph include:",
     [("A", "Statement of financial position, statement of comprehensive income, statement of changes in equity, statement of cash flows, and notes."),
      ("B", "Tax return only."),
      ("C", "Board of directors' personal wealth records."),
      ("D", "Budget forecasts for the next five years.")]),
    (13, "Nature and Elements of the Auditor's Report", "The auditor's address in the report indicates:",
     [("A", "The residence of the managing partner."),
      ("B", "The location in the jurisdiction where the auditor practices."),
      ("C", "The location of the client's largest factory."),
      ("D", "The address of the Securities and Exchange Commission.")]),
    (14, "Nature and Elements of the Auditor's Report", "A financial reporting framework designed to meet the common financial information needs of a wide range of users is a:",
     [("A", "Special purpose framework"),
      ("B", "Compliance framework"),
      ("C", "General purpose framework"),
      ("D", "Cash basis framework")]),
    (15, "Nature and Elements of the Auditor's Report", "When the auditor concludes that the financial statements are prepared in accordance with PFRS, the phrase used is:",
     [("A", "Are accurate and mathematically verified"),
      ("B", "Are beyond any reasonable doubt"),
      ("C", "Present fairly, in all material respects... in accordance with Philippine Financial Reporting Standards"),
      ("D", "Are completely correct and sound")]),
    (16, "Nature and Elements of the Auditor's Report", "In which section does the auditor describe the concept of materiality and how it affects the audit?",
     [("A", "Introduction"),
      ("B", "Opinion"),
      ("C", "Auditor's Responsibilities for the Audit of the Financial Statements"),
      ("D", "Title")]),
    (17, "Nature and Elements of the Auditor's Report", "The description of management's responsibilities includes their responsibility to:",
     [("A", "Select the audit firm."),
      ("B", "Assess the entity's ability to continue as a going concern."),
      ("C", "Determine the auditor's materiality threshold."),
      ("D", "Supervise the external audit staff.")]),
    (18, "Nature and Elements of the Auditor's Report", "If an entity has an audit committee, the auditor's report may address communication with:",
     [("A", "The media"),
      ("B", "Those charged with governance"),
      ("C", "Competitors"),
      ("D", "Customers")]),
    (19, "Nature and Elements of the Auditor's Report", "A standard unqualified report is also known as:",
     [("A", "An unmodified opinion"),
      ("B", "A disclaimer"),
      ("C", "A qualified report"),
      ("D", "An adverse report")]),
    (20, "Nature and Elements of the Auditor's Report", "Which of the following is not a requirement for issuing an unmodified opinion?",
     [("A", "The financial statements are prepared in accordance with acceptable framework."),
      ("B", "The auditor obtained sufficient appropriate evidence."),
      ("C", "Adequate disclosures are made."),
      ("D", "The entity has achieved higher profits than the previous year.")]),
    (21, "Nature and Elements of the Auditor's Report", "The date of the auditor's report informs the user that:",
     [("A", "The auditor examined every transaction occurring after that date."),
      ("B", "The auditor has considered the effect of events and transactions of which the auditor became aware up to that date."),
      ("C", "The company will never fail after that date."),
      ("D", "The financial statements cannot be revised.")]),
    (22, "Nature and Elements of the Auditor's Report", "The auditor's report on comparative financial statements covers:",
     [("A", "Only the current year."),
      ("B", "Only the prior year."),
      ("C", "Each of the periods for which financial statements are presented."),
      ("D", "All future periods.")]),
    (23, "Nature and Elements of the Auditor's Report", "If the auditor issues an unmodified opinion on the parent and component financial statements, the report is governed by:",
     [("A", "PSA 200"), ("B", "PSA 300"), ("C", "PSA 500"), ("D", "PSA 700 (Revised)")]),
    (24, "Nature and Elements of the Auditor's Report", "An audit report that includes an 'Other Reporting Responsibilities' section is used when:",
     [("A", "The auditor has no responsibility."),
      ("B", "The auditor has additional statutory or regulatory reporting obligations (e.g., BIR requirements)."),
      ("C", "The client refuses to pay fees."),
      ("D", "The auditor disclaims an opinion.")]),
    (25, "Nature and Elements of the Auditor's Report", "The introductory paragraph in previous standard formats is now integrated into the:",
     [("A", "Opinion section"),
      ("B", "Auditor's signature"),
      ("C", "Date of report"),
      ("D", "Table of contents")]),
    (26, "Nature and Elements of the Auditor's Report", "Which of the following is true regarding the auditor's independence statement?",
     [("A", "It must be explicitly stated in the Basis for Opinion section."),
      ("B", "It is only required for private entities."),
      ("C", "It is optional in the Philippines."),
      ("D", "It can be omitted if the client pays a retainer.")]),
    (27, "Nature and Elements of the Auditor's Report", "When the auditor's report is on consolidated financial statements, the opinion states:",
     [("A", "Fair presentation of the parent company only"),
      ("B", "Fair presentation of subsidiaries only"),
      ("C", "Fair presentation of the consolidated financial statements of the Group"),
      ("D", "Fair presentation of each supplier")]),
    (28, "Nature and Elements of the Auditor's Report", "The auditor's report format under PSA 700 (Revised) applies to audits of financial statements for periods:",
     [("A", "Ended prior to 2010"),
      ("B", "Of government agencies only"),
      ("C", "Of small sole proprietorships only"),
      ("D", "Ending on or after December 15, 2016")]),
    (29, "Nature and Elements of the Auditor's Report", "The auditor communicates with those charged with governance regarding:",
     [("A", "The planned scope and timing of the audit."),
      ("B", "Significant audit findings."),
      ("C", "Auditor independence."),
      ("D", "All of the above.")]),
    (30, "Nature and Elements of the Auditor's Report", "Which document is not part of the complete set of financial statements covered by the audit opinion?",
     [("A", "Statement of cash flows"),
      ("B", "Chairman's annual report to shareholders"),
      ("C", "Statement of financial position"),
      ("D", "Notes comprising significant accounting policies")]),
    (31, "Modifications to the Opinion", "Which of the following are types of modified audit opinions under PSA 705 (Revised)?",
     [("A", "Qualified opinion"),
      ("B", "Adverse opinion"),
      ("C", "Disclaimer of opinion"),
      ("D", "All of the above")]),
    (32, "Modifications to the Opinion", "The auditor expresses a qualified opinion when:",
     [("A", "Financial statements are perfectly stated in every single detail."),
      ("B", "Misstatements are material but not pervasive, or the auditor is unable to obtain evidence and the possible effects are material but not pervasive."),
      ("C", "The entity has entered bankruptcy."),
      ("D", "The auditor is not independent.")]),
    (33, "Modifications to the Opinion", "The auditor expresses an adverse opinion when:",
     [("A", "Misstatements, individually or in the aggregate, are both material and pervasive to the financial statements."),
      ("B", "There is a minor immaterial error in depreciation."),
      ("C", "The client has multiple bank accounts."),
      ("D", "The auditor is unable to observe inventory but can perform alternative procedures.")]),
    (34, "Modifications to the Opinion", "The auditor disclaims an opinion when:",
     [("A", "The financial statements are presented fairly."),
      ("B", "The auditor is fully satisfied with all evidence obtained."),
      ("C", "The auditor is unable to obtain sufficient appropriate audit evidence and the possible effects could be both material and pervasive."),
      ("D", "The company changes its accounting method with full retrospective application.")]),
    (35, "Modifications to the Opinion", "Pervasive effects on the financial statements are those that, in the auditor's judgment:",
     [("A", "Are not confined to specific elements, accounts, or items of the financial statements."),
      ("B", "If confined, represent or could represent a substantial proportion of the financial statements."),
      ("C", "In relation to disclosures, are fundamental to users' understanding of the financial statements."),
      ("D", "All of the above.")]),
    (36, "Modifications to the Opinion", "When the auditor modifies the opinion, the section heading 'Basis for Opinion' is amended to:",
     [("A", "Explanation of Error"),
      ("B", "'Basis for Qualified Opinion', 'Basis for Adverse Opinion', or 'Basis for Disclaimer of Opinion'"),
      ("C", "Court Notice"),
      ("D", "Regulatory Warning")]),
    (37, "Modifications to the Opinion", "When expressing a qualified opinion due to material misstatement, the opinion paragraph states that, 'except for the effects of the matter described in the Basis for Qualified Opinion section':",
     [("A", "The financial statements present fairly, in all material respects..."),
      ("B", "The financial statements are totally fraudulent"),
      ("C", "The financial statements cannot be relied upon at all"),
      ("D", "No opinion is expressed")]),
    (38, "Modifications to the Opinion", "Which of the following situations would result in an adverse opinion?",
     [("A", "An immaterial math error in petty cash."),
      ("B", "A restriction on the audit scope imposed by circumstances."),
      ("C", "The auditor is not independent."),
      ("D", "The client consolidated a subsidiary using illegal non-PFRS methods, causing assets, revenues, and net income to be overstated by 80%.")]),
    (39, "Modifications to the Opinion", "If the auditor is not independent with respect to the entity being audited, the auditor shall:",
     [("A", "Issue a qualified opinion"),
      ("B", "Disclaim an opinion and state that the auditor is not independent"),
      ("C", "Issue an adverse opinion"),
      ("D", "Issue an unmodified opinion with emphasis")]),
    (40, "Modifications to the Opinion", "A limitation on the scope of the audit may arise from:",
     [("A", "Circumstances beyond the control of the entity (e.g., records destroyed in flood)."),
      ("B", "Circumstances relating to the nature or timing of the auditor's work."),
      ("C", "Limitations imposed by management (e.g., refusing to allow receivable confirmation)."),
      ("D", "All of the above.")]),
    (41, "Modifications to the Opinion", "If management imposes a limitation that will result in a disclaimer of opinion prior to accepting the engagement, the auditor should:",
     [("A", "Not accept the engagement, unless required by law."),
      ("B", "Accept and charge double the fee."),
      ("C", "Accept and immediately issue an adverse opinion."),
      ("D", "Ignore the limitation.")]),
    (42, "Modifications to the Opinion", "If the auditor expresses an adverse opinion, the opinion section states that:",
     [("A", "The financial statements present fairly except for minor matters."),
      ("B", "The financial statements do not present fairly (or give a true and fair view)... in accordance with PFRS."),
      ("C", "We do not express an opinion."),
      ("D", "The company is liquidated.")]),
    (43, "Modifications to the Opinion", "If the auditor disclaims an opinion, the opinion section states that:",
     [("A", "The financial statements are completely accurate."),
      ("B", "The auditor does not express an opinion on the accompanying financial statements."),
      ("C", "The financial statements present fairly."),
      ("D", "The company owes back taxes.")]),
    (44, "Modifications to the Opinion", "When an auditor disclaims an opinion due to an inability to obtain sufficient evidence, the Basis for Disclaimer section:",
     [("A", "Is omitted entirely."),
      ("B", "Lists all audit procedures performed."),
      ("C", "Describes the reasons for the inability to obtain sufficient appropriate audit evidence."),
      ("D", "Calculates net income under US GAAP.")]),
    (45, "Modifications to the Opinion", "An entity refuses to capitalize leases as required by PFRS 16. The lease obligations and assets represent 10% of total assets and 8% of total liabilities. The effect is material but not pervasive. The auditor should express a(n):",
     [("A", "Qualified opinion"),
      ("B", "Adverse opinion"),
      ("C", "Disclaimer of opinion"),
      ("D", "Unmodified opinion")]),
    (46, "Modifications to the Opinion", "An entity was unable to count inventory at year-end due to military conflict, and no alternative procedures were feasible. Inventory is 60% of total assets. The possible effect is both material and pervasive. The auditor should express a(n):",
     [("A", "Disclaimer of opinion"),
      ("B", "Adverse opinion"),
      ("C", "Qualified opinion"),
      ("D", "Unmodified opinion")]),
    (47, "Modifications to the Opinion", "Which of the following opinion modifications never arises from a scope limitation?",
     [("A", "Qualified opinion"),
      ("B", "Disclaimer of opinion"),
      ("C", "Adverse opinion"),
      ("D", "Both A and B")]),
    (48, "Modifications to the Opinion", "Which opinion modification arises exclusively from material and pervasive misstatements?",
     [("A", "Qualified opinion"),
      ("B", "Disclaimer of opinion"),
      ("C", "Adverse opinion"),
      ("D", "Emphasis of matter")]),
    (49, "Modifications to the Opinion", "When a qualified opinion is issued, where is the Basis for Qualified Opinion section located?",
     [("A", "At the very end of the notes to financial statements."),
      ("B", "Before the Title."),
      ("C", "In the client's press release."),
      ("D", "Immediately following the Qualified Opinion section.")]),
    (50, "Modifications to the Opinion", "If the auditor determines that a departure from PFRS is justified to prevent the financial statements from being misleading (fair presentation override), the auditor may issue:",
     [("A", "An adverse opinion"),
      ("B", "A disclaimer of opinion"),
      ("C", "An unmodified opinion with adequate disclosure and explanation"),
      ("D", "A fine to the client")]),
    (51, "Modifications to the Opinion", "An auditor who qualifies an opinion because of an inadequate disclosure should describe the omission in:",
     [("A", "The opinion paragraph only"),
      ("B", "The engagement letter"),
      ("C", "The Basis for Qualified Opinion section, and include the omitted disclosure if practicable"),
      ("D", "A separate letter to the BIR")]),
    (52, "Modifications to the Opinion", "When the auditor disclaims an opinion, the auditor's responsibility section:",
     [("A", "Is expanded to ten pages."),
      ("B", "States that the auditor is an insurer."),
      ("C", "Is eliminated entirely."),
      ("D", "Is amended to state only that the auditor's responsibility is to conduct the audit in accordance with PSAs and issue an auditor's report.")]),
    (53, "Modifications to the Opinion", "A scope limitation imposed by management that prevents the auditor from removing an impediment to obtaining evidence will most likely cause the auditor to:",
     [("A", "Resign from the engagement, if practicable and permitted by law, or disclaim an opinion."),
      ("B", "Express an unqualified opinion."),
      ("C", "Issue an adverse opinion automatically."),
      ("D", "Perform no further work and bill the client.")]),
    (54, "Modifications to the Opinion", "Can an auditor express an adverse opinion on one financial statement while expressing an unmodified opinion on another in the same report?",
     [("A", "Yes, piecemeal opinions are allowed in specific separate financial statements if not contradicting each other (e.g., adverse on financial position, but unmodified on cash flows)."),
      ("B", "No, never."),
      ("C", "Only if approved by the client's internal auditor."),
      ("D", "Only for nonprofit organizations.")]),
    (55, "Modifications to the Opinion", "When the auditor expresses an adverse opinion, the Key Audit Matters section (PSA 701):",
     [("A", "Must be expanded to 20 pages."),
      ("B", "Still applies, but the matter giving rise to the adverse opinion is described in the Basis for Adverse Opinion section, not KAM."),
      ("C", "Is prohibited from being included."),
      ("D", "Replaces the financial statements.")]),
    (56, "Modifications to the Opinion", "When the auditor disclaims an opinion, the Key Audit Matters section:",
     [("A", "Must be included with full details."),
      ("B", "Shall not be included, unless required by law or regulation."),
      ("C", "Must list at least five items."),
      ("D", "Is sent to the SEC only.")]),
    (57, "Modifications to the Opinion", "In a qualified opinion, the phrase used in the opinion paragraph is typically:",
     [("A", "'With the exception of the general ledger...'"),
      ("B", "'Subject to the future results of...'"),
      ("C", "'In our opinion, except for the effects of the matter described in the Basis for Qualified Opinion section...'"),
      ("D", "'We do not believe these statements are true...'")]),
    (58, "Modifications to the Opinion", "The phrase 'subject to' in an audit opinion paragraph is:",
     [("A", "Mandatory under PSA 705"),
      ("B", "Permitted for going concern issues only"),
      ("C", "No longer permissible because it is ambiguous"),
      ("D", "Required when taxes are unpaid")]),
    (59, "Modifications to the Opinion", "An auditor assesses an uncorrected misstatement of P50,000 against overall materiality of P500,000. The misstatement is immaterial. The appropriate opinion is:",
     [("A", "Unmodified opinion"),
      ("B", "Qualified opinion"),
      ("C", "Adverse opinion"),
      ("D", "Disclaimer of opinion")]),
    (60, "Modifications to the Opinion", "If an entity has an accounting records fire and all documentation for 90% of the year's revenue is lost, and no alternative evidence can be found, the auditor should express:",
     [("A", "Unmodified opinion"),
      ("B", "Adverse opinion"),
      ("C", "Disclaimer of opinion"),
      ("D", "Qualified opinion only")]),
    (61, "Emphasis of Matter and Other Matter Paragraphs", "An Emphasis of Matter paragraph is a paragraph included in the auditor's report that refers to:",
     [("A", "A matter appropriately presented or disclosed in the financial statements that, in the auditor's judgment, is of such importance that it is fundamental to users' understanding."),
      ("B", "A matter other than those presented or disclosed in the financial statements."),
      ("C", "A material misstatement that management refused to correct."),
      ("D", "A disagreement with the board of directors.")]),
    (62, "Emphasis of Matter and Other Matter Paragraphs", "An Emphasis of Matter paragraph:",
     [("A", "Is a substitute for expressing a modified opinion."),
      ("B", "Does not affect the auditor's opinion (the opinion is unmodified regarding the matter)."),
      ("C", "Is a substitute for disclosures required of management under PFRS."),
      ("D", "Replaces the Basis for Opinion section.")]),
    (63, "Emphasis of Matter and Other Matter Paragraphs", "An Emphasis of Matter paragraph should:",
     [("A", "Be placed before the Opinion section."),
      ("B", "State that the auditor disclaims all responsibility."),
      ("C", "Be included immediately after the Basis for Opinion section, with a clear heading 'Emphasis of Matter', and refer to the relevant note."),
      ("D", "Be printed in invisible ink.")]),
    (64, "Emphasis of Matter and Other Matter Paragraphs", "Circumstances where an Emphasis of Matter paragraph may be appropriate include:",
     [("A", "A material misstatement in accounts receivable."),
      ("B", "An uncertainty relating to the future outcome of exceptional litigation or regulatory action, or early application of a new accounting standard."),
      ("C", "A scope limitation preventing audit of inventory."),
      ("D", "Lack of auditor independence.")]),
    (65, "Emphasis of Matter and Other Matter Paragraphs", "An Other Matter paragraph is a paragraph that refers to:",
     [("A", "A matter presented and disclosed in Note 1."),
      ("B", "A matter other than those presented or disclosed in the financial statements that is relevant to users' understanding of the audit, auditor's responsibilities, or report."),
      ("C", "Management's secret business plans."),
      ("D", "A qualification of the audit opinion.")]),
    (66, "Emphasis of Matter and Other Matter Paragraphs", "Which of the following is an example of when an Other Matter paragraph is used?",
     [("A", "When the auditor qualifies the report for a departure from GAAP."),
      ("B", "When reporting on comparative financial statements where prior period was audited by a predecessor auditor."),
      ("C", "When management commits fraud."),
      ("D", "When the entity has negative operating cash flows.")]),
    (67, "Emphasis of Matter and Other Matter Paragraphs", "Can an Emphasis of Matter paragraph be used instead of a qualification if management's note disclosure is comprehensive?",
     [("A", "Yes, always."),
      ("B", "Yes, if approved by the audit committee."),
      ("C", "No, an Emphasis of Matter is not a substitute for a modified opinion when PFRS is breached."),
      ("D", "Yes, if the auditor files a waiver with the PRC.")]),
    (68, "Emphasis of Matter and Other Matter Paragraphs", "The heading for an Emphasis of Matter paragraph must include the term:",
     [("A", "'Warning to Investors'"),
      ("B", "'Emphasis of Matter'"),
      ("C", "'Qualified Item'"),
      ("D", "'Special Note'")]),
    (69, "Emphasis of Matter and Other Matter Paragraphs", "If an auditor applies PSA 706 and includes an Emphasis of Matter paragraph, the opinion paragraph shall state:",
     [("A", "'Our opinion is modified in respect of this matter.'"),
      ("B", "'Our opinion is not modified in respect of this matter.'"),
      ("C", "'We disclaim an opinion on this matter.'"),
      ("D", "'We guarantee the outcome of this matter.'")]),
    (70, "Emphasis of Matter and Other Matter Paragraphs", "Where is an Other Matter paragraph positioned in the auditor's report?",
     [("A", "Immediately after the Basis for Opinion section or after Key Audit Matters, with the heading 'Other Matter'."),
      ("B", "At the top before the title."),
      ("C", "Inside the balance sheet."),
      ("D", "In the client's directory.")]),
    (71, "Emphasis of Matter and Other Matter Paragraphs", "Which standard provides guidelines on Emphasis of Matter and Other Matter paragraphs?",
     [("A", "PSA 500"), ("B", "PSA 315"), ("C", "PSA 700"), ("D", "PSA 706 (Revised)")]),
    (72, "Emphasis of Matter and Other Matter Paragraphs", "An Emphasis of Matter paragraph is used for a significant subsequent event occurring between report date and issuance date when:",
     [("A", "Financial statements are amended and a new auditor's report is issued."),
      ("B", "The client refuses to amend the financial statements."),
      ("C", "The event is immaterial."),
      ("D", "The auditor withdraws from the audit.")]),
    (73, "Emphasis of Matter and Other Matter Paragraphs", "An Other Matter paragraph cannot be used to discuss:",
     [("A", "Auditor's reporting responsibilities under local laws."),
      ("B", "Matters that the auditor is prohibited by professional standards from disclosing."),
      ("C", "Prior period financial statements audited by another CPA."),
      ("D", "Supplementary financial information not required to be audited.")]),
    (74, "Emphasis of Matter and Other Matter Paragraphs", "If a material catastrophe (e.g., major flood) severely impacted the entity after the reporting period and is disclosed in Note 25, the auditor should:",
     [("A", "Issue an adverse opinion."),
      ("B", "Include an Emphasis of Matter paragraph referring to Note 25."),
      ("C", "Disclaim an opinion."),
      ("D", "Refuse to sign the report.")]),
    (75, "Emphasis of Matter and Other Matter Paragraphs", "When communicating Key Audit Matters, does a matter described as KAM also require an Emphasis of Matter paragraph?",
     [("A", "No, matters determined to be Key Audit Matters are not included in an Emphasis of Matter paragraph."),
      ("B", "Yes, all KAMs must be duplicated in Emphasis of Matter."),
      ("C", "Only if the client agrees."),
      ("D", "Only for financial institutions.")]),
    (76, "Emphasis of Matter and Other Matter Paragraphs", "If an entity prepares financial statements in accordance with a special purpose framework, the auditor's report shall include:",
     [("A", "An adverse opinion"),
      ("B", "A disclaimer of opinion"),
      ("C", "An Emphasis of Matter paragraph alerting users that the financial statements are prepared in accordance with a special purpose framework"),
      ("D", "No opinion")]),
    (77, "Emphasis of Matter and Other Matter Paragraphs", "Restriction on distribution or use of the auditor's report is typically accomplished by:",
     [("A", "A verbal agreement"),
      ("B", "An Other Matter paragraph stating that the report is intended solely for specific users"),
      ("C", "Locking the report in a safe"),
      ("D", "A qualified opinion")]),
    (78, "Emphasis of Matter and Other Matter Paragraphs", "An auditor wishes to draw attention to the fact that the company is a subsidiary of a foreign multinational corporation. If appropriately disclosed, this can be done via:",
     [("A", "A qualified opinion"),
      ("B", "An Emphasis of Matter paragraph"),
      ("C", "An adverse opinion"),
      ("D", "A disclaimer of opinion")]),
    (79, "Emphasis of Matter and Other Matter Paragraphs", "An Other Matter paragraph stating that prior period financial statements were audited by a predecessor auditor will specify:",
     [("A", "The predecessor auditor's home address."),
      ("B", "That prior financial statements were audited by a predecessor, the type of opinion expressed, and the date of that report."),
      ("C", "The predecessor's hourly billing rate."),
      ("D", "The names of all predecessor audit assistants.")]),
    (80, "Emphasis of Matter and Other Matter Paragraphs", "Can an Emphasis of Matter paragraph be included in a report containing a qualified opinion?",
     [("A", "No, never."),
      ("B", "Only if the qualification is due to scope limitation."),
      ("C", "Only if the qualification is due to departure from GAAP."),
      ("D", "Yes, provided the matter emphasized is not the matter that gave rise to the qualification.")]),
    (81, "Key Audit Matters & Comparative Information", "Key Audit Matters (PSA 701) are defined as:",
     [("A", "All matters discussed during audit committee meetings."),
      ("B", "Those matters that, in the auditor's professional judgment, were of most significance in the audit of the financial statements of the current period."),
      ("C", "The largest dollar balances on the balance sheet."),
      ("D", "All errors detected and corrected by management.")]),
    (82, "Key Audit Matters & Comparative Information", "Under PSA 701, the communication of Key Audit Matters is mandatory for:",
     [("A", "Audits of complete sets of general purpose financial statements of listed entities."),
      ("B", "All audits of sole proprietorships."),
      ("C", "Audits of small charities only."),
      ("D", "Compilation engagements.")]),
    (83, "Key Audit Matters & Comparative Information", "Key Audit Matters are selected from:",
     [("A", "Newspaper clippings about the client."),
      ("B", "Matters communicated with those charged with governance."),
      ("C", "Personal notes of the junior auditor."),
      ("D", "The client's social media posts.")]),
    (84, "Key Audit Matters & Comparative Information", "Which of the following is true regarding Key Audit Matters?",
     [("A", "KAM provides a separate opinion on individual matters."),
      ("B", "KAM is not a substitute for disclosures in the financial statements or for a modified opinion."),
      ("C", "KAM eliminates the need for an audit opinion."),
      ("D", "KAM is only used when the auditor resigns.")]),
    (85, "Key Audit Matters & Comparative Information", "The description of each Key Audit Matter in the auditor's report must include:",
     [("A", "Why the matter was considered to be one of most significance in the audit."),
      ("B", "How the matter was addressed in the audit."),
      ("C", "Reference to the related disclosure(s), if any, in the financial statements."),
      ("D", "All of the above.")]),
    (86, "Key Audit Matters & Comparative Information", "Areas that are commonly identified as Key Audit Matters include:",
     [("A", "Significant accounting estimates with high estimation uncertainty (e.g., goodwill impairment, fair value of complex instruments)."),
      ("B", "Immaterial petty cash balances."),
      ("C", "Routine monthly utility payments."),
      ("D", "Payment of standard trade receivables.")]),
    (87, "Key Audit Matters & Comparative Information", "If an auditor has no Key Audit Matters to communicate for a listed entity, the auditor should:",
     [("A", "Invent an imaginary matter."),
      ("B", "Omit the KAM section without explanation."),
      ("C", "State in the KAM section that there are no key audit matters to communicate."),
      ("D", "Disclaim an opinion.")]),
    (88, "Key Audit Matters & Comparative Information", "Comparative information in the financial statements (PSA 710) may be presented as:",
     [("A", "Current figures only."),
      ("B", "Unaudited projections."),
      ("C", "Corresponding figures or comparative financial statements."),
      ("D", "Tax-basis figures.")]),
    (89, "Key Audit Matters & Comparative Information", "When 'corresponding figures' are presented, the auditor's opinion:",
     [("A", "Explicitly refers to each year separately in all cases."),
      ("B", "Refers only to prior years."),
      ("C", "Refers to the current period only, unless the prior period audit report was modified and the matter remains unresolved."),
      ("D", "Disclaims the prior year.")]),
    (90, "Key Audit Matters & Comparative Information", "When 'comparative financial statements' are presented, the auditor's opinion:",
     [("A", "Ignores the prior period."),
      ("B", "Is signed by the predecessor auditor only."),
      ("C", "Covers only the earliest year."),
      ("D", "Refers to each period for which financial statements are presented.")]),
    (91, "Key Audit Matters & Comparative Information", "If the prior period financial statements were not audited, the auditor shall state in an Other Matter paragraph that:",
     [("A", "The corresponding figures are unaudited."),
      ("B", "The prior statements are fully certified."),
      ("C", "The auditor assumes full liability for the prior period."),
      ("D", "The prior statements must be discarded.")]),
    (92, "Key Audit Matters & Comparative Information", "If the auditor changes the audit opinion on the prior period financial statements in the current report, the auditor shall disclose:",
     [("A", "The attorney's legal fees."),
      ("B", "The date and opinion previously expressed, the reason for the change, and the fact that the updated opinion differs."),
      ("C", "The bonus received by the auditor."),
      ("D", "The name of the competing audit firm.")]),
    (93, "Key Audit Matters & Comparative Information", "The communication of KAM is intended to:",
     [("A", "Confuse users of financial statements."),
      ("B", "Provide an excuse for poor auditing."),
      ("C", "Enhance the communicative value of the auditor's report by providing greater transparency about the audit."),
      ("D", "Replace management's responsibility for financial reporting.")]),
    (94, "Key Audit Matters & Comparative Information", "When determining Key Audit Matters, the auditor takes into account:",
     [("A", "Areas of higher assessed risk of material misstatement or significant risks."),
      ("B", "Significant auditor judgments relating to areas that involved significant management judgment."),
      ("C", "The effect on the audit of significant events or transactions during the period."),
      ("D", "All of the above.")]),
    (95, "Key Audit Matters & Comparative Information", "Can an auditor be required to communicate KAM for non-listed entities?",
     [("A", "Yes, when required by law or regulation, or when the auditor decides to do so voluntarily."),
      ("B", "No, it is strictly illegal for non-listed entities."),
      ("C", "Only if the entity has foreign sales."),
      ("D", "Only if the entity has more than 1,000 employees.")]),
    (96, "Key Audit Matters & Comparative Information", "If the prior period financial statements were audited by another auditor (predecessor), the successor auditor:",
     [("A", "Must re-audit the prior year in all cases."),
      ("B", "May state in an Other Matter paragraph that prior statements were audited by a predecessor, type of opinion, and date of report."),
      ("C", "Must delete the prior year from the comparative columns."),
      ("D", "Is legally liable for the predecessor's work.")]),
    (97, "Key Audit Matters & Comparative Information", "The concept of 'Key Audit Matters' was introduced into auditing standards to address user demands for:",
     [("A", "Lower audit fees."),
      ("B", "Shorter audit reports."),
      ("C", "More relevant, entity-specific insights into the audit process beyond standardized boilerplate wording."),
      ("D", "Simpler accounting rules.")]),
    (98, "Key Audit Matters & Comparative Information", "If a matter that is a Key Audit Matter also gives rise to a qualified opinion, it is:",
     [("A", "Reported in the Basis for Qualified Opinion section, and referenced in the KAM section."),
      ("B", "Omitted completely from the report."),
      ("C", "Reported only in the local newspaper."),
      ("D", "Kept secret between the auditor and management.")]),
    (99, "Key Audit Matters & Comparative Information", "Under PSA 720 (Revised), the auditor's responsibilities relating to other information (such as an Annual Report) include:",
     [("A", "Auditing the other information with full substantive testing."),
      ("B", "Reading the other information and considering whether there is a material inconsistency between it and the financial statements or audit knowledge."),
      ("C", "Writing the other information on behalf of management."),
      ("D", "Ignoring the other information completely.")]),
    (100, "Key Audit Matters & Comparative Information", "If the auditor identifies a material inconsistency in other information that management refuses to correct, the auditor should:",
     [("A", "Issue a standard clean report without comment."),
      ("B", "Destroy the client's annual report."),
      ("C", "Communicate the matter to those charged with governance and determine appropriate action, including describing it in the 'Other Information' section of the report."),
      ("D", "Pay the fine on behalf of the client.")])
]

chapter12 = {
    "id": "at-12",
    "code": "AT-12",
    "title": "Reports on Audited Financial Statements",
    "description": "Forming an opinion and reporting on financial statements (PSA 700 Revised), unmodified opinions, modifications to the opinion (qualified, adverse, disclaimer - PSA 705 Revised), Emphasis of Matter and Other Matter paragraphs (PSA 706 Revised), Key Audit Matters (PSA 701), and comparative information (PSA 710).",
    "objectives": [
        "Nature and Elements of the Auditor's Report",
        "Modifications to the Opinion",
        "Emphasis of Matter and Other Matter Paragraphs",
        "Key Audit Matters & Comparative Information"
    ],
    "totalQuestions": 100,
    "questions": []
}

for num, obj, qtext, opts in at12_raw:
    correct = at12_answers[num]
    expl = at12_explanations.get(num, f"Suggested Answer: {correct}. In accordance with PSA 700 (Revised), PSA 701, PSA 705 (Revised), PSA 706 (Revised), and PSA 710.")
    chapter12["questions"].append({
        "id": f"at12-{num}",
        "number": num,
        "chapterId": "at-12",
        "chapterCode": "AT-12",
        "chapterTitle": "Reports on Audited Financial Statements",
        "objective": obj,
        "question": qtext,
        "options": [{"key": k, "text": t} for k, t in opts],
        "correctAnswer": correct,
        "explanation": expl
    })

with open("src/data/chapters/at12.ts", "w", encoding="utf-8") as f:
    f.write(f"import {{ Chapter }} from '../../types/quiz';\n\nexport const chapter12: Chapter = {json.dumps(chapter12, indent=2)};\n")

print("Created at12.ts with 100 questions")
