#!/usr/bin/env python3
import json

at08_answers = {
    1: 'B', 2: 'C', 3: 'C', 4: 'C', 5: 'A', 6: 'D', 7: 'B', 8: 'A', 9: 'D', 10: 'C',
    11: 'C', 12: 'D', 13: 'D', 14: 'D', 15: 'C', 16: 'C', 17: 'C', 18: 'A', 19: 'C', 20: 'A',
    21: 'D', 22: 'C', 23: 'B', 24: 'D', 25: 'D', 26: 'D', 27: 'D', 28: 'B', 29: 'B', 30: 'D',
    31: 'D', 32: 'C', 33: 'A', 34: 'A', 35: 'A', 36: 'B', 37: 'B', 38: 'C', 39: 'A', 40: 'C',
    41: 'D', 42: 'D', 43: 'C', 44: 'B', 45: 'B', 46: 'D', 47: 'B', 48: 'B', 49: 'C', 50: 'C',
    51: 'C', 52: 'C', 53: 'D', 54: 'C', 55: 'D', 56: 'C', 57: 'C', 58: 'C', 59: 'B', 60: 'A',
    61: 'B', 62: 'B', 63: 'B', 64: 'B', 65: 'B', 66: 'D', 67: 'C', 68: 'B', 69: 'D', 70: 'C',
    71: 'C', 72: 'D', 73: 'A', 74: 'C', 75: 'D', 76: 'B', 77: 'B', 78: 'C', 79: 'C', 80: 'D',
    81: 'A', 82: 'C', 83: 'C', 84: 'A', 85: 'C', 86: 'C', 87: 'D', 88: 'C', 89: 'D', 90: 'D'
}

at08_explanations = {
    4: "Tests of details of balances involve testing of the ending balance of an account.",
    6: "Tests of details of balances are broader in nature, as auditors must gather sufficient appropriate evidence for the entire balance.",
    7: "Substantive testing procedures are typically the most costly, but also typically the most effective. Sampling may help reduce these costs.",
    8: "Choices B, C, and D refer to test of controls.",
    9: "The objective of the auditor is to obtain sufficient and appropriate evidence that are effective and cost-efficient.",
    10: "A does not refer to any tests. B refers to gaining an understanding a client's internal control system. D refers to tests of transactions.",
    11: "Analytical procedures amongst all procedures are typically the most cost efficient.",
    13: "A refers to test of balances. Choices B and C refer to test of controls.",
    14: "By increasing appropriate analytical procedures, fewer substantive tests are required to properly support the conclusion which the auditor's opinion is based.",
    15: "Audit of the income statement focuses on the transactions that create an effect on the income statement. Choices A, B, D are more focused on the balances of the accounts themselves.",
    16: "A is impossible to guarantee as an auditor. B refers to only compliance, and nothing about materiality. D is wrong because we are only to determine that the balances are not materially misstated.",
    19: "Effectiveness is the priority over efficiency.",
    22: "When internal controls are deemed to be effective, this means that control risk is low and that evidence from these procedures can be relied upon.",
    23: "It is the relevance and reliability of the evidence to support the conclusions on which the auditor's opinion is based.",
    24: "A is incorrect because it is not only one-one relationships that are possible. B refers to quality of evidence. C refers to the quantity of audit evidence.",
    25: "Sufficiency of evidence refers to quantity of evidence.",
    26: "Appropriateness of evidence refers the quality of evidence.",
    27: "The auditor's professional judgement will always be the basis for all evidence gathering procedures.",
    28: "Choices A, C, and D all affect the types and quantity of evidence required to be obtained by the auditor.",
    29: "This has no bearing on the collection of appropriate evidence.",
    30: "Inquiry relies on the assertions of management, not what the auditor himself has obtained.",
    32: "A, B, and D are more persuasive than C because they are either obtained from the auditor himself, the client, or a 3rd party. Pre-numbered purchase order forms only assures that the documents are complete, nothing about its accuracy etc.",
    33: "Choices B, C, and D are impossible to guarantee in an audit engagement.",
    34: "Confirmation gives the most reliable evidence because it is externally generated.",
    35: "Choices B, C, and D are incorrect because confirmations should not pass through the client at all, if possible. This would lessen the risk that the information may be materially altered before it is obtained by the auditor.",
    36: "Size of sample has no bearing on whether an evidence can be considered reliable.",
    37: "Choices A, C, and D are incorrect because they are either irrelevant or they must be subjected to further testing to obtain assurance.",
    38: "Vendor's invoice can be proof of the said transaction.",
    39: "Inspection may be done during Tests of controls and but confirmation as a procedure is only available to test of details of balances and transactions.",
    40: "The best corroborating evidence are source documents that evidence the existence of a transaction.",
    41: "Bank statements originate from outside the company's system.",
    42: "The confirmation from a 3rd party will always be considered the most reliable because they have their own financial interests in maintaining the correct balance.",
    50: "Choices A, B, and D are all experts who may have knowledge or certifications that an auditor may not possess.",
    51: "Choices A, B, and D do not require the advice/work of an expert to be conducted.",
    52: "C would not require the work of an expert as it relies upon the professional judgement of the auditor.",
    64: "One of the primary purposes of the working papers is to provide documentation that the audit was properly conducted.",
    65: "A is incorrect as documentation by the customer may be considered reliable and relevant to the audit. C/D are incorrect as only significant matters should be documented in the audit working papers.",
    66: "An auditor's working papers must help substantiate the conclusion reached by the auditor that led to his opinion. One of the other primary purposes of the working papers is to provide documentation that the audit was properly conducted.",
    67: "Working papers should never be considered a replacement of the client's accounting records.",
    68: "Auditors may allow their clients to use their working papers as a reference source but not as a replacement of accounting records.",
    69: "Timing and number of personnel assigned to the audit will have no bearing on the working papers themselves.",
    70: "The working paper cannot be used to Justify the financial statement as this is just Documentation of Findings and Procedures done during the audit.",
    71: "Statement II is false because audit documentation is not meant to benefit the client's staff, but the auditor's staff instead.",
    72: "A is incorrect as auditors may allow their clients to use their working papers as a reference source. B is incorrect because it should only be used as a reference source and not as a replacement. C is incorrect because the statutory retention period of working papers in the Philippines is 10 years.",
    75: "The working trial balance will not be included in the permanent working papers as they only relate to the current audit and may not be applicable in the next period.",
    76: "Audit working paper does not provide proof of the records, but is just a documentation of the work done and conducted which is in accordance to the PSAs.",
    77: "A is incorrect as documents must be retained for a minimum of 5 years. C is incorrect as working papers can be made available to the client under certain circumstances (as a reference source). D is incorrect as working papers should never be considered a replacement of the client's accounting records.",
    78: "An auditor's working papers must help substantiate the conclusion reached by the auditor that led to his opinion. The nature and condition of the client's accounting and internal control system would determine the data and procedures listed in the working papers.",
    79: "Choices A, B, and D are included in the permanent working papers.",
    80: "A is incorrect because audit documentation has a minimum retention period before it can be considered deleted. B/C are incorrect because audit documentation may be deleted after the retention period of 10 years has lapsed.",
    81: "Cross-referencing is necessary to provide a trail for the supervisors in adequately reviewing the working papers.",
    82: "Audit documentation is also required to enable an experienced auditor, having no connection to the audit, to understand the audit procedures completed, the evidence obtained from said procedures, and significant matters arising during the audit.",
    83: "Choices A, B, and D are included in the permanent working papers.",
    84: "PSA 230 prescribes a 5-year retention period (or 7 years/10 years per local regulations).",
    85: "All data relating to supporting the auditor's opinion must documented in the auditor's working papers.",
    86: "The Audit program is required to be documented in the conduct of the audit to show evidence about the compliance with the PSAs.",
    88: "Documentation of procedures conducted should coincide with the objectives of the audit."
}

at08_raw = [
    (1, "Substantive Tests", "A procedure designed to test for monetary misstatements directly affecting the validity of the financial statement balances is a:",
     [("A", "Test of controls"), ("B", "Substantive test"), ("C", "Test of attributes"), ("D", "Monetary-unit sampling test.")]),
    (2, "Substantive Tests", "In the context of an audit of financial statements, substantive tests are audit procedures that:",
     [("A", "May be eliminated under certain conditions."), ("B", "Are designed under certain conditions."), ("C", "May be either tests of transactions, tests of balances, or analytical procedures."), ("D", "Will increase proportionately with the auditor's reliance on internal control.")]),
    (3, "Substantive Tests", "The objective of tests of details of transactions performed as substantive tests is to",
     [("A", "Monitor the design and use of entity documents such as prenumbered shipping form"), ("B", "Determine whether controls have been placed in operation"), ("C", "Detect material misstatements in the account balances of the financial statements"), ("D", "Evaluate whether controls operated effectively")]),
    (4, "Substantive Tests", "Which of the following is accurate?",
     [("A", "Tests of details of balances focus on the transactions during the period."), ("B", "Tests of details of balances focus on the auditor's understanding of internal controls."), ("C", "Tests of details of balances focus on the ending balances of accounts in the client's trial balance."), ("D", "Tests of details of balances focus on comparing reported amounts to the auditor's expectations.")]),
    (5, "Substantive Tests", "The primary emphasis in most tests of details of balances is on the:",
     [("A", "Balance sheet accounts."), ("B", "Income statement accounts."), ("C", "Cash flow statement."), ("D", "All of the Above")]),
    (6, "Substantive Tests", "More types of evidence are obtained by using what type of test than any other?",
     [("A", "Substantive tests of transactions."), ("B", "Test of controls."), ("C", "Analytical procedures."), ("D", "Tests of details of balances.")]),
    (7, "Substantive Tests", "When selecting audit tests to execute, the auditor analyzes cost in order to maximize audit efficiency. Which of the following audit tests would be the most costly?",
     [("A", "Analytical procedures"), ("B", "Test of details of balances"), ("C", "Risk assessment procedures"), ("D", "Test of controls")]),
    (8, "Substantive Tests", "The logic behind tests of details of transactions performed as substantive tests is to:",
     [("A", "Detect material misstatements in the account balances of the financial statements."), ("B", "Determine whether controls have been placed in operation."), ("C", "Evaluate whether controls operated effectively."), ("D", "Monitor the design and use of entity documents such as prenumbered shipping form.")]),
    (9, "Substantive Tests", "The reason why an auditor may decide to replace tests of details with analytical procedures is:",
     [("A", "Analytical procedures are not reliable."), ("B", "Analytical procedures are more persuasive."), ("C", "Tests of details are more difficult to interpret."), ("D", "Analytical procedures are less expensive or cost-efficient.")]),
    (10, "Substantive Tests", "Tests of details of balances are specific procedures applied in order to",
     [("A", "Prove that trial balance is in balance"), ("B", "Identify the details of the internal control system"), ("C", "Test for monetary errors in the balances in the financial statements"), ("D", "Prove that the accounts with material balances are classified correctly")]),
    (11, "Substantive Tests", "Which of the following audit tests is considered to be the least costly to apply?",
     [("A", "Tests of details of balances"), ("B", "Substantive tests of transactions"), ("C", "Analytical Procedures"), ("D", "Test of controls")]),
    (12, "Substantive Tests", "Analytical procedures are required to be performed during which phase(s) of an audit?\nPlanning | Test of Control | Completion\nA. Yes | Yes | No\nB. No | No | Yes\nC. Yes | Yes | Yes\nD. Yes | No | Yes",
     [("A", "Yes, Yes, No"), ("B", "No, No, Yes"), ("C", "Yes, Yes, Yes"), ("D", "Yes, No, Yes")]),
    (13, "Substantive Tests", "Analytical procedures pertain to those that:",
     [("A", "Evaluate the accuracy of the account balances"), ("B", "Review the effectiveness of internal control procedures on the accounting system"), ("C", "Analyze of the effect of management procedures on the accounting system"), ("D", "Evaluate the transactions and balances in terms of their overall reasonableness.")]),
    (14, "Substantive Tests", "The main significance of performing analytical procedures in the testing phase of an audit is to:",
     [("A", "Assist the auditor in gaining a thorough grasp of the client's industry and operations."), ("B", "Assess the going concern assumption."), ("C", "Indicate possible misstatements."), ("D", "Reduce tests of details of balances.")]),
    (15, "Substantive Tests", "The main distinction between an audit of the balance sheet and an audit of the income statement lies in the fact that the audit of the income statement deals with the verification of:",
     [("A", "Authorizations"), ("B", "Costs"), ("C", "Transactions"), ("D", "Cutoffs")]),
    (16, "Audit Procedures", "Which of the following statements is most correct regarding the primary purpose of audit procedures?",
     [("A", "To detect all errors or fraudulent activities as well as illegal activities."), ("B", "To comply with the SEC."), ("C", "To gather corroborative audit evidence about management's assertions regarding the client's financial statements."), ("D", "To determine the amount of errors in the balance sheet accounts in order to adjust the accounts to actual.")]),
    (17, "Audit Evidence", "The information obtained by the auditor in arriving at the conclusion on which the audit is based is called:",
     [("A", "Audit working papers"), ("B", "Audit assertions"), ("C", "Audit evidence"), ("D", "Audit standards")]),
    (18, "Audit Evidence", "The major reason an independent auditor gathers evidence is to:",
     [("A", "Form an opinion on the financial statements."), ("B", "Detect fraud."), ("C", "Evaluate management."), ("D", "Evaluate internal control.")]),
    (19, "Audit Evidence", "The different ways an auditor can gather evidence are influenced by two overarching considerations:\nI. Sufficient appropriate evidence must be gathered in order for the auditor to fulfill his or her professional responsibilities.\nII. The cost of gathering evidence should minimized.\nWhich is the most accurate in evaluating these considerations?",
     [("A", "The second is more important than the first"), ("B", "They are equally important"), ("C", "The first is more important than the second"), ("D", "It is impossible to prioritize them")]),
    (20, "Audit Evidence", "Evidence is usually more persuasive for balance sheet accounts when it is obtained:",
     [("A", "As close to the balance sheet date as possible."), ("B", "Only from transactions occurring on the balance sheet date."), ("C", "From various times throughout the client's year."), ("D", "From the time period when transactions in that account were most numerous during the fiscal period.")]),
    (21, "Audit Evidence", "Which of the following statements relating to the competence of evidential matter is always true?",
     [("A", "Evidence from outside an enterprise is always reliable"), ("B", "Accounting data developed under satisfactory conditions of internal control are more relevant that data developed under unsatisfactory internal control conditions"), ("C", "Oral representations made by management are not reliable evidence"), ("D", "Evidence must be both reliable and relevant to be considered appropriate")]),
    (22, "Audit Evidence", "Which of the following is correct about the appropriateness of evidence?",
     [("A", "Audit evidence from external sources is more relevant than evidence generated internally"), ("B", "Audit evidence is more persuasive when items of evidence from different sources of different nature are not consistent"), ("C", "Audit evidence generated internally is more reliable when the related accounting and internal control systems are effective"), ("D", "Sufficiency refers to the amount of evidence needed")]),
    (23, "Audit Evidence", "Appropriateness of evidence is a measure of the:",
     [("A", "Quantity of evidence"), ("B", "Quality of evidence"), ("C", "Sufficiency of evidence"), ("D", "Meaning of evidence")]),
    (24, "Audit Evidence", "Which of the following statements about audit evidence is correct?",
     [("A", "There should be a one-to-one relationship between audit objective and audit procedure."), ("B", "Appropriateness is the measure of the quantity of audit evidence."), ("C", "Sufficiency is the measure of the quality of audit evidence and its relevance to a particular assertion an its reliability."), ("D", "Audit evidence is more persuasive when items of evidence from different sources or of different nature are consistent.")]),
    (25, "Audit Evidence", "Evidence is considered to be sufficient if:",
     [("A", "It is appropriate."), ("B", "It has the qualities of being relevant, objective, and free of bias."), ("C", "It has been obtained by random selection."), ("D", "It is enough to provide a reasonable basis for an audit opinion on the financial statements.")]),
    (26, "Audit Evidence", "Evidence is considered to be appropriate if:",
     [("A", "It consists of representations made by management of the company under audit."), ("B", "It has been obtained by random selection."), ("C", "It is enough to provide a reasonable basis for an audit opinion on the financial statements."), ("D", "It has the qualities of being relevant, objective, and free from known bias")]),
    (27, "Audit Evidence", "The sufficiency and appropriateness of evidential matter ultimately is based on the:",
     [("A", "Availability of corroborating data"), ("B", "Philippine Standards on Auditing"), ("C", "Pertinence of the evidence"), ("D", "Judgment of the auditor")]),
    (28, "Audit Evidence", "Which of the following would not have an effect on the amount of audit evidence gathered by the auditor?",
     [("A", "The type of opinion to be issued"), ("B", "Whether the client is required to file a report with the Securities and Exchange Commission."), ("C", "The auditor's evaluation of internal control"), ("D", "The types of audit evidence available to the auditor")]),
    (29, "Audit Evidence", "Which of the following is not a characteristic of the appropriateness of evidence?",
     [("A", "Effectiveness of client internal controls"), ("B", "Education of auditor"), ("C", "Independence of information provider"), ("D", "Timeliness")]),
    (30, "Audit Evidence", "Evidence obtained directly by the auditor is more reliable than information obtained indirectly. Which of the following is not an example of the auditor's direct knowledge?",
     [("A", "Physical examination"), ("B", "Observation"), ("C", "Computation"), ("D", "Inquiry")]),
    (31, "Audit Evidence", "Which of the following \"decisions\" are relevant to the auditor's evidence accumulation?",
     [("A", "Type of audit procedure to use."), ("B", "Number of items to examine."), ("C", "Timing of audit procedures."), ("D", "All of the above are relevant.")]),
    (32, "Audit Evidence", "Which of the following types of audit evidence is considered to be the least persuasive?",
     [("A", "Test counts of inventory performed by the auditor"), ("B", "Correspondence from the client's attorney about litigation."), ("C", "Prenumbered purchase order forms"), ("D", "Bank statements obtained from the client")]),
    (33, "Audit Evidence", "Given the economic and tie limits on auditors' ability to gather evidence about management's financial statement assertions, the auditor normally gathers evidence that is;",
     [("A", "Persuasive"), ("B", "Completely convincing"), ("C", "Irrefutable"), ("D", "Conclusively")]),
    (34, "Audit Evidence", "Which of the following audit procedures gives the most reliable evidence of the accounts receivable balance's validity?",
     [("A", "Confirmation"), ("B", "Observations"), ("C", "Recalculation"), ("D", "Reperformance")]),
    (35, "Audit Evidence", "In order to be considered as reliable evidence, confirmation must be controlled by:",
     [("A", "A financial statement auditor"), ("B", "A client employee tasked to oversee for accounts receivable"), ("C", "A client's internal audit department"), ("D", "A client's controller")]),
    (36, "Audit Evidence", "Which of the following features of reliable evidence is not one of them?",
     [("A", "Effectiveness of internal control structure"), ("B", "Size of the sample"), ("C", "Degree of objectivity"), ("D", "Independence of provider")]),
    (37, "Audit Evidence", "For the auditor, relevance and dependability are the two most important aspects in audit evidence. Which of the following provides the auditor with the most reliable audit evidence?",
     [("A", "General ledger account balances"), ("B", "Confirmation of accounts payable balance received from a vendor or any other independent third party"), ("C", "Internal memo explaining the issuance of a credit memo"), ("D", "Copy of month-end adjusting entries")]),
    (38, "Audit Evidence", "The inspection of a vendor's invoice by the auditors is:",
     [("A", "Direct evidence about occurrence of a transaction."), ("B", "Physical evidence about occurrence of a transaction."), ("C", "Documentary evidence about occurrence of a transaction."), ("D", "Part of the client's accounting system.")]),
    (39, "Audit Evidence", "Physical examination and confirmations as part of audit evidence, may only be obtained by applying:",
     [("A", "Test of details of balances"), ("B", "Test of controls"), ("C", "Analytical procedures"), ("D", "Test of loyalty")]),
    (40, "Audit Evidence", "Which of the following is the best example of a corroborating evidence?",
     [("A", "General journal"), ("B", "Worksheet cost allocations"), ("C", "Vendor's invoice"), ("D", "Cash receipts journal")]),
    (41, "Audit Evidence", "Which of the following is considered as external documents?",
     [("A", "Purchase order for company purchases"), ("B", "Carbon copies of checks"), ("C", "Employees' time reports"), ("D", "Bank statements")]),
    (42, "Audit Evidence", "Which of the following forms of evidence is considered to be the most reliable?",
     [("A", "General ledger account balances"), ("B", "Internal memo explaining the issuance of a credit memo"), ("C", "Copy of month-end adjusting entries"), ("D", "Confirmation of receivable balance received from a customer")]),
    (43, "Audit Evidence", "A person or firm possessing special skill, knowledge and experience in a particular field other than accounting and auditing is called a/an",
     [("A", "Professional"), ("B", "Consultant"), ("C", "Expert"), ("D", "Assistant")]),
    (44, "Audit Evidence", "Which of the following is not an expert upon whose work an auditor may rely?",
     [("A", "Actuary"), ("B", "Internal Auditor"), ("C", "Appraiser"), ("D", "Engineer")]),
    (45, "Audit Evidence", "During an audit, the auditor may need the assistance of an expert in obtaining sufficient appropriate evidence. A common example is",
     [("A", "Evaluating the potential financial statement effect of a employee fraud"), ("B", "Determination of the amounts using actuarial computations"), ("C", "Evaluating the integrity of management"), ("D", "Determining the sufficiency and appropriateness of evidential matter obtained")]),
    (46, "Audit Evidence", "Each of the following procedure requires the assistance of an expert except",
     [("A", "Determining the physical condition or quantity of underground mineral"), ("B", "Determining the value of works of art"), ("C", "Interpreting major contracts"), ("D", "Determining the adequacy of disclosure in the notes to the financial statements")]),
    (47, "Audit Evidence", "A individual, or firm with specialized knowledge, skills, and expertise in a sector other than accounting and auditing is referred to as a/an.",
     [("A", "Consultant"), ("B", "Expert"), ("C", "Professional"), ("D", "Assistant")]),
    (48, "Audit Evidence", "An expert whose expertise is used by the entity in preparing financial statements is called a(n):",
     [("A", "Financial expert"), ("B", "Management expert"), ("C", "Auditor's expert"), ("D", "Specialist")]),
    (49, "Audit Evidence", "An expert whose expertise is used by the firm in obtaining sufficient appropriate evidence is called a(n):",
     [("A", "Financial expert"), ("B", "Management expert"), ("C", "Auditor's expert"), ("D", "Specialist")]),
    (50, "Audit Evidence", "Which of the following is not a qualified expert on whose work an auditor may rely?",
     [("A", "Appraiser"), ("B", "Engineer"), ("C", "Internal Auditor"), ("D", "Actuary")]),
    (51, "Audit Evidence", "Obtaining adequate acceptable evidence during an audit may necessitate the assistance of an expert. A common example is",
     [("A", "Evaluating the potential financial statement effect of a employee fraud"), ("B", "Assessing the sufficiency and appropriateness of the evidence gathered"), ("C", "Calculation of the amounts based on actuarial calculations"), ("D", "Evaluating the integrity of management")]),
    (52, "Audit Evidence", "Each of the following procedure requires the assistance of an expert, which one is exception?",
     [("A", "Determining the physical state or quantity of underground mineral deposits."), ("B", "Interpreting major contracts"), ("C", "Determining the sufficiency of the notes to the financial statements in terms of disclosure"), ("D", "Determining the value of works of art")]),
    (53, "Audit Evidence", "When may the auditor refer to an expert's work in the audit report?\nOnly if report results in a modified opinion | Only when expert assisted in audit of material accounts\nA. Yes | Yes\nB. No | No\nC. No | Yes\nD. Yes | No",
     [("A", "Yes, Yes"), ("B", "No, No"), ("C", "No, Yes"), ("D", "Yes, No")]),
    (54, "Audit Evidence", "The independent auditor should acquire an understanding of the internal audit function as it relates to the independent auditor's study and evaluation of internal control because the:",
     [("A", "Audit programs, working papers, and reports of internal auditors can often be used as a substitute for the work of the independent auditor's staff."),
      ("B", "Procedures performed by the internal audit staff may eliminate the independent auditors need for an extensive study and evaluation of internal control"),
      ("C", "Work performed by internal auditors may be a factor in determining the nature, timing and extent of the independent auditor's procedures"),
      ("D", "Understanding of the internal audit function is an important substantive test to be performed by the independent auditor")]),
    (55, "Audit Evidence", "External auditors must obtain evidence regarding what attributes of an internal audit department if the external auditors intend to rely on internal auditor's work?",
     [("A", "Integrity"), ("B", "Objectivity"), ("C", "Competence"), ("D", "All of the above")]),
    (56, "Audit Evidence", "Which of the following statements about internal auditor and the external auditor is not correct?",
     [("A", "The role of internal auditing is determined by management and its objectives differ from those of the external auditor who is appointed to report independently on the financial statements"),
      ("B", "The external auditor has the sole responsibility for the audit opinion expresses and that responsibility is not reduced by any use made of internal auditing"),
      ("C", "Internal auditors should exercise the same degree of independence as required of the external auditor"),
      ("D", "All judgements relating to the audit of the financial statements are those of the external auditor")]),
    (57, "Audit Evidence", "Which of the following statements in relation to the preliminary assessment of internal auditing is false?",
     [("A", "The external auditor should obtain a sufficient understanding of internal audit activities to assist in planning the audit and developing an effective audit approach"),
      ("B", "During the course of planning the audit, the external auditor should perform a preliminary assessment of the internal audit function when it appears that internal auditing is relevant to external audit of the financial statements in specific audit areas"),
      ("C", "Effective internal auditing will often allow a modification in the nature, timing, reduction in the extent and even eliminate in its entirety some procedures performed by the external auditor"),
      ("D", "In dome cases, after having considered the activities of internal auditing, the external auditor may decide that internal auditing will have no effect on external audit procedures")]),
    (58, "Audit Evidence", "An independent auditor might consider the procedures performed by the internal auditors because",
     [("A", "They are employees whose work must be reviewed during substantive testing"), ("B", "Their work affects the cost benefit trade-off"), ("C", "They are employees whose work may affect the nature, timing, and extent of audit procedures"), ("D", "Their degree of independence may be inferred from the nature of their work")]),
    (59, "Audit Evidence", "To assess the objectivity of the internal auditors; an independent auditor would most likely",
     [("A", "Consider the professional qualifications and experience of the internal auditors"), ("B", "Consider the organizational level to which the internal auditors report the results of their work"), ("C", "Consider proper planning, supervision and documentation of internal auditor's work"), ("D", "Consider the nature and extent of the internal auditors' assignment")]),
    (60, "Audit Documentation", "It refers to the material (working papers) prepared by and for, or obtained and retained by the auditor in connection with the performance of:",
     [("A", "Audit documentation"), ("B", "Audit report"), ("C", "Accounting data"), ("D", "Corroborative evidence")]),
    (61, "Audit Documentation", "Which of the following is the main advantage of properly indexing working papers?",
     [("A", "Reduce the size of the file."), ("B", "Better organize the working papers."), ("C", "Allow for division of labor among the audit team members."), ("D", "Facilitate the efficient use of audit staff.")]),
    (62, "Audit Documentation", "The primary purpose for cross-indexing audit working papers is to",
     [("A", "Give the working papers a professional appearance."), ("B", "Provide a trail for the auditor and the reviewer."), ("C", "Explain the purpose of tick marks."), ("D", "Provide explanation.")]),
    (63, "Audit Documentation", "Audit documentation must contain sufficient information to allow what type of auditor to understand the nature, timing, extent and results of procedures performed?",
     [("A", "An experienced audit team member."), ("B", "An experienced auditor having no previous connection with the engagement."), ("C", "Any certified public accountant."), ("D", "An auditor qualified as a peer review specialist.")]),
    (64, "Audit Documentation", "Which of the following is one of the objectives of audit documentation?",
     [("A", "To defend against claims of a deficient audit"), ("B", "To support auditor's representation of compliance with PSA"), ("C", "Provide reasonable assurance that the financial statements are fairly presented"), ("D", "None of the above")]),
    (65, "Audit Documentation", "Which of the following claims concerning working papers is correct?",
     [("A", "Documentation created by the customer should not be included in the working papers."),
      ("B", "The auditor should provide working papers that are comprehensive and detailed enough to provide a comprehensive understanding of the audit."),
      ("C", "Every matter the auditor considers in an audit must be documented in the working papers"),
      ("D", "Every aspect of an audit that the auditor considers must be documented in the working papers.")]),
    (66, "Audit Documentation", "In terms of audit documentation, which of the following criteria must audit documentation of the information acquired by the auditor meet?",
     [("A", "The purpose of gathering audit evidence is to assess if the client's financial statements, as prepared by management, can be relied upon to make economic decisions."),
      ("B", "Workpapers be indexed to the general ledger accounts and include both a permanent file and a general file."),
      ("C", "The purpose of audit evidence, as shown in the workpapers, is to protect the auditing company in the event of a lawsuit by investors."),
      ("D", "The content must be sufficient to support the auditor's opinion, including the auditor's representation that the auditing standards have been followed.")]),
    (67, "Audit Documentation", "Which of the following is not a primary function of working papers?",
     [("A", "To serve as an aid in the supervision and review of work"), ("B", "To serve as an aid in planning and performance of the audit"), ("C", "To serve as a substitute the client's accounting records"), ("D", "To serve as a record of the audit evidence resulting from audit work performed to support the auditor's opinion")]),
    (68, "Audit Documentation", "Which of the statements concerning working papers is true?",
     [("A", "The auditor should document the basis for assessing control risk at the maximum level"), ("B", "The client may be allowed to use working papers as a reference source."), ("C", "The financial statements are mostly supported by working papers."), ("D", "After two years, the independent auditor may discard working papers.")]),
    (69, "Audit Documentation", "Which of the following does not influence the independent auditor's decision on the quantity, type, and content of working papers?",
     [("A", "The nature of the engagement."), ("B", "The need for supervision."), ("C", "Forms of the report."), ("D", "The timing and the number of personnel to be assigned to the engagement.")]),
    (70, "Audit Documentation", "Which of the following is not a primary purpose of audit working papers?",
     [("A", "To coordinate the audit."), ("B", "To assist in preparation of the audit report."), ("C", "To support the financial statements."), ("D", "To provide evidence of the audit work performed.")]),
    (71, "Audit Documentation", "Certain characteristics should be present in audit documentation. Which of the following is true regarding those characteristics?\nS1: The audit documentation should be cross-referenced and indexed.\nS2: Audit documentation should be organized to benefit the client's staff.",
     [("A", "Both statements are true"), ("B", "Both statements are false"), ("C", "Statement I is true but statement II is false"), ("D", "Statement I is false but statement II is true")]),
    (72, "Audit Documentation", "Which of the following claims regarding working papers is true?",
     [("A", "Working papers are not permitted to be used as a reference source by the client"), ("B", "Working papers can be used in place of the client's accounting records."), ("C", "The independent auditor may destroy working materials after two years when reporting on comparative financial statements."), ("D", "In order to plan the audit, the auditor should document his or her understanding of the client's internal controls.")]),
    (73, "Audit Documentation", "An auditor's working papers serve mainly to:",
     [("A", "Provide the principal support for the auditor's report"), ("B", "Satisfy the auditor's responsibilities concerning the Code of Professional Ethics"), ("C", "Monitor the effectiveness of the CPA firm's quality control procedures"), ("D", "Document the level of independence maintained by the auditor")]),
    (74, "Audit Documentation", "Audit files that are updated with new information of continuing importance is called",
     [("A", "Current files"), ("B", "Working paper file"), ("C", "Permanent files"), ("D", "Correspondence file")]),
    (75, "Audit Documentation", "Which of the following would not be included as permanent file of an auditor's working papers?",
     [("A", "Bond indenture agreements"), ("B", "Lease agreements"), ("C", "Flowchart of the internal control structure"), ("D", "Working trial balance")]),
    (76, "Audit Documentation", "Which of the following is not a function of the audit working papers?",
     [("A", "Provide support for the auditors' report."), ("B", "Provide support for the accounting records."), ("C", "Aid partners in planning and conducting future audits."), ("D", "Document staff compliance with generally accepted auditing standards.")]),
    (77, "Audit Documentation", "PSA 230 establishes general standards for working paper ownership, custody, and secrecy. Accordingly,",
     [("A", "The auditor should keep the working papers for a reasonable amount of time, but not more than five years."), ("B", "The auditor's working papers are his or her personal property, and the client has no rights to the auditor's working papers."), ("C", "Working papers should not be made available to the client"), ("D", "Working papers could be used in place of the client's accounting records")]),
    (78, "Audit Documentation", "Which of the following influences the auditor's decisions on the quantity, type, and content of working papers the most?",
     [("A", "The content of the client's representation letter."), ("B", "When substantive testing were completed before the balance sheet date."), ("C", "The nature and condition of the client's accounting and internal control systems."), ("D", "The client's ability to use the working papers as a reference source.")]),
    (79, "Audit Documentation", "Which of the following should be included in the current file of the auditor's working papers?",
     [("A", "A flowchart of the internal accounting controls"), ("B", "Organization chart"), ("C", "A copy of the financial statements"), ("D", "Copies of bond and note indentures")]),
    (80, "Audit Documentation", "Which of the following statements about audit documentation deletion is correct?",
     [("A", "Superseded audit documentation should always be deleted from the audit file."), ("B", "The auditor should not destroy or discard audit documents after the audit file has been finished."), ("C", "Audit documentation should never be deleted from the audit file."), ("D", "When deciding which audit documents should be deleted, auditors should exercise professional skepticism.")]),
    (81, "Audit Documentation", "An audit supervisor discovers that the auditor's reported conclusions are not sufficiently cross-referenced to supporting documents during the working paper review. The supervisor will most likely instruct the auditor to",
     [("A", "Provide a workpaper indexing system that shows the relationship between findings, conclusions, and the related facts."), ("B", "Create a working paper to show that the audit was completed in its entirety."), ("C", "Familiarize himself/herself with the sequence of working papers so that he/she can respond to questions concerning the report's conclusions."), ("D", "Remove any cross-references to other working papers due to the ambiguity of the system.")]),
    (82, "Audit Documentation", "Which of the following statements about audit documentations is incorrect?",
     [("A", "The only time anyone has a legal right to examine audit documentation is if it is summoned as legal evidence by a court."), ("B", "Audit documentation is the primary frame of reference used by supervisory personnel to evaluate the sufficiency of evidence"), ("C", "Audit documentation is merely required to defend against claims that the auditor performed a deficient audit"), ("D", "All of the above are incorrect statements")]),
    (83, "Audit Documentation", "Which of the following would most likely be included in the current file of an auditor's working papers?",
     [("A", "Articles of incorporation"), ("B", "Pension plan contract"), ("C", "Bank reconciliation"), ("D", "Flowchart of the internal control procedures")]),
    (84, "Audit Documentation", "Ignoring any particular legal or regulatory requirement audit documentation should be retained:",
     [("A", "A minimum of five years"), ("B", "A maximum of five years"), ("C", "Until 3 years after the client selects another auditor"), ("D", "Working papers must be maintained indefinitely")]),
    (85, "Audit Documentation", "Which one of the following statements about working papers is false?",
     [("A", "The form of working papers should be designed to meet the circumstances off a particular engagement."), ("B", "A client's reference source may not be an auditor's working papers."), ("C", "An auditor may support an opinion by other means in addition to working papers."), ("D", "Working papers should demonstrate that the internal accounting control system has been thoroughly examined and reviewed.")]),
    (86, "Audit Documentation", "Which of the following is required documentation in an audit?",
     [("A", "A written engagement letter formalizing the level of services to be provided."), ("B", "A flowchart of the client's organization."), ("C", "A written audit program."), ("D", "A memo setting forth the scope of the audit.")]),
    (87, "Audit Documentation", "Although the quantity, type, and content of working papers will vary with the circumstances, the working papers generally would include the:",
     [("A", "Copies of those client records examined by the auditor during the course of the engagement."), ("B", "Evaluation of the efficiency and competence of the audit staff assistants by the partner responsible for the audit."), ("C", "Auditor's comments concerning the efficiency and competence of client management personnel."), ("D", "Auditing procedures followed, and the testing performed in obtaining audit evidence.")]),
    (88, "Audit Documentation", "Working papers that record the procedures used by the auditor to gather evidence should be:",
     [("A", "Considered the primary support for the financial statements being examined."), ("B", "Viewed as the connecting link between the books of account and the financial statements."), ("C", "Designed to meet the circumstances of the engagement."), ("D", "Destroyed when the audited entity ceases to be a client.")]),
    (89, "Audit Documentation", "Which of the following statements most accurately summarizes the auditor's responsibility for reviewing the client's correspondence files?",
     [("A", "The auditor should review all correspondence for items relevant to the audit."), ("B", "The auditor should not review any correspondence; to do so would waste time more productively spent on gathering other evidence."), ("C", "The auditor should apply statistical selection techniques to draw a random sample of correspondence for review."), ("D", "The auditor should review correspondence with banks, other lending institutions, attorneys and governmental agencies.")]),
    (90, "Audit Documentation", "Which of the following would not be included in the auditor's working papers?",
     [("A", "A time budget for the various audit areas."), ("B", "The results of the preceding year's audit."), ("C", "Descriptive information about the internal control structure."), ("D", "The accounting manual.")])
]

chapter08 = {
    "id": "at-08",
    "code": "AT-08",
    "title": "Audit Procedures, Evidence, and Documentation",
    "description": "Substantive tests (transactions, balances, analytical procedures), audit procedures, sufficiency and appropriateness of audit evidence (PSA 500), management representations (PSA 580), using the work of an expert (PSA 620), internal audit (PSA 610), and audit documentation/working papers (PSA 230).",
    "objectives": [
        "Substantive Tests",
        "Audit Procedures",
        "Audit Evidence",
        "Audit Documentation"
    ],
    "totalQuestions": 90,
    "questions": []
}

for num, obj, qtext, opts in at08_raw:
    correct = at08_answers[num]
    expl = at08_explanations.get(num, f"Suggested Answer: {correct}. In accordance with PSA 500 (Audit Evidence) and PSA 230 (Audit Documentation).")
    chapter08["questions"].append({
        "id": f"at08-{num}",
        "number": num,
        "chapterId": "at-08",
        "chapterCode": "AT-08",
        "chapterTitle": "Audit Procedures, Evidence, and Documentation",
        "objective": obj,
        "question": qtext,
        "options": [{"key": k, "text": t} for k, t in opts],
        "correctAnswer": correct,
        "explanation": expl
    })

with open("src/data/chapters/at08.ts", "w", encoding="utf-8") as f:
    f.write(f"import {{ Chapter }} from '../../types/quiz';\n\nexport const chapter08: Chapter = {json.dumps(chapter08, indent=2)};\n")

print("Created at08.ts with 90 questions")
