#!/usr/bin/env python3
import json

at14_answers = {
    1: 'B', 2: 'C', 3: 'A', 4: 'C', 5: 'D', 6: 'B', 7: 'C', 8: 'A', 9: 'C', 10: 'D',
    11: 'B', 12: 'A', 13: 'B', 14: 'C', 15: 'C', 16: 'C', 17: 'B', 18: 'B', 19: 'A', 20: 'D',
    21: 'B', 22: 'C', 23: 'D', 24: 'B', 25: 'A', 26: 'A', 27: 'C', 28: 'D', 29: 'D', 30: 'B',
    31: 'D', 32: 'B', 33: 'A', 34: 'C', 35: 'D', 36: 'B', 37: 'A', 38: 'D', 39: 'B', 40: 'D',
    41: 'A', 42: 'B', 43: 'B', 44: 'C', 45: 'A', 46: 'A', 47: 'C', 48: 'C', 49: 'D', 50: 'C',
    51: 'C', 52: 'D', 53: 'A', 54: 'A', 55: 'B', 56: 'B', 57: 'C', 58: 'C', 59: 'A', 60: 'C',
    61: 'A', 62: 'B', 63: 'C', 64: 'B', 65: 'B', 66: 'B', 67: 'C', 68: 'B', 69: 'B', 70: 'A',
    71: 'D', 72: 'A', 73: 'B', 74: 'B', 75: 'A', 76: 'C', 77: 'B', 78: 'B', 79: 'B', 80: 'D',
    81: 'B', 82: 'A', 83: 'B', 84: 'B', 85: 'D', 86: 'A', 87: 'C', 88: 'C', 89: 'C', 90: 'D',
    91: 'A', 92: 'B', 93: 'C', 94: 'D', 95: 'A', 96: 'B', 97: 'C', 98: 'A', 99: 'B', 100: 'C'
}

at14_explanations = {
    1: "Republic Act No. 9298 is also known as the Philippine Accountancy Act of 2004.",
    2: "The Professional Regulatory Board of Accountancy (BOA) is composed of a Chairman and six (6) members appointed by the President of the Philippines.",
    41: "The fundamental principles of the Code of Ethics are: Integrity, Objectivity, Professional Competence and Due Care, Confidentiality, and Professional Behavior.",
    76: "Independence comprises Independence of Mind (state of mind permitting unbiased opinion) and Independence in Appearance (avoidance of facts that a reasonable third party would conclude compromised integrity/objectivity).",
    77: "The five categories of threats to independence are: Self-interest threat, Self-review threat, Advocacy threat, Familiarity threat, and Intimidation threat."
}

at14_raw = [
    (1, "Philippine Accountancy Act of 2004", "Republic Act No. 9298 is formally known as:",
     [("A", "The Accountancy Law of 1975"),
      ("B", "The Philippine Accountancy Act of 2004"),
      ("C", "The Revised Corporation Code of the Philippines"),
      ("D", "The National Internal Revenue Code")]),
    (2, "Philippine Accountancy Act of 2004", "The Professional Regulatory Board of Accountancy (BOA) consists of:",
     [("A", "A Chairman and three members"),
      ("B", "A Chairman and five members"),
      ("C", "A Chairman and six members"),
      ("D", "A President and twelve directors")]),
    (3, "Philippine Accountancy Act of 2004", "The members of the Board of Accountancy are appointed by the:",
     [("A", "President of the Philippines"),
      ("B", "Chairman of the Professional Regulation Commission"),
      ("C", "President of PICPA"),
      ("D", "Commissioner of Internal Revenue")]),
    (4, "Philippine Accountancy Act of 2004", "The four recognized sectors of the practice of accountancy under RA 9298 are:",
     [("A", "Audit, Tax, Advisory, and Legal"),
      ("B", "Domestic, Foreign, Multilateral, and NGO"),
      ("C", "Public Practice, Commerce and Industry, Education/Academe, and Government"),
      ("D", "Primary, Secondary, Tertiary, and Public")]),
    (5, "Philippine Accountancy Act of 2004", "A member of the Board of Accountancy shall hold office for a term of:",
     [("A", "One year"), ("B", "Two years"), ("C", "Four years"), ("D", "Three years, and can be reappointed for another term not exceeding twelve years total")]),
    (6, "Philippine Accountancy Act of 2004", "Qualifications of members of the Board of Accountancy include:",
     [("A", "Must be a natural-born citizen and resident of the Philippines."),
      ("B", "Must be a duly registered Certified Public Accountant with at least ten (10) years of work experience in any scope of practice."),
      ("C", "Must not have any pecuniary interest in any school offering CPA review courses."),
      ("D", "All of the above.")]),
    (7, "Philippine Accountancy Act of 2004", "The Certified Public Accountant (CPA) Licensure Examination is given by the Board:",
     [("A", "Once every two years"),
      ("B", "Once a year only"),
      ("C", "At least once a year, normally twice a year in May and October"),
      ("D", "Every month")]),
    (8, "Philippine Accountancy Act of 2004", "To pass the CPA licensure examination, a candidate must obtain a general average of:",
     [("A", "At least seventy-five percent (75%), with no grade lower than sixty-five percent (65%) in any given subject."),
      ("B", "At least eighty percent (80%) in all subjects."),
      ("C", "At least seventy percent (70%) in half the subjects."),
      ("D", "At least ninety percent (90%) overall.")]),
    (9, "Philippine Accountancy Act of 2004", "A candidate who gets a general average of 75% or above, but obtains a rating below 65% in one or two subjects:",
     [("A", "Passes the exam completely"),
      ("B", "Fails the exam completely and must retake all subjects"),
      ("C", "Is considered a conditional examinee and shall take an examination in the remaining subjects within two years"),
      ("D", "Is permanently disqualified")]),
    (10, "Philippine Accountancy Act of 2004", "Any candidate who fails in two (2) complete CPA examinations shall:",
     [("A", "Never be allowed to take the exam again."),
      ("B", "Be required to serve as an apprentice for five years."),
      ("C", "Pay a P100,000 fine to PRC."),
      ("D", "Be disqualified from taking another exam unless the candidate takes a refresher course of at least twenty-four (24) units.")]),
    (11, "Philippine Accountancy Act of 2004", "A Certificate of Accreditation to practice public accountancy issued by the PRC-BOA is valid for:",
     [("A", "One year"), ("B", "Three (3) years and renewable every three years"), ("C", "Lifetime"), ("D", "Five years")]),
    (12, "Philippine Accountancy Act of 2004", "Continuing Professional Development (CPD) is required for CPAs for:",
     [("A", "Renewal of the Professional Identification Card every three years and accreditation to practice"),
      ("B", "Passing the CPA board exam"),
      ("C", "Graduating with a bachelor's degree"),
      ("D", "Opening a savings account")]),
    (13, "Philippine Accountancy Act of 2004", "The Accredited Professional Organization (APO) for CPAs in the Philippines recognized by the PRC is:",
     [("A", "AICPA"), ("B", "Philippine Institute of Certified Public Accountants (PICPA)"), ("C", "IFAC"), ("D", "FINEX")]),
    (14, "Philippine Accountancy Act of 2004", "Foreign CPAs may be allowed to practice in the Philippines under:",
     [("A", "Automatic universal reciprocity without condition"),
      ("B", "Tourist visa"),
      ("C", "Special/temporary permit or foreign reciprocity provisions of RA 9298"),
      ("D", "None, foreign CPAs are strictly banned forever")]),
    (15, "Philippine Accountancy Act of 2004", "Any person who violates any provision of RA 9298 or its IRR shall, upon conviction, be punished by:",
     [("A", "A fine of not less than P500"),
      ("B", "Community service for one week"),
      ("C", "A fine of not less than P50,000 or imprisonment for a period not exceeding two (2) years, or both"),
      ("D", "Suspension of driver's license")]),
    (16, "Philippine Accountancy Act of 2004", "A sole practitioner or firm in public practice is prohibited from:",
     [("A", "Conducting audits of corporations"),
      ("B", "Having branch offices"),
      ("C", "Using a fictitious name or corporate form (must practice under registered individual or partnership name)"),
      ("D", "Charging audit fees")]),
    (17, "Philippine Accountancy Act of 2004", "The Financial Reporting Standards Council (FRSC) is the accounting standard setting body created to assist the BOA in establishing:",
     [("A", "Tax rates"), ("B", "Philippine Financial Reporting Standards (PFRS)"), ("C", "Criminal penalties"), ("D", "Tariff rates")]),
    (18, "Philippine Accountancy Act of 2004", "The Auditing and Assurance Standards Council (AASC) is established to assist the BOA in establishing:",
     [("A", "Accounting software programs"), ("B", "Philippine Standards on Auditing (PSAs)"), ("C", "Corporate bylaws"), ("D", "Labor codes")]),
    (19, "Philippine Accountancy Act of 2004", "Meaning of public practice of accountancy includes:",
     [("A", "Holding out oneself as a skilled CPA to offer audit, tax, consulting, or accounting services to the public for a fee"),
      ("B", "Working exclusively as a clerk in a private store"),
      ("C", "Teaching high school mathematics"),
      ("D", "Serving as a bank teller")]),
    (20, "Philippine Accountancy Act of 2004", "Under RA 9298, all working papers, schedules, and memoranda made by a CPA in an audit remain the property of the:",
     [("A", "Client"), ("B", "Securities and Exchange Commission"), ("C", "Bureau of Internal Revenue"), ("D", "CPA / Audit firm, unless otherwise agreed upon")]),
    (21, "Philippine Accountancy Act of 2004", "A CPA certificate may be suspended or revoked by the Board of Accountancy for:",
     [("A", "Passing the CPA board exam with honors"),
      ("B", "Unprofessional or dishonorable conduct, gross negligence, or violation of RA 9298 or Code of Ethics"),
      ("C", "Retiring at age 65"),
      ("D", "Refusing to accept an audit engagement due to conflict of interest")]),
    (22, "Philippine Accountancy Act of 2004", "The Education Technical Council (ETC) assists the Board of Accountancy in:",
     [("A", "Collecting licensing fees"),
      ("B", "Auditing the national treasury"),
      ("C", "Setting and updating educational requirements and curriculum for accountancy degree programs"),
      ("D", "Grading the bar examination")]),
    (23, "Philippine Accountancy Act of 2004", "Who has the power to inspect CPA accounting firms to ensure compliance with professional standards?",
     [("A", "Bureau of Customs"),
      ("B", "Department of Labor"),
      ("C", "Philippine Coast Guard"),
      ("D", "Professional Regulatory Board of Accountancy (PRC-BOA) through the Quality Review Committee")]),
    (24, "Philippine Accountancy Act of 2004", "The seal of a Certified Public Accountant shall bear the CPA's:",
     [("A", "Blood type and height"),
      ("B", "Name, registration number, and title 'Certified Public Accountant'"),
      ("C", "Birthdate and zodiac sign"),
      ("D", "Social security number only")]),
    (25, "Philippine Accountancy Act of 2004", "Under RA 9298, the death of a partner in a registered partnership of CPAs:",
     [("A", "Allows the continuing partners to use the deceased partner's name in the firm title for a period not exceeding two years, provided it is indicated that the partner is deceased"),
      ("B", "Requires immediate dissolution of the firm within 24 hours"),
      ("C", "Automatically revokes all client audits"),
      ("D", "Requires all employees to be dismissed")]),
    (26, "Code of Ethics for Professional Accountants", "The Code of Ethics for Professional Accountants in the Philippines is based on the Code issued by the:",
     [("A", "International Ethics Standards Board for Accountants (IESBA) of IFAC"),
      ("B", "United States Internal Revenue Service"),
      ("C", "Philippine Chamber of Commerce"),
      ("D", "World Trade Organization")]),
    (27, "Code of Ethics for Professional Accountants", "The fundamental ethical principles under the Code of Ethics are:",
     [("A", "Speed, Accuracy, Wealth, Discretion, and Power"),
      ("B", "Loyalty, Courage, Obedience, Discipline, and Strength"),
      ("C", "Integrity, Objectivity, Professional Competence and Due Care, Confidentiality, and Professional Behavior"),
      ("D", "Materiality, Relevance, Reliability, Comparability, and Understandability")]),
    (28, "Code of Ethics for Professional Accountants", "The principle of Integrity imposes an obligation on all professional accountants to be:",
     [("A", "Clever in evading taxes"),
      ("B", "Silent during fraud inquiries"),
      ("C", "Passive when witnessing violations"),
      ("D", "Straightforward and honest in all professional and business relationships")]),
    (29, "Code of Ethics for Professional Accountants", "The principle of Objectivity requires a professional accountant not to:",
     [("A", "Charge reasonable fees"),
      ("B", "Perform services for multiple clients"),
      ("C", "Work for a publicly listed company"),
      ("D", "Compromise professional or business judgment because of bias, conflict of interest, or undue influence of others")]),
    (30, "Code of Ethics for Professional Accountants", "The principle of Professional Competence and Due Care requires a professional accountant to:",
     [("A", "Guarantee zero misstatements in all audits"),
      ("B", "Attain and maintain professional knowledge and skill at a level required to ensure competent professional service, and act diligently in accordance with applicable standards"),
      ("C", "Memorize all tax circulars within 24 hours"),
      ("D", "Never consult other experts")]),
    (31, "Code of Ethics for Professional Accountants", "The principle of Confidentiality requires a professional accountant to respect the confidentiality of information acquired as a result of professional relationships and:",
     [("A", "Disclose information on social media for public awareness"),
      ("B", "Share client information with competing businesses"),
      ("C", "Use confidential information for personal advantage"),
      ("D", "Not disclose such information to third parties without proper authority unless there is a legal or professional duty or right to disclose")]),
    (32, "Code of Ethics for Professional Accountants", "Confidential client information may be disclosed without client permission in which situation?",
     [("A", "To a curious friend at a dinner party"),
      ("B", "When subpoenaed by a court of competent jurisdiction or during a professional regulatory review/investigation"),
      ("C", "To help a rival firm bid for a contract"),
      ("D", "To an online reporter writing a gossip column")]),
    (33, "Code of Ethics for Professional Accountants", "The principle of Professional Behavior imposes an obligation on a CPA to:",
     [("A", "Comply with relevant laws and regulations and avoid any conduct that the professional accountant knows or should know might discredit the profession"),
      ("B", "Wear formal suits at all times"),
      ("C", "Refuse to communicate with non-accountants"),
      ("D", "Criticize fellow practitioners in public advertisements")]),
    (34, "Code of Ethics for Professional Accountants", "A professional accountant who knowingly associates with reports, returns, or communications containing materially false or misleading information violates the principle of:",
     [("A", "Confidentiality"), ("B", "Competence"), ("C", "Integrity"), ("D", "Punctuality")]),
    (35, "Code of Ethics for Professional Accountants", "The conceptual framework approach requires a professional accountant to:",
     [("A", "Identify threats to compliance with the fundamental principles"),
      ("B", "Evaluate the significance of the threats identified"),
      ("C", "Apply safeguards, when necessary, to eliminate the threats or reduce them to an acceptable level"),
      ("D", "All of the above")]),
    (36, "Independence, Threats, and Safeguards", "The five categories of threats to the fundamental principles are:",
     [("A", "Financial, Physical, Emotional, Mental, and Legal"),
      ("B", "Self-interest, Self-review, Advocacy, Familiarity, and Intimidation"),
      ("C", "Civil, Criminal, Administrative, Commercial, and Labor"),
      ("D", "Inherent, Control, Detection, Sampling, and Non-sampling")]),
    (37, "Independence, Threats, and Safeguards", "A self-interest threat occurs when:",
     [("A", "A financial or other interest will inappropriately influence the professional accountant's judgment or behavior (e.g., direct financial interest in audit client)."),
      ("B", "The CPA advocates for a client's position in court."),
      ("C", "The CPA is threatened with dismissal."),
      ("D", "A close relative is employed by the client.")]),
    (38, "Independence, Threats, and Safeguards", "A self-review threat occurs when:",
     [("A", "The auditor refuses to review audit files."),
      ("B", "A member of the firm receives expensive gifts."),
      ("C", "The audit fee is disputed."),
      ("D", "A previous judgment or service rendered by the firm needs to be re-evaluated by the same firm in reaching audit conclusions (e.g., auditing financial statements prepared by the firm).")]),
    (39, "Independence, Threats, and Safeguards", "An advocacy threat occurs when:",
     [("A", "The auditor charges contingent fees."),
      ("B", "The professional accountant promotes a client's position or opinion to the point that subsequent objectivity may be compromised (e.g., acting as advocate for audit client in litigation)."),
      ("C", "The client threatens to replace the auditor."),
      ("D", "The auditor has an overdue receivable from the client.")]),
    (40, "Independence, Threats, and Safeguards", "A familiarity threat occurs when:",
     [("A", "The auditor is unfamiliar with the client's business."),
      ("B", "The auditor has never met the client's management."),
      ("C", "The auditor changes engagement partners annually."),
      ("D", "Because of a long or close relationship with a client, the accountant becomes too sympathetic to their interests or too accepting of their work.")]),
    (41, "Independence, Threats, and Safeguards", "An intimidation threat occurs when:",
     [("A", "The professional accountant is deterred from acting objectively because of actual or perceived pressures, including attempts to exercise undue influence (e.g., threat of litigation or dismissal)."),
      ("B", "The auditor intimidates the client's bookkeeper."),
      ("C", "The CPA firm has too many clients."),
      ("D", "The client pays audit fees in cash.")]),
    (42, "Independence, Threats, and Safeguards", "Independence in audit engagements comprises:",
     [("A", "Independence in law and independence in fact"),
      ("B", "Independence of mind and independence in appearance"),
      ("C", "Independence in title and independence in action"),
      ("D", "Independence of contract and independence of status")]),
    (43, "Independence, Threats, and Safeguards", "Independence of mind is defined as:",
     [("A", "Being able to work without any sleep"),
      ("B", "The state of mind that permits the expression of a conclusion without being affected by influences that compromise professional judgment, thereby allowing an individual to act with integrity and exercise objectivity and professional skepticism"),
      ("C", "Ignoring all evidence provided by the client"),
      ("D", "Having no formal education in auditing")]),
    (44, "Independence, Threats, and Safeguards", "Independence in appearance is defined as:",
     [("A", "Wearing professional formal attire at all meetings"),
      ("B", "Having clean audit workpapers"),
      ("C", "The avoidance of facts and circumstances that are so significant that a reasonable and informed third party would be likely to conclude that a firm's or a member's integrity, objectivity, or skepticism has been compromised"),
      ("D", "Displaying the CPA license on the office wall")]),
    (45, "Independence, Threats, and Safeguards", "If an audit partner has a direct financial interest (such as owning shares of stock) in the audit client, the threat created is:",
     [("A", "A self-interest threat so significant that no safeguards could reduce it to an acceptable level; independence is impaired."),
      ("B", "An advocacy threat only."),
      ("C", "An intimidation threat."),
      ("D", "Completely acceptable if the stock ownership is under P1,000,000.")]),
    (46, "Independence, Threats, and Safeguards", "An indirect material financial interest in an audit client (such as owning a mutual fund that heavily invests in the client):",
     [("A", "Also creates a significant self-interest threat that impairs independence unless eliminated."),
      ("B", "Is always permissible without restriction."),
      ("C", "Is an intimidation threat."),
      ("D", "Requires an adverse audit opinion.")]),
    (47, "Independence, Threats, and Safeguards", "A loan from an audit client that is a bank, made under normal lending procedures, terms, and conditions:",
     [("A", "Automatically impairs independence in all circumstances."),
      ("B", "Requires the auditor to resign immediately."),
      ("C", "Does not impair independence, provided it is not material to either party and made in the ordinary course of business."),
      ("D", "Is illegal under RA 9298.")]),
    (48, "Independence, Threats, and Safeguards", "Close family members under the Code of Ethics include:",
     [("A", "A distant cousin living abroad"),
      ("B", "A neighbor"),
      ("C", "A parent, child, or sibling"),
      ("D", "A former classmate")]),
    (49, "Independence, Threats, and Safeguards", "Immediate family members include:",
     [("A", "Spouse (or equivalent) and dependents"),
      ("B", "Parents and siblings only"),
      ("C", "In-laws and cousins"),
      ("D", "All blood relatives up to the fourth degree")]),
    (50, "Independence, Threats, and Safeguards", "If the spouse of an audit team member is the Chief Financial Officer (CFO) of the audit client, the threat created is:",
     [("A", "Zero threat"),
      ("B", "Easily resolved by a disclaimer of opinion"),
      ("C", "A self-interest and familiarity threat that impairs independence; the individual must be removed from the engagement team"),
      ("D", "A routine business occurrence requiring no action")]),
    (51, "Independence, Threats, and Safeguards", "Partner rotation under the Philippine Code of Ethics requires that for audits of public interest entities (listed entities), the key audit partner shall be rotated after a period of not more than:",
     [("A", "One year"), ("B", "Two years"), ("C", "Seven (7) years (or five years under SEC rules), with a cooling-off period"), ("D", "Twenty years")]),
    (52, "Independence, Threats, and Safeguards", "Accepting gifts or hospitality from an audit client impairs independence unless:",
     [("A", "The gift is worth more than P100,000."),
      ("B", "The gift is given during the holidays."),
      ("C", "The gift is approved by the client's internal auditor."),
      ("D", "The value is trivial and inconsequential.")]),
    (53, "Independence, Threats, and Safeguards", "Contingent fees (fees calculated on a predetermined basis relating to the outcome of a transaction or result of services) for an audit engagement are:",
     [("A", "Strictly prohibited because they create an unacceptable self-interest threat."),
      ("B", "Encouraged to reward good audit performance."),
      ("C", "Allowed if approved by the court."),
      ("D", "Permissible for government audits only.")]),
    (54, "Independence, Threats, and Safeguards", "Overdue audit fees from a client for prior year services:",
     [("A", "May create a self-interest threat equivalent to a loan to the client; if fees remain unpaid before the next report is issued, independence may be impaired."),
      ("B", "Improve independence by showing auditor patience."),
      ("C", "Are automatically converted into common stock."),
      ("D", "Have no ethical significance.")]),
    (55, "Independence, Threats, and Safeguards", "Providing bookkeeping and accounting services to an audit client that is a public interest entity (listed company):",
     [("A", "Is standard professional practice."),
      ("B", "Is prohibited because it creates an insurmountable self-review threat."),
      ("C", "Is allowed if billed separately."),
      ("D", "Is required by the PSE.")]),
    (56, "Independence, Threats, and Safeguards", "Providing valuation services to an audit client that involve matters material to the financial statements and significant subjectivity:",
     [("A", "Does not affect audit independence."),
      ("B", "Creates a self-review threat so significant that independence is impaired."),
      ("C", "Is required under PSA 620."),
      ("D", "Is permitted if the client's bookkeeper signs the valuation.")]),
    (57, "Independence, Threats, and Safeguards", "Acting as an advocate for an audit client in resolving tax litigation before the Court of Tax Appeals:",
     [("A", "Is an obligation of all auditors."),
      ("B", "Creates a familiarity threat."),
      ("C", "Creates an advocacy and self-review threat that impairs independence."),
      ("D", "Is allowed if fees are hourly.")]),
    (58, "Independence, Threats, and Safeguards", "When total fees generated from an audit client represent a large proportion of the firm's total revenue (fee dependency):",
     [("A", "The firm becomes more independent because of client importance."),
      ("B", "The firm is immune to client pressure."),
      ("C", "A self-interest or intimidation threat is created because of fear of losing the client."),
      ("D", "The firm must forfeit all fees to the government.")]),
    (59, "Independence, Threats, and Safeguards", "Safeguards created by the profession, legislation, or regulation include:",
     [("A", "Educational, training, and experience requirements for entry into the profession, CPD requirements, and external review of quality control."),
      ("B", "Advertising campaigns on social media."),
      ("C", "Lowering board passing rates."),
      ("D", "Waiving all ethics rules for large firms.")]),
    (60, "Independence, Threats, and Safeguards", "Safeguards in the work environment include:",
     [("A", "Refusing to document audit procedures."),
      ("B", "Allowing junior staff to sign audit reports."),
      ("C", "Involving an independent professional accountant to review the work done (engagement quality control review) or consulting an objective third party."),
      ("D", "Increasing the audit fee.")]),
    (61, "Questions 61 to 100", "Under the Code of Ethics, a CPA in public practice who is asked to replace another CPA shall:",
     [("A", "Request the client's permission to communicate with the existing/predecessor accountant to discuss any professional reasons why the appointment should not be accepted."),
      ("B", "Accept immediately and undercut the prior auditor's fee."),
      ("C", "Refuse all replacement engagements."),
      ("D", "File a complaint against the existing accountant.")]),
    (62, "Questions 61 to 100", "Advertising and solicitation by CPAs in the Philippines is governed by BOA rules which state that advertising is:",
     [("A", "Prohibited in all forms, including calling cards."),
      ("B", "Permitted provided it is informative, objective, dignified, and not false, misleading, or deceptive."),
      ("C", "Permitted to make exaggerated claims about services and superior competence."),
      ("D", "Required to include comparisons with named competitors.")]),
    (63, "Questions 61 to 100", "Referral fees or commissions for referring a client to a third party or receiving a commission from a supplier:",
     [("A", "Are encouraged as business incentives."),
      ("B", "Are mandatory under the Corporation Code."),
      ("C", "Create significant self-interest threats to objectivity; in public practice, receiving or paying referral fees for assurance clients is generally prohibited."),
      ("D", "Are tax-exempt bonuses.")]),
    (64, "Questions 61 to 100", "A CPA who is offered an engagement where the fee is based on the percentage of net tax savings achieved (contingent fee):",
     [("A", "May accept for financial statement audits."),
      ("B", "Cannot accept if the service is for an audit or review client."),
      ("C", "Must charge at least 50%."),
      ("D", "Can accept without disclosure.")]),
    (65, "Questions 61 to 100", "When a CPA in commerce and industry is pressured by an employer to falsify inventory values, the CPA should:",
     [("A", "Comply immediately to maintain employment."),
      ("B", "Not compromise professional judgment, evaluate the threat, consult superiors/audit committee, seek legal advice, and resign if necessary."),
      ("C", "Report the error only after 10 years."),
      ("D", "Take a vacation.")]),
    (66, "Questions 61 to 100", "Serving as an officer, director, or secretary of an audit client:",
     [("A", "Enhances audit quality by providing internal access."),
      ("B", "Creates self-review and self-interest threats that compromise independence; no member of the firm shall serve as director/officer of an audit client."),
      ("C", "Is required for listed companies."),
      ("D", "Is allowed if the CPA receives no director fees.")]),
    (67, "Questions 61 to 100", "The recruitment of senior management personnel (such as CEO or CFO) for an audit client by the CPA firm:",
     [("A", "Is a routine consulting service with no ethical implications."),
      ("B", "Is required by the SEC."),
      ("C", "Creates significant self-interest, familiarity, and intimidation threats; the firm should not make management decisions or recruit key executives for audit clients."),
      ("D", "Guarantees a permanent audit contract.")]),
    (68, "Questions 61 to 100", "Actual or threatened litigation between the audit firm and the audit client:",
     [("A", "Enhances auditor objectivity through legal scrutiny."),
      ("B", "Creates self-interest and intimidation threats that impair independence; safeguards must be applied or the firm must withdraw."),
      ("C", "Has no effect on independence until a verdict is rendered."),
      ("D", "Requires an immediate adverse opinion without further audit work.")]),
    (69, "Questions 61 to 100", "An audit firm's system of quality control is governed by:",
     [("A", "PSA 100"), ("B", "PSQC 1 / ISQM 1"), ("C", "PFRS 1"), ("D", "RA 1425")]),
    (70, "Questions 61 to 100", "Leadership responsibilities for quality within the firm under PSQC 1 require that:",
     [("A", "The firm's managing partner/chief executive assumes ultimate responsibility for the firm's system of quality control."),
      ("B", "Junior assistants assume all quality liabilities."),
      ("C", "Clients control the quality of the audit."),
      ("D", "Quality is evaluated only when a lawsuit is filed.")]),
    (71, "Questions 61 to 100", "The elements of a firm's system of quality control include:",
     [("A", "Leadership responsibilities for quality within the firm"),
      ("B", "Relevant ethical requirements, acceptance and continuance of relationships, and human resources"),
      ("C", "Engagement performance and monitoring"),
      ("D", "All of the above")]),
    (72, "Questions 61 to 100", "At least annually, the audit firm shall obtain written confirmation of compliance with its policies on independence from:",
     [("A", "All firm personnel required to be independent"),
      ("B", "The client's board of directors"),
      ("C", "The BIR Commissioner"),
      ("D", "Local police authorities")]),
    (73, "Questions 61 to 100", "Engagement quality control review (EQCR) is required for:",
     [("A", "Every tax return filed by an individual."),
      ("B", "All audits of financial statements of listed entities, and other engagements meeting firm criteria."),
      ("C", "Sole proprietorship compilations."),
      ("D", "Bank loan applications under P10,000.")]),
    (74, "Questions 61 to 100", "An engagement quality control reviewer must be:",
     [("A", "A subordinate of the engagement partner."),
      ("B", "A suitably qualified person who does not participate in the performance of the engagement, maintaining objectivity."),
      ("C", "An employee of the client."),
      ("D", "The client's internal audit director.")]),
    (75, "Questions 61 to 100", "The assembly of the final audit file should ordinarily be completed not more than:",
     [("A", "60 days after the date of the auditor's report (PSQC 1 / PSA 230)"),
      ("B", "365 days after report date"),
      ("C", "5 days before the report is issued"),
      ("D", "10 years after fieldwork")]),
    (76, "Questions 61 to 100", "Retention period for audit documentation under PSQC 1 is ordinarily not shorter than:",
     [("A", "One year"), ("B", "Two years"), ("C", "Five years (or 10 years under local tax/PRC regulations) from the date of the auditor's report"), ("D", "Six months")]),
    (77, "Questions 61 to 100", "A CPA whose certificate of registration has been revoked may be reinstated by the Board of Accountancy:",
     [("A", "Never under any condition"),
      ("B", "After the expiration of two (2) years from the date of revocation, upon proper application and for reasons deemed commendable"),
      ("C", "Within 24 hours of paying a fine"),
      ("D", "By running for political office")]),
    (78, "Questions 61 to 100", "Can a CPA in public practice engage in another business or occupation?",
     [("A", "No, RA 9298 forbids any other commercial activity."),
      ("B", "Yes, provided the secondary business does not create a conflict of interest or impair independence and integrity in public practice."),
      ("C", "Only if it is in agriculture."),
      ("D", "Only with written permission from the President of the Philippines.")]),
    (79, "Questions 61 to 100", "A CPA in public practice was offered a luxury car as a gift from an audit client's CEO upon issuing a clean opinion. The CPA should:",
     [("A", "Accept the car and register it under a family member's name."),
      ("B", "Politely reject the gift because its value is neither trivial nor inconsequential, and accepting it impairs independence."),
      ("C", "Accept the car but deduct its value from the audit bill."),
      ("D", "Donate the car to the firm's recreation center.")]),
    (80, "Questions 61 to 100", "Independence is not required for which of the following professional engagements?",
     [("A", "Financial statement audit"),
      ("B", "Review of interim financial statements"),
      ("C", "Examination of prospective financial information"),
      ("D", "Preparation of tax returns and compilation of financial statements")]),
    (81, "Questions 61 to 100", "A CPA firm audits Company X. A senior audit staff member is offered employment as Controller of Company X while the audit is ongoing. The firm should:",
     [("A", "Promote the senior immediately."),
      ("B", "Remove the senior from the audit engagement team immediately, and review any work performed by the individual."),
      ("C", "Demand that the senior pay a fine to the firm."),
      ("D", "Issue a qualified opinion.")]),
    (82, "Questions 61 to 100", "Which body conducts quality reviews of audit firms in the Philippines?",
     [("A", "The Quality Review Committee (QRC) created under RA 9298"),
      ("B", "The Commission on Higher Education"),
      ("C", "The Department of Justice"),
      ("D", "The Land Transportation Office")]),
    (83, "Questions 61 to 100", "The Code of Ethics defines a 'Public Interest Entity' (PIE) as:",
     [("A", "Any company with more than five employees"),
      ("B", "A listed entity, or an entity defined by regulation/legislation as such (e.g., banks, public utilities, insurance companies)"),
      ("C", "A nonprofit religious organization only"),
      ("D", "A partnership of professionals")]),
    (84, "Questions 61 to 100", "Under RA 9298, the Board of Accountancy may issue a Certificate of Registration and Professional ID Card without examination to:",
     [("A", "Any college graduate with high grades"),
      ("B", "No one; passing the licensure exam is mandatory under RA 9298 (except via foreign reciprocity provisions)"),
      ("C", "All certified bookkeepers"),
      ("D", "Elected government officials")]),
    (85, "Questions 61 to 100", "A CPA in public practice may charge audit fees based on:",
     [("A", "A percentage of the client's reported net profit"),
      ("B", "A percentage of taxes saved"),
      ("C", "The number of errors concealed"),
      ("D", "The time spent, difficulty of service, expertise required, and standard billing rates")]),
    (86, "Questions 61 to 100", "Under the Code of Ethics, lowballing (quoting a significantly lower fee than the market rate to win an audit engagement):",
     [("A", "Creates a self-interest threat that audit quality may be compromised due to inadequate time and staffing."),
      ("B", "Is required to ensure free market competition."),
      ("C", "Is strictly prohibited by criminal statutes."),
      ("D", "Guarantees a clean audit opinion.")]),
    (87, "Questions 61 to 100", "The fundamental ethical principle that obligates a professional accountant to be fair, intellectually honest, and free of conflicts of interest is:",
     [("A", "Confidentiality"), ("B", "Integrity"), ("C", "Objectivity"), ("D", "Due care")]),
    (88, "Questions 61 to 100", "When a CPA firm performs internal audit services for an external audit client that is a public interest entity:",
     [("A", "It is encouraged under PFRS."),
      ("B", "It has no effect on independence."),
      ("C", "It creates a significant self-review threat and is generally prohibited."),
      ("D", "It can be performed without notification.")]),
    (89, "Questions 61 to 100", "The PRC Modernization Act of 2000 is known as:",
     [("A", "RA 7160"), ("B", "RA 8792"), ("C", "RA 8981"), ("D", "RA 9184")]),
    (90, "Questions 61 to 100", "Under RA 9298, a member of the Board of Accountancy must not be connected with any CPA review school for at least how many years prior to appointment?",
     [("A", "One year"), ("B", "Two years"), ("C", "Five years"), ("D", "Three (3) years")]),
    (91, "Questions 61 to 100", "The practice of accountancy in commerce and industry requires that the position of chief accountant in a business with paid-up capital of at least P5,000,000 and/or annual revenue of at least P10,000,000 must be held by a:",
     [("A", "Registered Certified Public Accountant (CPA)"),
      ("B", "Master in Business Administration (MBA)"),
      ("C", "Certified Bookkeeper"),
      ("D", "Civil Engineer")]),
    (92, "Questions 61 to 100", "An audit partner's independence is considered impaired if the partner's sibling is:",
     [("A", "A customer who buys goods at regular retail price"),
      ("B", "In a position to exert significant influence over the financial statements of the audit client (such as Controller or Internal Audit Director)"),
      ("C", "An assembly line worker in the factory"),
      ("D", "A security guard at the gate")]),
    (93, "Questions 61 to 100", "The 'cooling-off period' for a key audit partner of a public interest entity before returning to the audit team is:",
     [("A", "Six months"), ("B", "One year"), ("C", "Two to five years depending on the role played"), ("D", "Twenty years")]),
    (94, "Questions 61 to 100", "A CPA discovers that an audit client is engaged in money laundering activities. Under the Philippine Anti-Money Laundering Act (AMLA) and Code of Ethics (NOCLAR):",
     [("A", "The CPA must conceal the violation to preserve confidentiality."),
      ("B", "The CPA must help the client launder the money."),
      ("C", "The CPA is prohibited from telling anyone forever."),
      ("D", "The CPA must respond to non-compliance with laws and regulations (NOCLAR), discuss with management/governance, and comply with reporting obligations under the law without confidentiality breach.")]),
    (95, "Questions 61 to 100", "Under RA 9298, the PRC-BOA has the power to:",
     [("A", "Prescribe and adopt the rules and regulations necessary for carrying out the provisions of the Act."),
      ("B", "Declare martial law."),
      ("C", "Print national currency."),
      ("D", "Enact statutory legislation.")]),
    (96, "Questions 61 to 100", "Which document is issued by the PRC-BOA upon passing the CPA licensure examination?",
     [("A", "Passport"),
      ("B", "Certificate of Registration and Professional Identification Card"),
      ("C", "Police clearance"),
      ("D", "Business permit")]),
    (97, "Questions 61 to 100", "The Professional Identification Card of a CPA is renewable every:",
     [("A", "Year"), ("B", "Two years"), ("C", "Three (3) years on the CPA's birth month"), ("D", "Ten years")]),
    (98, "Questions 61 to 100", "A CPA whose client refuses to pay agreed-upon audit fees cannot withhold the client's books of account because:",
     [("A", "Client records belong to the client and withholding them is unprofessional and illegal."),
      ("B", "The CPA must burn the records."),
      ("C", "The records have no value."),
      ("D", "The bank owns the books.")]),
    (99, "Questions 61 to 100", "The Code of Ethics applies to:",
     [("A", "Only CPAs in public practice"),
      ("B", "All professional accountants in the Philippines, whether in public practice, commerce and industry, education, or government"),
      ("C", "Foreign tourists only"),
      ("D", "Unlicensed bookkeepers only")]),
    (100, "Questions 61 to 100", "The highest governing body of the accountancy profession in the Philippines is the:",
     [("A", "Supreme Court"),
      ("B", "Department of Finance"),
      ("C", "Professional Regulatory Board of Accountancy (PRC-BOA) under the Professional Regulation Commission"),
      ("D", "Bureau of Internal Revenue")])
]

chapter14 = {
    "id": "at-14",
    "code": "AT-14",
    "title": "The Code of Professional Ethics and The Republic Act No. 9298",
    "description": "Philippine Accountancy Act of 2004 (RA 9298), Board of Accountancy (BOA), CPA licensure, accreditation, CPD, Code of Ethics for Professional Accountants in the Philippines, fundamental principles (Integrity, Objectivity, Due Care, Confidentiality, Professional Behavior), and Independence (Threats and Safeguards).",
    "objectives": [
        "Philippine Accountancy Act of 2004",
        "Code of Ethics for Professional Accountants",
        "Independence, Threats, and Safeguards",
        "Questions 61 to 100"
    ],
    "totalQuestions": 100,
    "questions": []
}

for num, obj, qtext, opts in at14_raw:
    correct = at14_answers[num]
    expl = at14_explanations.get(num, f"Suggested Answer: {correct}. In accordance with Republic Act No. 9298 and the Code of Ethics for Professional Accountants in the Philippines.")
    chapter14["questions"].append({
        "id": f"at14-{num}",
        "number": num,
        "chapterId": "at-14",
        "chapterCode": "AT-14",
        "chapterTitle": "The Code of Professional Ethics and The Republic Act No. 9298",
        "objective": obj,
        "question": qtext,
        "options": [{"key": k, "text": t} for k, t in opts],
        "correctAnswer": correct,
        "explanation": expl
    })

with open("src/data/chapters/at14.ts", "w", encoding="utf-8") as f:
    f.write(f"import {{ Chapter }} from '../../types/quiz';\n\nexport const chapter14: Chapter = {json.dumps(chapter14, indent=2)};\n")

print("Created at14.ts with 100 questions")
