#!/usr/bin/env python3
import json

finale_answers = {
    1: 'A', 2: 'B', 3: 'C', 4: 'D', 5: 'B', 6: 'A', 7: 'C', 8: 'D', 9: 'B', 10: 'A',
    11: 'C', 12: 'D', 13: 'B', 14: 'A', 15: 'C', 16: 'D', 17: 'B', 18: 'A', 19: 'C', 20: 'D',
    21: 'B', 22: 'A', 23: 'C', 24: 'D', 25: 'B', 26: 'A', 27: 'C', 28: 'D', 29: 'B', 30: 'A',
    31: 'C', 32: 'D', 33: 'B', 34: 'A', 35: 'C', 36: 'D', 37: 'B', 38: 'A', 39: 'C', 40: 'D',
    41: 'B', 42: 'A', 43: 'C', 44: 'D', 45: 'B', 46: 'A', 47: 'C', 48: 'D', 49: 'B', 50: 'A',
    51: 'C', 52: 'D', 53: 'B', 54: 'A', 55: 'C', 56: 'D', 57: 'B', 58: 'A', 59: 'C', 60: 'D',
    61: 'B', 62: 'A', 63: 'C', 64: 'D', 65: 'B', 66: 'A', 67: 'C', 68: 'D', 69: 'B', 70: 'A'
}

finale_explanations = {
    1: "The primary objective of an independent financial statement audit is the expression of an opinion on whether the financial statements present fairly, in all material respects, the financial position and results of operations in accordance with PFRS.",
    2: "Independence of mind and independence in appearance are the two essential components of professional auditor independence.",
    3: "Inherent risk and control risk exist independently of the audit; the auditor cannot alter them, but rather assesses them.",
    4: "Detection risk is the only risk component that the auditor can manage directly by modifying the nature, timing, and extent of substantive audit procedures.",
    15: "An adverse opinion is rendered when the financial statements are materially misstated and the effects are pervasive.",
    25: "Under PSA 505, external confirmations directly obtained from independent third parties provide higher reliability than internal client documents.",
    35: "Subsequent events occurring after balance sheet date that provide evidence of conditions existing at year-end require financial statement adjustment.",
    70: "Under RA 9298, the CPA license requires passing the licensure examination with a general average of at least 75% with no grade below 65% in any subject."
}

finale_raw = [
    (1, "Pre-Board Mock Exam: Assurance Concepts", "The primary objective of an independent financial statement audit is to:",
     [("A", "Express an opinion on the fair presentation of the financial statements in accordance with the applicable financial reporting framework."),
      ("B", "Provide absolute assurance that no fraud or illegal acts exist in the entity."),
      ("C", "Certify the future profitability and operational efficiency of the entity."),
      ("D", "Protect investors against bad business decisions by management.")]),
    (2, "Pre-Board Mock Exam: Assurance Concepts", "Professional skepticism requires the auditor to:",
     [("A", "Assume management is dishonest until proven otherwise."),
      ("B", "Maintain an attitude that includes a questioning mind and a critical assessment of audit evidence."),
      ("C", "Accept all management representations without corroborating evidence."),
      ("D", "Refuse to communicate with client personnel.")]),
    (3, "Pre-Board Mock Exam: Risk Assessment", "Which of the following risks exist independently of the audit of financial statements?",
     [("A", "Detection risk and sampling risk"),
      ("B", "Non-sampling risk and audit risk"),
      ("C", "Inherent risk and control risk"),
      ("D", "Detection risk and business risk")]),
    (4, "Pre-Board Mock Exam: Risk Assessment", "An auditor reduces detection risk by:",
     [("A", "Decreasing substantive tests"),
      ("B", "Increasing tolerable misstatement"),
      ("C", "Reducing sample sizes in confirmation"),
      ("D", "Increasing the extent of substantive tests, testing closer to year-end, and using more effective audit procedures")]),
    (5, "Pre-Board Mock Exam: Risk Assessment", "The concept of materiality in auditing recognizes that:",
     [("A", "Auditors must find every minor error in the accounting records."),
      ("B", "Matters are material if they could reasonably be expected to influence economic decisions of users taken on the basis of financial statements."),
      ("C", "Materiality is determined solely by mathematical percentage formulas without professional judgment."),
      ("D", "Materiality is identical for all companies in all industries.")]),
    (6, "Pre-Board Mock Exam: Internal Control", "The primary responsibility for designing, implementing, and maintaining effective internal control rests with:",
     [("A", "Management and those charged with governance"),
      ("B", "The independent external auditor"),
      ("C", "The Securities and Exchange Commission"),
      ("D", "The Professional Regulatory Board of Accountancy")]),
    (7, "Pre-Board Mock Exam: Internal Control", "Which of the following is not one of the five interrelated components of internal control under COSO / PSA 315?",
     [("A", "Control environment"),
      ("B", "Risk assessment process"),
      ("C", "Marketing and advertising strategies"),
      ("D", "Information system and communication")]),
    (8, "Pre-Board Mock Exam: Internal Control", "Proper segregation of duties requires that which functions be separated?",
     [("A", "Hiring and orientation"),
      ("B", "Billing and tax payment"),
      ("C", "Filing and printing"),
      ("D", "Authorization of transactions, custody of related assets, recordkeeping, and reconciliation")]),
    (9, "Pre-Board Mock Exam: Fraud & Non-Compliance", "Under PSA 240, the auditor's primary responsibility regarding fraud is to:",
     [("A", "Prevent all fraudulent acts by client employees."),
      ("B", "Obtain reasonable assurance that the financial statements taken as a whole are free from material misstatement, whether caused by fraud or error."),
      ("C", "Act as a detective and prosecute perpetrators."),
      ("D", "Guarantee the recovery of all misappropriated funds.")]),
    (10, "Pre-Board Mock Exam: Fraud & Non-Compliance", "The fraud triangle identifies three conditions generally present when material misstatements due to fraud occur:",
     [("A", "Incentive/pressure, opportunity, and rationalization/attitude"),
      ("B", "Greed, stupidity, and malice"),
      ("C", "Weak management, high taxes, and inflation"),
      ("D", "Computer bugs, manual entry, and lack of training")]),
    (11, "Pre-Board Mock Exam: Audit Evidence", "Which of the following types of audit evidence is generally considered most reliable?",
     [("A", "Oral inquiries of management"),
      ("B", "Internal client purchase requisitions"),
      ("C", "Direct written confirmation received by the auditor from an independent third-party bank"),
      ("D", "Sales invoices prepared by the client's billing department")]),
    (12, "Pre-Board Mock Exam: Audit Evidence", "Inspecting physical tangible assets primarily provides audit evidence regarding the assertion of:",
     [("A", "Rights and obligations"),
      ("B", "Completeness"),
      ("C", "Valuation and allocation"),
      ("D", "Existence")]),
    (13, "Pre-Board Mock Exam: Audit Evidence", "Substantive analytical procedures are most appropriate when:",
     [("A", "Testing unique, non-recurring transactions"),
      ("B", "Testing large volumes of transactions that tend to be predictable over time (e.g., payroll, interest expense)"),
      ("C", "The internal control environment is completely broken"),
      ("D", "Testing inventory obsolescence of custom machinery")]),
    (14, "Pre-Board Mock Exam: Audit Sampling", "Sampling risk is the risk that:",
     [("A", "The auditor's conclusion based on a sample may differ from the conclusion reached if the entire population were subjected to the same procedure."),
      ("B", "The auditor will misinterpret the evidence obtained."),
      ("C", "The client's internal controls will fail completely."),
      ("D", "The auditor uses incorrect audit software.")]),
    (15, "Pre-Board Mock Exam: Audit Sampling", "In testing controls, the risk of assessing control risk too low affects:",
     [("A", "Audit efficiency because unnecessary work is done"),
      ("B", "The client's tax bill"),
      ("C", "Audit effectiveness because the auditor inappropriately reduces substantive tests, creating risk of an erroneous clean opinion"),
      ("D", "The auditor's professional license immediately")]),
    (16, "Pre-Board Mock Exam: Audit Sampling", "Monetary Unit Sampling (MUS) is characterized by:",
     [("A", "Selecting every 10th physical invoice"),
      ("B", "Stratifying based on item weight"),
      ("C", "Excluding all large balances"),
      ("D", "Defining the individual peso of book value as the sampling unit, giving larger dollar items higher probability of selection")]),
    (17, "Pre-Board Mock Exam: CIS & IT Auditing", "General IT controls (GITCs) include controls over:",
     [("A", "Input validation of sales invoice numbers"),
      ("B", "Data center and network operations, system software acquisition and maintenance, access security, and application system development"),
      ("C", "Petty cash voucher approvals"),
      ("D", "Credit approval limits for individual retail customers")]),
    (18, "Pre-Board Mock Exam: CIS & IT Auditing", "When the auditor processes simulated test data containing valid and invalid transactions through the client's actual computer system, this CAAT is called:",
     [("A", "Test data approach"),
      ("B", "Parallel simulation"),
      ("C", "Integrated test facility"),
      ("D", "Embedded audit module")]),
    (19, "Pre-Board Mock Exam: Audit Completion", "A subsequent event occurring after balance sheet date that provides additional evidence about conditions existing at balance sheet date is a:",
     [("A", "Type 2 non-adjusting event requiring disclosure only"),
      ("B", "Non-financial event to be ignored"),
      ("C", "Type 1 adjusting event requiring financial statement adjustment"),
      ("D", "Contingent asset")]),
    (20, "Pre-Board Mock Exam: Audit Completion", "If a material uncertainty regarding the entity's going concern is adequately disclosed in the notes, the auditor expresses:",
     [("A", "An adverse opinion"),
      ("B", "A disclaimer of opinion"),
      ("C", "A qualified opinion"),
      ("D", "An unmodified opinion with a 'Material Uncertainty Related to Going Concern' section")]),
    (21, "Pre-Board Mock Exam: Audit Completion", "A management representation letter (PSA 580) should be dated:",
     [("A", "As of the balance sheet date"),
      ("B", "As near as practicable to, but not after, the date of the auditor's report"),
      ("C", "When the engagement letter is executed"),
      ("D", "After the annual stockholders' meeting")]),
    (22, "Pre-Board Mock Exam: Audit Reporting", "Under PSA 700 (Revised), the section of the independent auditor's report that appears first is:",
     [("A", "Auditor's Opinion"),
      ("B", "Basis for Opinion"),
      ("C", "Management's Responsibility"),
      ("D", "Auditor's Responsibilities")]),
    (23, "Pre-Board Mock Exam: Audit Reporting", "An adverse opinion is rendered when the auditor concludes that misstatements are:",
     [("A", "Material but not pervasive"),
      ("B", "Immaterial"),
      ("C", "Both material and pervasive to the financial statements"),
      ("D", "Related to an isolated math error in petty cash")]),
    (24, "Pre-Board Mock Exam: Audit Reporting", "A disclaimer of opinion is issued when:",
     [("A", "The financial statements are presented fairly in all material respects"),
      ("B", "The auditor identified a minor departure from PFRS"),
      ("C", "The company changes its fiscal year-end"),
      ("D", "The auditor is unable to obtain sufficient appropriate audit evidence and possible effects could be both material and pervasive")]),
    (25, "Pre-Board Mock Exam: Audit Reporting", "An Emphasis of Matter paragraph (PSA 706) is used to draw users' attention to a matter:",
     [("A", "Not disclosed anywhere in the financial statements"),
      ("B", "Appropriately presented or disclosed in the financial statements that is fundamental to users' understanding"),
      ("C", "That requires a modification of the audit opinion"),
      ("D", "Relating to the auditor's private fee arrangements")]),
    (26, "Pre-Board Mock Exam: Audit Reporting", "Key Audit Matters (PSA 701) are mandatory for audits of:",
     [("A", "General purpose financial statements of listed entities"),
      ("B", "All sole proprietorships"),
      ("C", "Small local bakeries"),
      ("D", "Nonprofit charities only")]),
    (27, "Pre-Board Mock Exam: Special Engagements", "A review of historical financial statements (PSRE 2400) provides:",
     [("A", "Reasonable assurance"),
      ("B", "Absolute assurance"),
      ("C", "Moderate / limited assurance expressed in negative form"),
      ("D", "No assurance whatsoever")]),
    (28, "Pre-Board Mock Exam: Special Engagements", "In an agreed-upon procedures engagement (PSRS 4400), the practitioner:",
     [("A", "Expresses an unmodified audit opinion"),
      ("B", "Provides negative assurance"),
      ("C", "Guarantees the client's internal controls"),
      ("D", "Issues a report of factual findings without expressing an opinion or assurance")]),
    (29, "Pre-Board Mock Exam: Special Engagements", "In a compilation engagement (PSRS 4410), the accountant:",
     [("A", "Performs extensive substantive tests of details"),
      ("B", "Applies accounting expertise to assist management in presenting financial statements without obtaining audit evidence or giving assurance"),
      ("C", "Sends confirmation letters to all debtors"),
      ("D", "Counts vault cash on a surprise basis")]),
    (30, "Pre-Board Mock Exam: Professional Ethics", "The fundamental principles of professional ethics for accountants include:",
     [("A", "Integrity, Objectivity, Professional Competence and Due Care, Confidentiality, and Professional Behavior"),
      ("B", "Profitability, Speed, Aggressiveness, Secrecy, and Loyalty"),
      ("C", "Obedience, Subservience, Silence, Modesty, and Thrift"),
      ("D", "Commercialism, Exclusivity, Advertising, Self-promotion, and Pride")]),
    (31, "Pre-Board Mock Exam: Professional Ethics", "The threat that a financial or other interest will inappropriately influence the accountant's judgment is a:",
     [("A", "Familiarity threat"),
      ("B", "Self-review threat"),
      ("C", "Self-interest threat"),
      ("D", "Advocacy threat")]),
    (32, "Pre-Board Mock Exam: Professional Ethics", "The threat that arises when an audit team member promotes a client's position to the point that objectivity is compromised is an:",
     [("A", "Intimidation threat"),
      ("B", "Self-review threat"),
      ("C", "Familiarity threat"),
      ("D", "Advocacy threat")]),
    (33, "Pre-Board Mock Exam: Professional Ethics", "Under the Philippine Accountancy Act of 2004 (RA 9298), the Board of Accountancy consists of:",
     [("A", "A Chairman and three members"),
      ("B", "A Chairman and six members appointed by the President of the Philippines"),
      ("C", "Twelve members elected by PICPA"),
      ("D", "Five members appointed by the SEC")]),
    (34, "Pre-Board Mock Exam: Professional Ethics", "To pass the CPA licensure examination in the Philippines, a candidate must obtain:",
     [("A", "A general average of at least 75% with no grade lower than 65% in any subject"),
      ("B", "A general average of 80% with no grade lower than 70%"),
      ("C", "At least 70% in all subjects"),
      ("D", "At least 90% in auditing theory")]),
    (35, "Pre-Board Mock Exam: Transaction Cycles", "The primary audit procedure to test the existence assertion for trade accounts receivable is:",
     [("A", "Recalculating sales discounts"),
      ("B", "Inquiring of the shipping clerk"),
      ("C", "Direct external confirmation with debtors (PSA 505)"),
      ("D", "Aging the accounts receivable balance")]),
    (36, "Pre-Board Mock Exam: Transaction Cycles", "Kiting is a fraudulent cash scheme that involves:",
     [("A", "Stealing cash from petty cash boxes"),
      ("B", "Falsifying inventory count tags"),
      ("C", "Recording unearned revenue as earned"),
      ("D", "Exploiting the float period by transferring funds between bank accounts to artificially inflate cash balances at year-end")]),
    (37, "Pre-Board Mock Exam: Transaction Cycles", "The primary purpose of the auditor's search for unrecorded liabilities is to test the assertion of:",
     [("A", "Existence"),
      ("B", "Completeness of accounts payable"),
      ("C", "Rights and obligations"),
      ("D", "Presentation")]),
    (38, "Pre-Board Mock Exam: Transaction Cycles", "Under PSA 501, if inventory is material to the financial statements, the auditor must:",
     [("A", "Attend the physical inventory count, unless impracticable"),
      ("B", "Accept management's count certificate without question"),
      ("C", "Hire an external appraiser for all items"),
      ("D", "Sell all inventory before year-end")]),
    (39, "Pre-Board Mock Exam: Transaction Cycles", "A three-way match in the expenditure cycle requires comparing:",
     [("A", "Sales order, credit approval, and shipping slip"),
      ("B", "Check, deposit slip, and passbook"),
      ("C", "Purchase order, receiving report, and vendor's invoice"),
      ("D", "Time card, payroll check, and tax return")]),
    (40, "Pre-Board Mock Exam: Transaction Cycles", "To verify the valuation assertion for inventory, the auditor tests that inventory is carried at:",
     [("A", "Replacement cost"),
      ("B", "Fair market value less 10%"),
      ("C", "Historical list price"),
      ("D", "The lower of cost and net realizable value (LCNRV) in accordance with PAS 2")]),
    (41, "Pre-Board Mock Exam: Mixed Comprehensive", "An auditor who accepts an engagement to audit financial statements without having sufficient industry expertise must:",
     [("A", "Issue an immediate disclaimer"),
      ("B", "Obtain a sufficient level of knowledge of the client's business and industry to perform the audit competently"),
      ("C", "Subcontract the entire audit to competitors"),
      ("D", "Charge double the normal fee")]),
    (42, "Pre-Board Mock Exam: Mixed Comprehensive", "The pre-engagement phase includes evaluating client integrity primarily to:",
     [("A", "Minimize the likelihood of associating with a client whose management lacks integrity (management fraud risk)"),
      ("B", "Determine the client's credit score"),
      ("C", "Help the client avoid taxes"),
      ("D", "Ensure high audit profitability")]),
    (43, "Pre-Board Mock Exam: Mixed Comprehensive", "Communication between the successor auditor and predecessor auditor is:",
     [("A", "Prohibited by ethics rules"),
      ("B", "Mandatory only if litigation exists"),
      ("C", "A necessary procedure, initiated by the successor auditor with the client's written permission"),
      ("D", "Conducted secretly without client knowledge")]),
    (44, "Pre-Board Mock Exam: Mixed Comprehensive", "Which document confirms the auditor's acceptance of appointment, objectives, scope, and management's responsibilities?",
     [("A", "Management representation letter"),
      ("B", "Audit charter"),
      ("C", "Comfort letter"),
      ("D", "Audit engagement letter (PSA 210)")]),
    (45, "Pre-Board Mock Exam: Mixed Comprehensive", "Overall audit strategy sets the:",
     [("A", "Exact sample sizes for every single account"),
      ("B", "Scope, timing, and direction of the audit, and guides the development of the more detailed audit plan"),
      ("C", "Hourly billing rates of junior staff"),
      ("D", "Annual dividend payment schedule")]),
    (46, "Pre-Board Mock Exam: Mixed Comprehensive", "Performance materiality is set by the auditor to:",
     [("A", "Reduce to an appropriately low level the probability that the aggregate of uncorrected and undetected misstatements exceeds overall materiality"),
      ("B", "Increase audit fees"),
      ("C", "Equal total assets"),
      ("D", "Determine the client's bonus structure")]),
    (47, "Pre-Board Mock Exam: Mixed Comprehensive", "Tests of controls are performed to test:",
     [("A", "The mathematical accuracy of general ledger balances"),
      ("B", "The market value of investments"),
      ("C", "The operating effectiveness of internal controls in preventing or detecting material misstatements"),
      ("D", "The honesty of the client's competitors")]),
    (48, "Pre-Board Mock Exam: Mixed Comprehensive", "Substantive procedures comprise:",
     [("A", "Inquiries of janitorial staff only"),
      ("B", "Review of corporate bylaws only"),
      ("C", "Reading newspaper articles"),
      ("D", "Tests of details (of classes of transactions, account balances, and disclosures) and substantive analytical procedures")]),
    (49, "Pre-Board Mock Exam: Mixed Comprehensive", "Audit working papers serve as:",
     [("A", "A substitute for client accounting records"),
      ("B", "The principal record of audit procedures performed, relevant audit evidence obtained, and conclusions reached"),
      ("C", "Public records open to all citizens"),
      ("D", "A legal deed of ownership")]),
    (50, "Pre-Board Mock Exam: Mixed Comprehensive", "Audit documentation must be assembled into a final audit file not later than:",
     [("A", "60 days after the date of the auditor's report (PSA 230)"),
      ("B", "365 days after report date"),
      ("C", "The end of the fiscal year"),
      ("D", "5 days after fieldwork")]),
    (51, "Pre-Board Mock Exam: Mixed Comprehensive", "Which assertion is being tested when the auditor traces transactions from source documents to accounting records?",
     [("A", "Occurrence"),
      ("B", "Existence"),
      ("C", "Completeness"),
      ("D", "Rights and obligations")]),
    (52, "Pre-Board Mock Exam: Mixed Comprehensive", "Which assertion is being tested when the auditor vouches entries from accounting records to supporting source documents?",
     [("A", "Completeness"),
      ("B", "Classification"),
      ("C", "Cutoff"),
      ("D", "Occurrence / Existence")]),
    (53, "Pre-Board Mock Exam: Mixed Comprehensive", "An auditor who discovers that management intentionally misstated revenue by 20% should consider this finding:",
     [("A", "Immaterial if dollar amounts are low"),
      ("B", "A qualitative indicator of fraud that may have broad implications for audit integrity and risk assessment"),
      ("C", "A clerical mistake to be corrected quietly"),
      ("D", "A tax deduction")]),
    (54, "Pre-Board Mock Exam: Mixed Comprehensive", "PSA 260 requires the auditor to communicate which of the following to those charged with governance?",
     [("A", "Significant difficulties encountered, uncorrected misstatements, and auditor independence"),
      ("B", "Detailed personal backgrounds of audit staff"),
      ("C", "Passwords to audit firm software"),
      ("D", "Stock investment tips")]),
    (55, "Pre-Board Mock Exam: Mixed Comprehensive", "Dual dating of an auditor's report is used when:",
     [("A", "The auditor wishes to double the audit fee"),
      ("B", "The audit was performed by two independent firms"),
      ("C", "A subsequent event occurs after the audit report date but before issuance, and management amends the disclosures for that specific event"),
      ("D", "The client operates in two different time zones")]),
    (56, "Pre-Board Mock Exam: Mixed Comprehensive", "When prior period financial statements were audited by another CPA (predecessor auditor), the successor auditor may:",
     [("A", "Disclaim all comparative figures"),
      ("B", "Re-issue the predecessor's report under the successor's name"),
      ("C", "Delete comparative columns entirely"),
      ("D", "State in an Other Matter paragraph that prior statements were audited by a predecessor, the type of opinion expressed, and date of report")]),
    (57, "Pre-Board Mock Exam: Mixed Comprehensive", "A scope limitation imposed by management that prevents the auditor from obtaining sufficient evidence for a material and pervasive item results in:",
     [("A", "An adverse opinion"),
      ("B", "A disclaimer of opinion"),
      ("C", "An unqualified opinion with emphasis"),
      ("D", "A standard review report")]),
    (58, "Pre-Board Mock Exam: Mixed Comprehensive", "If an auditor is not independent with respect to an assurance client, the auditor must:",
     [("A", "Disclaim an opinion and state that the auditor is not independent"),
      ("B", "Issue an adverse opinion"),
      ("C", "Issue a qualified opinion"),
      ("D", "Add an Emphasis of Matter paragraph")]),
    (59, "Pre-Board Mock Exam: Mixed Comprehensive", "An auditor's report on financial statements prepared using a cash receipts and disbursements basis (special purpose framework) shall include:",
     [("A", "An adverse opinion on compliance with PFRS"),
      ("B", "A disclaimer of opinion on cash receipts"),
      ("C", "An Emphasis of Matter paragraph drawing attention to the note describing the basis of accounting"),
      ("D", "No opinion section")]),
    (60, "Pre-Board Mock Exam: Mixed Comprehensive", "Which of the following standards governs engagements to report on summary financial statements?",
     [("A", "PSA 700"), ("B", "PSA 705"), ("C", "PSA 706"), ("D", "PSA 810")]),
    (61, "Pre-Board Mock Exam: Mixed Comprehensive", "Under RA 9298, all registered CPAs who practice public accountancy must renew their accreditation every:",
     [("A", "Year"), ("B", "Three (3) years"), ("C", "Five years"), ("D", "Ten years")]),
    (62, "Pre-Board Mock Exam: Mixed Comprehensive", "The standard-setting body responsible for preparing and promulgating Philippine Standards on Auditing is the:",
     [("A", "Auditing and Assurance Standards Council (AASC)"),
      ("B", "Financial Reporting Standards Council (FRSC)"),
      ("C", "Securities and Exchange Commission"),
      ("D", "Bureau of Internal Revenue")]),
    (63, "Pre-Board Mock Exam: Mixed Comprehensive", "A key audit partner of a public interest entity must be rotated off the engagement after serving for a maximum period of:",
     [("A", "Two years"), ("B", "Three years"), ("C", "Seven years (or 5 years under SEC rules)"), ("D", "Fifteen years")]),
    (64, "Pre-Board Mock Exam: Mixed Comprehensive", "Contingent fee arrangements for financial statement audit engagements are:",
     [("A", "Encouraged for small business clients"),
      ("B", "Permitted if approved by the Board of Directors"),
      ("C", "Permitted for non-profit entities only"),
      ("D", "Strictly prohibited by the Code of Ethics because they create an insurmountable self-interest threat")]),
    (65, "Pre-Board Mock Exam: Mixed Comprehensive", "When counting cash on hand at client headquarters, surprise counts are conducted primarily to prevent:",
     [("A", "Excessive employee breaks"),
      ("B", "Concealment of cash shortages by borrowing funds or transferring cash from other sources"),
      ("C", "Overtime charges by the auditor"),
      ("D", "Bank service charges")]),
    (66, "Pre-Board Mock Exam: Mixed Comprehensive", "The primary purpose of preparing a cutoff bank statement in an audit is to:",
     [("A", "Verify outstanding checks and deposits in transit on the year-end bank reconciliation"),
      ("B", "Compute average daily bank balance"),
      ("C", "Detect counterfeit bills"),
      ("D", "Authorize wire transfers")]),
    (67, "Pre-Board Mock Exam: Mixed Comprehensive", "In testing payroll, the discovery of hours recorded for an employee who has been terminated three months ago indicates a risk of:",
     [("A", "Overtime miscalculation"),
      ("B", "Inadequate fringe benefits"),
      ("C", "Fictitious (ghost) employees on the payroll"),
      ("D", "Income tax overwithholding")]),
    (68, "Pre-Board Mock Exam: Mixed Comprehensive", "Which document constitutes the best evidence of title and ownership for land and buildings?",
     [("A", "Real estate tax declaration only"),
      ("B", "Purchase order"),
      ("C", "Vendor billing statement"),
      ("D", "Original Transfer Certificate of Title (TCT) registered with the Registry of Deeds")]),
    (69, "Pre-Board Mock Exam: Mixed Comprehensive", "The primary reason why an auditor attends physical inventory counting is to:",
     [("A", "Determine retail pricing markups"),
      ("B", "Evaluate management's count procedures, observe the count, inspect inventory, and perform test counts to verify existence and condition"),
      ("C", "Unload freight from shipping trucks"),
      ("D", "Sign delivery receipts on behalf of the warehouse")]),
    (70, "Pre-Board Mock Exam: Mixed Comprehensive", "The overarching goal of the CPA licensure examination and professional regulation under RA 9298 is to:",
     [("A", "Protect the public interest by ensuring high standards of competence, integrity, and ethical conduct in the accountancy profession"),
      ("B", "Limit the number of practicing accountants to increase salaries"),
      ("C", "Collect taxes for the national treasury"),
      ("D", "Promote commercial interests of accounting software vendors")])
]

chapterFinale = {
    "id": "at-finale",
    "code": "FINALE",
    "title": "Chapter Finale: CPALE Mock Examination (70 Comprehensive Board Questions)",
    "description": "Comprehensive summative assessment simulating the Certified Public Accountant Licensure Examination (CPALE) in Auditing Theory. Covers all 14 knowledge areas: Assurance Concepts, Risk Assessment, Internal Control, CIS, Evidence, Sampling, Reporting, Ethics & RA 9298, and Transaction Cycles.",
    "objectives": [
        "Pre-Board Mock Exam: Assurance Concepts",
        "Pre-Board Mock Exam: Risk Assessment",
        "Pre-Board Mock Exam: Internal Control",
        "Pre-Board Mock Exam: Fraud & Non-Compliance",
        "Pre-Board Mock Exam: Audit Evidence",
        "Pre-Board Mock Exam: Audit Sampling",
        "Pre-Board Mock Exam: CIS & IT Auditing",
        "Pre-Board Mock Exam: Audit Completion",
        "Pre-Board Mock Exam: Audit Reporting",
        "Pre-Board Mock Exam: Special Engagements",
        "Pre-Board Mock Exam: Professional Ethics",
        "Pre-Board Mock Exam: Transaction Cycles",
        "Pre-Board Mock Exam: Mixed Comprehensive"
    ],
    "totalQuestions": 70,
    "questions": []
}

for num, obj, qtext, opts in finale_raw:
    correct = finale_answers[num]
    expl = finale_explanations.get(num, f"Suggested Answer: {correct}. In accordance with Philippine Standards on Auditing (PSAs), the Code of Ethics for Professional Accountants, and Republic Act No. 9298.")
    chapterFinale["questions"].append({
        "id": f"finale-{num}",
        "number": num,
        "chapterId": "at-finale",
        "chapterCode": "FINALE",
        "chapterTitle": "Chapter Finale: CPALE Mock Examination",
        "objective": obj,
        "question": qtext,
        "options": [{"key": k, "text": t} for k, t in opts],
        "correctAnswer": correct,
        "explanation": expl
    })

with open("src/data/chapters/finale.ts", "w", encoding="utf-8") as f:
    f.write(f"import {{ Chapter }} from '../../types/quiz';\n\nexport const chapterFinale: Chapter = {json.dumps(chapterFinale, indent=2)};\n")

print("Created finale.ts with 70 questions")
