#!/usr/bin/env python3
import json

at04_answers = {
    1: 'B', 2: 'D', 3: 'D', 4: 'C', 5: 'B', 6: 'D', 7: 'D', 8: 'A', 9: 'A', 10: 'A',
    11: 'C', 12: 'B', 13: 'A', 14: 'A', 15: 'D', 16: 'A', 17: 'D', 18: 'B', 19: 'C', 20: 'D',
    21: 'B', 22: 'A', 23: 'A', 24: 'D', 25: 'D', 26: 'B', 27: 'B', 28: 'D', 29: 'A', 30: 'A',
    31: 'A', 32: 'C', 33: 'D', 34: 'B', 35: 'B', 36: 'B', 37: 'B', 38: 'D', 39: 'B', 40: 'A',
    41: 'A', 42: 'A', 43: 'A', 44: 'C', 45: 'A', 46: 'B', 47: 'D', 48: 'A', 49: 'A', 50: 'D'
}

at04_explanations = {
    1: "An audit of FS can only provide reasonable assurance or express an opinion on the fairness of the FS in all material respects. It cannot provide absolute assurance nor express an opinion on the accuracy of the FS in respects because of its inherent limitations.",
    2: "Professional skepticism is an attitude that includes a questioning mind, a critical assessment of validity of audit evidence, and being alert to conditions which may indicate possible misstatement due to error or fraud.",
    4: "The auditability of client's financial statements determine whether the auditor will be able to accumulate sufficient appropriate audit evidence to render an opinion on the financial statements by considering the adequacy of accounting records and quality of internal control.",
    5: "In the case of new clients, the firm is required to conduct a background investigation of the prospective client in order to minimize the likelihood of association with clients whose management lacks integrity. In the case of continuing clients, this is to ensure the audit firm's compliance with acceptance and continuance procedures of the auditing standards.",
    6: "Choice D is being done throughout the audit, not during pre-engagement activities.",
    7: "Choice D is being done during the planning phase of the audit.",
    9: "The preparation of financial statements should be in accordance with the PFRSs, not with the AASC.",
    17: "When evidence is difficult to obtain from the client, it would be best to reject the client as costs may outweigh the benefits of the audit.",
    23: "These matters should be gathered internally.",
    24: "Under the Code of Ethics for CPAs, the successor auditor has the responsibility to initiate communication with the predecessor auditor. However, the communication requires prior client's permission/consent (preferably in writing) to avoid violation of confidentiality principle.",
    27: "The matters to be inquired of the predecessor auditor include: integrity of management, reasons for change of auditors, disagreements regarding accounting or auditing procedures, and communication to governance regarding fraud or internal control deficiencies.",
    32: "This is not an appropriate inquiry as this might show that the auditor is not objective.",
    33: "Contact with the predecessor should be conducted prior to the acceptance of the audit.",
    34: "For confidentiality purposes there must be consent with the potential client about the discussion with the successor auditor.",
    35: "The written communication is known as the audit engagement letter.",
    44: "The details of the audit procedures should not be made known to the client."
}

at04_raw = [
    (1, "Pre-Engagement Activities and Procedures", "The objective of the ordinary audit of financial statements is the expression of an opinion on:",
     [("A", "The fairness of the financial statements in all respects."),
      ("B", "The fairness of the financial statements in all material respects."),
      ("C", "The accuracy of the financial statements in all respects."),
      ("D", "The accuracy of the financial statements in all material respects.")]),
    (2, "Pre-Engagement Activities and Procedures", "Given that an audit in accordance with generally accepted auditing standards is influenced by the possibility of material errors and fraud, the auditor should conduct the audit with an attitude of:",
     [("A", "Professional responsiveness"), ("B", "Conservative advocacy"), ("C", "Objective judgment"), ("D", "Professional skepticism")]),
    (3, "Pre-Engagement Activities and Procedures", "An audit process is a well-defined methodology for organizing an audit to ensure that:\nA. The evidence gathered is both sufficient and competent.\nB. All appropriate audit objectives are specified.\nC. All appropriate audit objectives are met\nD. All of the above.",
     [("A", "A only"), ("B", "B only"), ("C", "C only"), ("D", "All of the above.")]),
    (4, "Pre-Engagement Activities and Procedures", "Which of the following factors most likely would influence an auditor's determination of the auditability of the entity's financial statements?",
     [("A", "The complexity of the accounting system."),
      ("B", "The existence of related party transactions."),
      ("C", "The adequacy of the accounting records."),
      ("D", "The operating effectiveness of control procedures.")]),
    (5, "Pre-Engagement Activities and Procedures", "Investigation of new clients and re-evaluation of existing ones is an essential part of deciding:",
     [("A", "Inherent risk."), ("B", "Whether to accept the engagement."), ("C", "Statistical risk."), ("D", "Financial risk.")]),
    (6, "Pre-Engagement Activities and Procedures", "Which of the following is not one of the reasons why auditors should perform preliminary engagement activities?",
     [("A", "To ensure that the auditor maintains the necessary independence and ability to perform the engagement."),
      ("B", "To help ensure that there are no issues with management integrity that may affect the auditor's willingness to continue the engagement."),
      ("C", "To ensure that there is no misunderstanding with the client as to the terms of the engagement."),
      ("D", "To ensure that sufficient appropriate evidence will be obtained to support the auditor's opinion on the financial statements.")]),
    (7, "Pre-Engagement Activities and Procedures", "Which of the following is not normally performed in the pre-engagement phase?",
     [("A", "Deciding whether to accept or reject an audit engagement."),
      ("B", "Inquiring from predecessor auditor."),
      ("C", "Preparing an engagement letter."),
      ("D", "Making a preliminary estimate of materiality.")]),
    (8, "Pre-Engagement Activities and Procedures", "Which of the following is not normally performed in the pre-engagement phase?",
     [("A", "Assessing control risk."),
      ("B", "Deciding whether to accept or reject an audit engagement."),
      ("C", "Inquiring from predecessor auditor."),
      ("D", "Preparing an engagement letter.")]),
    (9, "Pre-Engagement Activities and Procedures", "An audit is conducted on the premise that management and, where appropriate, those charged with governance, have acknowledged and understand that they have responsibilities that are fundamental to the conduct of an audit in accordance with PSAs. Which of the following is not one of those responsibilities?",
     [("A", "The preparation of financial statements in accordance with relevant pronouncements issued by the AASC."),
      ("B", "The establishment and maintenance of an adequate internal control system that is necessary to enable the preparation of financial statements that are free from material misstatement, whether due to fraud or error."),
      ("C", "To provide the auditor with access to all information that is relevant to the preparation of financial statements such as records, documentation, and other matters."),
      ("D", "To provide the auditor with unrestricted access to persons within the entity from which the auditor determines it necessary to obtain audit evidence.")]),
    (10, "Pre-Engagement Activities and Procedures", "Before accepting an engagement to audit a new client, a CPA is required to obtain:",
     [("A", "A preliminary understanding of the prospective client's industry and business."),
      ("B", "The prospective client's signature to the engagement letter."),
      ("C", "An understanding of the prospective client's control environment."),
      ("D", "A representation letter from the prospective client.")]),
    (11, "Pre-Engagement Activities and Procedures", "The auditor may accept or continue an audit engagement only when the basis upon which it is to be performed has been agreed, through\nI. Establishing whether the preconditions for an audit are present.\nII. Confirming that there is a common understanding between the auditor and management and, where appropriate, those charged with governance of the terms of the audit engagement.",
     [("A", "I only"), ("B", "II only"), ("C", "Both I and II"), ("D", "Neither I nor II")]),
    (12, "Pre-Engagement Activities and Procedures", "The use of management of an acceptable financial reporting framework in the preparation of the financial statements and the agreement of management and, where appropriate, those charged with governance to the premise on which an audit is conducted.",
     [("A", "Terms of audit engagement"), ("B", "Preconditions for the audit"), ("C", "Scope of the audit"), ("D", "Financial statement audit")]),
    (13, "Pre-Engagement Activities and Procedures", "In making a decision to accept or continue with a client, the auditor should consider which of the following?\nIts competence | Its independence | Its ability to serve properly | Integrity of management\nA. Yes | Yes | Yes | Yes\nB. Yes | No | Yes | Yes\nC. Yes | Yes | Yes | No\nD. Yes | No | No | Yes",
     [("A", "Yes, Yes, Yes, Yes"), ("B", "Yes, No, Yes, Yes"), ("C", "Yes, Yes, Yes, No"), ("D", "Yes, No, No, Yes")]),
    (14, "Pre-Engagement Activities and Procedures", "Statement I: If management or those charged with governance impose a limitation on the scope of the auditor's work in the terms of a proposed audit engagement such that the auditor believes the limitation will result in the auditor disclaiming an opinion on the financial statements, the auditor shall not accept such a limited engagement as an audit engagement, unless required by law or regulation to do so.\nStatement II: The auditor shall agree the terms of the audit engagement with management or those charged with governance, as appropriate.",
     [("A", "True, True"), ("B", "False, False"), ("C", "True, False"), ("D", "False, True")]),
    (15, "Pre-Engagement Activities and Procedures", "Which of the following would an auditor least likely perform as part of the auditor's preliminary engagement activities?",
     [("A", "Perform procedures regarding the continuance of the client relationship and the specific audit engagement."),
      ("B", "Evaluate compliance with ethical requirements, including independence."),
      ("C", "Establish an understanding of the terms of the engagement."),
      ("D", "Obtain understanding of the legal and regulatory framework applicable to the entity.")]),
    (16, "Pre-Engagement Activities and Procedures", "Which of the following most likely would cause an auditor to decline a new audit engagement?",
     [("A", "Concluding that the entity's management probably lacks integrity."),
      ("B", "An inability to perform preliminary analytical procedures before assessing control risk."),
      ("C", "An inadequate understanding of the entity's internal control."),
      ("D", "The close proximity to the end of the entity's reporting period.")]),
    (17, "Pre-Engagement Activities and Procedures", "Which of the following factors most likely would lead a CPA to assume that a potential audit engagement should be rejected?",
     [("A", "There are significant related party transactions that management claims occurred in the ordinary course of business."),
      ("B", "Internal control activities requiring the segregation of duties are subject to management override."),
      ("C", "Management continues to employ an inefficient system of information technology to record financial transactions."),
      ("D", "It is unlikely that sufficient evidence is available to support an opinion on the financial statements.")]),
    (18, "Pre-Engagement Activities and Procedures", "If an auditor believes that an understanding with the client has not been established, he or she should ordinarily:",
     [("A", "Perform the audit with increased professional skepticism."),
      ("B", "Decline to accept or perform the audit."),
      ("C", "Assess the control risk at the maximum level and perform a primarily substantive audit."),
      ("D", "Modify the scope of the audit to reflect an increased risk of material misstatement due to fraud.")]),
    (19, "Pre-Engagement Activities and Procedures", "An initial audit requires more audit time to complete than a recurring audit. One of the reasons for this is that:",
     [("A", "The new auditors are usually assigned to an initial audit."),
      ("B", "The predecessor auditors need to be consulted."),
      ("C", "The client's business, industry, and internal control are unfamiliar to the auditor and he needs to carefully study them."),
      ("D", "A larger proportion of customer accounts receivable need to be confirmed on an initial audit.")]),
    (20, "Pre-Engagement Activities and Procedures", "Which of the following factors most likely would cause a CPA to not accept a new audit engagement?",
     [("A", "The prospective client has fired its prior auditor."),
      ("B", "The CPA lacks a thorough understanding of the prospective client's operations and industry."),
      ("C", "The CPA is unable to review the predecessor auditor's working papers."),
      ("D", "The prospective client is unwilling to make financial records available to the CPA.")]),
    (21, "Pre-Engagement Activities and Procedures", "Preplanning the audit involves several key activities. Which of the following would not be included in preplanning an audit?",
     [("A", "Investigating the client's background."),
      ("B", "Determining the likelihood of issuing an unqualified audit opinion on the client's financial statements."),
      ("C", "Communicating with the prospective client's prior auditor to inquire about any disagreements with the client."),
      ("D", "Understanding the client's reasons for obtaining an audit.")]),
    (22, "Pre-Engagement Activities and Procedures", "Preliminary knowledge about the client's business and industry must be obtained prior to the acceptance of the engagement primarily to:",
     [("A", "Determine the degree of knowledge and expertise required by the engagement."),
      ("B", "Determine the integrity of management."),
      ("C", "Determine whether the firm is independent with the client."),
      ("D", "Gather evidence about the fairness of the financial statements.")]),
    (23, "Pre-Engagement Activities and Procedures", "Which of the following is not considered a valid source of information about the client's processes?",
     [("A", "Confirmation from third parties."),
      ("B", "Review of the client's budget."),
      ("C", "A tour of the client's plant facility."),
      ("D", "Management inquiry.")]),
    (24, "Pre-Engagement Activities and Procedures", "Prior to the acceptance of an audit engagement with a client who has terminated the services of the predecessor auditor, the CPA should:",
     [("A", "Contact the predecessor auditor without advising the prospective client and request a complete report of the circumstance leading to the termination with the understanding that all information disclosed will be kept confidential."),
      ("B", "Accept the engagement without contacting the predecessor auditor since the CPA can include audit procedures to verify the reason given by the client for the termination."),
      ("C", "Not communicate with the predecessor auditor because this would in effect be asking the auditor to violate the confidential relationship between the auditor and the client."),
      ("D", "Advise the client of the intention to contact the predecessor auditor and request permission for the contact.")]),
    (25, "Pre-Engagement Activities and Procedures", "Before accepting an engagement to audit a new client, a CPA is required to obtain:",
     [("A", "An understanding of the prospective client's industry and business."),
      ("B", "The prospective client's signature to the engagement letter."),
      ("C", "A preliminary understanding of the prospective client's control environment."),
      ("D", "The prospective client's consent to make inquiries of the predecessor auditor, if any.")]),
    (26, "Pre-Engagement Activities and Procedures", "The purpose of the requirement in having communication between the predecessor and successor auditor is to:",
     [("A", "Allow the predecessor to disclose information which would otherwise be confidential."),
      ("B", "Help the successor auditor evaluate whether to accept the engagement or not."),
      ("C", "Help the client by facilitating the change of auditors."),
      ("D", "Ensure the predecessor collects all unpaid fees prior to a change in auditor.")]),
    (27, "Pre-Engagement Activities and Procedures", "What information should an incoming auditor obtain during the inquiry of the predecessor auditor prior to acceptance of the audit?\nI. Facts that bear on the integrity of management.\nII. Whether statistical or non-statistical sampling was used to gather evidence.\nIII. Disagreement with management concerning auditing procedures.\nIV. The effect of the client's internal audit function on the scope of the independent auditor's examination",
     [("A", "I and II"), ("B", "I and III"), ("C", "I and IV"), ("D", "III and IV")]),
    (28, "Pre-Engagement Activities and Procedures", "A successor auditor requested permission to communicate with the predecessor auditor and review certain portions of the predecessor auditor's working papers. The prospective client's refusal to permit this will bear directly on the successor auditor's decision concerning the:",
     [("A", "Adequacy of the preplanned audit program"),
      ("B", "Ability to establish consistency in application of accounting principles between periods."),
      ("C", "Apparent scope limitation."),
      ("D", "Integrity of the management")]),
    (29, "Pre-Engagement Activities and Procedures", "A predecessor auditor withdrew from the engagement after discovering that a client's financial statements are materially misstated that it would not revise. If asked by the successor auditor about the termination of the engagement, the predecessor auditor should:",
     [("A", "Suggest that the successor auditor should obtain the client's consent to discuss the reasons."),
      ("B", "Suggest that the successor auditor ask the client."),
      ("C", "Indicate there was a misunderstanding."),
      ("D", "State that the audit revealed material misstatement that the client would not revise.")]),
    (30, "Pre-Engagement Activities and Procedures", "When a company has changed auditors, according to the professional standards:\nA. The successor auditor has the responsibility to initiate contact with the predecessor auditor to ask about the client before the engagement is accepted; the predecessor has no responsibility to initiate this contact, even when aware of matters bearing on the integrity of management.\nB. The predecessor must respond fully to all inquiries made by the successor auditor.\nC. The successor must discuss with the predecessor matters bearing on the engagement prior to accepting the engagement.\nD. The successor may choose not to attempt any communication with the predecessor auditor.",
     [("A", "Statement A is correct."),
      ("B", "Statement B is correct."),
      ("C", "Statement C is correct."),
      ("D", "Statement D is correct.")]),
    (31, "Pre-Engagement Activities and Procedures", "Before accepting an audit engagement, a successor auditor should make specific inquiries of the predecessor auditor regarding:",
     [("A", "Disagreements the predecessor had with the client concerning auditing procedures and accounting principles."),
      ("B", "The predecessor's evaluation of matters of continuing accounting significance."),
      ("C", "The degree of cooperation the predecessor received concerning the inquiry of the client's lawyer."),
      ("D", "The predecessor's assessments of inherent risk and judgments about materiality.")]),
    (32, "Pre-Engagement Activities and Procedures", "When inquiring the predecessor auditor regarding the client which of the following is not an appropriate inquiry?",
     [("A", "Reason for replacing the auditor."),
      ("B", "Misunderstandings with the client."),
      ("C", "If the client allows payment for a specific opinion."),
      ("D", "Understanding more about the client.")]),
    (33, "Pre-Engagement Activities and Procedures", "A successor auditor is required to attempt communication with the predecessor auditor prior to:",
     [("A", "Performing test of controls."),
      ("B", "Testing beginning balances for the current year."),
      ("C", "Making a proposal for the audit engagement."),
      ("D", "Accepting the engagement.")]),
    (34, "Pre-Engagement Activities and Procedures", "Which statement is correct relating to a successor auditor's responsibility for communicating with the predecessor auditors in connection with a prospective new audit client?",
     [("A", "The successor auditors have no responsibility to contact the predecessor auditors."),
      ("B", "The successor auditors should obtain permission from the prospective client to contact the predecessor auditors."),
      ("C", "The successor auditors should contact the predecessors regardless of whether the prospective client authorizes contact."),
      ("D", "The successor auditors need not contact the predecessors if the successors are aware of all available relevant facts.")]),
    (35, "Audit Engagement Letter", "The auditors' understanding established with a client should be established through a(n):",
     [("A", "Oral communication with the client."),
      ("B", "Written communication with the client."),
      ("C", "Written or oral communication with the client."),
      ("D", "Completely detailed audit plan.")]),
    (36, "Audit Engagement Letter", "Preliminary arrangements agreed to by the auditors and the client should be in writing by the auditors. The best place to set forth these arrangements is in:",
     [("A", "A memorandum to be placed in the permanent section of the auditing working papers."),
      ("B", "An engagement letter."),
      ("C", "A client representation letter."),
      ("D", "A confirmation letter attached to the constructive services letter.")]),
    (37, "Audit Engagement Letter", "According to PSA 210, the auditor and the client should agree on the terms of engagement. The agreed terms would need to be recorded in a(n):",
     [("A", "Memorandum to be placed in the permanent section of the auditing working papers."),
      ("B", "Engagement letter"),
      ("C", "Client representation letter"),
      ("D", "Comfort letter")]),
    (38, "Audit Engagement Letter", "Engagement letter that documents and confirms the auditor's acceptance of the engagement would normally be sent to the client:",
     [("A", "Before the audit report is issued."),
      ("B", "After the audit report is issued."),
      ("C", "At the end of fieldwork."),
      ("D", "Before the commencement of the engagement.")]),
    (39, "Audit Engagement Letter", "The purpose of an engagement letter is to:",
     [("A", "Document the CPA firm's responsibility to external users of the audited financial statements."),
      ("B", "Document the terms of the engagement to writing in order to minimize misunderstandings."),
      ("C", "Notify the audit staff of an upcoming engagement so that personnel scheduling can be facilitated."),
      ("D", "All of the above.")]),
    (40, "Audit Engagement Letter", "Which of the following matters is generally included in an auditor's engagement letter?",
     [("A", "Limitations of the engagement."),
      ("B", "Factors to be considered in establishing preliminary judgments about materiality."),
      ("C", "Management's liability for illegal acts committed by its employees."),
      ("D", "The auditor's responsibility to obtain negative assurance relating to the occurrence of illegal acts.")]),
    (41, "Audit Engagement Letter", "Which of the following topics is not normally included in an engagement letter?",
     [("A", "The auditors' preliminary assessment of internal control."),
      ("B", "The auditors' estimate of the fee for the engagement."),
      ("C", "Limitations on the scope of the engagement."),
      ("D", "A description of responsibility for the detection of fraud.")]),
    (42, "Audit Engagement Letter", "Which of the following is (are) valid reasons why an auditor sends to his client an engagement letter?\nTo avoid misunderstanding with respect to engagement | To confirm acceptance | To document objective and scope\nA. Yes | Yes | Yes\nB. Yes | No | Yes\nC. No | Yes | Yes\nD. Yes | Yes | No",
     [("A", "Yes, Yes, Yes"), ("B", "Yes, No, Yes"), ("C", "No, Yes, Yes"), ("D", "Yes, Yes, No")]),
    (43, "Audit Engagement Letter", "An engagement letter should ordinarily include information on the objectives of the engagement and:\nCPA's responsibilities | Client's responsibilities | Limitation of engagement\nA. Yes | Yes | Yes\nB. Yes | No | Yes\nC. Yes | No | No\nD. No | No | No",
     [("A", "Yes, Yes, Yes"), ("B", "Yes, No, Yes"), ("C", "Yes, No, No"), ("D", "No, No, No")]),
    (44, "Audit Engagement Letter", "An engagement letter would not normally include:",
     [("A", "Billing arrangement."),
      ("B", "Arrangement concerning client's assistance."),
      ("C", "Details of the procedure that will be performed."),
      ("D", "Expectation of receiving a representation letter from management.")]),
    (45, "Audit Engagement Letter", "Which of the following matters is generally included in an auditor's engagement letter?",
     [("A", "Management's responsibility for the entity's compliance with laws and regulations."),
      ("B", "The factors to be considered in setting preliminary judgments about materiality."),
      ("C", "Management's explicit liability for illegal acts committed by its employees."),
      ("D", "The auditor's responsibility to search for significant internal control deficiencies.")]),
    (46, "Audit Engagement Letter", "An audit engagement least likely includes:",
     [("A", "A reference to the inherent limitation of an audit that some material misstatements may remain undiscovered."),
      ("B", "Identification of specific audit procedures that the auditor needs to undertake."),
      ("C", "Description of any letters or reports that the auditor expects to submit to the client."),
      ("D", "Arrangements concerning the involvement of internal auditors and other client's staff.")]),
    (47, "Audit Engagement in Recurring Audits", "In which of the following situations would the auditor be unlikely to send a new engagement letter to a continuing client?",
     [("A", "A change in terms of the engagement."),
      ("B", "A significant change in the nature or size of the client's business."),
      ("C", "A recent change of client management."),
      ("D", "A recent change in the partner and/or staff in the audit engagement.")]),
    (48, "Audit of Components", "When the auditor of a parent entity is also the auditor of its component (i.e., subsidiary, branch or division), which of the following factors would least likely influence the auditor's decision to send separate letter to a component of a parent?",
     [("A", "Geographical location of the component."),
      ("B", "Legal requirements"),
      ("C", "Degree of ownership by parent"),
      ("D", "Degree of independence of component's management")]),
    (49, "Acceptance of a Change in the Terms of the Audit Engagement", "The auditor shall not agree to a request from the entity to change the terms of the audit engagement or to change the audit engagement to an engagement that conveys a lower level of assurance when there is no reasonable justification for doing so. Which of the following may be considered reasonable justifications for the change in the audit engagement?\nI. A change in circumstances affecting the need for the service.\nII. A misunderstanding as to the nature of an audit as originally requested.\nIII. A restriction on the scope of the engagement, whether imposed by management or caused by other circumstances.",
     [("A", "I and II only"), ("B", "I and III only"), ("C", "II and III only"), ("D", "I, II, and III")]),
    (50, "Acceptance of a Change in the Terms of the Audit Engagement", "If the auditor is unable to agree to a change of the engagement and is not permitted to continue the original engagement, the auditor should:",
     [("A", "Insist on continuing the original engagement"),
      ("B", "Express a qualified opinion"),
      ("C", "Express an adverse opinion"),
      ("D", "Withdraw from the engagement.")])
]

chapter04 = {
    "id": "at-04",
    "code": "AT-04",
    "title": "Pre-Engagement Activities and Procedures",
    "description": "Client acceptance and continuance, preconditions for an audit, communication with predecessor auditors, audit engagement letters (PSA 210), recurring audits, components, and changes in engagement terms.",
    "objectives": [
        "Pre-Engagement Activities and Procedures",
        "Audit Engagement Letter",
        "Audit Engagement in Recurring Audits",
        "Audit of Components",
        "Acceptance of a Change in the Terms of the Audit Engagement"
    ],
    "totalQuestions": 50,
    "questions": []
}

for num, obj, qtext, opts in at04_raw:
    correct = at04_answers[num]
    expl = at04_explanations.get(num, f"Suggested Answer: {correct}. In accordance with PSA 210 (Agreeing the Terms of Audit Engagements) and Code of Ethics.")
    chapter04["questions"].append({
        "id": f"at04-{num}",
        "number": num,
        "chapterId": "at-04",
        "chapterCode": "AT-04",
        "chapterTitle": "Pre-Engagement Activities and Procedures",
        "objective": obj,
        "question": qtext,
        "options": [{"key": k, "text": t} for k, t in opts],
        "correctAnswer": correct,
        "explanation": expl
    })

with open("src/data/chapters/at04.ts", "w", encoding="utf-8") as f:
    f.write(f"import {{ Chapter }} from '../../types/quiz';\n\nexport const chapter04: Chapter = {json.dumps(chapter04, indent=2)};\n")

print("Created at04.ts with 50 questions")
