#!/usr/bin/env python3
import json

at15_answers = {
    1: 'B', 2: 'C', 3: 'A', 4: 'C', 5: 'D', 6: 'B', 7: 'C', 8: 'A', 9: 'C', 10: 'D',
    11: 'B', 12: 'A', 13: 'B', 14: 'C', 15: 'C', 16: 'C', 17: 'B', 18: 'B', 19: 'A', 20: 'D',
    21: 'B', 22: 'C', 23: 'D', 24: 'B', 25: 'A', 26: 'A', 27: 'C', 28: 'D', 29: 'D', 30: 'B',
    31: 'D', 32: 'B', 33: 'A', 34: 'C', 35: 'D', 36: 'B', 37: 'A', 38: 'D', 39: 'B', 40: 'D',
    41: 'A', 42: 'B', 43: 'B', 44: 'C', 45: 'A', 46: 'A', 47: 'C', 48: 'C', 49: 'D', 50: 'C',
    51: 'C', 52: 'D', 53: 'A', 54: 'A', 55: 'B', 56: 'B', 57: 'C', 58: 'C', 59: 'A', 60: 'C',
    61: 'A', 62: 'B', 63: 'C', 64: 'B', 65: 'B', 66: 'B', 67: 'C', 68: 'B', 69: 'B', 70: 'A',
    71: 'D', 72: 'A', 73: 'B', 74: 'B', 75: 'A', 76: 'C', 77: 'B', 78: 'B', 79: 'B', 80: 'D',
    81: 'B', 82: 'A', 83: 'B', 84: 'B', 85: 'D', 86: 'A', 87: 'C', 88: 'C', 89: 'C', 90: 'D',
    91: 'A', 92: 'B', 93: 'C', 94: 'D', 95: 'A', 96: 'B', 97: 'C', 98: 'A', 99: 'B', 100: 'C'
}

at15_explanations = {
    1: "The primary internal control objective in the revenue cycle is to ensure sales are authorized, recorded at proper amounts, goods shipped only against valid customer orders, and receivables recorded accurately.",
    2: "To achieve proper segregation of duties in sales, credit approval must be separate from sales order processing and billing.",
    31: "In the expenditure cycle, matching the vendor's invoice with the purchase order and receiving report before approving payment prevents payments for unauthorized or unreceived goods (three-way match).",
    56: "Auditor attendance at physical inventory count is required under PSA 501 when inventory is material to the financial statements.",
    76: "Substantive tests of financing cycle involve examining authorization of debt/equity issuances in minutes of the board of directors and verifying compliance with debt covenants."
}

at15_raw = [
    (1, "Revenue and Collection Cycle", "The fundamental documents in a typical sales and collection cycle include:",
     [("A", "Purchase requisition, purchase order, and receiving report"),
      ("B", "Customer sales order, credit approval, shipping document (bill of lading), sales invoice, and remittance advice"),
      ("C", "Time card, payroll register, and pay slip"),
      ("D", "Job order sheet and materials requisition")]),
    (2, "Revenue and Collection Cycle", "Proper segregation of duties in the revenue cycle requires that the credit approval department be independent of:",
     [("A", "The shipping department"),
      ("B", "The warehouse"),
      ("C", "The sales department (to prevent granting credit to uncreditworthy customers just to boost sales)"),
      ("D", "The board of directors")]),
    (3, "Revenue and Collection Cycle", "Tracing shipping documents to recorded sales invoices and the sales journal tests which financial statement assertion?",
     [("A", "Completeness (ensuring all goods shipped were invoiced and recorded)"),
      ("B", "Existence"),
      ("C", "Rights and obligations"),
      ("D", "Valuation")]),
    (4, "Revenue and Collection Cycle", "Vouching recorded sales transactions in the sales journal back to shipping documents and approved customer orders tests which assertion?",
     [("A", "Completeness"),
      ("B", "Classification"),
      ("C", "Occurrence / Existence (ensuring sales recorded actually occurred and goods were shipped)"),
      ("D", "Presentation")]),
    (5, "Revenue and Collection Cycle", "The most effective audit procedure to verify the existence of accounts receivable balances is:",
     [("A", "Recalculating bad debt expense"),
      ("B", "Inquiring of the sales director"),
      ("C", "Reviewing subsequent month sales returns"),
      ("D", "External confirmation with customers (PSA 505)")]),
    (6, "Revenue and Collection Cycle", "In a positive confirmation request, the customer is asked to respond:",
     [("A", "Only if the balance is incorrect"),
      ("B", "In each case, whether the customer agrees or disagrees with the recorded amount"),
      ("C", "Only if the balance exceeds P1,000,000"),
      ("D", "Directly to the client's internal auditor")]),
    (7, "Revenue and Collection Cycle", "A negative confirmation request asks the debtor to respond:",
     [("A", "Directly to the client's credit manager"),
      ("B", "Under all circumstances"),
      ("C", "Only if the debtor disagrees with the stated amount"),
      ("D", "Only by telephone")]),
    (8, "Revenue and Collection Cycle", "Negative confirmations are appropriate when:",
     [("A", "Risk of material misstatement is low, controls are effective, population consists of a large number of small homogeneous balances, and a low exception rate is expected."),
      ("B", "Risk of material misstatement is high."),
      ("C", "Accounts receivable consists of five huge customers."),
      ("D", "Customers are known to ignore confirmations.")]),
    (9, "Revenue and Collection Cycle", "When a customer fails to respond to a positive accounts receivable confirmation after second requests, the auditor should:",
     [("A", "Write off the account as bad debt"),
      ("B", "Assume the balance is correct"),
      ("C", "Perform alternative audit procedures, such as examining subsequent cash collections, shipping documents, and sales invoices"),
      ("D", "Immediately disclaim an opinion")]),
    (10, "Revenue and Collection Cycle", "Lapping is an irregularity involving:",
     [("A", "Overstating sales discounts"),
      ("B", "Understating cash disbursements"),
      ("C", "Recording fictitious purchase orders"),
      ("D", "Concealing a cash shortage by delaying the recording of cash receipts and using collections from subsequent customers to cover prior shortages")]),
    (11, "Revenue and Collection Cycle", "Lapping can be detected by:",
     [("A", "Performing inventory counts"),
      ("B", "Comparing details of remittance advices and bank deposit slips with customer accounts receivable subsidiary ledger credits"),
      ("C", "Vouching fixed asset additions"),
      ("D", "Reviewing board minutes")]),
    (12, "Revenue and Collection Cycle", "The sales cutoff test is designed to obtain evidence that:",
     [("A", "Sales and related receivables are recorded in the accounting period in which the title transferred or goods were shipped"),
      ("B", "All credit customers pay within 30 days"),
      ("C", "No discounts were granted"),
      ("D", "Sales taxes were paid to BIR")]),
    (13, "Revenue and Collection Cycle", "A sales transaction with terms FOB destination should be recognized as a sale when:",
     [("A", "The goods leave the seller's shipping dock"),
      ("B", "The goods are received by the buyer at the specified destination"),
      ("C", "The sales order is approved"),
      ("D", "The contract is signed")]),
    (14, "Revenue and Collection Cycle", "Sales transactions with terms FOB shipping point should be recognized as sales when:",
     [("A", "Payment is collected in cash"),
      ("B", "Goods arrive at the customer's warehouse"),
      ("C", "Goods are placed in the possession of the common carrier at the shipping point"),
      ("D", "At year-end regardless of delivery")]),
    (15, "Revenue and Collection Cycle", "An auditor examining the valuation assertion for accounts receivable will focus on:",
     [("A", "Checking serial numbers on shipping documents"),
      ("B", "Confirming customers' business registrations"),
      ("C", "Evaluating the adequacy of the allowance for doubtful accounts / expected credit losses (PFRS 9)"),
      ("D", "Recalculating sales commission rates")]),
    (16, "Revenue and Collection Cycle", "Aging of accounts receivable is primarily used by the auditor to evaluate:",
     [("A", "Existence"),
      ("B", "Completeness"),
      ("C", "Valuation and allocation of trade receivables"),
      ("D", "Rights and obligations")]),
    (17, "Revenue and Collection Cycle", "Kiting is a fraudulent technique that involves:",
     [("A", "Overstating inventory through physical count manipulation"),
      ("B", "Drawing a check on one bank and depositing it in another bank right before period-end, recording deposit immediately but delaying recording disbursement to artificially inflate cash"),
      ("C", "Understating depreciation expense"),
      ("D", "Fictitious payroll employees")]),
    (18, "Revenue and Collection Cycle", "Kiting can be detected by the auditor using:",
     [("A", "Accounts receivable aging schedules"),
      ("B", "A bank transfer schedule covering transfers before and after year-end"),
      ("C", "Observation of fixed assets"),
      ("D", "Vouching marketing expenses")]),
    (19, "Revenue and Collection Cycle", "A bank confirmation (standard bank confirmation request) provides audit evidence concerning:",
     [("A", "Cash balances on deposit, loan balances, contingent liabilities, and collateral arrangements directly with the bank"),
      ("B", "The credit score of client's customers"),
      ("C", "The integrity of bank tellers"),
      ("D", "Tax liabilities to BIR")]),
    (20, "Revenue and Collection Cycle", "A bank reconciliation is prepared to reconcile the difference between:",
     [("A", "Petty cash and vault cash"),
      ("B", "Sales journal and general ledger"),
      ("C", "Accounts receivable and inventory"),
      ("D", "The cash balance per bank statement and the cash balance per accounting records (general ledger)")]),
    (21, "Revenue and Collection Cycle", "In reviewing a client's bank reconciliation, an outstanding check is one that:",
     [("A", "Was honored by the bank during the month"),
      ("B", "Has been written and recorded in the cash disbursements journal but has not yet cleared the bank"),
      ("C", "Was drawn with insufficient funds"),
      ("D", "Was lost by the mail carrier")]),
    (22, "Revenue and Collection Cycle", "A deposit in transit is one that:",
     [("A", "Was credited by the bank but not recorded on books"),
      ("B", "Has bounced due to NSF"),
      ("C", "Was recorded on the client's books before year-end but not credited by the bank until the following month"),
      ("D", "Was transferred via wire from a customer")]),
    (23, "Revenue and Collection Cycle", "A proof of cash is an audit procedure that reconciles:",
     [("A", "Sales to cost of goods sold"),
      ("B", "Total assets to total liabilities"),
      ("C", "Capital stock to retained earnings"),
      ("D", "Cash receipts and cash disbursements recorded on the client's books with deposits and withdrawals on bank statements for a period, in addition to beginning and ending balances")]),
    (24, "Revenue and Collection Cycle", "A proof of cash is especially useful when:",
     [("A", "Internal control over cash is evaluated as exceptionally strong"),
      ("B", "Internal control over cash is weak or cash fraud/irregularity is suspected"),
      ("C", "The company operates on a purely credit basis"),
      ("D", "The client has zero bank accounts")]),
    (25, "Revenue and Collection Cycle", "A cutoff bank statement is:",
     [("A", "A bank statement for a short period (e.g., 7 to 14 days) following the date of the financial statements sent directly to the auditor to verify reconciling items"),
      ("B", "A statement showing accounts closed during the year"),
      ("C", "A bank statement with all personal checks removed"),
      ("D", "The regular monthly statement mailed to the client")]),
    (26, "Revenue and Collection Cycle", "To test the assertion of completeness for cash receipts, the auditor should:",
     [("A", "Trace daily remittance advices or prelisting of cash receipts to the cash receipts journal and bank deposits"),
      ("B", "Vouch entries in the cash receipts journal to sales invoices"),
      ("C", "Recalculate bank interest"),
      ("D", "Inspect stock certificate stubs")]),
    (27, "Revenue and Collection Cycle", "To test the assertion of occurrence for cash receipts, the auditor should:",
     [("A", "Trace customer orders to the general ledger"),
      ("B", "Count petty cash on hand"),
      ("C", "Vouch recorded entries in the cash receipts journal to bank statements, deposit slips, and remittance advices"),
      ("D", "Confirm loan agreements with lenders")]),
    (28, "Revenue and Collection Cycle", "Which internal control prevents unauthorized cash disbursements?",
     [("A", "Using unnumbered check forms"),
      ("B", "Permitting any employee to sign checks"),
      ("C", "Leaving checks signed in blank"),
      ("D", "Requiring two authorized signatures on checks above a specified amount and matching with approved vouchers")]),
    (29, "Revenue and Collection Cycle", "When counting petty cash funds, the auditor should:",
     [("A", "Count the fund alone without anyone present"),
      ("B", "Allow the custodian to leave during the count"),
      ("C", "Deposit all coins into the auditor's bank account"),
      ("D", "Ensure the custodian is present throughout the count and obtain a signed receipt acknowledging return of funds intact")]),
    (30, "Revenue and Collection Cycle", "Simultaneous counting of all negotiable funds (petty cash, undeposited collections, marketable securities) is done to prevent:",
     [("A", "Audit fee inflation"),
      ("B", "Substitution of funds from one source to cover a shortage in another"),
      ("C", "Bank service charges"),
      ("D", "Employee tardiness")]),
    (31, "Expenditure and Disbursement Cycle", "The primary objective of internal controls in the purchasing cycle is to ensure:",
     [("A", "All purchases are made at list price without discount"),
      ("B", "The company buys exclusively imported materials"),
      ("C", "Suppliers are paid before goods arrive"),
      ("D", "Goods and services are acquired only upon authorized requisitions, at best prices, and disbursements are made only for goods actually received")]),
    (32, "Expenditure and Disbursement Cycle", "A three-way match in the voucher system requires matching which three documents before approving payment?",
     [("A", "Check, bank statement, and tax return"),
      ("B", "Purchase order, receiving report, and vendor's invoice"),
      ("C", "Sales invoice, shipping order, and remittance advice"),
      ("D", "Time card, job ticket, and pay envelope")]),
    (33, "Expenditure and Disbursement Cycle", "In auditing accounts payable, the auditor's primary concern regarding assertions is usually:",
     [("A", "Completeness (search for unrecorded liabilities)"),
      ("B", "Existence"),
      ("C", "Rights and obligations"),
      ("D", "Fair value disclosure")]),
    (34, "Expenditure and Disbursement Cycle", "The 'search for unrecorded liabilities' is typically performed by:",
     [("A", "Confirming zero balance customer accounts"),
      ("B", "Reconciling bank accounts at interim date"),
      ("C", "Examining cash disbursements made subsequent to the balance sheet date and unpaid vendor invoices for liabilities that should have been recorded at year-end"),
      ("D", "Counting warehouse equipment")]),
    (35, "Expenditure and Disbursement Cycle", "Which of the following is not a procedure in the search for unrecorded liabilities?",
     [("A", "Reviewing receiving reports issued before year-end that have not been matched with vendor invoices"),
      ("B", "Reviewing unmatched vendor invoices received after year-end"),
      ("C", "Examining subsequent disbursements in January"),
      ("D", "Vouching sales returns recorded in the sales journal")]),
    (36, "Expenditure and Disbursement Cycle", "Confirmation of accounts payable is:",
     [("A", "Mandatory in all audits under PSA 505"),
      ("B", "Not mandatory, but often used when internal control is weak or when vendors maintain large ongoing business with the entity"),
      ("C", "Illegal under Philippine law"),
      ("D", "Required only for foreign suppliers")]),
    (37, "Expenditure and Disbursement Cycle", "When selecting vendor accounts to confirm, the auditor should place emphasis on:",
     [("A", "Major active suppliers, vendors with zero or small balances at year-end, and accounts with unusual fluctuations"),
      ("B", "Vendors with the largest recorded ending balances only"),
      ("C", "Vendors with who the company did no business"),
      ("D", "Inactive accounts with zero transactions")]),
    (38, "Expenditure and Disbursement Cycle", "Vouchers and supporting documents should be stamped or marked 'PAID' or canceled upon check issuance to:",
     [("A", "Satisfy tax inspectors only"),
      ("B", "Save filing space"),
      ("C", "Notify the receiving dock"),
      ("D", "Prevent duplicate submission and payment of the same invoice")]),
    (39, "Expenditure and Disbursement Cycle", "The separation of purchasing, receiving, and accounts payable prevents:",
     [("A", "Payment of dividend taxes"),
      ("B", "Unauthorized purchases, misappropriation of goods, and fraudulent payments to fictitious vendors"),
      ("C", "Discounts from being taken"),
      ("D", "Depreciation calculation errors")]),
    (40, "Expenditure and Disbursement Cycle", "An auditor traces a sample of receiving reports prepared before year-end to the accounts payable voucher register. This procedure tests:",
     [("A", "Existence of payables"),
      ("B", "Occurrence of purchases"),
      ("C", "Valuation of inventory"),
      ("D", "Completeness of recorded accounts payable")]),
    (41, "Expenditure and Disbursement Cycle", "The purchase cutoff test is designed to verify that:",
     [("A", "Purchases and corresponding liabilities are recorded in the proper accounting period"),
      ("B", "Purchases are made exclusively in cash"),
      ("C", "Suppliers are satisfied with payment terms"),
      ("D", "Purchase orders are written in ink")]),
    (42, "Expenditure and Disbursement Cycle", "If goods shipped FOB shipping point were in transit on December 31, they should be included in:",
     [("A", "Neither inventory nor accounts payable"),
      ("B", "Both the buyer's inventory and accounts payable as of December 31"),
      ("C", "The seller's inventory only"),
      ("D", "The buyer's sales journal")]),
    (43, "Expenditure and Disbursement Cycle", "If goods shipped FOB destination were in transit on December 31, they belong to:",
     [("A", "The buyer"),
      ("B", "The seller until arrival at the buyer's warehouse"),
      ("C", "The common carrier"),
      ("D", "The customs bureau")]),
    (44, "Expenditure and Disbursement Cycle", "An auditor detects that a client recorded a purchase of inventory on December 30, but the goods arrived and were received on January 4 (terms FOB destination). The effect on December 31 financial statements is:",
     [("A", "Understatement of liabilities"),
      ("B", "Understatement of inventory"),
      ("C", "Overstatement of both inventory and accounts payable"),
      ("D", "No effect")]),
    (45, "Expenditure and Disbursement Cycle", "A debit balance in an accounts payable account usually represents:",
     [("A", "An advance payment to a vendor or return of goods, which should be reclassified as a current asset if material"),
      ("B", "An unrecorded liability"),
      ("C", "A fraud by the cashier"),
      ("D", "A reduction in equity")]),
    (46, "Expenditure and Disbursement Cycle", "To test whether payments were made for goods actually received, the auditor should vouch cash disbursement entries to:",
     [("A", "Canceled checks, approved vouchers, vendor invoices, and receiving reports"),
      ("B", "Customer purchase orders"),
      ("C", "Sales tax returns"),
      ("D", "Stock transfer registers")]),
    (47, "Expenditure and Disbursement Cycle", "Which department should be responsible for approving vendor invoices for payment?",
     [("A", "Receiving department"),
      ("B", "Purchasing department"),
      ("C", "Accounts payable (voucher) department"),
      ("D", "Shipping department")]),
    (48, "Expenditure and Disbursement Cycle", "An auditor tests petty cash by:",
     [("A", "Confirming petty cash with local banks"),
      ("B", "Asking the CEO about petty cash rules"),
      ("C", "Surprise count of the petty cash fund, examining supporting vouchers for proper authorization and cancellation"),
      ("D", "Vouching sales receipts")]),
    (49, "Expenditure and Disbursement Cycle", "When an entity uses an imprest petty cash system, expenses are recorded in the general ledger when:",
     [("A", "The petty cash fund is initially established only"),
      ("B", "Cash is disbursed from the fund"),
      ("C", "The petty cash vouchers are drafted"),
      ("D", "The petty cash fund is replenished")]),
    (50, "Expenditure and Disbursement Cycle", "At balance sheet date, unreplenished petty cash vouchers should be:",
     [("A", "Ignored if under P50,000"),
      ("B", "Charged to retained earnings"),
      ("C", "Adjusted by recording the expenses and reducing cash so cash is not overstated"),
      ("D", "Reclassified as long-term investments")]),
    (51, "Production and Inventory Cycle", "Under PSA 501, when inventory is material to the financial statements, the auditor is required to obtain sufficient appropriate audit evidence regarding existence and condition of inventory by:",
     [("A", "Confirming inventory values with competitors"),
      ("B", "Reading trade magazines"),
      ("C", "Attendance at physical inventory counting, unless impracticable"),
      ("D", "Relying entirely on management representation letters")]),
    (52, "Production and Inventory Cycle", "The auditor's attendance at the physical inventory count is performed to:",
     [("A", "Act as the client's inventory counter"),
      ("B", "Supervise and manage the warehouse workers"),
      ("C", "Determine the retail selling price of goods"),
      ("D", "Evaluate management's instructions and procedures for recording and controlling count results, observe conduct of procedures, inspect inventory, and perform test counts")]),
    (53, "Production and Inventory Cycle", "If the auditor is unable to attend the physical inventory count due to unforeseen circumstances (e.g., severe typhoon), the auditor shall:",
     [("A", "Make or observe some counts on an alternative date and perform audit procedures on intervening transactions"),
      ("B", "Issue an immediate disclaimer of opinion without any other procedures"),
      ("C", "Instruct the client to discard the inventory"),
      ("D", "Charge the client a penalty fee")]),
    (54, "Production and Inventory Cycle", "If attendance at physical inventory count is impracticable (e.g., inventory located in a hazardous war zone):",
     [("A", "The auditor shall perform alternative audit procedures (e.g., documentation of subsequent sale) to obtain sufficient appropriate evidence, or modify the opinion"),
      ("B", "The auditor must issue an unmodified opinion"),
      ("C", "The inventory is removed from the balance sheet"),
      ("D", "The auditor must resign immediately")]),
    (55, "Production and Inventory Cycle", "When observing inventory counts, the auditor's test counts are traced in two directions: from count tags to inventory compilation sheets to test ________, and from compilation sheets to count tags to test ________:",
     [("A", "Valuation; rights"),
      ("B", "Completeness; existence"),
      ("C", "Existence; completeness"),
      ("D", "Accuracy; presentation")]),
    (56, "Production and Inventory Cycle", "Inventory held by third parties (public warehouses or consignees) can be verified by the auditor by:",
     [("A", "Counting the third party's cash"),
      ("B", "Requesting confirmation from the third party, or performing inspection/other procedures if doubt exists (PSA 501)"),
      ("C", "Writing off the consigned goods"),
      ("D", "Confirming with the SEC")]),
    (57, "Production and Inventory Cycle", "The valuation assertion for inventory requires the auditor to test that inventory is recorded at the:",
     [("A", "Historical replacement cost"),
      ("B", "Retail list price"),
      ("C", "Lower of cost and net realizable value (LCNRV) in accordance with PAS 2"),
      ("D", "Liquidation auction price")]),
    (58, "Production and Inventory Cycle", "Net realizable value (NRV) of inventory is defined as:",
     [("A", "Estimated selling price plus disposal costs"),
      ("B", "Original historical invoice price"),
      ("C", "Estimated selling price in the ordinary course of business less estimated costs of completion and estimated costs necessary to make the sale"),
      ("D", "Fair market value determined by municipal assessors")]),
    (59, "Production and Inventory Cycle", "To identify slow-moving, obsolete, or damaged inventory, the auditor typically:",
     [("A", "Inspects the physical condition of inventory during count, reviews inventory turnover ratios, and analyzes inventory aging reports"),
      ("B", "Confirms with customer banks"),
      ("C", "Recalculates depreciation on office furniture"),
      ("D", "Inspects board minutes for stock dividends")]),
    (60, "Production and Inventory Cycle", "An inventory cutoff test is performed by examining receiving and shipping records around year-end to ensure:",
     [("A", "All staff received Christmas bonuses"),
      ("B", "All inventory was sold"),
      ("C", "Goods received are included in inventory and accounts payable, and goods shipped are excluded from inventory and included in sales/receivables"),
      ("D", "Warehouse rental was paid")]),
    (61, "Production and Inventory Cycle", "In a standard cost accounting system, the auditor tests standard costs by:",
     [("A", "Examining actual invoices for raw materials, testing labor rates against payroll, and evaluating overhead allocation bases"),
      ("B", "Accepting standard costs as fact without audit work"),
      ("C", "Dividing total sales by total inventory"),
      ("D", "Asking warehouse security")]),
    (62, "Production and Inventory Cycle", "Consigned goods sent out to consignees should be:",
     [("A", "Excluded from the consignor's inventory"),
      ("B", "Included in the consignor's inventory at cost plus freight until sold by consignee"),
      ("C", "Included in the consignee's inventory as assets"),
      ("D", "Treated as bad debts")]),
    (63, "Production and Inventory Cycle", "Consigned goods held by the client belonging to third parties (consignors) should be:",
     [("A", "Included in the client's inventory at full retail value"),
      ("B", "Added to accounts payable"),
      ("C", "Excluded from the client's inventory, with proper separation during physical count"),
      ("D", "Pledged as collateral for client loans")]),
    (64, "Production and Inventory Cycle", "Perpetual inventory records should be verified by periodic physical counts because:",
     [("A", "Perpetual records are illegal in the Philippines"),
      ("B", "Differences arise between recorded quantities and actual quantities due to shrinkage, theft, spoilage, or recording errors"),
      ("C", "Computer systems always delete data after 30 days"),
      ("D", "Warehouse staff request overtime pay")]),
    (65, "Production and Inventory Cycle", "An auditor observes inventory tags being used sequentially during count. This internal control ensures:",
     [("A", "Tax compliance"),
      ("B", "Completeness of count and prevention of omission or duplication of items"),
      ("C", "Immediate payment to counters"),
      ("D", "Proper valuation under LIFO")]),
    (66, "Financing and Investing Cycle", "The primary assertion tested when inspecting physical share certificates or bond certificates held in the vault is:",
     [("A", "Completeness"),
      ("B", "Existence and ownership (rights)"),
      ("C", "Presentation and classification"),
      ("D", "Cutoff")]),
    (67, "Financing and Investing Cycle", "Marketable securities held by a third-party independent custodian should be verified by:",
     [("A", "Counting the client's petty cash"),
      ("B", "Inquiring of the custodian's security guards"),
      ("C", "Direct confirmation in writing with the independent custodian"),
      ("D", "Examining sales catalogs")]),
    (68, "Financing and Investing Cycle", "Valuation of investments in listed equity securities under PFRS 9 is verified by:",
     [("A", "Tracing to vendor purchase orders"),
      ("B", "Checking closing market prices on the stock exchange (PSE) as of the balance sheet date"),
      ("C", "Recalculating bond interest only"),
      ("D", "Confirming with the company's legal counsel")]),
    (69, "Financing and Investing Cycle", "Substantive tests of property, plant, and equipment (PPE) focus heavily on:",
     [("A", "100% confirmation of all small hand tools"),
      ("B", "Testing additions and retirements during the period rather than recurring unchanged balances"),
      ("C", "Estimating retail replacement prices"),
      ("D", "Confirming land with tenant farmers")]),
    (70, "Financing and Investing Cycle", "Vouching PPE additions involves examining:",
     [("A", "Purchase contracts, invoices, deeds, board authorization, and physical inspection"),
      ("B", "Sales invoices to customers"),
      ("C", "Employee pay stubs"),
      ("D", "Petty cash vouchers under P500")]),
    (71, "Financing and Investing Cycle", "To test for unrecorded retirements or disposals of equipment, the auditor should:",
     [("A", "Review new stock issuances"),
      ("B", "Confirm bank accounts"),
      ("C", "Check insurance policies for premium increases"),
      ("D", "Select recorded assets from property ledger and inspect them in the plant; inquire about assets not found, and review miscellaneous revenues for salvage proceeds")]),
    (72, "Financing and Investing Cycle", "Testing depreciation expense involves:",
     [("A", "Evaluating depreciation methods, useful lives, and salvage values for reasonableness, and testing mathematical calculations"),
      ("B", "Confirming depreciation with the BIR"),
      ("C", "Vouching land values"),
      ("D", "Counting building bricks")]),
    (73, "Financing and Investing Cycle", "Reviewing repair and maintenance expense accounts is performed primarily to detect:",
     [("A", "Understated operating expenses"),
      ("B", "Capital expenditures that were improperly expensed (completeness of PPE assets)"),
      ("C", "Unrecorded sales"),
      ("D", "Excessive charitable contributions")]),
    (74, "Financing and Investing Cycle", "Authorization for long-term borrowings and bond issuances should be found in:",
     [("A", "Daily cash register logs"),
      ("B", "Minutes of the meetings of the Board of Directors"),
      ("C", "The purchasing department manual"),
      ("D", "The warehouse receiving dock log")]),
    (75, "Financing and Investing Cycle", "When auditing debt agreements, the auditor examines debt covenants to:",
     [("A", "Ensure the entity has complied with all restrictive provisions (e.g., working capital ratios, dividend restrictions) to avoid debt acceleration"),
      ("B", "Negotiate lower interest rates on behalf of the client"),
      ("C", "Forgive the client's loans"),
      ("D", "Cancel the lender's charter")]),
    (76, "Financing and Investing Cycle", "Confirmation of long-term debt balances and covenants is sent to:",
     [("A", "Stock exchange analysts"),
      ("B", "The client's suppliers"),
      ("C", "The lending financial institutions or bond trustees"),
      ("D", "General public")]),
    (77, "Financing and Investing Cycle", "When an entity has an independent stock transfer agent and registrar, the auditor verifies shares outstanding by:",
     [("A", "Counting cash in banks"),
      ("B", "Direct confirmation with the independent registrar and transfer agent"),
      ("C", "Inspecting cancelled payroll checks"),
      ("D", "Recalculating sales tax")]),
    (78, "Financing and Investing Cycle", "When an entity maintains its own capital stock certificate book, the auditor verifies shares outstanding by:",
     [("A", "Asking shareholders directly via telephone"),
      ("B", "Examining open stock certificate stubs and accounting for all unissued certificate numbers"),
      ("C", "Confirming with local police"),
      ("D", "Inspecting warehouse bins")]),
    (79, "Financing and Investing Cycle", "Authorization for cash dividends declared must be documented in:",
     [("A", "The customer billing summary"),
      ("B", "Minutes of the Board of Directors' meetings"),
      ("C", "The delivery logbook"),
      ("D", "Employee contracts")]),
    (80, "Financing and Investing Cycle", "Treasury stock held by the entity should be verified by:",
     [("A", "Confirming with competitors"),
      ("B", "Reviewing customer purchase orders"),
      ("C", "Writing off the shares to cost of goods sold"),
      ("D", "Physical inspection of share certificates held in the company vault in the presence of company officers")]),
    (81, "Payroll Cycle", "The most significant payroll risk in many organizations is:",
     [("A", "Overpaying dividend taxes"),
      ("B", "Payments to fictitious employees (ghost employees) or falsification of hours worked"),
      ("C", "Understating cash in bank"),
      ("D", "Overpaying sales tax")]),
    (82, "Payroll Cycle", "Proper segregation of duties in the payroll cycle requires that personnel/HR (hiring and wage authorization) be segregated from:",
     [("A", "Timekeeping, payroll preparation, and payroll disbursement"),
      ("B", "Warehouse shipping"),
      ("C", "Customer credit approval"),
      ("D", "Fixed asset counts")]),
    (83, "Payroll Cycle", "A surprise observation of a payroll distribution (payoff) by the auditor is designed to detect:",
     [("A", "Understated fringe benefits"),
      ("B", "Ghost employees (fictitious workers) on the payroll"),
      ("C", "Errors in sales commission calculations"),
      ("D", "Unrecorded trade receivables")]),
    (84, "Payroll Cycle", "In testing payroll transactions, the auditor traces hours recorded on the payroll summary to:",
     [("A", "The general ledger journal"),
      ("B", "Approved time cards, biometric clock records, or time sheets"),
      ("C", "Vendor invoices"),
      ("D", "Sales contracts")]),
    (85, "Payroll Cycle", "Wage rates and deductions used in payroll calculations should be traced to:",
     [("A", "Bank deposit slips"),
      ("B", "Customer purchase orders"),
      ("C", "Shipping receipts"),
      ("D", "Approved personnel records, union contracts, and statutory withholding tables (BIR, SSS, PhilHealth, Pag-IBIG)")]),
    (86, "Payroll Cycle", "Use of an independent imprest payroll bank account helps control payroll disbursements because:",
     [("A", "The exact net payroll amount is transferred to the payroll account, and unauthorized checks or overdrafts can be easily detected."),
      ("B", "It eliminates the need for any internal controls."),
      ("C", "It earns double interest rates."),
      ("D", "It allows employees to write their own checks.")]),
    (87, "Payroll Cycle", "Unclaimed wages returned to the cashier should be:",
     [("A", "Divided among the payroll clerks as bonuses"),
      ("B", "Discarded after 24 hours"),
      ("C", "Redeposited into the bank account and recorded as a liability (unclaimed wages) to prevent theft"),
      ("D", "Used to buy office snacks")]),
    (88, "Payroll Cycle", "Analytical procedures for payroll typically involve:",
     [("A", "Confirming employee addresses with city hall"),
      ("B", "Testing petty cash vouchers"),
      ("C", "Comparing monthly payroll expense with prior year and budget, and multiplying average employee headcount by average wage rates"),
      ("D", "Inspecting raw materials inventory")]),
    (89, "Payroll Cycle", "Payroll tax withholdings (BIR withholding tax on compensation, SSS, PhilHealth, Pag-IBIG) should be verified by:",
     [("A", "Inspecting customer credit reports"),
      ("B", "Vouching land purchases"),
      ("C", "Testing monthly tax remittance returns and official receipts from government agencies"),
      ("D", "Counting vault cash")]),
    (90, "Audit of Transaction Cycles", "The ultimate purpose of testing internal controls in transaction cycles is to:",
     [("A", "Determine client compliance with corporate fashion policies"),
      ("B", "Replace external audit with internal audit"),
      ("C", "Eliminate all substantive tests completely"),
      ("D", "Determine the nature, timing, and extent of substantive audit procedures to be performed")]),
    (91, "Audit of Transaction Cycles", "If the auditor assesses control risk as low after testing controls in the revenue cycle, the auditor may:",
     [("A", "Reduce the extent of substantive tests of details of accounts receivable (e.g., smaller confirmation sample size)"),
      ("B", "Eliminate substantive tests entirely"),
      ("C", "Issue an immediate clean opinion without substantive testing"),
      ("D", "Triple the sample size")]),
    (92, "Audit of Transaction Cycles", "Which cycle typically involves the highest volume of transactions in a merchandising company?",
     [("A", "Financing cycle"),
      ("B", "Revenue and expenditure cycles"),
      ("C", "Investing cycle"),
      ("D", "Stockholders' equity cycle")]),
    (93, "Audit of Transaction Cycles", "Which of the following is a key substantive test for completeness of revenue?",
     [("A", "Vouching recorded sales to shipping documents"),
      ("B", "Confirming large customer balances"),
      ("C", "Tracing a sample of shipping documents to the sales journal and general ledger"),
      ("D", "Inspecting marketable securities")]),
    (94, "Audit of Transaction Cycles", "Which of the following is a key substantive test for occurrence of purchases?",
     [("A", "Tracing receiving reports to the purchase journal"),
      ("B", "Scanning bank statements for round amounts"),
      ("C", "Recalculating interest on bank debt"),
      ("D", "Vouching entries in the voucher register to approved purchase orders, receiving reports, and vendor invoices")]),
    (95, "Audit of Transaction Cycles", "To verify the rights and obligations assertion for inventory, the auditor should:",
     [("A", "Inquire about consigned goods, inspect loan agreements for inventory pledged as collateral, and review purchase commitments"),
      ("B", "Perform mathematical test counts"),
      ("C", "Vouch petty cash slips"),
      ("D", "Confirm common stock ownership")]),
    (96, "Audit of Transaction Cycles", "To test the completeness of accounts payable, the auditor focuses primarily on testing:",
     [("A", "Large balances recorded in the general ledger"),
      ("B", "Transactions occurring immediately after year-end (subsequent payments and unrecorded invoices)"),
      ("C", "Transactions occurring in the first month of the year"),
      ("D", "Accounts with debit balances only")]),
    (97, "Audit of Transaction Cycles", "In auditing intangible assets (such as goodwill or patents), the auditor focuses on:",
     [("A", "Physical inspection of the asset"),
      ("B", "Counting tangible units in the warehouse"),
      ("C", "Evaluating legal documentation of rights, testing amortization calculations, and evaluating impairment testing under PAS 36"),
      ("D", "Confirming patent values with retail customers")]),
    (98, "Audit of Transaction Cycles", "In auditing retained earnings, the auditor reviews:",
     [("A", "Net income closed from income statement, dividends declared, prior period adjustments, and restrictions on retained earnings"),
      ("B", "Petty cash counts"),
      ("C", "Inventory standard cost cards"),
      ("D", "Vendor shipping reports")]),
    (99, "Audit of Transaction Cycles", "When auditing related party receivables and payables, the auditor must verify that:",
     [("A", "All related party transactions are cancelled"),
      ("B", "They are properly identified, evaluated for business rationale, and separately disclosed in accordance with PAS 24"),
      ("C", "No interest was charged"),
      ("D", "They are classified as intangible assets")]),
    (100, "Audit of Transaction Cycles", "The primary reason an auditor performs cutoff tests across multiple transaction cycles at year-end is to:",
     [("A", "Reduce the audit fee"),
      ("B", "Allow audit staff to take holiday vacations"),
      ("C", "Ensure transactions are recorded in the correct accounting period so that financial statements reflect appropriate matching and balances at period-end"),
      ("D", "Satisfy labor union requirements")])
]

chapter15 = {
    "id": "at-15",
    "code": "AT-15",
    "title": "Audit of Transaction Cycles",
    "description": "Internal control evaluation and substantive audit procedures for primary business cycles: Revenue and Collection Cycle (Sales, Receivables, Cash Receipts, Confirmations, Cutoff), Expenditure and Disbursement Cycle (Purchases, Payables, Search for Unrecorded Liabilities), Production and Inventory Cycle (Physical Count, Valuation, PSA 501), Financing and Investing Cycle (PPE, Debt, Equity), and Payroll Cycle.",
    "objectives": [
        "Revenue and Collection Cycle",
        "Expenditure and Disbursement Cycle",
        "Production and Inventory Cycle",
        "Financing and Investing Cycle",
        "Payroll Cycle",
        "Audit of Transaction Cycles"
    ],
    "totalQuestions": 100,
    "questions": []
}

for num, obj, qtext, opts in at15_raw:
    correct = at15_answers[num]
    expl = at15_explanations.get(num, f"Suggested Answer: {correct}. Testing transaction cycles in accordance with PSAs and Philippine Financial Reporting Standards.")
    chapter15["questions"].append({
        "id": f"at15-{num}",
        "number": num,
        "chapterId": "at-15",
        "chapterCode": "AT-15",
        "chapterTitle": "Audit of Transaction Cycles",
        "objective": obj,
        "question": qtext,
        "options": [{"key": k, "text": t} for k, t in opts],
        "correctAnswer": correct,
        "explanation": expl
    })

with open("src/data/chapters/at15.ts", "w", encoding="utf-8") as f:
    f.write(f"import {{ Chapter }} from '../../types/quiz';\n\nexport const chapter15: Chapter = {json.dumps(chapter15, indent=2)};\n")

print("Created at15.ts with 100 questions")
