#!/usr/bin/env python3
import json

at05_answers = {
    1: 'A', 2: 'C', 3: 'B', 4: 'A', 5: 'A', 6: 'A', 7: 'B', 8: 'A', 9: 'A', 10: 'D',
    11: 'B', 12: 'C', 13: 'B', 14: 'C', 15: 'C', 16: 'D', 17: 'A', 18: 'D', 19: 'A', 20: 'A',
    21: 'D', 22: 'B', 23: 'D', 24: 'D', 25: 'A', 26: 'A', 27: 'D', 28: 'D', 29: 'D', 30: 'D',
    31: 'A', 32: 'A', 33: 'A', 34: 'D', 35: 'C', 36: 'D', 37: 'D', 38: 'C', 39: 'D', 40: 'B',
    41: 'D', 42: 'B', 43: 'C', 44: 'C', 45: 'C', 46: 'D', 47: 'C', 48: 'B', 49: 'A', 50: 'B',
    51: 'A', 52: 'A', 53: 'B', 54: 'C', 55: 'C', 56: 'C', 57: 'D', 58: 'C', 59: 'A', 60: 'B',
    61: 'C', 62: 'D', 63: 'C', 64: 'A', 65: 'C', 66: 'C', 67: 'B', 68: 'D', 69: 'D', 70: 'B',
    71: 'C', 72: 'B', 73: 'C', 74: 'B', 75: 'B', 76: 'A', 77: 'A', 78: 'A', 79: 'D', 80: 'C',
    81: 'A', 82: 'C', 83: 'A', 84: 'A', 85: 'B', 86: 'A', 87: 'B', 88: 'D', 89: 'C', 90: 'D',
    91: 'B', 92: 'B', 93: 'C', 94: 'A', 95: 'D'
}

at05_explanations = {
    2: "Planning an audit involves establishing the overall audit strategy that sets the scope, timing and direction of the audit engagement and for developing an audit plan.",
    4: "Planning is not a discrete phase of an audit, but rather a continual and iterative process.",
    5: "An auditor usually begins the audit planning by understanding the client's business and industry. Choice B is performed during substantive testing. Choice C is performed during wrapping-up activities. Choice D is performed during internal control evaluation.",
    6: "The auditor shall plan and execute the audit engagement regardless of the opinion to be expressed.",
    7: "When more information is available, the auditor can change their initial assessment of a particular account or item during the audit.",
    8: "Choice A refers to the auditor's substantive procedures.",
    9: "Scheduling inventory observations does not affect the element of surprise an audit should have.",
    11: "The audit program provides the details of the procedures that the auditor will perform to gather sufficient and appropriate audit evidences.",
    17: "Since planning is a continual and iterative process of the audit, the audit plan and strategies are allowed to be changed throughout the audit as more information becomes available to the auditor.",
    19: "Choice A is an expertise already possessed by a CPA.",
    21: "A CPA is expected to have a basic understanding of the industry where its audit client operates.",
    39: "Materiality serves as a quantitative threshold that could influence the economic decisions of users taken on the basis of the financial statements. The auditor's determination of materiality is a matter of professional judgment and is affected by the auditor's perception of the financial information needs of users of the financial statements.",
    40: "The more misstatements the auditor expects the lower the aggregate threshold should be.",
    46: "The higher the materiality level, the lesser the amount of audit evidence needed to be accumulated by the auditor. The lower the materiality level, the higher the amount of audit evidence needed to be accumulated by the auditor.",
    47: "The higher the risk, the lower the materiality threshold to be able to identify misstatements.",
    48: "FS audit is known as risk-based audit. The procedures to be performed depend on the assessment of materiality and risk.",
    50: "Choice B is incorrect because it should be in terms of the smallest, not largest, aggregate level of misstatements.",
    53: "Overall materiality or tolerable misstatement is the term used to indicate materiality at the financial statement level.",
    54: "Out of the choices, the net income before tax is the smallest amount that can be used as a basis for materiality for a profit-oriented entity.",
    55: "Auditing standards requires the auditor to document the basis used to determine materiality.",
    57: "The audit risk is composed of the following components: 1. Inherent risk, 2. Control risk, 3. Detection risk.",
    58: "Inherent and control risks are the components of risk of material misstatement.",
    68: "If inherent risk is high, the detection risk should be set to a lower level. Hence, the auditor should accumulate more amount of evidence.",
    69: "AR = IR x CR x DR. AR = 0.50 x 0.40 x 0.10 = 0.02 or 2%.",
    70: "There is an inverse relationship between the RMM and DR.",
    71: "IR and CR are uncontrollable risks.",
    73: "The auditor has a responsibility to identify or assess risks only those that are related to the financial statement assertions. Take note that not all business risks are related to FS assertions.",
    74: "This increases the control risk and not inherent risk.",
    75: "When inherent and control risks are high, it is more acceptable to gather more independent evidence, as the evidence that the client may provide might not be reliable.",
    77: "AR = IR x CR x DR. DR = AR / (IR x CR). Choice A: DR = 0.10 / (0.20 x 0.40) = 1.25 or 125%, which yields the highest DR allowing the auditor to perform less substantive procedures.",
    79: "We cannot eliminate risks; we can only minimize them.",
    87: "The use of analytical procedures is required during planning and wrap-up activities.",
    89: "Analytical procedures are applied mathematically and cannot determine the substance of transaction.",
    90: "Fluctuations of sales can be discovered in the application of analytical procedures.",
    91: "Understand the root cause of the fluctuations."
}

at05_raw = [
    (1, "Audit Planning", "This involves developing an overall strategy for the expected conduct and scope of the examination; the nature, extent, and timing of which vary with the size and complexity, and experience with and knowledge of the entity.",
     [("A", "Audit planning"), ("B", "Audit procedure"), ("C", "Audit program"), ("D", "Audit strategy")]),
    (2, "Audit Planning", "Planning an audit involves\nI. Establishing the overall audit strategy for the engagement.\nII. Developing an audit plan",
     [("A", "I only"), ("B", "II only"), ("C", "Both I and II"), ("D", "Neither I nor II")]),
    (3, "Audit Planning", "Adequate planning helps to ensure that:\nAppropriate attention is devoted to important areas | Potential problems are identified and resolved timely | Audit engagement is properly organized and managed\nA. No | Yes | Yes\nB. Yes | Yes | Yes\nC. Yes | No | No\nD. No | No | No",
     [("A", "No, Yes, Yes"), ("B", "Yes, Yes, Yes"), ("C", "Yes, No, No"), ("D", "No, No, No")]),
    (4, "Audit Planning", "Which of the following statements concerning audit planning is incorrect?",
     [("A", "Planning is a discrete phase of an audit."),
      ("B", "Planning is a continual and iterative process."),
      ("C", "In a recurring audit, planning often begins shortly after (or in connection with) the completion of the previous audit and continues until the completion of the current audit engagement."),
      ("D", "In planning an audit, the auditor considers the timing of certain planning activities and audit procedures that are to be completed prior to the performance of further audit procedures.")]),
    (5, "Audit Planning", "Which of the following procedures would a CPA ordinarily perform during audit planning?",
     [("A", "Obtain understanding of the client's business and industry."),
      ("B", "Review the client's bank reconciliation."),
      ("C", "Obtain client's representation letter."),
      ("D", "Review and evaluate client's internal control.")]),
    (6, "Audit Planning", "In planning the audit engagement, the auditor should consider each of the following, except",
     [("A", "The type of opinion that is likely to be expressed."),
      ("B", "The entity's accounting policies and procedures."),
      ("C", "Matters relating to the entity's business and the industry in which it operates."),
      ("D", "Materiality level and audit risk.")]),
    (7, "Audit Planning", "An auditor judged an item to be immaterial when planning an audit. However, the auditor may still include the item if it is subsequently determined that:",
     [("A", "Sufficient staff is available."),
      ("B", "Adverse effects related to the item are likely to occur."),
      ("C", "Related evidence is reliable."),
      ("D", "Miscellaneous income is affected.")]),
    (8, "Audit Planning", "Which of the following is not a component of audit planning?",
     [("A", "Observing the client's annual physical inventory taking and making test counts of selected items."),
      ("B", "Planning with the client concerning the timing of audit field work and use of the client's staff in completing certain phases of the examination."),
      ("C", "Obtaining an understanding of the business."),
      ("D", "Developing audit programs.")]),
    (9, "Audit Planning", "The element of the audit planning process most likely to be agreed upon with the client before implementation of the audit strategy is the determination of the",
     [("A", "Timing of inventory observation procedures to be performed."),
      ("B", "Evidence to be gathered to provide a sufficient basis for the auditor's opinion."),
      ("C", "Procedures to be undertaken to discover litigation, claims, and assessments."),
      ("D", "Pending legal matters to be included in the inquiry of the client's attorney.")]),
    (10, "Audit Planning", "The establishment of an overall audit strategy involves which of the following?\nI. Determining the characteristics of the engagement that defines its scope.\nII. Ascertaining the reporting objectives of the engagement to plan the timing of the audit and the nature of the communications required.\nIII. Considering the important factors that will determine the focus of the engagement team's efforts.",
     [("A", "I and II only"), ("B", "II and III only"), ("C", "I and III only"), ("D", "I, II, and III")]),
    (11, "Audit Planning", "A document that details what the auditor will do to gather sufficient and appropriate evidence is the:",
     [("A", "Audit strategy"), ("B", "Audit program"), ("C", "Audit procedure"), ("D", "Audit risk model")]),
    (12, "Audit Planning", "An auditor should design the written audit program so that:",
     [("A", "All material transactions will be selected for substantive testing."),
      ("B", "Substantive tests prior to the balance sheet date will be minimized."),
      ("C", "The audit procedures selected will achieve specific audit objectives."),
      ("D", "Each account balance will be tested under either tests of controls or tests of transactions.")]),
    (13, "Audit Planning", "An audit plan is a:",
     [("A", "Detailed plan of analytical procedures and all substantive tests to be performed in the course of the audit."),
      ("B", "Document that provides an overview of the company and a general plan for the audit work to be accomplished, timing of work, and other matters of concern to the audit."),
      ("C", "Generic document that auditing firms have developed to lead the process of the audit through a systematic and logical process."),
      ("D", "Budget of the time that should be necessary to complete each phase of the audit procedures.")]),
    (14, "Audit Planning", "Which of the following should be included in the audit plan?\nI. The nature, timing and extent of planned risk assessment procedures.\nII. The nature, timing and extent of planned further audit procedures at the assertion level.",
     [("A", "I only"), ("B", "II only"), ("C", "Both I and II"), ("D", "Neither I nor II")]),
    (15, "Audit Planning", "In developing the overall audit plan for a new client, which of the following is not a factor to be considered?",
     [("A", "Materiality levels"),
      ("B", "The client's business, including the structure of the organization and accounting system used."),
      ("C", "The amount of estimated audit fee."),
      ("D", "The audit risks and procedures to be performed to achieve audit objectives.")]),
    (16, "Audit Planning", "In designing written audit programs, an auditor should establish specific audit objectives that relate primarily to the:",
     [("A", "Selected audit techniques."),
      ("B", "Cost-benefit of gathering audit evidence."),
      ("C", "Timing of audit procedures."),
      ("D", "Financial statement assertions")]),
    (17, "Audit Planning", "Which of the following statements is incorrect about audit planning documentation?",
     [("A", "The audit plan and related program should no longer be changed once the audit is started."),
      ("B", "Although the precise form and content of the audit plan may vary, it should be sufficiently detailed to guide the development of an audit program."),
      ("C", "The audit program should set out the nature, timing and extent of planned audit procedures required to implement the overall audit plan."),
      ("D", "In preparing an audit program, the auditor should consider the specific assessments of inherent and control risks and the required level of assurance to be provided by substantive tests.")]),
    (18, "Audit Planning", "Which of the following situations would most likely require special audit planning by the auditors?",
     [("A", "Some items of factory and office equipment do not bear identification numbers."),
      ("B", "Depreciation methods used on the client's tax return differ from those used on the books."),
      ("C", "Assets costing less than P5,000 are expensed even though the expected life exceeds one year."),
      ("D", "Inventory is comprised of precious stones.")]),
    (19, "Audit Planning", "In which of the following situations would an expert be least likely contracted by a CPA?",
     [("A", "Application of accounting methods in computing inventory balances."),
      ("B", "Determination of fair values using specialized statistical techniques."),
      ("C", "Legal opinions concerning interpretations of engagements, statutes and regulations."),
      ("D", "Valuations of certain types of assets like land and buildings.")]),
    (20, "Audit Planning", "Which of the following factors or conditions is an auditor least likely to plan an audit to discover?",
     [("A", "Financial pressures affecting employees."),
      ("B", "High turnover of senior management."),
      ("C", "Inadequate monitoring of significant controls."),
      ("D", "Inability to generate positive cash flows from operations.")]),
    (21, "Major Audit Planning Activities", "Prior to beginning the field work on a new audit engagement in which a CPA does not possess expertise in the industry in which the client operates, the CPA should:",
     [("A", "Reduce audit risk by lowering the preliminary levels of materiality."),
      ("B", "Design special substantive tests to compensate for the lack of industry expertise."),
      ("C", "Engage financial experts familiar with the nature of the industry."),
      ("D", "Obtain a knowledge of matters that relate to the nature of the entity's business.")]),
    (22, "Major Audit Planning Activities", "In performing an audit of financial statements, the auditor should obtain knowledge of the client's business sufficient to:",
     [("A", "Make constructive suggestions concerning improvements in internal controls."),
      ("B", "Identify transactions and events that may affect the financial statements."),
      ("C", "Develop an attitude of professional skepticism."),
      ("D", "Assess the level of control risk.")]),
    (23, "Major Audit Planning Activities", "Each of the following may be relevant to an auditor when obtaining knowledge about the client's business and industry except:",
     [("A", "Discussion with people within or outside the entity."),
      ("B", "Reading publications related to the industry."),
      ("C", "Visits of the entity's premises."),
      ("D", "Performing tests of control.")]),
    (24, "Major Audit Planning Activities", "Which of the following procedures would an auditor most likely include in the initial planning of a financial statement audit?",
     [("A", "Obtaining a written representation letter from the client's management."),
      ("B", "Examining documents to detect illegal acts having a material effect on the financial statements."),
      ("C", "Considering whether the client's accounting estimates are reasonable in the circumstances."),
      ("D", "Determining the extent of involvement of the client's internal auditors.")]),
    (25, "Major Audit Planning Activities", "The auditor should obtain sufficient understanding of the entity and its environment, including its internal control in order to:\nIdentify and assess risk of material misstatement | Design appropriate audit procedures\nA. Yes | Yes\nB. Yes | No\nC. No | No\nD. No | Yes",
     [("A", "Yes, Yes"), ("B", "Yes, No"), ("C", "No, No"), ("D", "No, Yes")]),
    (26, "Major Audit Planning Activities", "Information about the client's business appropriately assists the auditor in:\nAssessing risks and identifying potential problems | Planning and performing the audit effectively and efficiently | Evaluating audit evidence\nA. Yes | Yes | Yes\nB. Yes | No | Yes\nC. No | Yes | Yes\nD. Yes | Yes | No",
     [("A", "Yes, Yes, Yes"), ("B", "Yes, No, Yes"), ("C", "No, Yes, Yes"), ("D", "Yes, Yes, No")]),
    (27, "Major Audit Planning Activities", "The auditors will not ordinarily initiate discussion with the client's audit committee concerning the:",
     [("A", "Extent to which the work of internal auditors will influence the scope of the examination."),
      ("B", "Extent to which change in the company's organization will influence the scope of the examination."),
      ("C", "Details of potential problems which the auditors believe might cause a qualified opinion."),
      ("D", "Details of the procedures which the auditors intend to apply.")]),
    (28, "Major Audit Planning Activities", "PSA 315 Redrafted requires that the auditor should obtain an understanding of relevant industry, regulatory and other external factors including the applicable financial reporting framework. Which of the following is not an example of matters relating to regulatory environment that the auditor would usually consider?",
     [("A", "Regulatory framework for a regulated industry"),
      ("B", "Legislation and regulation significantly affecting the entity's operation"),
      ("C", "Taxation"),
      ("D", "Product technology relating to the entity's product")]),
    (29, "Major Audit Planning Activities", "PSA 315 Redrafted requires that the auditor should obtain an understanding of relevant industry, regulatory and other external factors including the applicable financial reporting framework. Which of the following is not among the items that relate to industry conditions?",
     [("A", "Energy, supply and cost"),
      ("B", "Cyclical of seasonal activity"),
      ("C", "Market and competition"),
      ("D", "Inflation and currency revaluation")]),
    (30, "Major Audit Planning Activities", "PSA 315 Redrafted requires that the auditor should obtain an understanding of the entity's selection and application of accounting policies and consider whether they are appropriate for its business and consistent with the applicable financial reporting framework and accounting policies used in the relevant industry. The understanding does not encompass",
     [("A", "The methods the entity uses to account for significant and unusual transactions."),
      ("B", "The effect of significant accounting policies in contractual or emerging areas for which there is lack of authoritative guidance or consensus."),
      ("C", "Changes in the entity's accounting policies."),
      ("D", "Criteria in the selection of the company's chief accounting executive.")]),
    (31, "Risk Assessment Procedures", "In the planning stage of an audit engagement, the auditor is required to perform audit procedures to obtain an understanding of the entity and its environment, including its internal control. These procedures are called",
     [("A", "Risk assessment procedures"), ("B", "Substantive tests"), ("C", "Tests of controls"), ("D", "Dual-purpose tests")]),
    (32, "Risk Assessment Procedures", "Risk assessment procedures are performed by auditors during an audit in order to:",
     [("A", "Determine the risk of material misstatement in the financial statements."),
      ("B", "Determine the acceptable level of audit risk."),
      ("C", "Determine the level of materiality."),
      ("D", "Determine whether engagement will be accepted.")]),
    (33, "Risk Assessment Procedures", "The main purpose of risk assessment procedure is to:",
     [("A", "Obtain an understanding of the entity and its environment, including its internal control, and to assess the risks of material misstatement at the financial statement and assertion level."),
      ("B", "Test the operating effectiveness of controls in preventing, or detecting and correcting, material misstatements at the assertion level."),
      ("C", "Detection material misstatements at the assertion level."),
      ("D", "All of the given choices are main purposes of risk assessment procedures.")]),
    (34, "Risk Assessment Procedures", "Which of the following are part of the auditor's risk assessment procedures?",
     [("A", "Inquiries of management and of others within the entity."),
      ("B", "Analytical procedures."),
      ("C", "Observation and inspection."),
      ("D", "All of the above.")]),
    (35, "Risk Assessment Procedures", "PSA 315 requires the auditor to perform risk assessment procedures at:",
     [("A", "The financial statement level only."),
      ("B", "The assertion level only."),
      ("C", "The financial statement level and the assertion level for classes of transactions, account balances and disclosures."),
      ("D", "Either the financial statement or assertion level.")]),
    (36, "Risk Assessment Procedures", "Which of the following statements is incorrect regarding obtaining an understanding of the entity and its environment?",
     [("A", "Obtaining an understanding of the entity and its environment is an essential aspect of performing an audit in accordance with PSAs."),
      ("B", "Understanding of the entity and its environment establishes a frame of reference within which the auditor plans the audit and exercises professional judgment about assessing risks of material misstatement in the financial statements and responding to those risks throughout the audit."),
      ("C", "The auditor's primary consideration is whether the understanding that has been obtained is sufficient to assess the risks of material misstatement in the financial statements and to design and perform further audit procedures."),
      ("D", "The depth of the overall understanding that is required by the auditor in performing the audit is at least equal to that possessed by management in managing the entity.")]),
    (37, "Risk Assessment Procedures", "The auditor should determine overall responses to address the risks of material misstatement at the financial statement level. Such responses least likely include:",
     [("A", "Emphasizing to the audit team the need to maintain professional skepticism in gathering and evaluating audit evidence."),
      ("B", "Assigning more experienced staff or those with special skills or using experts."),
      ("C", "Incorporating additional elements of unpredictability in the selection of further audit procedures to be performed."),
      ("D", "Performing substantive procedures at an interim date instead of at period end.")]),
    (38, "Risk Assessment Procedures", "Prior to commencing fieldwork, an auditor usually discusses the general audit strategy with the client's management. Which of the following details do management and the auditor usually agree upon at this time?",
     [("A", "The specific matters to be included in the communication with the audit committee."),
      ("B", "The minimum amount of misstatements that may be considered to be significant deficiencies and material weaknesses."),
      ("C", "The schedules and analyses that the client's staff should prepare."),
      ("D", "The effects that inadequate controls may have over the safeguarding of assets.")]),
    (39, "Materiality in the Context of Audit", "Which of the following statements best describes materiality?",
     [("A", "Materiality is typically measured as a fixed percentage of assets."),
      ("B", "Materiality is typically measured as a fixed percentage of net income."),
      ("C", "Materiality does not depend on the company being audited, but is solely dependent on the auditor's discretion."),
      ("D", "Materiality provides a cutoff point at which a judgment, based on the financial statements, may be altered.")]),
    (40, "Materiality in the Context of Audit", "Which of the following statements concerning materiality thresholds is false?",
     [("A", "Aggregate materiality thresholds are a function of the auditor's preliminary judgments concerning audit risk."),
      ("B", "In general, the more misstatements the auditor expects, the higher should be the aggregate materiality threshold."),
      ("C", "The smallest aggregate level of errors or fraud that could be considered material to any one of the financial statements is referred to as a \"materiality threshold.\""),
      ("D", "Materiality thresholds may change between the planning and review stages of the audit. These changes may be due to quantitative and/or qualitative factors.")]),
    (41, "Materiality in the Context of Audit", "Which of the following statements concerning materiality is incorrect?",
     [("A", "When establishing the overall audit strategy, the auditor shall determine materiality for the financial statements as a whole."),
      ("B", "If, in the specific circumstances of the entity, there is one or more particular classes of transactions, account balances or disclosures for which misstatements of lesser amounts than materiality for the financial statements as a whole could reasonably be expected to influence the economic decisions of users taken on the basis of the financial statements, the auditor shall also determine the materiality level or levels to those particular classes of transactions, account balances or disclosures."),
      ("C", "Determining materiality involves the exercise of professional judgment."),
      ("D", "The materiality level for the financial statements as a whole determined in the planning stage of the audit should not be affected by changes in the circumstances of the engagement.")]),
    (42, "Materiality in the Context of Audit", "Which of the following statements is not correct about materiality?",
     [("A", "The concept of materiality recognizes that some matters are important for fair presentation of financial statements in conformity with the applicable financial reporting framework, while other matters are not important."),
      ("B", "An auditor considers materiality for planning purposes in terms of the largest aggregate level of misstatements that could be material to any one of the financial statements."),
      ("C", "Materiality judgments are made in light of surrounding circumstances and necessarily involve both quantitative and qualitative judgments."),
      ("D", "An auditor's consideration of materiality is influenced by the auditor's perception of the needs of a reasonable person who will rely on the financial statements.")]),
    (43, "Materiality in the Context of Audit", "Which of the following would an auditor most likely use in determining a preliminary judgment about materiality?",
     [("A", "The contents of the management representation letter."),
      ("B", "The anticipated sample size of the planned substantive tests."),
      ("C", "The entity's annualized interim financial statements."),
      ("D", "The results of internal control questionnaire.")]),
    (44, "Materiality in the Context of Audit", "An auditor shall consider materiality when:\nI. Determining the nature, timing, and extent of audit procedures.\nII. Evaluating the effect of misstatements.",
     [("A", "I only"), ("B", "II only"), ("C", "Both I and II"), ("D", "Neither I nor II")]),
    (45, "Materiality in the Context of Audit", "Why do auditors establish a preliminary judgment about materiality?",
     [("A", "To determine the appropriate level of staff to assign the audit."),
      ("B", "So that the client can know what records to make available to the auditor."),
      ("C", "To plan the appropriate audit evidence to accumulate and develop an overall audit strategy."),
      ("D", "To finalize the control risk assessment.")]),
    (46, "Materiality in the Context of Audit", "The preliminary judgment about materiality and the amount of audit evidence to be accumulated are ______ related.",
     [("A", "Directly"), ("B", "Indirectly"), ("C", "Not"), ("D", "Inversely")]),
    (47, "Materiality in the Context of Audit", "The relationship between materiality and risk is ordinarily:",
     [("A", "Direct"), ("B", "Parallel"), ("C", "Inverse"), ("D", "None")]),
    (48, "Materiality in the Context of Audit", "The main reason why auditors make a preliminary assessment of materiality and risk is to:",
     [("A", "Determine the type of opinion to express."),
      ("B", "Determine the scope of the audit procedures to be performed."),
      ("C", "Evaluate the integrity of client's management."),
      ("D", "Have a basis for constructive suggestions to clients.")]),
    (49, "Materiality in the Context of Audit", "If the auditor sets the preliminary judgment about materiality level at a relatively low peso amount:",
     [("A", "More evidence will be required than for a high level."),
      ("B", "Less evidence will be required than for a high level."),
      ("C", "The same amount of evidence will be required as for a high level."),
      ("D", "The amount of evidence required will not be affected.")]),
    (50, "Materiality in the Context of Audit", "Which of the following statements is not correct about materiality?",
     [("A", "The concept of materiality recognizes that some matters are important for fair presentation of financial statements in conformity with the applicable financial reporting framework, while other matters are not important."),
      ("B", "An auditor considers materiality for planning purposes in terms of the largest aggregate level of misstatements that could be material to any one of the financial statements."),
      ("C", "Materiality judgments are made in light of surrounding circumstances and necessarily involve both quantitative and qualitative judgments."),
      ("D", "An auditor's consideration of materiality is influenced by the auditor's perception of the needs of a reasonable person who will rely on the financial statements.")]),
    (51, "Materiality in the Context of Audit", "When assessing materiality levels for audit purposes, the auditor should consider the:\nAmount involved | Nature of misstatement\nA. Yes | Yes\nB. Yes | No\nC. No | No\nD. No | Yes",
     [("A", "Yes, Yes"), ("B", "Yes, No"), ("C", "No, No"), ("D", "No, Yes")]),
    (52, "Materiality in the Context of Audit", "In considering materiality for planning purposes, an auditor believes that misstatements aggregating P1,000,000 would have a material effect on an entity's income statement, but those misstatements would have to aggregate P2,000,000 to materially affect the balance sheet. Ordinarily, it would be appropriate to design audit procedures that would be expected to detect misstatements that aggregate:",
     [("A", "P1,000,000"), ("B", "P1,500,000"), ("C", "P2,000,000"), ("D", "P3,000,000")]),
    (53, "Materiality in the Context of Audit", "Performance materiality is the term used to indicate materiality at the:",
     [("A", "Financial statement level"),
      ("B", "Account balance level"),
      ("C", "Company-wide level"),
      ("D", "Professional judgment level of the auditor")]),
    (54, "Materiality in the Context of Audit", "Which of the following is the primary basis used to decide materiality for a profit-oriented entity?",
     [("A", "Net sales"), ("B", "Net assets"), ("C", "Net income before tax"), ("D", "All of the above")]),
    (55, "Materiality in the Context of Audit", "Auditing standards ______ that the basis used to determine the preliminary judgment about materiality be documented in the audit files.",
     [("A", "Permit"), ("B", "Do not allow"), ("C", "Require"), ("D", "Strongly encourage")]),
    (56, "The Audit Risk", "The risk that the auditor may give an inappropriate opinion when the financial statements are materially misstated is called:",
     [("A", "Detection risk"), ("B", "Business risk"), ("C", "Audit risk"), ("D", "Inherent risk")]),
    (57, "The Audit Risk", "Which of the following is/are the components of the audit risk?\nI. Inherent risk\nII. Control risk\nIII. Detection risk",
     [("A", "I only"), ("B", "II only"), ("C", "I and II"), ("D", "I, II, III")]),
    (58, "The Audit Risk", "Risk of material misstatements include\nI. Inherent risk\nII. Control risk\nIII. Detection risk",
     [("A", "I only"), ("B", "II only"), ("C", "I and II"), ("D", "I, II, III")]),
    (59, "The Audit Risk", "It is the susceptibility of an account balance or class of transactions to misstatement that could be material, individually or when aggregated with misstatements in other balances or classes, assuming that there were no related internal controls.",
     [("A", "Inherent risk"), ("B", "Control risk"), ("C", "Detection risk"), ("D", "Business risk")]),
    (60, "The Audit Risk", "It is the risk that a misstatement that could occur in an account balance or class of transactions that could be material, individually or when aggregated with other misstatements in other balances or classes, will not be prevented, or detected and corrected, on a timely basis, by the accounting and internal control systems.",
     [("A", "Inherent risk"), ("B", "Control risk"), ("C", "Detection risk"), ("D", "Business risk")]),
    (61, "The Audit Risk", "It is the risk that an auditor's substantive procedures will not detect a misstatement that exists in an account balance or class of transactions that could be material, individually or when aggregated with misstatements in other balances or classes.",
     [("A", "Inherent risk"), ("B", "Control risk"), ("C", "Detection risk"), ("D", "Business risk")]),
    (62, "The Audit Risk", "The probability of an auditor's procedures leading to the conclusion that a material error does not exist in an account balance when, in fact, such error does exist is referred to as:",
     [("A", "Prevention risk."), ("B", "Inherent risk."), ("C", "Control risk."), ("D", "Detection risk.")]),
    (63, "The Audit Risk", "Which of the following statements concerning audit risk and its components is incorrect?",
     [("A", "Regardless of the assessed levels of inherent and control risks, the auditor should always perform some substantive procedures for material account balances and classes of transactions."),
      ("B", "The higher the assessment of inherent and control risks, the more evidence the auditor should obtain from the performance of substantive procedures."),
      ("C", "The assessed level of inherent risk need not be considered in determining the nature, timing, and extent of substantive procedures required to reduce audit risk to an acceptably low level."),
      ("D", "After obtaining an understanding of the accounting and internal control systems, the auditor should make a preliminary assessment of control risk, at the assertion level, for each material account balance or class of transactions.")]),
    (64, "The Audit Risk", "When planning a financial statement audit, the auditor should assess inherent risk at the:\nFinancial statement level | Account balance level\nA. Yes | Yes\nB. Yes | No\nC. No | No\nD. No | Yes",
     [("A", "Yes, Yes"), ("B", "Yes, No"), ("C", "No, No"), ("D", "No, Yes")]),
    (65, "The Audit Risk", "Which of the following is an example of the concept of inherent risk?",
     [("A", "Humans make more errors than computers, therefore a manual accounting system is riskier than a computerized system."),
      ("B", "Accounting systems with vouchers have many more controls built-in, so the risk that there will be errors on the financial statements is reduced."),
      ("C", "Loans receivable for a finance company are less likely to be collectible than those of a bank."),
      ("D", "Audits with larger sample sizes are less risky than those with smaller sample sizes.")]),
    (66, "The Audit Risk", "Which of the following discoveries by the auditor would not raise the red flag of increased inherent risk?",
     [("A", "Management bonuses are based on a percentage of net income."),
      ("B", "A bond indenture requires a current ratio of at least three to one."),
      ("C", "Client makes extensive use of notes receivable and notes payable rather than buying and selling on open-account basis."),
      ("D", "Client is a parent company with a subsidiary.")]),
    (67, "The Audit Risk", "In which of the following order would the auditors perform the following steps?",
     [("A", "Determine audit risk, assess control risk, determine detection risk, set materiality."),
      ("B", "Set materiality, determine audit risk, assess control risk, determine detection risk."),
      ("C", "Set materiality, assess control risk, determine detection risk, determine audit risk."),
      ("D", "Determine audit risk, set materiality, assess control risk, determine detection risk.")]),
    (68, "The Audit Risk", "Inherent risk is ______ related to detection risk and ______ related to the amount of audit evidence.",
     [("A", "Directly, inversely"), ("B", "Directly, directly"), ("C", "Inversely, inversely"), ("D", "Inversely, directly")]),
    (69, "The Audit Risk", "What is the magnitude of audit risk if inherent risk is 0.50, control risk, 0.40, and detection risk, 0.10?",
     [("A", "0.20"), ("B", "0.04"), ("C", "0.10"), ("D", "0.02")]),
    (70, "The Audit Risk", "As the risk of material misstatement increases, detection risk should:",
     [("A", "Increase."), ("B", "Decrease."), ("C", "Stay the same."), ("D", "Increase or decrease depending on materiality level.")]),
    (71, "The Audit Risk", "Inherent risk and control risk differ from detection risk in that inherent and control risks:",
     [("A", "Arise from the misapplication of auditing procedures."),
      ("B", "May be assessed in either quantitative or non-quantitative terms."),
      ("C", "Exist independently of the financial statement audit."),
      ("D", "Can be changed at the auditor's discretion.")]),
    (72, "The Audit Risk", "As the acceptable level of detection risk decreases, an auditor may:",
     [("A", "Timing of substantive tests by performing them at an interim date rather than at year-end."),
      ("B", "Nature of substantive tests from a less effective to a more effective procedure."),
      ("C", "Timing of tests of controls by performing them at several dates rather than at one time."),
      ("D", "Assessed level of inherent risk to a higher level.")]),
    (73, "The Audit Risk", "The auditor should obtain an understanding of the entity's objectives and strategies, and those business risks that may result in risks of material misstatement. Which of the following statements concerning the entity's business risk is incorrect?",
     [("A", "Business risk is broader than the risk of material misstatement of the financial statements, though it includes the latter."),
      ("B", "An understanding of the business risks facing the entity increases the likelihood of identifying risks of material misstatement."),
      ("C", "The auditor has a responsibility to identify or assess all business risks."),
      ("D", "Business risk may arise from the development of new products or services that may fail.")]),
    (74, "The Audit Risk", "Inherent risk is defined as the susceptibility of an account balance or class of transactions to error that could be material assuming that there were no related internal controls. Of the following conditions, which one does not increase the assessed level of inherent risk?",
     [("A", "The client has entered numerous related party transactions during the year under audit."),
      ("B", "Internal control over shipping, billing, and recording of sales revenue is weak."),
      ("C", "The client has lost a major customer accounting for approximately 30% of annual revenue."),
      ("D", "The board of directors approved a substantial bonus for the president and chief executive officer and approved an attractive stock option plan for themselves.")]),
    (75, "The Audit Risk", "Which of the following statements is true regarding the relationship among audit risk, audit evidence, and materiality?",
     [("A", "The lower the inherent risk and control risk, the lower the aggregate materiality threshold."),
      ("B", "Under conditions of high inherent and control risk, the auditor should place more emphasis on obtaining external evidence and should reduce reliance on internal evidence."),
      ("C", "Where inherent risk is high and control risk is low, the auditor may safely ignore inherent risk."),
      ("D", "Aggregate materiality thresholds should not change under conditions of changing risk levels.")]),
    (76, "The Audit Risk", "Risk in auditing means that the auditor accepts some level of uncertainty in performing the audit function. An effective audit:",
     [("A", "Design audit procedures to achieve the desired level of audit risk."),
      ("B", "Take any means available to reduce the risk to the lowest possible level."),
      ("C", "Set the risk level between 5% to 10%."),
      ("D", "Perform audit procedures first and quantitatively set the risk level before forming an opinion and writing the report.")]),
    (77, "The Audit Risk", "Which of the following models expresses the general relationship of risks associated with the auditor's evaluation of internal control for Control Risk study of the business and application of analytical procedures for Inherent Risk, and overall Audit Risk, that would lead the auditor to conclude that additional substantive tests of details of an account balance are not necessary?\nInherent risk | Control risk | Audit risk\nA. 20% | 40% | 10%\nB. 20% | 60% | 5%\nC. 10% | 70% | 4.5%\nD. 30% | 40% | 5.5%",
     [("A", "20% | 40% | 10%"), ("B", "20% | 60% | 5%"), ("C", "10% | 70% | 4.5%"), ("D", "30% | 40% | 5.5%")]),
    (78, "The Audit Risk", "Which of the following does an auditor least likely perform in assessing audit risk?",
     [("A", "Gather audit evidence in support of recorded transactions."),
      ("B", "Obtain an understanding of the client's system of internal control."),
      ("C", "Understand the economic substance of significant transactions completed by the client."),
      ("D", "Understand the entity and the industry in which it operates.")]),
    (79, "The Audit Risk", "The risk that the audit will fail to uncover a material misstatement is eliminated:",
     [("A", "If a client has strong internal controls."),
      ("B", "If a client follows generally accepted accounting principles (GAAP)."),
      ("C", "When the auditor has complied with generally accepted auditing standards (GAAS)."),
      ("D", "Under no circumstances.")]),
    (80, "The Audit Risk", "Which statement is incorrect regarding the extent of further audit procedures?",
     [("A", "Extent includes the quantity of a specific audit procedure to be performed."),
      ("B", "The extent of an audit procedure is determined by the judgment of the auditor after considering the materiality, the assessed risk, and the degree of assurance the auditor plans to obtain."),
      ("C", "The auditor ordinarily decreases the extent of audit procedures as the risk of material misstatement increases."),
      ("D", "Increasing the extent of an audit procedure is effective only if the audit procedure itself is relevant to the specific risk.")]),
    (81, "The Audit Risk", "It is appropriate and acceptable under auditing standards for an auditor to:",
     [("A", "Assess both inherent and control risk at 100% and achieve an acceptably low audit risk by performing extensive detection work."),
      ("B", "Assess control risk at zero and perform a minimum of detection work."),
      ("C", "Assess control risk at zero and perform a minimum of detection work."),
      ("D", "Decide that audit risk can be 40%.")]),
    (82, "Analytical Procedures", "These consist of the analysis of significant ratios and trends including the resulting investigation of fluctuations and relationship that are inconsistent with other relevant information or deviate from predictable amount.",
     [("A", "Financial statement analysis"), ("B", "Variance analysis"), ("C", "Analytical procedures"), ("D", "Regression analysis")]),
    (83, "Analytical Procedures", "Evaluations of financial information made by a study of plausible relationships among financial and nonfinancial data involving comparisons of recorded amounts to expectations developed by the auditor is a definition of:",
     [("A", "Analytical procedures"), ("B", "Tests of balances"), ("C", "Tests of transactions"), ("D", "Auditing")]),
    (84, "Analytical Procedures", "A basic premise underlying analytical procedures is that:",
     [("A", "Plausible relationships among data may reasonably be expected to exist and continue in the absence of known conditions to the contrary."),
      ("B", "These procedures cannot replace tests of details of transactions and balances."),
      ("C", "Statistical tests of financial information may lead to the detection of material misstatements in the financial statements."),
      ("D", "The study of financial ratios is an acceptable alternative to the investigation of unusual fluctuations.")]),
    (85, "Analytical Procedures", "The purpose of analytical procedures during the audit planning stage is to:",
     [("A", "Aid in planning the observation of physical inventory."),
      ("B", "Identify unusual circumstances that the auditor may need to investigate further."),
      ("C", "Flag individual transactions for further review."),
      ("D", "Determine whether sales transactions are approved.")]),
    (86, "Analytical Procedures", "Analytical procedures used as of risk assessment procedure are performed primarily to assist the auditor in:",
     [("A", "Identifying areas that may represent specific risks."),
      ("B", "Obtaining knowledge about the design of internal control."),
      ("C", "Obtaining knowledge about the operating effectiveness of the client's internal control."),
      ("D", "Gathering corroborative evidence about the validity of an account balance.")]),
    (87, "Analytical Procedures", "For all audits of financial statements conducted in accordance with PSAs, the use of analytical procedures is required to some extent:\nAs risk assessment in planning | As substantive test | In overall review\nA. Yes | Yes | Yes\nB. Yes | No | Yes\nC. Yes | No | No\nD. No | Yes | Yes",
     [("A", "Yes, Yes, Yes"), ("B", "Yes, No, Yes"), ("C", "Yes, No, No"), ("D", "No, Yes, Yes")]),
    (88, "Analytical Procedures", "Analytical procedures are used for the following purposes except:",
     [("A", "To assist the auditor in planning the nature, timing and extent of other auditing procedures."),
      ("B", "As a substantive test to obtain evidential matter about particular assertion related to account balances or classes of transactions."),
      ("C", "As an overall review of financial information in the final review stage of the audit."),
      ("D", "To evaluate the effectiveness of the client's internal control.")]),
    (89, "Analytical Procedures", "Which of the following situations would not serve the purpose in the application of analytical procedures?",
     [("A", "As part of audit planning to assist in locating significant changes in revenues and expenses."),
      ("B", "To provide a basis for lowering materiality thresholds where significant earnings inflation is indicated."),
      ("C", "To determine the economic substance of related party transactions."),
      ("D", "As part of audit review to determine that all significant abnormalities have been resolved to the auditor's satisfaction.")]),
    (90, "Analytical Procedures", "An abnormal fluctuation in gross profit that might suggest the need for extended audit procedures for sales and inventories would most likely be identified in the planning phase of the audit using",
     [("A", "Tests of transactions and balances."),
      ("B", "A preliminary review of internal control."),
      ("C", "Specialized audit programs."),
      ("D", "Analytical procedures.")]),
    (91, "Analytical Procedures", "The auditor notices significant fluctuations in key elements of the company's financial statements. If management is unable to provide an acceptable explanation, the auditor should:",
     [("A", "Consider the matter a scope limitation."),
      ("B", "Perform additional audit procedures to investigate the matter further."),
      ("C", "Intensify the examination with the expectation of detecting management fraud."),
      ("D", "Withdraw from the engagement.")]),
    (92, "Analytical Procedures", "If, when performing analytical procedures, an auditor observes that operating income has declined significantly between the preceding year and the current year, the auditor should next",
     [("A", "Require that the decline be disclosed in the financial statements."),
      ("B", "Consider the possibility that the financial statements may be materially misstated."),
      ("C", "Inform management that a qualified opinion on the financial statements will be necessary."),
      ("D", "Determine management's responsibility for the decline and discuss the audit with the audit committee.")]),
    (93, "Analytical Procedures", "When must an auditor perform analytical procedures in a financial statement audit?",
     [("A", "Testing controls over financial cycles."),
      ("B", "Performing tests to substantiate balances."),
      ("C", "Planning the nature, timing and extent of procedures."),
      ("D", "Performing tests to substantiate transactions.")]),
    (94, "Analytical Procedures", "Analytical procedures used as of risk assessment procedure are performed primarily to assist the auditor in",
     [("A", "Identifying areas that may represent specific risks."),
      ("B", "Obtaining knowledge about the design of internal control."),
      ("C", "Obtaining knowledge about the operating effectiveness of the client's internal control."),
      ("D", "Gathering corroborative evidence about the validity of an account balance.")]),
    (95, "Analytical Procedures", "At what stage in the audit are the analytical procedures performed?",
     [("A", "In the planning stage."),
      ("B", "In conjunction with test of transactions and test of details of balances."),
      ("C", "Near the end."),
      ("D", "During all three stages.")])
]

chapter05 = {
    "id": "at-05",
    "code": "AT-05",
    "title": "Planning the Audit of Financial Statements",
    "description": "Overall audit strategy and plan (PSA 300), risk assessment procedures (PSA 315), materiality and performance materiality (PSA 320), audit risk model (IR, CR, DR), and analytical procedures in planning (PSA 520).",
    "objectives": [
        "Audit Planning",
        "Major Audit Planning Activities",
        "Risk Assessment Procedures",
        "Materiality in the Context of Audit",
        "The Audit Risk",
        "Analytical Procedures"
    ],
    "totalQuestions": 95,
    "questions": []
}

for num, obj, qtext, opts in at05_raw:
    correct = at05_answers[num]
    expl = at05_explanations.get(num, f"Suggested Answer: {correct}. In accordance with PSA 300, PSA 315, PSA 320, and PSA 520.")
    chapter05["questions"].append({
        "id": f"at05-{num}",
        "number": num,
        "chapterId": "at-05",
        "chapterCode": "AT-05",
        "chapterTitle": "Planning the Audit of Financial Statements",
        "objective": obj,
        "question": qtext,
        "options": [{"key": k, "text": t} for k, t in opts],
        "correctAnswer": correct,
        "explanation": expl
    })

with open("src/data/chapters/at05.ts", "w", encoding="utf-8") as f:
    f.write(f"import {{ Chapter }} from '../../types/quiz';\n\nexport const chapter05: Chapter = {json.dumps(chapter05, indent=2)};\n")

print("Created at05.ts with 95 questions")
