#!/usr/bin/env python3
import json

at11_answers = {
    1: 'B', 2: 'D', 3: 'A', 4: 'C', 5: 'A', 6: 'C', 7: 'B', 8: 'C', 9: 'C', 10: 'D',
    11: 'B', 12: 'B', 13: 'B', 14: 'C', 15: 'C', 16: 'C', 17: 'B', 18: 'B', 19: 'A', 20: 'D',
    21: 'B', 22: 'C', 23: 'D', 24: 'B', 25: 'A', 26: 'A', 27: 'C', 28: 'D', 29: 'D', 30: 'B',
    31: 'D', 32: 'B', 33: 'A', 34: 'C', 35: 'D', 36: 'B', 37: 'A', 38: 'D', 39: 'B', 40: 'D',
    41: 'A', 42: 'B', 43: 'B', 44: 'C', 45: 'A', 46: 'A', 47: 'C', 48: 'C', 49: 'D', 50: 'C',
    51: 'C', 52: 'D', 53: 'A', 54: 'A', 55: 'B', 56: 'B', 57: 'C', 58: 'C', 59: 'A', 60: 'C',
    61: 'A', 62: 'B', 63: 'C', 64: 'B', 65: 'B', 66: 'B', 67: 'C', 68: 'B', 69: 'B', 70: 'A'
}

at11_explanations = {
    1: "Subsequent events refer to events occurring between the date of the financial statements and the date of the auditor's report, and facts that become known to the auditor after the date of the auditor's report.",
    2: "Type 1 subsequent events (adjusting events) provide evidence of conditions that existed at the date of the financial statements. Type 2 events (non-adjusting events) provide evidence of conditions that arose after the date of the financial statements.",
    3: "Bankruptcy of a customer after balance sheet date due to deteriorating financial condition existing before year-end requires adjustment (Type 1).",
    4: "Loss of plant or inventory due to fire or natural disaster after year-end requires disclosure only (Type 2).",
    21: "Under PSA 570, the auditor's responsibility is to obtain sufficient appropriate audit evidence about the appropriateness of management's use of the going concern assumption.",
    24: "If adequate disclosure about material uncertainty is made in the financial statements, the auditor expresses an unmodified opinion and includes a 'Material Uncertainty Related to Going Concern' section.",
    51: "Written representations are audit evidence obtained from management to confirm certain matters or to support other audit evidence (PSA 580).",
    53: "The date of the written representations should be as near as practicable to, but not after, the date of the auditor's report."
}

at11_raw = [
    (1, "Subsequent Events", "Subsequent events refer to:",
     [("A", "Events occurring only after the financial statements are issued."),
      ("B", "Events occurring between the date of the financial statements and the date of the auditor's report, and facts that become known to the auditor after the date of the auditor's report."),
      ("C", "Transactions occurring only during the last month of the fiscal year."),
      ("D", "Adjustments made by the client's internal auditors.")]),
    (2, "Subsequent Events", "Events that provide additional evidence with respect to conditions that existed at the date of the balance sheet and affect estimates require:",
     [("A", "Disclosure only"), ("B", "No disclosure and no adjustment"), ("C", "Disclaimer of opinion"), ("D", "Adjustment of the financial statements")]),
    (3, "Subsequent Events", "Which of the following subsequent events would most likely require an adjustment to the financial statements?",
     [("A", "Settlement of litigation for an amount different from the liability recorded at year-end."),
      ("B", "Issuance of capital stock or bonds after the reporting period."),
      ("C", "Loss of plant from fire or flood after the balance sheet date."),
      ("D", "Unrealized decline in market value of investments after year-end.")]),
    (4, "Subsequent Events", "A major customer's warehouse was destroyed by a fire in January following the December 31 balance sheet date. This event:",
     [("A", "Requires adjustment of the December 31 financial statements."),
      ("B", "Requires restatement of prior period financial statements."),
      ("C", "Requires disclosure in notes to the December 31 financial statements."),
      ("D", "Requires no adjustment or disclosure.")]),
    (5, "Subsequent Events", "The auditor has an active responsibility to perform audit procedures to identify subsequent events up to:",
     [("A", "The date of the auditor's report."),
      ("B", "The date the financial statements are issued."),
      ("C", "The next annual general meeting."),
      ("D", "The date management approves the budget.")]),
    (6, "Subsequent Events", "Procedures performed to identify subsequent events typically include:",
     [("A", "Confirming all accounts payable again."),
      ("B", "Performing 100% recalculation of depreciation."),
      ("C", "Inquiring of management, reading interim financial statements, and reading minutes of meetings."),
      ("D", "Reperforming tests of internal control.")]),
    (7, "Subsequent Events", "When the auditor dates the report as of February 15, and a subsequent event occurs on March 1 before issuance, dual dating is used to:",
     [("A", "Extend responsibility for all events up to March 1."),
      ("B", "Limit the auditor's responsibility for events occurring after February 15 to the specific event disclosed."),
      ("C", "Withdraw the audit report."),
      ("D", "Indicate a qualified opinion.")]),
    (8, "Subsequent Events", "Which format represents dual dating in an audit report?",
     [("A", "February 15, 2024"),
      ("B", "March 1, 2024"),
      ("C", "February 15, 2024, except for Note X, as to which the date is March 1, 2024"),
      ("D", "From January 1 to December 31, 2023")]),
    (9, "Subsequent Events", "If management refuses to amend the financial statements for a material adjusting subsequent event, the auditor should:",
     [("A", "Issue an unqualified opinion with emphasis of matter"),
      ("B", "Issue a disclaimer of opinion"),
      ("C", "Express a qualified or adverse opinion"),
      ("D", "Resign immediately and notify the media")]),
    (10, "Subsequent Events", "Which of the following is not a procedure to obtain evidence about subsequent events?",
     [("A", "Reviewing latest available interim financial statements"),
      ("B", "Inquiring of the entity's legal counsel regarding litigation"),
      ("C", "Reading minutes of board of directors' meetings"),
      ("D", "Confirming beginning accounts receivable balances")]),
    (11, "Subsequent Events", "Type 2 subsequent events are those that:",
     [("A", "Provide evidence of conditions existing at the balance sheet date."),
      ("B", "Provide evidence with respect to conditions that arose subsequent to the balance sheet date."),
      ("C", "Never require disclosure."),
      ("D", "Require adjustments to retained earnings.")]),
    (12, "Subsequent Events", "If a material Type 2 event is not disclosed in the notes to the financial statements, the audit opinion should be:",
     [("A", "Unmodified"), ("B", "Qualified or adverse"), ("C", "Disclaimer"), ("D", "Review report")]),
    (13, "Subsequent Events", "The date of the auditor's report should be:",
     [("A", "The balance sheet date"),
      ("B", "No earlier than the date on which the auditor has obtained sufficient appropriate audit evidence on which to base the opinion"),
      ("C", "The date the report is mailed to stockholders"),
      ("D", "The date the engagement letter was signed")]),
    (14, "Subsequent Events", "After the date of the auditor's report but before issuance of financial statements, the auditor has:",
     [("A", "An active duty to perform ongoing audit procedures."),
      ("B", "No responsibility under any circumstances."),
      ("C", "No obligation to perform procedures, but if facts become known, must consider whether amendment is needed."),
      ("D", "An obligation to re-audit all cash transactions.")]),
    (15, "Subsequent Events", "A customer declared bankruptcy on January 10 due to a sudden flood that destroyed their operations on January 5. The balance sheet date is December 31. This is:",
     [("A", "An adjusting event requiring restatement of receivable balance."),
      ("B", "A prior period error."),
      ("C", "A non-adjusting event requiring disclosure if material."),
      ("D", "Neither an adjusting nor a disclosing event.")]),
    (16, "Subsequent Events", "If an auditor dual dates the audit report, the auditor's responsibility for events occurring after the original report date is:",
     [("A", "Extended to all aspects of the financial statements."),
      ("B", "Completely terminated."),
      ("C", "Limited specifically to the event referred to in the dual date."),
      ("D", "Transferred to the client's internal auditor.")]),
    (17, "Subsequent Events", "Which of the following would least likely require disclosure as a subsequent event?",
     [("A", "A major business combination after year-end."),
      ("B", "A routine collection of a recorded trade receivable in January."),
      ("C", "Loss of plant assets from an earthquake in January."),
      ("D", "Issuance of substantial debt securities after year-end.")]),
    (18, "Subsequent Events", "Inquiry of the client's legal counsel is primarily conducted to obtain evidence concerning:",
     [("A", "Compliance with the Corporation Code."),
      ("B", "Litigation, claims, and assessments that may affect financial statements."),
      ("C", "Internal auditor performance."),
      ("D", "Depreciation methods used for taxation.")]),
    (19, "Subsequent Events", "If the client's lawyer refuses to provide information regarding material litigation, this constitutes:",
     [("A", "A scope limitation resulting in a qualified opinion or disclaimer of opinion."),
      ("B", "An adverse opinion."),
      ("C", "A standard unqualified opinion with emphasis paragraph."),
      ("D", "A regulatory violation requiring immediate report to the BIR.")]),
    (20, "Subsequent Events", "PSA 560 provides guidance on the auditor's responsibilities regarding:",
     [("A", "Related parties"), ("B", "Opening balances"), ("C", "Audit sampling"), ("D", "Subsequent events")]),
    (21, "Going Concern", "The going concern assumption means that:",
     [("A", "The entity will be liquidated within six months."),
      ("B", "The entity is viewed as continuing in business for the foreseeable future with neither intention nor necessity of liquidation."),
      ("C", "The entity will generate record profits."),
      ("D", "The entity's assets are valued at liquidation fire-sale values.")]),
    (22, "Going Concern", "Under PSA 570, the foreseeable future is generally considered to be at least:",
     [("A", "3 months from balance sheet date"),
      ("B", "6 months from report date"),
      ("C", "12 months from the date of the financial statements"),
      ("D", "5 years from report date")]),
    (23, "Going Concern", "Which of the following is a financial indicator that may cast significant doubt on the going concern assumption?",
     [("A", "Consistent net operating cash inflows"),
      ("B", "Substantial lines of credit available"),
      ("C", "Payment of regular cash dividends"),
      ("D", "Net liability or negative operating cash flows")]),
    (24, "Going Concern", "If the auditor concludes that a material uncertainty exists regarding going concern but it is adequately disclosed in the financial statements, the auditor should express:",
     [("A", "An adverse opinion"),
      ("B", "An unmodified opinion with a 'Material Uncertainty Related to Going Concern' section"),
      ("C", "A qualified opinion due to scope limitation"),
      ("D", "A disclaimer of opinion in all cases")]),
    (25, "Going Concern", "If the use of the going concern basis of accounting is inappropriate, the auditor shall express:",
     [("A", "An adverse opinion"), ("B", "A qualified opinion"), ("C", "An unqualified opinion"), ("D", "A review disclaimer")]),
    (26, "Going Concern", "If adequate disclosure about a material uncertainty related to going concern is not made in the financial statements, the auditor shall express:",
     [("A", "A qualified or adverse opinion"), ("B", "An unmodified opinion"), ("C", "A special review report"), ("D", "An unqualified opinion with emphasis paragraph")]),
    (27, "Going Concern", "Management's plans to mitigate going concern doubts might include:",
     [("A", "Increasing operating expenses"),
      ("B", "Paying extra executive bonuses"),
      ("C", "Plans to dispose of non-core assets, borrow money, or restructure debt"),
      ("D", "Declaring stock splits")]),
    (28, "Going Concern", "Which of the following operating conditions may cast doubt on going concern?",
     [("A", "Expansion into new profitable markets"),
      ("B", "Successful introduction of high-margin products"),
      ("C", "Favorable labor union agreements"),
      ("D", "Loss of a key management personnel without replacement or loss of major customer")]),
    (29, "Going Concern", "When evaluating management's plans to address going concern issues, the auditor examines:",
     [("A", "Feasibility of the plans"),
      ("B", "Likelihood that the outcome of plans will improve the situation"),
      ("C", "Cash flow forecasts and supporting data"),
      ("D", "All of the above")]),
    (30, "Going Concern", "The auditor's report includes a 'Material Uncertainty Related to Going Concern' section when:",
     [("A", "The entity will definitely go bankrupt within 30 days."),
      ("B", "A material uncertainty exists, going concern basis is appropriate, and disclosure in the notes is adequate."),
      ("C", "The client refuses to provide bank reconciliations."),
      ("D", "Internal controls are assessed as strong.")]),
    (31, "Going Concern", "Which of the following is not an auditor's responsibility regarding going concern under PSA 570?",
     [("A", "Obtaining sufficient evidence regarding appropriateness of going concern basis"),
      ("B", "Concluding whether a material uncertainty exists"),
      ("C", "Determining implications for the auditor's report"),
      ("D", "Guaranteeing that the entity will remain in business for at least two years")]),
    (32, "Going Concern", "An auditor's inquiry regarding going concern is performed:",
     [("A", "Only if requested by the audit committee"),
      ("B", "Throughout planning, conducting, and concluding the audit"),
      ("C", "Only after the audit report is signed"),
      ("D", "Exclusively during the pre-engagement phase")]),
    (33, "Going Concern", "If the auditor concludes that management's use of the going concern basis is appropriate and no material uncertainty exists, the report will:",
     [("A", "Not mention going concern in an emphasis or uncertainty section"),
      ("B", "Include an adverse opinion on going concern"),
      ("C", "Include a disclaimer of opinion"),
      ("D", "Require dual dating")]),
    (34, "Going Concern", "Which procedure is most relevant when assessing going concern?",
     [("A", "Vouching equipment purchases"),
      ("B", "Counting petty cash funds"),
      ("C", "Analyzing cash flows, reviewing compliance with loan covenants, and reading minutes"),
      ("D", "Confirming petty cash custodian integrity")]),
    (35, "Going Concern", "An entity preparing financial statements on a liquidation basis because going concern is invalid will receive:",
     [("A", "An adverse opinion because liquidation basis is never allowed"),
      ("B", "A disclaimer of opinion"),
      ("C", "A standard unqualified report"),
      ("D", "An unmodified opinion if liquidation basis is acceptable and adequately disclosed")]),
    (36, "Going Concern", "When management is unwilling to assess going concern for at least 12 months when requested, the auditor considers:",
     [("A", "Issuing an immediate adverse opinion"),
      ("B", "The implications for the auditor's report, including potential scope limitation"),
      ("C", "Reporting management to the labor department"),
      ("D", "Waiving all going concern requirements")]),
    (37, "Going Concern", "Loan defaults and breach of covenants are classified as:",
     [("A", "Financial indicators of going concern problems"),
      ("B", "Operating indicators"),
      ("C", "Other legal indicators"),
      ("D", "Non-sampling risks")]),
    (38, "Going Concern", "Under revised PSA 570, the 'Material Uncertainty Related to Going Concern' paragraph:",
     [("A", "Replaces the opinion paragraph"),
      ("B", "Is placed in the engagement letter only"),
      ("C", "Is a form of disclaimer of opinion"),
      ("D", "Draws attention to the note in the financial statements that discloses the uncertainty")]),
    (39, "Going Concern", "The absence of reference to going concern uncertainty in an audit report:",
     [("A", "Guarantees the future solvency of the entity"),
      ("B", "Cannot be viewed as a guarantee as to the entity's ability to continue as a going concern"),
      ("C", "Means the auditor is legally liable if the company fails"),
      ("D", "Indicates that management made no forecasts")]),
    (40, "Going Concern", "Which of the following mitigates doubts about an entity's going concern?",
     [("A", "Postponing maintenance on production machinery indefinitely"),
      ("B", "Selling core operating assets at huge discounts"),
      ("C", "Issuing high-interest predatory loans"),
      ("D", "Subordinated loans from a wealthy parent company or binding agreement to provide financial support")]),
    (41, "Related Parties", "Under PSA 550, the auditor's primary objective regarding related party transactions is to:",
     [("A", "Obtain sufficient appropriate audit evidence about whether related party relationships and transactions have been appropriately identified, accounted for, and disclosed."),
      ("B", "Prevent all related party transactions."),
      ("C", "Set prices for transactions between related parties."),
      ("D", "Approve contracts with directors.")]),
    (42, "Related Parties", "Related party transactions are not conducted at 'arm's length' because:",
     [("A", "They are always fraudulent."),
      ("B", "The relationship between parties may allow terms and conditions different from those with unrelated third parties."),
      ("C", "They are strictly prohibited by PFRS."),
      ("D", "They are only between companies in different countries.")]),
    (43, "Related Parties", "Which procedure is most useful in identifying related parties?",
     [("A", "Recalculating interest expense"),
      ("B", "Reviewing shareholder records, SEC filings, and conflict of interest statements"),
      ("C", "Testing petty cash vouchers"),
      ("D", "Performing physical inventory counts")]),
    (44, "Related Parties", "Transactions that are outside the entity's normal course of business may indicate:",
     [("A", "Efficient management"),
      ("B", "Lack of audit risk"),
      ("C", "Fraudulent financial reporting or concealment of related party transactions"),
      ("D", "Standard recurring operations")]),
    (45, "Related Parties", "If the auditor identifies related parties not previously disclosed by management, the auditor should:",
     [("A", "Promptly communicate the relevant information to the other members of the engagement team."),
      ("B", "Conceal the finding until the audit report is signed."),
      ("C", "Ignore the finding if the amounts are under materiality."),
      ("D", "Withdraw from the audit immediately without inquiry.")]),
    (46, "Related Parties", "Disclosure of related party transactions in the notes to financial statements is required by:",
     [("A", "PAS 24"), ("B", "PFRS 9"), ("C", "PSA 200"), ("D", "PSA 705")]),
    (47, "Related Parties", "Which of the following is an example of a related party transaction?",
     [("A", "Paying income tax to the BIR"),
      ("B", "Paying regular salaries to rank-and-file factory workers"),
      ("C", "A loan from a major shareholder at below-market interest rate"),
      ("D", "Purchasing office supplies from an unrelated retail store")]),
    (48, "Related Parties", "When testing related party transactions, the auditor should verify:",
     [("A", "Only the mathematical accuracy of the invoice"),
      ("B", "Whether the entity paid taxes on time"),
      ("C", "Business rationale, authorization, and whether terms are properly disclosed"),
      ("D", "The credit rating of all customers")]),
    (49, "Related Parties", "Management claims that a related party transaction was conducted on terms equivalent to an arm's length transaction. The auditor should:",
     [("A", "Accept the claim without testing"),
      ("B", "Disallow the transaction entirely"),
      ("C", "Require the claim to be deleted from the notes"),
      ("D", "Obtain sufficient appropriate audit evidence to support the claim")]),
    (50, "Related Parties", "If management fails to adequately disclose material related party transactions, the auditor's report should be:",
     [("A", "Unmodified with emphasis of matter"),
      ("B", "Disclaimer of opinion"),
      ("C", "Qualified or adverse opinion"),
      ("D", "Review report")]),
    (51, "Written Representations", "A management representation letter (PSA 580) is:",
     [("A", "A substitute for all other audit procedures."),
      ("B", "Prepared by the client's internal auditors for the board."),
      ("C", "A written statement by management provided to the auditor to confirm certain matters or to support other audit evidence."),
      ("D", "Addressed to the Securities and Exchange Commission.")]),
    (52, "Written Representations", "Written representations are required from management regarding:",
     [("A", "Fulfillment of their responsibility for the preparation of financial statements."),
      ("B", "Provision of all relevant information and access to the auditor."),
      ("C", "Completeness of transactions recorded in the financial statements."),
      ("D", "All of the above.")]),
    (53, "Written Representations", "The representation letter should be dated:",
     [("A", "As near as practicable to, but not after, the date of the auditor's report."),
      ("B", "On the balance sheet date."),
      ("C", "When the engagement letter is executed."),
      ("D", "At least one month after issuance of financial statements.")]),
    (54, "Written Representations", "The representation letter should ordinarily be signed by:",
     [("A", "The Chief Executive Officer (CEO) and Chief Financial Officer (CFO)"),
      ("B", "The audit partner and audit manager"),
      ("C", "The internal audit supervisor"),
      ("D", "The chairperson of the SEC")]),
    (55, "Written Representations", "If management refuses to provide written representations requested by the auditor, the auditor shall:",
     [("A", "Issue an unmodified opinion with emphasis"),
      ("B", "Disclaim an opinion on the financial statements"),
      ("C", "Accept oral representations as equal evidence"),
      ("D", "File criminal charges against management")]),
    (56, "Written Representations", "Can written representations be used as a substitute for other audit procedures that are practically available?",
     [("A", "Yes, in all situations"),
      ("B", "No, they complement other procedures but do not replace them"),
      ("C", "Yes, if signed under oath"),
      ("D", "Yes, if approved by the audit committee")]),
    (57, "Written Representations", "If management's representations are inconsistent with other audit evidence, the auditor should:",
     [("A", "Ignore the inconsistency"),
      ("B", "Assume the written representation is always correct"),
      ("C", "Perform audit procedures to attempt to resolve the matter and reassess management integrity"),
      ("D", "Discard all other audit evidence")]),
    (58, "Written Representations", "A management representation letter is addressed to:",
     [("A", "The shareholders"),
      ("B", "The board of directors"),
      ("C", "The independent auditor"),
      ("D", "The Philippine Stock Exchange")]),
    (59, "Written Representations", "Written representations do not include:",
     [("A", "Financial statements, the assertions therein, or supporting books and records"),
      ("B", "Acknowledgment of management's responsibilities"),
      ("C", "Statements regarding subsequent events"),
      ("D", "Confirmation of related party disclosures")]),
    (60, "Written Representations", "The auditor should request written representations concerning uncorrected misstatements stating that:",
     [("A", "All misstatements have been eliminated."),
      ("B", "The auditor is responsible for all undetected misstatements."),
      ("C", "Management believes the effects of uncorrected misstatements are immaterial, individually and in aggregate."),
      ("D", "Misstatements were intentionally created.")]),
    (61, "Post-Audit Responsibilities", "Subsequent discovery of facts existing at the date of the auditor's report refers to:",
     [("A", "Facts that become known to the auditor after the date of the auditor's report which, had they been known, might have caused amendment of the report."),
      ("B", "Normal transactions occurring in the subsequent year."),
      ("C", "Changes in tax laws enacted in subsequent years."),
      ("D", "New product launches in the subsequent period.")]),
    (62, "Post-Audit Responsibilities", "When facts are discovered after the financial statements have been issued that would have affected the report, the auditor should first:",
     [("A", "Immediately inform the public media."),
      ("B", "Discuss the matter with management and those charged with governance, and determine whether financial statements need amendment."),
      ("C", "Notify the PRC to cancel the CPA license."),
      ("D", "Sue the client for damages.")]),
    (63, "Post-Audit Responsibilities", "If management revises the financial statements after issuance, the auditor should:",
     [("A", "Refuse to audit the revision."),
      ("B", "Destroy the previous working papers."),
      ("C", "Perform audit procedures on the revision, review management's steps to inform users, and issue a new auditor's report."),
      ("D", "Issue a letter of comfort to banks.")]),
    (64, "Post-Audit Responsibilities", "If management refuses to take steps to prevent reliance on issued financial statements that contain material misstatements, the auditor should:",
     [("A", "Resign from next year's audit without comment."),
      ("B", "Notify management and those charged with governance that the auditor will take action to prevent future reliance on the audit report."),
      ("C", "Alter the working papers secretly."),
      ("D", "Pay damages to affected third parties.")]),
    (65, "Post-Audit Responsibilities", "Omitted audit procedures discovered after the report has been issued require the auditor to:",
     [("A", "Ignore them because the audit is closed."),
      ("B", "Assess whether the omitted procedures currently impair the auditor's ability to support the issued opinion."),
      ("C", "Automatically recall the audit report in all circumstances."),
      ("D", "Re-perform the entire audit from the beginning.")]),
    (66, "Post-Audit Responsibilities", "If omitted procedures impair the current ability to support an opinion and users are relying on the report, the auditor should:",
     [("A", "Advise the client to liquidate."),
      ("B", "Promptly perform the omitted procedures or alternative procedures."),
      ("C", "Write an apology to regulatory authorities."),
      ("D", "Disclaim the previous opinion without further testing.")]),
    (67, "Post-Audit Responsibilities", "The final review phase of the audit includes:",
     [("A", "Initial client acceptance interviews"),
      ("B", "Assessment of inherent risk"),
      ("C", "Final analytical procedures, review of working papers, and evaluation of overall findings"),
      ("D", "Establishing initial materiality thresholds")]),
    (68, "Post-Audit Responsibilities", "Analytical procedures performed near the end of the audit are intended to:",
     [("A", "Replace tests of details."),
      ("B", "Form an overall conclusion as to whether the financial statements are consistent with the auditor's understanding of the entity."),
      ("C", "Determine the audit fee."),
      ("D", "Provide beginning balances for next year.")]),
    (69, "Post-Audit Responsibilities", "An engagement quality control review (EQCR) is performed:",
     [("A", "After the audit report is published and distributed."),
      ("B", "Before the audit report is issued, for audits of listed entities and other eligible engagements."),
      ("C", "By the client's internal auditors."),
      ("D", "By government tax inspectors.")]),
    (70, "Post-Audit Responsibilities", "The communication of audit matters to those charged with governance (PSA 260) includes:",
     [("A", "Significant difficulties encountered during the audit, disagreements with management, and uncorrected misstatements."),
      ("B", "Confidential passwords of audit team members."),
      ("C", "Detailed copies of all audit working papers."),
      ("D", "Personal tax advice for board members.")])
]

chapter11 = {
    "id": "at-11",
    "code": "AT-11",
    "title": "Audit Completion Stage and Post-Audit Responsibilities",
    "description": "Subsequent events (PSA 560), going concern considerations (PSA 570), related party transactions (PSA 550), management representation letters (PSA 580), subsequent discovery of facts, and communication with governance (PSA 260).",
    "objectives": [
        "Subsequent Events",
        "Going Concern",
        "Related Parties",
        "Written Representations",
        "Post-Audit Responsibilities"
    ],
    "totalQuestions": 70,
    "questions": []
}

for num, obj, qtext, opts in at11_raw:
    correct = at11_answers[num]
    expl = at11_explanations.get(num, f"Suggested Answer: {correct}. In accordance with PSA 560, PSA 570, PSA 550, and PSA 580.")
    chapter11["questions"].append({
        "id": f"at11-{num}",
        "number": num,
        "chapterId": "at-11",
        "chapterCode": "AT-11",
        "chapterTitle": "Audit Completion Stage and Post-Audit Responsibilities",
        "objective": obj,
        "question": qtext,
        "options": [{"key": k, "text": t} for k, t in opts],
        "correctAnswer": correct,
        "explanation": expl
    })

with open("src/data/chapters/at11.ts", "w", encoding="utf-8") as f:
    f.write(f"import {{ Chapter }} from '../../types/quiz';\n\nexport const chapter11: Chapter = {json.dumps(chapter11, indent=2)};\n")

print("Created at11.ts with 70 questions")
