#!/usr/bin/env python3
import json

at06_answers = {
    1: 'D', 2: 'D', 3: 'A', 4: 'C', 5: 'A', 6: 'C', 7: 'B', 8: 'A', 9: 'C', 10: 'C',
    11: 'B', 12: 'B', 13: 'A', 14: 'A', 15: 'C', 16: 'A', 17: 'C', 18: 'A', 19: 'D', 20: 'C',
    21: 'B', 22: 'A', 23: 'B', 24: 'D', 25: 'C', 26: 'D', 27: 'A', 28: 'A', 29: 'B', 30: 'C',
    31: 'B', 32: 'B', 33: 'D', 34: 'B', 35: 'B', 36: 'B', 37: 'B', 38: 'D', 39: 'B', 40: 'C',
    41: 'B', 42: 'B', 43: 'C', 44: 'A', 45: 'D', 46: 'C', 47: 'A', 48: 'A', 49: 'A', 50: 'A',
    51: 'A', 52: 'B', 53: 'C', 54: 'C', 55: 'C', 56: 'D', 57: 'B', 58: 'D', 59: 'C', 60: 'B'
}

at06_explanations = {
    1: "The auditor's responsibility is to design the audit to provide reasonable assurance of detecting material misstatements in the financial statements. These misstatements may emanate from: (4) Error, (5) Fraud, and (6) Noncompliance with laws and regulations.",
    12: "Error is unintentional while fraud is intentional.",
    18: "There are three fraud risk factors: 1. Incentives or pressure, 2. Opportunity, 3. Attitudes or rationalizations. Choice A falls under the first fraud risk factor. Providing incentives based on income can lead to pressure in the work environment thus increases the inherent risk.",
    20: "Several subsidiaries can cause an organization to complicate transaction with related parties.",
    21: "Fraud is harder to detect than errors because fraud may involve sophisticated and carefully organized schemes designed to conceal it.",
    24: "Choices A, B, and C are examples of fraud. Error is an unintentional mistake.",
    36: "Transactions not recorded is more difficult as there would be no evidence of its existence.",
    37: "Fraudulent financial reporting usually has something to do with overstating revenues and assets.",
    38: "Automated accounting systems usually lack transaction trail and does not necessarily increase the risk of fraud or error.",
    39: "All of the choices provided pertain to red flags of misstated financial statements, poor internal control structure however does not necessarily mean that the financial statements are materially misstated.",
    44: "There are three fraud risk factors: 1. Incentives or pressure, 2. Opportunity, 3. Attitudes or rationalizations.",
    51: "Fraud, regardless of the amount, should be reported to the audit committee."
}

at06_raw = [
    (1, "Errors and Fraud", "Material misstatements may emanate from all of the following except:",
     [("A", "Fraud"), ("B", "Error"), ("C", "Noncompliance with laws and regulations"), ("D", "Inadequacy of accounting records")]),
    (2, "Errors and Fraud", "Which of the following factors is most important concerning an auditor's responsibility to detect errors and fraud?",
     [("A", "The susceptibility of the accounting records to intentional manipulations, alterations, and the misapplication of accounting principles."),
      ("B", "The probability that unreasonable accounting estimates result from unintentional bias or intentional attempts to misstate the financial statements."),
      ("C", "The possibility that management fraud, defalcations, and the misappropriation of assets may indicate the existence of illegal acts."),
      ("D", "The risk that mistakes, falsifications, and omissions may cause the financial statements to contain material misstatements.")]),
    (3, "Errors and Fraud", "Which of the following statements best describes an auditor's responsibility regarding misstatements?",
     [("A", "An auditor should obtain reasonable assurance that the financial statements taken as a whole are free from material misstatement, whether caused by fraud or error."),
      ("B", "An auditor should obtain absolute assurance that material misstatements in the financial statements will be detected."),
      ("C", "An auditor is responsible to detect material errors but has no responsibility to detect material fraud that is concealed through employee collusion or management override of internal control."),
      ("D", "An auditor's failure to detect a material misstatement resulting from fraud is an indication of noncompliance with the requirements of PSAs.")]),
    (4, "Errors and Fraud", "The responsibility for the detection and prevention of errors, fraud and noncompliance with laws and regulations rests with the:",
     [("A", "Auditor"), ("B", "Client's legal counsel"), ("C", "Client management"), ("D", "Internal auditor")]),
    (5, "Errors and Fraud", "The responsibility for adopting sound accounting policies, maintaining adequate internal control, and making fair representation in the financial statement rests:",
     [("A", "With the management."), ("B", "With the independent auditor."), ("C", "Equally with management and the auditor."), ("D", "With the internal audit department.")]),
    (6, "Errors and Fraud", "The management responsibility to detect and prevent fraud and error is accomplished by:",
     [("A", "Implementing adequate quality control system."), ("B", "Having an annual audit of financial statements."), ("C", "Implementing adequate accounting and internal control system."), ("D", "Issuing a representation letter to the auditor.")]),
    (7, "Errors and Fraud", "Which of the following statements best describes the auditor's responsibility regarding the detection of material errors and frauds?",
     [("A", "The auditor is responsible for the failure to detect material errors and frauds only when such failure results from the misapplication of PSA."),
      ("B", "The audit should be designed to provide reasonable assurance that material errors and frauds will be detected."),
      ("C", "The auditor is responsible for the failure to detect material errors and fraud only when the auditor fails to confirm receivables or observe inventories."),
      ("D", "Extended auditing procedures are required to detect unrecorded transactions even if there is no evidence that material errors and frauds may exist.")]),
    (8, "Errors and Fraud", "Which of the following statements describes why an audit that is properly planned and performed in accordance with PSAs may not detect a material misstatement resulting from fraud?",
     [("A", "Fraud may involve carefully laid out plans of concealment."),
      ("B", "The auditor did not consider audit risk factors for accounts having pervasive effects on the financial statements."),
      ("C", "An audit is designed to provide reasonable assurance of detecting misstatements arising from errors, but there is no similar responsibility concerning material misstatements resulting from fraud."),
      ("D", "The risk of the auditor not detecting a material misstatement resulting from employee fraud is greater than for management fraud.")]),
    (9, "Errors and Fraud", "The auditor's best defense when material misstatements in the financial statements are not uncovered in the audit is that",
     [("A", "The audit was conducted in accordance with generally accepted accounting principles."),
      ("B", "Client is guilty of contributory negligence."),
      ("C", "The audit was conducted in accordance with PSA."),
      ("D", "The financial statements are client's responsibility.")]),
    (10, "Errors and Fraud", "The following statements relate to the auditor's responsibility for the detection of errors and fraud:\nI. Due to the inherent limitations of the audit, there is a possibility that material misstatements in the financial statements may not be detected.\nII. The subsequent discovery of material misstatement of the financial information resulting from fraud or error does not, in itself, indicate that the auditor failed to follow the basic principles and essential procedures of an audit.\nWhich is/are correct?",
     [("A", "I only."), ("B", "II only."), ("C", "I and II."), ("D", "None of the foregoing.")]),
    (11, "Errors and Fraud", "An intentional act by one or more individuals among management, employees, or third parties which results in misrepresentation of financial statements refers to:",
     [("A", "Error"), ("B", "Fraud"), ("C", "Noncompliance"), ("D", "Illegal acts")]),
    (12, "Errors and Fraud", "The factor which distinguishes an error from fraud is:",
     [("A", "Materiality"), ("B", "Intent"), ("C", "Whether it is a peso amount or a process."), ("D", "Whether it is caused by the auditor or the client.")]),
    (13, "Errors and Fraud", "Which of the following statements is correct regarding errors and fraud?",
     [("A", "An error is unintentional, whereas fraud is intentional."),
      ("B", "Frauds occur more often than errors in financial statements."),
      ("C", "Errors are always fraud and frauds are always errors."),
      ("D", "Auditors have more responsibility for finding fraud than errors.")]),
    (14, "Errors and Fraud", "In the context of financial statement presentation, fraud occurs when",
     [("A", "A misstatement is made and there is both knowledge of its falsity and the intent to deceive."),
      ("B", "A misstatement is made and there is knowledge of its falsity but no intent to deceive."),
      ("C", "The auditor fails to comply with PSA."),
      ("D", "The auditor has an absence of reasonable care in the performance of the audit.")]),
    (15, "Errors and Fraud", "Which of the following best identifies the two types of fraud?",
     [("A", "Theft of assets and employee fraud."),
      ("B", "Misappropriation of asset and defalcation."),
      ("C", "Management fraud and employee fraud."),
      ("D", "Fraudulent financial reporting and management fraud.")]),
    (16, "Errors and Fraud", "Fraudulent financial reporting is often called:",
     [("A", "Management fraud"), ("B", "Defalcation"), ("C", "Misappropriation of assets"), ("D", "Employee fraud")]),
    (17, "Errors and Fraud", "Fraudulent financial reporting is most likely to be committed by the:",
     [("A", "Line employees of the company"),
      ("B", "Outside members of the company's board of directors"),
      ("C", "Company's management"),
      ("D", "Company's auditors")]),
    (18, "Errors and Fraud", "The risk of fraudulent financial reporting increases in the presence of:",
     [("A", "Incentive systems based on operating income."),
      ("B", "Improved control systems."),
      ("C", "Substantial increase in sales."),
      ("D", "Frequent changes in suppliers.")]),
    (19, "Errors and Fraud", "Fraudulent financial reporting involves intentional misstatements including omissions of amounts or disclosures in financial statements to deceive financial statement users. It may be accomplished in a number of ways, including",
     [("A", "Embezzling receipts"),
      ("B", "Stealing physical assets or intellectual property."),
      ("C", "Using an entity's assets for personal use."),
      ("D", "Manipulation, falsification, or alteration of accounting records or supporting documentation from which the financial statements are prepared.")]),
    (20, "Errors and Fraud", "Which of the following might be considered a \"red flag\" indicating the likelihood of fraud in a large manufacturing company with several subsidiaries?",
     [("A", "The existence of a subsidiary."),
      ("B", "A consistent record of above average return on investment for all subsidiaries."),
      ("C", "Complex sales transactions and transfers of funds between affiliated companies."),
      ("D", "Use of separate bank accounts for payrolls by each subsidiary.")]),
    (21, "Errors and Fraud", "Which of the following statements is true?",
     [("A", "It is usually easier for the auditor to uncover fraud than errors."),
      ("B", "It is usually easier for the auditor to uncover errors than fraud."),
      ("C", "It is usually equally difficult for the auditor to uncover errors or fraud."),
      ("D", "None of the foregoing is true.")]),
    (22, "Errors and Fraud", "Which of the following statements is not true?",
     [("A", "It is usually easier for the auditor to uncover fraud than errors."),
      ("B", "It is usually easier for the auditor to uncover errors than fraud."),
      ("C", "The auditor's responsibility for the detection of fraud and error is ordinarily the same."),
      ("D", "Usually, the auditor designs procedures to uncover fraud or error that could materially affect the financial statements.")]),
    (23, "Errors and Fraud", "In comparing management fraud with employee fraud, the auditor's risk of failing to discover the fraud is:",
     [("A", "Greater for management fraud because managers are inherently smarter than employees."),
      ("B", "Greater for management fraud because of management's ability to override existing internal controls."),
      ("C", "Greater for employee fraud because of the higher crime rate among blue collar workers."),
      ("D", "Greater for employee fraud because of the larger number of employees in the organization.")]),
    (24, "Errors and Fraud", "Which of the following is an example of an error?",
     [("A", "Defalcation."),
      ("B", "Suppression or omission of the effects of transactions from the records or documents."),
      ("C", "Recording of transactions without substance."),
      ("D", "Misapplication of accounting policies.")]),
    (25, "Errors and Fraud", "Which of the following is an \"error\" as distinguished from \"fraud\"?",
     [("A", "Embezzlement of company's fund."),
      ("B", "Window dressing."),
      ("C", "Clerical mistakes in processing of transactions."),
      ("D", "Lapping.")]),
    (26, "Errors and Fraud", "Which of the following could be an example of fraud?",
     [("A", "Mistakes in the application of the accounting principles."),
      ("B", "Clerical errors in accounting data underlying the financial statements."),
      ("C", "Misinterpretation of facts that existed when financial statements are prepared."),
      ("D", "Misappropriation of assets or group of assets.")]),
    (27, "Errors and Fraud", "Which of the following statements best describes an auditor's responsibility to detect errors and fraud?",
     [("A", "An auditor should assess the risk that errors and fraud may cause the financial statements to contain material misstatements and should design the audit to provide reasonable assurance of detecting errors and fraud that are material to the financial statements."),
      ("B", "An auditor is responsible to detect material errors, but has no responsibility to detect material fraud that are concealed through employee collusion or management override of the internal control structure."),
      ("C", "An auditor has no responsibility to detect errors and fraud unless analytical procedures or tests of transactions identify conditions causing a reasonably prudent auditor to suspect that the financial statements were materially misstated."),
      ("D", "An auditor has no responsibility to detect errors and fraud because an auditor is not an insurer and an audit does not constitute a guarantee.")]),
    (28, "Errors and Fraud", "An auditor should recognize that the application of auditing procedures may produce evidential matter indicating the possibility of errors or fraud and therefore should:",
     [("A", "Plan and perform the engagement with an attitude of professional skepticism."),
      ("B", "Not depend on internal accounting control features that are designed to prevent or detect errors or fraud."),
      ("C", "Design audit tests to detect unrecorded transactions."),
      ("D", "Extend the work to audit most recorded transactions and records of an entity.")]),
    (29, "Errors and Fraud", "\"The auditor should not assume that management is dishonest, but the possibility of dishonesty must be considered.\" This is an example of:",
     [("A", "Unprofessional behavior."),
      ("B", "An attitude of professional skepticism."),
      ("C", "Due diligence."),
      ("D", "Reasonable assurance.")]),
    (30, "Errors and Fraud", "Professional skepticism dictates that when management makes a statement to the auditors, the auditors should",
     [("A", "Require that the statement be out in writing."),
      ("B", "Disregard the statement because it ranks low of the evidence quality scale."),
      ("C", "Corroborate evidence with other supporting documentation whenever possible."),
      ("D", "Believe on the statement in order to maintain the professional client-auditor relationship.")]),
    (31, "Errors and Fraud", "If an auditor conducted an audit in accordance with auditing standards, which of the following would the auditor likely detect?",
     [("A", "Unrecorded transactions."),
      ("B", "Errors in postings of recorded transactions."),
      ("C", "Counterfeit signatures on paid checks."),
      ("D", "Fraud involving collusion.")]),
    (32, "Errors and Fraud", "Which of the following statements is incorrect?",
     [("A", "The responsibility for the prevention and detection of fraud and error rests with management."),
      ("B", "The auditor is not and cannot be held responsible for the detection of fraud and error."),
      ("C", "In planning an audit, the auditor should assess the risk that fraud or error may cause the financial statements to contain material misstatements."),
      ("D", "The risk of not detecting a material fraud is higher than the risk of not detecting a material misstatement arising from error.")]),
    (33, "Errors and Fraud", "Which of the following statements about fraud and error is incorrect?",
     [("A", "The auditor is not and cannot be held responsible for the prevention of fraud and error."),
      ("B", "The responsibility for the prevention and detection of fraud and error rests with the management."),
      ("C", "The auditor should plan and perform the audit with an attitude of professional skepticism, recognizing that conditions or events may be found that fraud or error may exist."),
      ("D", "The likelihood of detecting fraud is ordinarily higher than that of detecting error.")]),
    (34, "Errors and Fraud", "Which of the following is not an assurance that the auditors give to the parties who rely on the financial statements?",
     [("A", "Auditors know how the amounts and disclosures in the financial statements were produced."),
      ("B", "Auditors give assurance that the financial statements are accurate."),
      ("C", "Auditors gathered enough evidence to provide a reasonable basis for forming an opinion."),
      ("D", "If the evidence allows the auditors to do so, auditors give assurance in the form of opinion, as to whether the financial statements taken as a whole are fairly presented in conformity with PFRS.")]),
    (35, "Errors and Fraud", "The risk of not detecting material misstatement resulting from fraud is greater than the risk of not detecting a material misstatement arising from error because",
     [("A", "The auditor designs only procedures to detect material error but no procedures are designed to detect material fraud."),
      ("B", "Fraud ordinarily involves acts designed to conceal it, such as collusion, forgery, or deliberate failure to record transactions."),
      ("C", "The professional standards do not require the auditor to discover information that is indicative of fraud."),
      ("D", "It is the responsibility of the management to detect fraud and the auditor's responsibility is confined only to the detection of material errors.")]),
    (36, "Errors and Fraud", "The most difficult type of misstatement to detect is fraud based on:",
     [("A", "Recorded transactions."),
      ("B", "Unrecorded transactions."),
      ("C", "Recorded transactions in subsidiaries."),
      ("D", "Related party receivable.")]),
    (37, "Errors and Fraud", "Which of the following is most likely to be presumed to represent fraud risk on an audit?",
     [("A", "Capitalization of repairs and maintenance into the property, plant and equipment asset account."),
      ("B", "Improper revenue recognition."),
      ("C", "Improper interest expense accrual."),
      ("D", "Introduction of significant new products.")]),
    (38, "Errors and Fraud", "Which of the following conditions or events would least likely increased risk of fraud or error?",
     [("A", "Questions with respect to competence or integrity of management."),
      ("B", "Unusual pressures within the entity."),
      ("C", "Unusual transactions."),
      ("D", "Lack of transaction trail.")]),
    (39, "Errors and Fraud", "Which of the following would be least likely to suggest to an auditor that the client's financial statements are materially misstated?",
     [("A", "There are numerous delays in preparing timely internal financial reports."),
      ("B", "Management does not correct internal control structure weaknesses that it knows about."),
      ("C", "Differences are reflected in the customer's confirmation replies."),
      ("D", "There have been two new controllers this year.")]),
    (40, "Errors and Fraud", "Which of the following conditions identified during fieldwork of an audit is most likely to affect the auditor's assessment of the risk of misstatement due to fraud?",
     [("A", "Checks for significant amounts outstanding at year-end."),
      ("B", "Computer-generated documents."),
      ("C", "Missing documents."),
      ("D", "Year-end adjusting journal entries.")]),
    (41, "Fraud Risk Factors", "When obtaining an understanding of the entity and its environment, including its internal control, the auditor may identify events or conditions that indicate an incentive or pressure to commit fraud or provide an opportunity to commit fraud. Such events or conditions are referred to as:",
     [("A", "Fraud conditions"), ("B", "Fraud risk factors"), ("C", "Fraudulent activities"), ("D", "Fraud environment")]),
    (42, "Fraud Risk Factors", "Which of the following best describes what is meant by the term \"fraud risk factor\"?",
     [("A", "Factor whose presence indicates that the risk of fraud is high."),
      ("B", "Factor whose presence often has been observed in circumstances where fraud has occurred."),
      ("C", "Factor whose presence require modification of planned audit procedures."),
      ("D", "Factor that indicates internal control weaknesses.")]),
    (43, "Fraud Risk Factors", "Which of the following characteristics most likely would heighten an auditor's concern about the risk of intentional manipulation of financial statements?",
     [("A", "Turnover of senior accounting personnel is low."),
      ("B", "Insiders recently purchased additional shares of the entity's stock."),
      ("C", "Management places substantial emphasis on meeting earnings projections."),
      ("D", "The rate of change in the entity's industry is slow.")]),
    (44, "Fraud Risk Factors", "Individuals who commit fraud are ordinarily able to rationalize the act and also have an:\nIncentive | Opportunity\nA. Yes | Yes\nB. Yes | No\nC. No | Yes\nD. No | No",
     [("A", "Yes, Yes"), ("B", "Yes, No"), ("C", "No, Yes"), ("D", "No, No")]),
    (45, "Fraud Risk Factors", "Which of the following conditions are generally present when misstatements due to fraud occur?\nI. Incentive or pressure\nII. Perceived opportunity\nIII. Rationalization",
     [("A", "I and II only"), ("B", "II and III only"), ("C", "I and III only"), ("D", "I, II, and III")]),
    (46, "Fraud Risk Factors", "Individuals may have an incentive or be under pressure to commit fraud, or circumstances may provide an opportunity. Also, certain individuals may have an attitude, character, or set of values that allow them to rationalize fraud. The auditor's concern about the risk of material misstatement is least likely to be increased if management",
     [("A", "Is interested in inappropriate means of minimizing reported earnings for tax purposes."),
      ("B", "Commits to unduly aggressive forecasts."),
      ("C", "Operating and financing decisions are made by numerous individuals."),
      ("D", "Has an excessive interest in increasing the entity's share price through application of unduly aggressive accounting practices.")]),
    (47, "Fraud Risk Factors", "Which of the following circumstances would least likely cause an auditor to consider whether material misstatements exist in an entity's financial statements?",
     [("A", "Management is dominated by several individuals."),
      ("B", "The industry in which the entity operates is declining."),
      ("C", "There is inadequate working capital due to declining profit."),
      ("D", "Supporting records that should be readily available are frequently not produced when requested.")]),
    (48, "Fraud Risk Factors", "The following are examples of fraud risk factors relating to misstatements arising from misappropriation of assets except:",
     [("A", "Recurring negative cash flows from operating activities while reporting earnings and earnings growth."),
      ("B", "Inadequate physical safeguards over cash, investments, inventory, or fixed assets."),
      ("C", "Inadequate segregation of duties or independent checks."),
      ("D", "Adverse relationship between the entity and employees with access to cash or other assets susceptible to theft created by recent changes made to employee compensation or benefit plans.")]),
    (49, "Fraud Risk Factors", "If an auditor believes that material errors or fraud exist, the auditor should",
     [("A", "Consider the implications and discuss the matter with appropriate levels of management."),
      ("B", "Make the investigation necessary to determine whether errors or fraud have in fact occurred."),
      ("C", "Request that management investigate whether errors or fraud have in fact occurred."),
      ("D", "Consider whether errors or fraud were the result of employee's failure to comply with specific controls.")]),
    (50, "Fraud Risk Factors", "When the auditor believes a misstatement is or may be the result of fraud but that the effect of the misstatements is not material to the financial statements, which of the following is required?",
     [("A", "Consider the implications for other aspects of the audit."),
      ("B", "Resign from the audit."),
      ("C", "Commence a fraud examination."),
      ("D", "Contact regulatory authorities.")]),
    (51, "Fraud Risk Factors", "What is an auditor's responsibility who discovers that management is involved in a potentially immaterial fraud?",
     [("A", "Report the fraud to the audit committee."),
      ("B", "Report the fraud to the SEC."),
      ("C", "Report the fraud to a level of management at least one level below those involved in the fraud."),
      ("D", "Determine that the amounts involved are immaterial, and if so, there is no reporting responsibility.")]),
    (52, "Fraud Risk Factors", "The following statements relate to communication of misstatements resulting from fraud to management and to those charged with governance. Which is false?",
     [("A", "The auditor need to bring to the attention of those charged with governance any material weaknesses in internal control related to the prevention and detection of fraud."),
      ("B", "The auditor need not bring to the attention of those charged with governance any material weaknesses in internal control related to the prevention and detection of fraud."),
      ("C", "If the auditor has identified a fraud, whether or not it results in a material misstatement in the financial statements, the auditor should communicate these matters to the appropriate level of management on a timely basis, and consider the need to report such matters to those charged with governance."),
      ("D", "If the auditor has obtained evidence that indicates that fraud may exist, even if the potential effect on the financial statements would not be material, the auditor should communicate these matters to the appropriate level of management on a timely basis, and consider the need to report such matters to those charged with governance.")]),
    (53, "Noncompliance", "These are acts of omission or commission by the entity being audited, either intentional or unintentional, which are contrary to the prevailing laws and regulations.",
     [("A", "Fraud"), ("B", "Misappropriation"), ("C", "Noncompliance"), ("D", "Defalcation")]),
    (54, "Noncompliance", "When the auditor knows that a noncompliance with laws and regulation has occurred, the auditor must:",
     [("A", "Issue an adverse opinion."),
      ("B", "Withdraw from the engagement."),
      ("C", "Consider the effects on the financial statements, including the adequacy of disclosure."),
      ("D", "Report the matter to the proper government authorities.")]),
    (55, "Noncompliance", "Which of the following is the auditor least likely to do when aware of a noncompliance?",
     [("A", "Discuss the matter with the client's legal counsel."),
      ("B", "Obtain evidence about the potential effect of the noncompliance on the financial statements."),
      ("C", "Contact the local law enforcement officials regarding potential criminal wrongdoing."),
      ("D", "Consider the impact of the noncompliance on the relationship with the company's management.")]),
    (56, "Noncompliance", "Which of the following statements about noncompliance is incorrect?",
     [("A", "An audit in accordance with PSA cannot be expected to detect all noncompliance with laws and regulations."),
      ("B", "It is the management's responsibility to ensure that entity's operations are conducted in accordance with laws and regulations."),
      ("C", "An auditor cannot be held responsible for preventing noncompliance."),
      ("D", "The determination of whether a particular act constitutes noncompliance is ultimately based on the judgment of the auditor.")]),
    (57, "Noncompliance", "Which of the following statements best describes why the auditor's examination cannot reasonably be expected to bring all acts of noncompliance with existing laws and regulations by the client to the auditor's attention?",
     [("A", "Acts of noncompliance by clients often relates to accounting aspects rather than operating aspects."),
      ("B", "Noncompliance may involve conduct designed to conceal it, such as collusion, forgery, deliberate failure to record transactions, senior management override of controls, or intentional misrepresentations being made to the auditor."),
      ("C", "Noncompliance may be perpetrated by the only person in the client's organization with access to both assets and the accounting records."),
      ("D", "The client's internal control may be so strong that the auditor performs only minimal substantive testing.")]),
    (58, "Noncompliance", "Which of the following circumstances is not an indication of possible noncompliance?",
     [("A", "Payment of fines or penalties."),
      ("B", "Payment for unspecified services to consultants, related parties, or government employees."),
      ("C", "Purchasing at prices significantly above or below market price."),
      ("D", "Payment for goods or services to the country from which the goods or services originated.")]),
    (59, "Noncompliance", "Which of the following conditions would least likely indicate the occurrence of noncompliance?",
     [("A", "Investigation by government agencies."),
      ("B", "Payments without proper documentation."),
      ("C", "Purchasing a real property for a price that is significantly higher than the seller's book value."),
      ("D", "Existence of an accounting system which fails to provide an adequate audit trail or sufficient evidence.")]),
    (60, "Noncompliance", "When the auditor becomes aware of information concerning a possible instance of noncompliance, the auditor should obtain an understanding of:\nThe nature of the act | The circumstances in which it has occurred | Sufficient other information to evaluate the possible effect\nA. No | No | Yes\nB. Yes | Yes | Yes\nC. Yes | No | No\nD. No | Yes | No",
     [("A", "No, No, Yes"), ("B", "Yes, Yes, Yes"), ("C", "Yes, No, No"), ("D", "No, Yes, No")])
]

chapter06 = {
    "id": "at-06",
    "code": "AT-06",
    "title": "Consideration of Fraud, Error, and Noncompliance",
    "description": "The auditor's responsibilities relating to fraud (PSA 240), errors vs. fraud, fraud risk triangle (incentive, opportunity, rationalization), and consideration of laws and regulations (PSA 250).",
    "objectives": [
        "Errors and Fraud",
        "Fraud Risk Factors",
        "Noncompliance"
    ],
    "totalQuestions": 60,
    "questions": []
}

for num, obj, qtext, opts in at06_raw:
    correct = at06_answers[num]
    expl = at06_explanations.get(num, f"Suggested Answer: {correct}. In accordance with PSA 240 (The Auditor's Responsibilities Relating to Fraud) and PSA 250 (Consideration of Laws and Regulations).")
    chapter06["questions"].append({
        "id": f"at06-{num}",
        "number": num,
        "chapterId": "at-06",
        "chapterCode": "AT-06",
        "chapterTitle": "Consideration of Fraud, Error, and Noncompliance",
        "objective": obj,
        "question": qtext,
        "options": [{"key": k, "text": t} for k, t in opts],
        "correctAnswer": correct,
        "explanation": expl
    })

with open("src/data/chapters/at06.ts", "w", encoding="utf-8") as f:
    f.write(f"import {{ Chapter }} from '../../types/quiz';\n\nexport const chapter06: Chapter = {json.dumps(chapter06, indent=2)};\n")

print("Created at06.ts with 60 questions")
