#!/usr/bin/env python3
import json

at13_answers = {
    1: 'B', 2: 'C', 3: 'A', 4: 'C', 5: 'D', 6: 'B', 7: 'C', 8: 'A', 9: 'C', 10: 'D',
    11: 'B', 12: 'A', 13: 'B', 14: 'C', 15: 'C', 16: 'C', 17: 'B', 18: 'B', 19: 'A', 20: 'D',
    21: 'B', 22: 'C', 23: 'D', 24: 'B', 25: 'A', 26: 'A', 27: 'C', 28: 'D', 29: 'D', 30: 'B',
    31: 'D', 32: 'B', 33: 'A', 34: 'C', 35: 'D', 36: 'B', 37: 'A', 38: 'D', 39: 'B', 40: 'D',
    41: 'A', 42: 'B', 43: 'B', 44: 'C', 45: 'A', 46: 'A', 47: 'C', 48: 'C', 49: 'D', 50: 'C'
}

at13_explanations = {
    1: "A special purpose framework is a financial reporting framework designed to meet the financial information needs of specific users (PSA 800).",
    2: "Examples of special purpose frameworks include cash receipts and disbursements basis, tax basis, regulatory reporting provisions, or contractual agreements.",
    16: "In a review engagement (PSRE 2400/2410), the practitioner provides moderate (limited) assurance expressed in negative form ('nothing has come to our attention...').",
    26: "In an agreed-upon procedures engagement (PSRS 4400), the auditor provides no assurance; only factual findings are reported, and the report is restricted to the specified parties who agreed to the procedures.",
    36: "In a compilation engagement (PSRS 4410), the accountant uses accounting expertise to collect, classify, and summarize financial data without providing any assurance on the statements."
}

at13_raw = [
    (1, "Special Purpose Frameworks & PSA 800", "A special purpose framework is defined under PSA 800 as:",
     [("A", "PFRS for listed companies"),
      ("B", "A financial reporting framework designed to meet the financial information needs of specific users"),
      ("C", "US GAAP exclusively"),
      ("D", "Any framework chosen without management approval")]),
    (2, "Special Purpose Frameworks & PSA 800", "Which of the following is an example of a special purpose framework?",
     [("A", "Full Philippine Financial Reporting Standards (PFRS)"),
      ("B", "PFRS for Small and Medium-sized Entities (PFRS for SMEs)"),
      ("C", "A cash receipts and disbursements basis of accounting for tax or creditor purposes"),
      ("D", "International Accounting Standards (IAS) for public companies")]),
    (3, "Special Purpose Frameworks & PSA 800", "An auditor's report on financial statements prepared in accordance with a special purpose framework shall include an Emphasis of Matter paragraph that:",
     [("A", "Alerts users of the auditor's report that the financial statements are prepared in accordance with a special purpose framework."),
      ("B", "States that the financial statements are totally inaccurate."),
      ("C", "Disclaims any opinion on the statements."),
      ("D", "Certifies the future profitability of the client.")]),
    (4, "Special Purpose Frameworks & PSA 800", "Under PSA 805, an audit of a single financial statement or of a specific element, account or item:",
     [("A", "Is prohibited by the Board of Accountancy."),
      ("B", "Can only be performed by government auditors."),
      ("C", "Is permitted, but the auditor must apply all PSAs relevant to the audit as necessary."),
      ("D", "Requires an adverse opinion on the complete set of financial statements.")]),
    (5, "Special Purpose Frameworks & PSA 800", "If an auditor undertakes an engagement to audit a single financial statement (e.g., balance sheet only) in conjunction with an audit of the complete set, the auditor shall:",
     [("A", "Issue a single combined report only."),
      ("B", "Disclaim the single statement."),
      ("C", "Refuse the assignment."),
      ("D", "Issue a separate auditor's report and express an opinion for each engagement.")]),
    (6, "Special Purpose Frameworks & PSA 800", "Can an auditor express an unmodified opinion on a specific element of a financial statement when an adverse opinion was expressed on the complete set?",
     [("A", "Yes, in all situations without restriction."),
      ("B", "Only if permitted by law, the element does not constitute a major portion, and the report is not published together with the adverse audit report."),
      ("C", "No, never under any circumstance."),
      ("D", "Only if the client pays a penalty.")]),
    (7, "Engagements to Report on Summary Financial Statements", "Under PSA 810, summary financial statements are defined as:",
     [("A", "A complete set of financial statements with all disclosures."),
      ("B", "Budgets and cash flow projections for the coming year."),
      ("C", "Historical financial information derived from financial statements but containing less detail than the complete financial statements."),
      ("D", "Unaudited quarterly tax returns.")]),
    (8, "Engagements to Report on Summary Financial Statements", "An auditor can only accept an engagement to report on summary financial statements under PSA 810 if:",
     [("A", "The auditor has been engaged to conduct an audit in accordance with PSAs of the financial statements from which the summary statements are derived."),
      ("B", "The summary statements have been prepared by an external bookkeeping service."),
      ("C", "The company is a sole proprietorship."),
      ("D", "The auditor has not audited the historical financial statements.")]),
    (9, "Engagements to Report on Summary Financial Statements", "The auditor's opinion on summary financial statements states whether the summary financial statements are:",
     [("A", "Completely free of all omissions."),
      ("B", "Guaranteed to be accurate in every detail."),
      ("C", "Consistent, in all material respects, with the audited financial statements, in accordance with the applied criteria."),
      ("D", "Better than the original audited statements.")]),
    (10, "Engagements to Report on Summary Financial Statements", "If the auditor's report on the audited financial statements contained an adverse opinion or a disclaimer of opinion, the auditor's report on the summary statements shall:",
     [("A", "Express an unmodified opinion on the summary statements."),
      ("B", "Disregard the adverse opinion."),
      ("C", "Qualify the summary statements only."),
      ("D", "State that the auditor's report on the audited financial statements contained an adverse opinion or disclaimer, and indicate the effect.")]),
    (11, "Review of Financial Statements", "A review of historical financial statements (PSRE 2400) provides what level of assurance?",
     [("A", "High, reasonable assurance"),
      ("B", "Moderate (limited) assurance"),
      ("C", "Absolute assurance"),
      ("D", "No assurance")]),
    (12, "Review of Financial Statements", "The negative assurance expressed in a review report states that:",
     [("A", "Nothing has come to the practitioner's attention that causes the practitioner to believe that the financial statements do not present fairly..."),
      ("B", "The financial statements are 100% certified accurate."),
      ("C", "We disclaim an opinion because no audit was performed."),
      ("D", "The practitioner guarantees all balances.")]),
    (13, "Review of Financial Statements", "The primary procedures performed in a review engagement consist of:",
     [("A", "Physical examination and confirmation of all assets."),
      ("B", "Inquiry and analytical procedures."),
      ("C", "100% substantive testing of all transactions."),
      ("D", "Search for unrecorded liabilities and observation of inventory count.")]),
    (14, "Review of Financial Statements", "A review engagement differs from an audit in that a review:",
     [("A", "Does not provide any basis for expressing an opinion or negative assurance."),
      ("B", "Requires a complete evaluation of internal control structure."),
      ("C", "Does not include obtaining an understanding of internal control, assessing fraud risk, tests of accounting records, or third-party confirmations."),
      ("D", "Is only performed for listed corporations.")]),
    (15, "Review of Financial Statements", "If a CPA is engaged to perform a review of interim financial statements of a public entity (PSRE 2410), the CPA must:",
     [("A", "Express an audit opinion on the interim statements."),
      ("B", "Confirm all trade receivables as of interim date."),
      ("C", "Perform inquiry, analytical procedures, and other review procedures to express a conclusion."),
      ("D", "Attend the mid-year inventory count.")]),
    (16, "Review of Financial Statements", "If during a review engagement, the practitioner becomes aware of a material departure from PFRS and management refuses to revise the financial statements, the practitioner should:",
     [("A", "Express an adverse audit opinion under PSA 705."),
      ("B", "Issue a clean review conclusion."),
      ("C", "Qualify the conclusion or give an adverse conclusion on the review report."),
      ("D", "Delete the affected notes.")]),
    (17, "Review of Financial Statements", "Can a CPA issue a review report if independence is impaired?",
     [("A", "Yes, if an Other Matter paragraph is added."),
      ("B", "No, a CPA must be independent to perform a review engagement."),
      ("C", "Yes, because a review provides only limited assurance."),
      ("D", "Yes, if disclosed in Note 1.")]),
    (18, "Review of Financial Statements", "The objective of a review of financial statements is to enable the practitioner to:",
     [("A", "Express an audit opinion on whether the financial statements are prepared in all material respects in accordance with PFRS."),
      ("B", "State whether, on the basis of procedures which do not provide all the evidence that would be required in an audit, anything has come to the practitioner's attention that causes the practitioner to believe that the financial statements are not prepared in accordance with framework."),
      ("C", "Compile the financial statements into professional presentation without verification."),
      ("D", "Provide tax compliance advice.")]),
    (19, "Review of Financial Statements", "Which standard governs review of historical financial statements for non-audit clients?",
     [("A", "PSRE 2400 (Revised)"), ("B", "PSA 700"), ("C", "PSRS 4400"), ("D", "PSAE 3400")]),
    (20, "Review of Financial Statements", "A review report does not include which of the following elements?",
     [("A", "Title indicating it is an independent practitioner's review report"),
      ("B", "Addressee"),
      ("C", "Description of procedures performed (inquiry and analytical procedures)"),
      ("D", "A statement that the examination was performed in accordance with Philippine Standards on Auditing (PSAs)")]),
    (21, "Assurance Engagements Other Than Audits or Reviews", "Under PSAE 3000 (Revised), an assurance engagement is an engagement in which a practitioner aims to:",
     [("A", "Provide bookkeeping and payroll processing."),
      ("B", "Obtain sufficient appropriate evidence in order to express a conclusion designed to enhance the degree of confidence of the intended users about the subject matter information."),
      ("C", "Represent the client before tax courts."),
      ("D", "Install new software hardware systems.")]),
    (22, "Assurance Engagements Other Than Audits or Reviews", "The two types of assurance engagement permitted under the Philippine Framework for Assurance Engagements are:",
     [("A", "Tax and non-tax engagements"),
      ("B", "Internal and external engagements"),
      ("C", "Reasonable assurance engagement and limited assurance engagement"),
      ("D", "Direct reporting and compilation engagements")]),
    (23, "Assurance Engagements Other Than Audits or Reviews", "In an attestation engagement (assertion-based):",
     [("A", "The practitioner measures or evaluates the underlying subject matter directly."),
      ("B", "No party is responsible for the subject matter."),
      ("C", "The report is provided orally only."),
      ("D", "The responsible party measures or evaluates the subject matter and provides subject matter information upon which the practitioner expresses a conclusion.")]),
    (24, "Assurance Engagements Other Than Audits or Reviews", "In a direct reporting engagement:",
     [("A", "The client writes the assurance report."),
      ("B", "The practitioner directly measures or evaluates the underlying subject matter and presents the resulting subject matter information in the assurance report."),
      ("C", "No evidence is gathered."),
      ("D", "The SEC directly signs the report.")]),
    (25, "Assurance Engagements Other Than Audits or Reviews", "Prospective financial information (PFI) under PSAE 3400 includes:",
     [("A", "Forecasts and projections"),
      ("B", "Prior year historical income statements"),
      ("C", "Current month bank statements"),
      ("D", "Audited balance sheets")]),
    (26, "Assurance Engagements Other Than Audits or Reviews", "A forecast is prospective financial information based on assumptions as to future events which management:",
     [("A", "Expects to take place as of the date the information is prepared (best-estimate assumptions)."),
      ("B", "Knows will definitely not take place."),
      ("C", "Assumes purely on hypothetical basis."),
      ("D", "Has copied from competitors.")]),
    (27, "Assurance Engagements Other Than Audits or Reviews", "A projection is prospective financial information based on:",
     [("A", "Historical figures without modification."),
      ("B", "Auditor's personal investment plans."),
      ("C", "Hypothetical assumptions about future events and management actions (what-if scenarios)."),
      ("D", "Tax rulings from the BIR.")]),
    (28, "Assurance Engagements Other Than Audits or Reviews", "When examining prospective financial information (PSAE 3400), the auditor shall not express an opinion on:",
     [("A", "Whether the assumptions provide a reasonable basis."),
      ("B", "Whether the PFI is properly prepared on the basis of assumptions."),
      ("C", "Whether presentation is informative."),
      ("D", "Whether the results forecasted will be achieved (because future events cannot be guaranteed).")]),
    (29, "Assurance Engagements Other Than Audits or Reviews", "Reports on the examination of prospective financial information must include:",
     [("A", "A statement of negative assurance regarding assumptions."),
      ("B", "A statement that prospective results may not be achieved."),
      ("C", "A warning that actual results are likely to be different from the forecast."),
      ("D", "All of the above.")]),
    (30, "Assurance Engagements Other Than Audits or Reviews", "An assurance engagement requires which five elements?",
     [("A", "Two parties, profit goal, contract, fees, and litigation guarantee"),
      ("B", "A three-party relationship, an appropriate subject matter, suitable criteria, sufficient appropriate evidence, and a written assurance report"),
      ("C", "Cash payment, bank guarantee, promissory note, stock certificate, and title deed"),
      ("D", "Auditor, tax collector, judge, bailiff, and lawyer")]),
    (31, "Agreed-Upon Procedures Engagements", "In an agreed-upon procedures engagement (PSRS 4400 Revised):",
     [("A", "The auditor provides reasonable assurance."),
      ("B", "The auditor provides limited assurance."),
      ("C", "The auditor expresses an audit opinion."),
      ("D", "The practitioner performs procedures agreed upon by the practitioner and engaging party, and reports factual findings without expressing an opinion or assurance.")]),
    (32, "Agreed-Upon Procedures Engagements", "The users of an agreed-upon procedures report evaluate for themselves:",
     [("A", "The auditor's salary."),
      ("B", "The procedures and findings reported by the practitioner and draw their own conclusions."),
      ("C", "Whether the practitioner violated criminal laws."),
      ("D", "The stock market valuation of the entity.")]),
    (33, "Agreed-Upon Procedures Engagements", "The distribution of an agreed-upon procedures report is:",
     [("A", "Restricted to those parties that have agreed to the procedures to be performed."),
      ("B", "Published in nationwide daily newspapers."),
      ("C", "Distributed freely to all prospective investors."),
      ("D", "Broadcast on public television.")]),
    (34, "Agreed-Upon Procedures Engagements", "Which of the following terms should not be used in describing procedures in an agreed-upon procedures engagement?",
     [("A", "Compare and vouch"),
      ("B", "Recalculate"),
      ("C", "Review, evaluate, or examine for fairness (terms that imply an audit or review)"),
      ("D", "Inspect shipping documents")]),
    (35, "Agreed-Upon Procedures Engagements", "A report on an agreed-upon procedures engagement shall state that:",
     [("A", "The procedures performed did not constitute an audit or review, and had additional procedures been performed, other matters might have come to attention."),
      ("B", "The practitioner does not express an opinion or assurance."),
      ("C", "The report relates only to the specific elements, accounts, or items specified."),
      ("D", "All of the above.")]),
    (36, "Compilation Engagements", "In a compilation engagement (PSRS 4410 Revised), the accountant:",
     [("A", "Provides reasonable assurance on the financial statements."),
      ("B", "Applies accounting and financial reporting expertise to assist management in the preparation and presentation of financial information without obtaining audit evidence."),
      ("C", "Performs detailed tests of controls."),
      ("D", "Verifies cash balances with third-party banks.")]),
    (37, "Compilation Engagements", "Does a compilation engagement require the accountant to verify the accuracy or completeness of the information provided by management?",
     [("A", "No, the accountant does not test or verify management's assertions or evidence."),
      ("B", "Yes, 100% verification is mandatory."),
      ("C", "Yes, attribute sampling is required."),
      ("D", "Yes, confirmation of receivables is required.")]),
    (38, "Compilation Engagements", "The accountant's compilation report shall include:",
     [("A", "A statement that the engagement was performed in accordance with PSRS 4410 (Revised)."),
      ("B", "A statement that the accountant has applied expertise in accounting and financial reporting."),
      ("C", "A statement that the accountant does not express an audit opinion or a review conclusion."),
      ("D", "All of the above.")]),
    (39, "Compilation Engagements", "If the accountant becomes aware that the records, documents, or explanations provided by management are incomplete, inaccurate, or unsatisfactory in a compilation engagement, the accountant shall:",
     [("A", "Fabricate the missing data."),
      ("B", "Request management to provide additional or corrected information, and withdraw if management refuses."),
      ("C", "Issue an adverse audit opinion under PSA 705."),
      ("D", "Report the client to the police.")]),
    (40, "Compilation Engagements", "Each page of the financial statements compiled by the practitioner should include a reference such as:",
     [("A", "'Audited by Independent CPA'"),
      ("B", "'Guaranteed Accurate by Certified Public Accountant'"),
      ("C", "'Approved by the Securities and Exchange Commission'"),
      ("D", "'Unaudited - See Compilation Report' or 'Unaudited'")]),
    (41, "Comparative Summary of Related Services", "Which engagement provides the highest level of assurance?",
     [("A", "Audit"), ("B", "Review"), ("C", "Agreed-upon procedures"), ("D", "Compilation")]),
    (42, "Comparative Summary of Related Services", "Which engagement provides moderate / limited assurance?",
     [("A", "Audit"), ("B", "Review"), ("C", "Agreed-upon procedures"), ("D", "Compilation")]),
    (43, "Comparative Summary of Related Services", "Which engagement provides factual findings only without assurance?",
     [("A", "Review"), ("B", "Agreed-upon procedures"), ("C", "Audit"), ("D", "Examination of PFI")]),
    (44, "Comparative Summary of Related Services", "Which engagement provides no assurance and assists in presenting financial statements?",
     [("A", "Audit"), ("B", "Review"), ("C", "Compilation"), ("D", "Comprehensive audit")]),
    (45, "Comparative Summary of Related Services", "Independence is required for:",
     [("A", "Audits and reviews (assurance engagements)"),
      ("B", "Compilation engagements only"),
      ("C", "Tax return preparation only"),
      ("D", "Internal bookkeeping only")]),
    (46, "Comparative Summary of Related Services", "If a CPA compiling financial statements is not independent, the compilation report:",
     [("A", "May disclose that the CPA is not independent."),
      ("B", "Must disclaim an audit opinion and fine the client."),
      ("C", "Cannot be issued under any circumstances."),
      ("D", "Must be kept confidential from banks.")]),
    (47, "Comparative Summary of Related Services", "Which of the following standards applies to reviews of interim financial information performed by the independent auditor of the entity?",
     [("A", "PSA 500"), ("B", "PSAE 3000"), ("C", "PSRE 2410"), ("D", "PSRS 4400")]),
    (48, "Comparative Summary of Related Services", "A comfort letter is a letter issued by an independent auditor to:",
     [("A", "The BIR regarding tax exemptions"),
      ("B", "Employees regarding wage increases"),
      ("C", "Underwriters in connection with a securities offering/prospectus"),
      ("D", "The media regarding company controversies")]),
    (49, "Comparative Summary of Related Services", "In a comfort letter, the independent auditor typically provides:",
     [("A", "Absolute guarantee of future stock prices"),
      ("B", "An adverse opinion on interim financials"),
      ("C", "A complete tax guarantee"),
      ("D", "Negative assurance on unaudited interim financial statements and compliance of registration statement with SEC requirements")]),
    (50, "Comparative Summary of Related Services", "Reports on compliance with contractual agreements (e.g., loan covenants) can be issued:",
     [("A", "Only by government attorneys"),
      ("B", "Only if the entire company is dissolved"),
      ("C", "As a separate report or in an Other Matter paragraph in connection with an audit of financial statements"),
      ("D", "Only if no audit was performed")])
]

chapter13 = {
    "id": "at-13",
    "code": "AT-13",
    "title": "Reporting on Special-Purpose Engagements and Other Audit-Related Services",
    "description": "Special purpose financial frameworks (PSA 800), single financial statements and elements (PSA 805), summary financial statements (PSA 810), review engagements (PSRE 2400/2410), assurance engagements other than audits/reviews (PSAE 3000/3400), agreed-upon procedures (PSRS 4400), and compilation engagements (PSRS 4410).",
    "objectives": [
        "Special Purpose Frameworks & PSA 800",
        "Engagements to Report on Summary Financial Statements",
        "Review of Financial Statements",
        "Assurance Engagements Other Than Audits or Reviews",
        "Agreed-Upon Procedures Engagements",
        "Compilation Engagements",
        "Comparative Summary of Related Services"
    ],
    "totalQuestions": 50,
    "questions": []
}

for num, obj, qtext, opts in at13_raw:
    correct = at13_answers[num]
    expl = at13_explanations.get(num, f"Suggested Answer: {correct}. In accordance with PSA 800/805/810, PSRE 2400/2410, PSAE 3000/3400, and PSRS 4400/4410.")
    chapter13["questions"].append({
        "id": f"at13-{num}",
        "number": num,
        "chapterId": "at-13",
        "chapterCode": "AT-13",
        "chapterTitle": "Reporting on Special-Purpose Engagements and Other Audit-Related Services",
        "objective": obj,
        "question": qtext,
        "options": [{"key": k, "text": t} for k, t in opts],
        "correctAnswer": correct,
        "explanation": expl
    })

with open("src/data/chapters/at13.ts", "w", encoding="utf-8") as f:
    f.write(f"import {{ Chapter }} from '../../types/quiz';\n\nexport const chapter13: Chapter = {json.dumps(chapter13, indent=2)};\n")

print("Created at13.ts with 50 questions")
