#!/usr/bin/env python3
import json

at07_answers = {
    1: 'B', 2: 'B', 3: 'D', 4: 'D', 5: 'C', 6: 'C', 7: 'D', 8: 'B', 9: 'B', 10: 'C',
    11: 'D', 12: 'B', 13: 'D', 14: 'A', 15: 'C', 16: 'C', 17: 'C', 18: 'D', 19: 'B', 20: 'C',
    21: 'D', 22: 'B', 23: 'A', 24: 'B', 25: 'C', 26: 'D', 27: 'B', 28: 'C', 29: 'A', 30: 'A',
    31: 'D', 32: 'C', 33: 'C', 34: 'B', 35: 'A', 36: 'A', 37: 'C', 38: 'C', 39: 'A', 40: 'D',
    41: 'B', 42: 'D', 43: 'B', 44: 'B', 45: 'C', 46: 'A', 47: 'B', 48: 'D', 49: 'C', 50: 'B',
    51: 'C', 52: 'B', 53: 'A', 54: 'D', 55: 'A', 56: 'D', 57: 'D', 58: 'A', 59: 'D', 60: 'C',
    61: 'B', 62: 'D', 63: 'D', 64: 'D', 65: 'D', 66: 'B', 67: 'B', 68: 'B', 69: 'C', 70: 'C',
    71: 'B', 72: 'B', 73: 'B', 74: 'B', 75: 'C', 76: 'C', 77: 'A', 78: 'C', 79: 'B', 80: 'A',
    81: 'C', 82: 'A', 83: 'D', 84: 'C', 85: 'A', 86: 'C', 87: 'A', 88: 'B', 89: 'D', 90: 'C',
    91: 'B', 92: 'C', 93: 'B', 94: 'B', 95: 'C', 96: 'D', 97: 'A', 98: 'A', 99: 'B', 100: 'A'
}

at07_explanations = {
    2: "An auditor is primarily concerned with internal control policies and procedures that are related to the entity's financial reporting objectives. Choice B reflects this concept.",
    3: "In the audit of financial statements, the auditor is only concerned with those policies and procedures within the accounting and internal control systems that are relevant to the financial statement assertions. Therefore, the objective that is most relevant to the audit is the financial reporting objective.",
    5: "The management and those charged with governance are primarily responsible for establishing and maintaining internal controls within the organization.",
    7: "Internal control is intended to provide reasonable assurance that the organization's objective will be achieved with regard to: Reliability of financial reporting, Effectiveness and efficiency of operations, Compliance with applicable laws and regulations.",
    9: "Establishment of internal control would also consider cost-benefit analysis, meaning, the cost of placing an internal control should not exceed the benefit deriving from it.",
    10: "Misstatements or errors cannot be eliminated even with effective internal controls. They can only be prevented, detected, or corrected.",
    11: "Efficiency of business processes are part of an entity's internal control but not a major consideration in the audit of financial statements.",
    15: "Understanding the industry where the client belongs to is very important in determining factors that may affect the financial statement of the company being audited.",
    16: "Assessment of risks of material misstatement in the financial statements is the responsibility of the auditor and not of the management.",
    18: "The components of internal controls are as follows: C.R.I.M.E. Control environment, Risk assessment process, Information and communication systems, Monitoring of controls, Existing control activities.",
    22: "The competence of an entity's employees have an effect on the achievement of the objectives of internal control.",
    25: "Control activities are actions, policies, or procedures that help management mitigate risks during the achievement of their objectives.",
    26: "Control activities are the policies and procedures that help ensure the management directives are carried out.",
    27: "Internal control includes policies and procedures designed to ensure that accounting systems function effectively and communicate reliable information in a timely manner.",
    28: "Control activities relevant to an audit include APIPS: Authorization, Performance reviews, Information processing, Physical inspection, and Segregation of duties.",
    29: "This pertains to the segregation of incompatible duties.",
    30: "Authorization and custodianship are two duties within the entity that should be segregated from one another.",
    32: "Direct observation of employees is the most effective way to gain audit evidence concerning proper segregation of duties.",
    38: "The primary consideration regarding an internal control activity is whether the control has an effect on financial statement assertions.",
    42: "The test of controls determines whether control risk is high or low and evaluates effectiveness.",
    43: "Auditors do not necessarily have to reperform internal control processes if there were no significant changes from the previous audit.",
    47: "Reading trade magazines is used to gain an understanding of the business, not internal controls.",
    49: "Reviewing policies and procedures manuals is a standard audit step in obtaining an understanding of internal controls.",
    52: "Tracing transactions through the accounting system is called a walk-through procedure.",
    54: "A walk-through alone cannot provide sufficient appropriate audit evidence to support a low assessment of control risk.",
    58: "If control risk is assessed at a high level, the auditor must document the conclusion that control risk is high, but not the basis.",
    63: "Any of the three techniques (questionnaires, flowcharts, or narrative memoranda) can accomplish the purpose of documenting understanding of internal control.",
    64: "Tests of controls are designed to obtain evidence to support the auditor's assessment of control risk at less than high level.",
    70: "Tests of controls are conducted when it is reasonable and efficient to rely on controls to reduce substantive testing.",
    74: "When controls are effective, CR is low. To maintain acceptable audit risk, the acceptable detection risk is increased.",
    77: "Control risk is assessed at maximum if the auditor deems controls unreliable or ineffective.",
    78: "If control risk is assessed as high, there is no need to perform tests of controls.",
    83: "To lower assessed control risk, the auditor must perform further tests of controls over processing and recording transactions.",
    89: "Extended tests of controls occur when controls are effective and assessed control risk is low.",
    90: "The audit committee of the board of directors is the appropriate body to receive written reports on material weaknesses.",
    92: "If controls are ineffective, assessed control risk is increased and the extent of tests of details is increased.",
    96: "Reportable conditions in internal control must be communicated to the audit committee or its equivalent.",
    99: "When control risk is assessed at a high level, the auditor documents the conclusion but not the basis.",
    100: "When control risk is assessed at less than high, the auditor must document both the conclusion and the basis for that assessment."
}

at07_raw = [
    (1, "Nature of Internal Control", "It is the process designed, implemented and maintained by those charged with governance, management, and other personnel to provide reasonable assurance about the achievement of the entity's objectives.",
     [("A", "Internal auditing"), ("B", "Internal control"), ("C", "Business strategy"), ("D", "Accounting process")]),
    (2, "Nature of Internal Control", "Which of the following is the most accurate?",
     [("A", "An auditor would most likely be concerned with internal control policies and procedures that provide reasonable assurance about the efficiency of management's decision-making process."),
      ("B", "An auditor would most likely be concerned with internal control policies and procedures that provide reasonable assurance about the entity's ability to process and summarize financial data."),
      ("C", "An auditor would most likely be concerned with internal control policies and procedures that provide reasonable assurance about the appropriate prices the entity should charge for its products."),
      ("D", "An auditor would most likely be concerned with internal control policies and procedures that provide reasonable assurance about the methods of assigning production tasks to employees.")]),
    (3, "Nature of Internal Control", "Which of the following objectives of internal control would be most relevant to the audit?",
     [("A", "Operational objective"), ("B", "Compliance objective"), ("C", "Administrative control objective"), ("D", "Financial reporting objective")]),
    (4, "Nature of Internal Control", "Which of the following is not one of the three primary objectives of effective internal control?",
     [("A", "Reliability of financial reporting."), ("B", "Efficiency and effectiveness of operations."), ("C", "Compliance with laws and regulations."), ("D", "Each of these is a primary objective of effective internal control.")]),
    (5, "Nature of Internal Control", "The primary responsibility for establishing and maintaining an internal control rests with:",
     [("A", "The external auditors"), ("B", "The internal auditors"), ("C", "The management and those charged with governance"), ("D", "The controller or the treasurer")]),
    (6, "Nature of Internal Control", "In a public firm, which of the following is in charge of developing internal controls?",
     [("A", "Management and auditors."), ("B", "Committee on Sponsoring Organizations."), ("C", "Management."), ("D", "Financial statement auditors.")]),
    (7, "Nature of Internal Control", "Which of the following pertains to the fundamental purpose of an internal control?",
     [("A", "To encourage compliance with organization objectives."),
      ("B", "To ensure the accuracy, reliability, and timeliness of information."),
      ("C", "To safeguard the resources of the organization."),
      ("D", "To provide reasonable assurance that the objectives of the organization are achieved.")]),
    (8, "Nature of Internal Control", "Which statement is correct concerning the relevance of various types of controls to a financial audit?",
     [("A", "An auditor may ordinarily ignore a consideration of controls when a substantive audit approach is taken."),
      ("B", "Controls over the reliability of financial reporting are ordinarily most directly relevant to an audit but other controls may also be relevant."),
      ("C", "Controls over safeguarding of assets are of primary importance, while controls over the reliability of financial reporting may also be relevant."),
      ("D", "All controls are ordinarily relevant to an audit.")]),
    (9, "Nature of Internal Control", "Which of the following is not typically one of the management's concerns in designing effective internal controls?",
     [("A", "Generating profits from operations"),
      ("B", "Designing the most effective internal control possible no matter how much it will cost."),
      ("C", "Complying with applicable laws and regulations"),
      ("D", "Generating fairly stated financial statements.")]),
    (10, "Nature of Internal Control", "An effective internal control is not expected to provide a reasonable assurance regarding the achievement of objectives concerning:",
     [("A", "Reliability of financial reporting."), ("B", "Compliance to applicable laws and regulations."), ("C", "Elimination of material misstatements."), ("D", "Effectiveness and efficiency of operations.")]),
    (11, "Nature of Internal Control", "Which of the following is not a major emphasis in the design of effective internal control?",
     [("A", "Assets are properly protected."), ("B", "Duties are segregated."), ("C", "Transactions are authorized."), ("D", "Processes are efficient.")]),
    (12, "Nature of Internal Control", "Internal control can only provide reasonable assurance of achieving an entity's objectives. This is because of the internal control's inherent limitations. Inherent limitations in an internal control must be considered in evaluating its effectiveness in preventing and detecting errors and fraud. Inherent limitations do not include:",
     [("A", "Misunderstanding of instructions, mistakes of judgment, personal carelessness, distraction, or fatigue."),
      ("B", "Incompatible functions performed by the same person."),
      ("C", "Collusion among employees."),
      ("D", "Management override of certain policies or procedures.")]),
    (13, "Nature of Internal Control", "Internal controls are not designed to provide reasonable assurance that:",
     [("A", "Transactions are executed in accordance with management's authorization."),
      ("B", "Access to assets is permitted only in accordance with management's authorization."),
      ("C", "Company personnel comply with applicable rules and regulations."),
      ("D", "All frauds will be detected.")]),
    (14, "Nature of Internal Control", "Which of the following is correct about internal control?",
     [("A", "One of the inherent limitations of accounting and internal control systems is the possibility that the procedures may become inadequate due to changes in conditions, and compliance with procedures may deteriorate."),
      ("B", "Accounting and internal control systems provide management with conclusive evidence that objectives are reached."),
      ("C", "Most internal controls tend to be directed at non-routine transactions."),
      ("D", "Management does not consider costs of the accounting and internal control systems.")]),
    (15, "Nature of Internal Control", "In performing an audit of financial statements, it is required that the auditor should obtain a sufficient knowledge of a client's business and industry to",
     [("A", "Develop professional skepticism when it comes to management's financial statement assertions."),
      ("B", "Make suggestions for improvements to the client's internal control system."),
      ("C", "Understand the events and transactions that may have an impact on the client's financial statements."),
      ("D", "Examine if the aggregate of known misstatements results in the financial statements being materially misstated as a whole.")]),
    (16, "Nature of Internal Control", "The financial statements must be prepared and presented in a fair and accurate manner by the entity's management. Its responsibility includes the following, except:",
     [("A", "Designing, implementing, and maintaining internal control related to the preparation and presentation of financial statements."),
      ("B", "Selecting and applying appropriate accounting policies."),
      ("C", "Assessing the risks of material misstatement of the financial statements."),
      ("D", "Making accounting estimates that are reasonable in the circumstances.")]),
    (17, "Nature of Internal Control", "Which of management's concerns about implementing internal controls is most important to the auditor?",
     [("A", "Efficiency of operations."), ("B", "Compliance with applicable laws and regulations."), ("C", "Reliability of financial reporting."), ("D", "Effectiveness of operations.")]),
    (18, "Components of Internal Control", "The following are components of internal control, except:",
     [("A", "Control activities"), ("B", "The entity's risk assessment process"), ("C", "Control environment"), ("D", "Business risk")]),
    (19, "Components of Internal Control", "Which of the following is not part of a company's internal control system?",
     [("A", "Information and communication."), ("B", "Control risk."), ("C", "The control environment."), ("D", "Risk assessment.")]),
    (20, "Components of Internal Control", "The overall attitude and awareness of an entity's board of directors concerning the importance of the internal control is usually reflected in its",
     [("A", "Computer-based controls"), ("B", "System of segregation of duties"), ("C", "Control environment"), ("D", "Safeguards over access to assets")]),
    (21, "Components of Internal Control", "In evaluating the design of the entity's internal control environment, the auditor considers certain subcomponents of control environment and how they have been incorporated into the entity's processes. Subcomponents of control environment would not include",
     [("A", "Integrity and ethical values"), ("B", "Commitment to competence"), ("C", "Organizational structure"), ("D", "Information and communications systems")]),
    (22, "Components of Internal Control", "It is important for the auditor to consider the competence of the audit client's employees because their competence bears directly and importantly upon the:",
     [("A", "Cost-benefit relationship of internal control."),
      ("B", "Achievement of the objectives of internal control."),
      ("C", "Comparison of recorded accountability with assets."),
      ("D", "Timing of the tests to be performed.")]),
    (23, "Components of Internal Control", "Which of the following subcomponents of the control environment define the existing lines of responsibility and authority?",
     [("A", "Organizational structure"), ("B", "Management philosophy and operating style"), ("C", "Human resource policies and practices"), ("D", "Management integrity and ethical values")]),
    (24, "Components of Internal Control", "Which of the following most accurately reflects the entity's risk management process?",
     [("A", "Entity's assessment of audit risks affecting the financial statements."),
      ("B", "The process through which an entity identifies business risks that are important to financial reporting objectives and decides what actions to take to address those risks."),
      ("C", "Entity's process of evaluating the risks of misstatements due to fraud."),
      ("D", "The entity's evaluation of the risks that internal controls would fail to detect financial statement misstatements.")]),
    (25, "Components of Internal Control", "The policies and procedures that help ensure that management directives are carried out are referred to as the:",
     [("A", "Control environment"), ("B", "Information system"), ("C", "Control activities"), ("D", "Monitoring of controls")]),
    (26, "Components of Internal Control", "Which of the following best describes the purpose of control activities?",
     [("A", "The actions, policies, and procedures that reflect the overall attitudes of management."),
      ("B", "The identification and analysis of risks relevant to the preparation of financial statements"),
      ("C", "Activities that deal with the ongoing assessment of the quality of internal control by management"),
      ("D", "The policies and procedures that help ensure that necessary actions are taken in order to achieve the entity's objectives.")]),
    (27, "Components of Internal Control", "One of the components of internal control that an independent auditor must come to understand about each audit client is \"information and communication.\" What is meant by this term?",
     [("A", "The ability of the management of the company to communicate its priorities to the appropriate staff levels within the organization."),
      ("B", "The ability of the accounting system to generate reliable information and convey it in a timely manner to those parties within the organization that needs it."),
      ("C", "The ability of employees in a company to warn the independent auditor of fraudulent actions within the organization."),
      ("D", "The ability of the internal auditor to communicate information about the various systems to people within the organization at an appropriate level of authority.")]),
    (28, "Components of Internal Control", "All of the following are specific control activities that are relevant to financial statement audit except:",
     [("A", "Performance reviews"), ("B", "Physical controls"), ("C", "Monitoring"), ("D", "Segregation of duties")]),
    (29, "Components of Internal Control", "The single most effective control procedure established to avoid allowing any person to be in a position to perpetrate and then conceal errors or fraud is:",
     [("A", "The separation of the functional responsibilities of authorization, record-keeping, and custodianship."),
      ("B", "Require each employee to take a vacation each year."),
      ("C", "Establish an internal audit department."),
      ("D", "Require the bonding of personnel in positions that necessitate handling of cash and other universally desirable valuables.")]),
    (30, "Components of Internal Control", "Which of the following is true with respect to separation of duties?",
     [("A", "It is desirable to prevent employees who authorize transactions from having custody of related assets."),
      ("B", "Employees should not be in charge of assets both temporarily and permanently."),
      ("C", "Allowing an employee to open cash receipts and record them is permissible."),
      ("D", "None of the above is correct.")]),
    (31, "Components of Internal Control", "Proper segregation of functional responsibilities in an effective structure of internal control calls for separation of the functions of:",
     [("A", "Custody, execution and reporting"), ("B", "Authorization, payment, and recording"), ("C", "Authorization, execution, and payment"), ("D", "Authorization, recording, and custody")]),
    (32, "Components of Internal Control", "An auditor commonly tests the segregation of duties in connection with the inventory through:",
     [("A", "Analytical procedures and invoice recalculation."), ("B", "Document inspection and reconciliation."), ("C", "Inquiry and observation."), ("D", "Test counts and cutoff procedures.")]),
    (33, "Components of Internal Control", "The best way to normally gain audit evidence concerning proper segregation of duties is through:",
     [("A", "Inquiries about the employee who implements control methods among coworkers."),
      ("B", "Preparation of a flowchart of duties performed and available personnel."),
      ("C", "Direct observation of the employee who performs control procedures."),
      ("D", "Inspection of third-party documents containing the initials of who applied control procedures.")]),
    (34, "Components of Internal Control", "Which of the following deal with ongoing or periodic assessment of the quality of internal control by management?",
     [("A", "Quality control activities"), ("B", "Monitoring activities"), ("C", "Oversight activities"), ("D", "Management activities")]),
    (35, "Consideration of Internal Control", "The auditor's consideration of a company's internal control is",
     [("A", "Required by PSA."), ("B", "Required by PFRS."), ("C", "Required under RA 9298."), ("D", "Not required.")]),
    (36, "Consideration of Internal Control", "The PSA require the auditor to obtain an understanding of the client's internal controls",
     [("A", "For every audit."), ("B", "For first-time audits."), ("C", "Sufficient to find any frauds which may exist."), ("D", "Whenever it would be appropriate.")]),
    (37, "Consideration of Internal Control", "The primary purpose of the auditor's consideration of internal control is to provide a basis for",
     [("A", "Determining whether procedures and records that are concerned with the safeguarding of assets are reliable."),
      ("B", "Constructive suggestions to clients concerning deficiencies in internal control."),
      ("C", "Determining the nature timing, and extent of audit tests to be applied."),
      ("D", "The expression of an opinion.")]),
    (38, "Consideration of Internal Control", "When it comes to an audit of financial statements, the primary consideration of an auditor regarding an internal control activity is whether the control:",
     [("A", "Helps in the management's decision-making process."),
      ("B", "Mirrors management's philosophy and operating style"),
      ("C", "Has an effect in the management's financial statement assertions."),
      ("D", "Provides sufficient safeguards over access to assets.")]),
    (39, "Consideration of Internal Control", "During the consideration of internal control in a financial statement audit, an auditor is not obliged to",
     [("A", "Search for significant deficiencies in the operation of the internal control."),
      ("B", "Understand the internal control and the information system."),
      ("C", "Determine whether the control activities relevant to audit have been implemented."),
      ("D", "Perform procedures to understand the design of internal control.")]),
    (40, "Consideration of Internal Control", "Control risk is a measure of the auditor's expectation that the internal control structure",
     [("A", "Will prevent material misstatements from occurring."),
      ("B", "Will detect and correct material misstatements."),
      ("C", "Will either prevent material misstatements or detect and correct them."),
      ("D", "Will neither prevent material misstatements nor detect and correct them.")]),
    (41, "Consideration of Internal Control", "When auditing a private company, the auditor should obtain an understanding of internal control sufficient to",
     [("A", "Provide reasonable protection against client fraud and defalcations by client employees."),
      ("B", "Assess control risk."),
      ("C", "Provide a basis for suggestions to the client for improving the accounting system."),
      ("D", "Provide a method for safeguarding assets, checking the accuracy and reliability of accounting data, promoting operational efficiency, and encouraging adherence to prescribed managerial policies.")]),
    (42, "Consideration of Internal Control", "The approach of tests of control is heading toward the control's:",
     [("A", "Efficiency."), ("B", "Efficiency and effectiveness."), ("C", "Cost benefit ratio."), ("D", "Effectiveness.")]),
    (43, "Consideration of Internal Control", "The auditor's understanding of the entity's accounting and internal control systems is usually gained through past experience with the entity. In addition, the auditor may perform the following procedures, except:",
     [("A", "Inquiries of relevant management, supervisory, and other people at various organizational levels within the entity, as well as citations to paperwork, job descriptions, and flow charts."),
      ("B", "Internal control processes must be re-performed."),
      ("C", "Inspecting the accounting and internal control system's documents and records."),
      ("D", "Observation of the entity's activities and operations, including computer operations organization, management people, and transaction processing nature.")]),
    (44, "Consideration of Internal Control", "The auditor observes client employees while obtaining an understanding of the internal control structure so that he can:",
     [("A", "Update information contained in the organization and procedure manuals."),
      ("B", "Become familiar with the control structure's design and implementation of applicable policies, procedures, and records."),
      ("C", "Prepare a flowchart."),
      ("D", "Determine the extent of compliance with quality control standards.")]),
    (45, "Consideration of Internal Control", "An auditor should consider two key issues when obtaining an understanding of a client's internal controls. These issues are",
     [("A", "The effectiveness and efficiency of the controls."),
      ("B", "The frequency and effectiveness of the controls."),
      ("C", "The design and implementation of the controls."),
      ("D", "The implementation and efficiency of the controls.")]),
    (46, "Consideration of Internal Control", "Evaluating the design of the entity's internal control would involve",
     [("A", "Considering whether the control, individually or in combination with other controls, is capable of effectively preventing, or detecting and correcting material misstatements."),
      ("B", "Determining whether the control exists and the entity is using it."),
      ("C", "Determining whether the control is operating effectively."),
      ("D", "Determining the consistency of application of internal control procedures.")]),
    (47, "Consideration of Internal Control", "Which of the following strategies is not appropriate for gaining knowledge about internal controls?",
     [("A", "Examine documents and records."), ("B", "Read industry trade magazines."), ("C", "Observe client activities and operations."), ("D", "Make inquiries of the client's personnel.")]),
    (48, "Consideration of Internal Control", "Which of the following would an auditor least likely perform when obtaining understanding of the entity's accounting and internal control systems?",
     [("A", "Inquiries of appropriate personnel."), ("B", "Inspection of documents and records."), ("C", "Observation of the entity's activities and operations."), ("D", "Performing analytical review procedures.")]),
    (49, "Consideration of Internal Control", "In obtaining an understanding of a manufacturing entity's internal control concerning inventory balances, an auditor most likely would",
     [("A", "Perform test counts of inventory during the entity's physical count."),
      ("B", "Analyze inventory turnover statistics to identify slow-moving and obsolete items."),
      ("C", "Review the entity's descriptions of inventory policies and procedures."),
      ("D", "Analyze monthly production reports to identify variances and unusual transactions.")]),
    (50, "Consideration of Internal Control", "When obtaining an understanding of an entity's internal control, the auditor should concentrate on the substance of controls rather than on their form because",
     [("A", "The controls may be operating effectively but may not be documented."),
      ("B", "Management may establish appropriate controls but not act on them."),
      ("C", "The controls may be so inappropriate that no reliance is contemplated by the auditor."),
      ("D", "Management may implement controls with costs in excess of benefits.")]),
    (51, "Consideration of Internal Control", "Obtaining knowledge about whether the control is implemented can best be obtained by",
     [("A", "Inquiry of client's personnel."),
      ("B", "Reading procedures manual."),
      ("C", "Tracing transactions through the information system relevant to financial reporting."),
      ("D", "Performing tests of control.")]),
    (52, "Consideration of Internal Control", "The auditor might follow multiple transactions through the control process to get a better knowledge of the internal control structure. The primary purpose of this task is to",
     [("A", "Determine the effectiveness of the control procedures."),
      ("B", "Determine whether the controls have been placed in operation."),
      ("C", "Replace substantive tests."),
      ("D", "Detect fraud done by the management.")]),
    (53, "Consideration of Internal Control", "When the auditor attempts to understand the operation of the accounting system by tracing a few transactions through the accounting system, the auditor is said to be:",
     [("A", "Performing a walk-through"), ("B", "Tracing"), ("C", "Vouching"), ("D", "Testing controls")]),
    (54, "Consideration of Internal Control", "Which of the following statements concerning walkthrough tests is incorrect?",
     [("A", "Tracing a few transactions through accounting systems is required."),
      ("B", "This approach could be used in test of control."),
      ("C", "This technique is used to assess if the controls are in place."),
      ("D", "The nature and scope of the walk-through performed by the auditor are such that they alone would provide sufficient appropriate audit evidence to support a low assessment of control risk.")]),
    (55, "Consideration of Internal Control", "An auditor uses the knowledge provided by the understanding of internal control and the final assessed level of control risk primarily to determine the nature, timing, and extent of the:",
     [("A", "Substantive tests"), ("B", "Attribute tests"), ("C", "Tests of controls"), ("D", "Compliance tests")]),
    (56, "Consideration of Internal Control", "Subsequent to the obtaining of sufficient understanding of the entity's accounting and internal control systems, the auditor should make a preliminary assessment of:",
     [("A", "Audit risk"), ("B", "Inherent risk"), ("C", "Detection risk"), ("D", "Control risk")]),
    (57, "Consideration of Internal Control", "Control risk should be assessed by:",
     [("A", "Control environment factors"), ("B", "Specific controls"), ("C", "Types of potential factors"), ("D", "Financial statement assertions")]),
    (58, "Consideration of Internal Control", "Which of the following statements concerning control risk is true?",
     [("A", "Control risk assessment and understanding of an entity's internal control system can be done at the same time."),
      ("B", "When control risk is at a high level, an auditor is required to document the basis for that assessment."),
      ("C", "Control risk may be deemed low enough to obviate the need for comprehensive assessment for key transaction classes."),
      ("D", "An auditor should not consider evidence gathered from previous audits about the operation of control procedures when evaluating control risk.")]),
    (59, "Consideration of Internal Control", "Which of the following is not a typical medium for an auditor to keep track of information on a client's internal control policies and procedures?",
     [("A", "Questionnaire"), ("B", "Narrative memorandum"), ("C", "Flowchart"), ("D", "Procedure manual")]),
    (60, "Consideration of Internal Control", "Which of the following best describes the primary reason for the auditor's use of flowcharts during an audit engagement?",
     [("A", "To comply with the requirements of generally accepted auditing standards."),
      ("B", "To classify the client's documents and transactions by major operating functions, e.g., cash receipts, cash disbursements, etc."),
      ("C", "To record the auditor's understanding of the client's internal control policies and procedures."),
      ("D", "To interpret the operational effectiveness of the client's existing organizational structure.")]),
    (61, "Consideration of Internal Control", "When obtaining knowledge of the entity's accounting and internal control systems, an auditor is least likely to do which of the following?",
     [("A", "Inquiries of appropriate personnel."), ("B", "Performing analytical review procedures."), ("C", "Inspection of documents and record."), ("D", "Observation of the entity's activities and operations.")]),
    (62, "Consideration of Internal Control", "A CPA firm is beginning the audit of Panny Corporation. One of the staff auditors has been assigned to gain and then document her understanding of the internal controls designed to be in place in the company's payroll system. At the end of the day, the staff auditor has created a series of flowcharts, questionnaires, and narrative descriptions based on the understanding she has obtained. Which of the following is correct?",
     [("A", "The questionnaire approach is preferred."),
      ("B", "The flowchart approach is preferred."),
      ("C", "She was correct in using all three of these techniques to fulfill this assignment."),
      ("D", "She only needed to use one of these techniques.")]),
    (63, "Consideration of Internal Control", "Which of the following statements regarding the auditor's documentation of the client's internal control structure is correct?",
     [("A", "Documentation must include flow charts."),
      ("B", "Documentation must include procedural write-ups."),
      ("C", "No documentation is necessary although it is desirable."),
      ("D", "No one particular form of documentation is necessary, and the extent of documentation may vary.")]),
    (64, "Consideration of Internal Control", "Which of the following is true?",
     [("A", "Tests of controls are designed to obtain evidence to support the auditor's assessment of control risk at a high level."),
      ("B", "Tests of controls are designed to obtain evidence to support the auditor's assessment of control risk at zero level."),
      ("C", "Tests of controls are designed to obtain evidence to support the auditor's assessment of control risk at the maximum level."),
      ("D", "Tests of controls are designed to obtain evidence to support the auditor's assessment of control risk at less than high level.")]),
    (65, "Consideration of Internal Control", "The auditor acquires a reasonable degree of assurance that the internal control procedures are in use and operating as designed before relying on the system of internal control. The auditor obtains this assurance by performing planned:",
     [("A", "Transaction tests"), ("B", "Tests of trends and ratios"), ("C", "Substantive tests"), ("D", "Tests of controls")]),
    (66, "Consideration of Internal Control", "The purpose of tests of controls is to provide reasonable assurance that the:",
     [("A", "Accounting treatment of transactions and balances is valid and proper."),
      ("B", "Control procedures are functioning as intended."),
      ("C", "Entity has complied with disclosure requirements of PFRS."),
      ("D", "Entity has complied with requirements of quality control.")]),
    (67, "Consideration of Internal Control", "Which of the following audit tests would be regarded as a test of controls?",
     [("A", "Comparison of inventory pricing to vendors' invoices."),
      ("B", "Tests of the signatures on canceled checks to board of directors' authorizations."),
      ("C", "Tests of the additions to property, plant, and equipment by physical inspections."),
      ("D", "Review of the specific items making up the balance in a given general ledger account.")]),
    (68, "Consideration of Internal Control", "Tests of controls do not include:",
     [("A", "Inspection of documentary support for transactions evidencing authorization."),
      ("B", "Analytical procedures involving comparison of operating expenses with budgeted amounts."),
      ("C", "Reperformance of internal control procedures."),
      ("D", "Inquiries about, and observation of, internal controls which leave no audit trail.")]),
    (69, "Consideration of Internal Control", "To obtain evidential matter about control risk, an auditor selects test from a variety of techniques including:",
     [("A", "Analytical procedures"), ("B", "Calculation"), ("C", "Inquiry"), ("D", "Confirmation")]),
    (70, "Consideration of Internal Control", "An auditor opted to conduct control tests after learning about the internal control structure and assessing control risk. The auditor most likely decided that",
     [("A", "There is insufficient data to support additional reductions in control risk."),
      ("B", "For certain financial statement assertions, an increase in the assessed level of control risk is justified."),
      ("C", "It would be more efficient to conduct control tests that would result in fewer substantive tests being conducted."),
      ("D", "There were numerous flaws in internal controls that might have allowed errors to enter the accounting system.")]),
    (71, "Consideration of Internal Control", "Control testing is applied in order to know whether or not:",
     [("A", "Incompatible functions exist."), ("B", "The assessed level of control risk can be reduced."), ("C", "Necessary controls are absent."), ("D", "Material peso errors exist.")]),
    (72, "Consideration of Internal Control", "What is the objective of tests of details of transactions performed as tests of controls?",
     [("A", "To monitor the design and use of entity documents such as prenumbered shipping form"),
      ("B", "To evaluate whether controls operated effectively."),
      ("C", "To determine whether control have been placed in operation."),
      ("D", "To direct material misstatements in the account balances of the financial statements")]),
    (73, "Consideration of Internal Control", "Documentary proof may not exist for certain controls, such as segregation of duties. An auditor would most likely test the procedures by",
     [("A", "Reperformance and corroboration."), ("B", "Observation and inquiry."), ("C", "Inspection and vouching."), ("D", "Confirmation and re-computation.")]),
    (74, "Consideration of Internal Control", "An auditor has decided that a client's existing internal controls are well designed and performing as intended after analyzing and evaluating them. Under these circumstances, the auditor would most likely:",
     [("A", "Conduct additional control tests as specified in the audit program."),
      ("B", "Set the direction risk at a lower level than it would be in the case of a lack of internal control."),
      ("C", "Determine the control policies and procedures that should prevent or detect mistakes and fraud."),
      ("D", "Set the detection risk at a higher level than it would be in the case of weak internal control.")]),
    (75, "Consideration of Internal Control", "An auditor found that the controls are well designed and functioning as expected after studying and evaluating the client's internal control system. Under these circumstances the auditor would most likely",
     [("A", "Increase the extent of planned analytical review procedures."),
      ("B", "Cease to perform further substantive tests."),
      ("C", "Not increase the extent of planned substantive tests."),
      ("D", "Carry out all control tests to the extent specified in the audit program.")]),
    (76, "Consideration of Internal Control", "Which of the following statements regarding tests of controls is true?",
     [("A", "Control test deviations are significant only if they occur in significant patterns never before seen by the auditor."),
      ("B", "Tests of controls must be performed on each audit."),
      ("C", "If the auditor plans to rely on the client's controls, the controls must be tested."),
      ("D", "All of the above are correct.")]),
    (77, "Consideration of Internal Control", "The auditor would most likely assess control risk at a high level when:",
     [("A", "The entity's accounting and internal control systems are not reliable."),
      ("B", "The auditor wants to rely on the accounting and internal control systems of the company."),
      ("C", "It would be efficient to perform test of control."),
      ("D", "The auditor wants to restrict substantive tests.")]),
    (78, "Consideration of Internal Control", "Which of the following may or may not be required during a company's audit?",
     [("A", "Substantive procedures"), ("B", "Risk assessment procedures"), ("C", "Tests of controls"), ("D", "Analytical procedures")]),
    (79, "Consideration of Internal Control", "After considering internal control, an auditor might decide to",
     [("A", "Increase the extent of tests of controls and substantive tests in areas where internal control is strong."),
      ("B", "Increase the extent of substantive tests in areas where internal control is weak."),
      ("C", "Reduce the extent of tests of controls in areas where internal control is strong."),
      ("D", "Reduce the extent of both substantive tests and tests of controls in areas where internal control is strong.")]),
    (80, "Consideration of Internal Control", "Prior to the assessment of control risk at a level lower than the maximum, the auditor is able to get reasonable assurance that controls are in place and functioning properly. The assurance is most likely obtained in part by:",
     [("A", "Inspection of documents."), ("B", "Preparing flowcharts."), ("C", "Performing substantive tests."), ("D", "Analyzing tests of trends and ratios.")]),
    (81, "Consideration of Internal Control", "Which of the following refers to the conclusion reached as a result of assessing control?",
     [("A", "Assurance provided by internal control structure."), ("B", "Determined level of acceptable detection risk."), ("C", "Assessed level of control risk"), ("D", "Product of the understanding of internal control.")]),
    (82, "Consideration of Internal Control", "The reason why an auditor assesses control risk is because it:",
     [("A", "Has an impact on the level of detection risk that the auditor is willing to accept."),
      ("B", "Is relevant to the auditor's understanding of the control environment."),
      ("C", "Assures that the auditor's materiality levels are not excessive."),
      ("D", "Indicates to the auditor where inherent risk may be the greatest.")]),
    (83, "Consideration of Internal Control", "If the auditor desires to further lower the assessed degree of control risk connected to plant asset transactions after gaining an initial grasp of a client's internal control, the auditor should next",
     [("A", "Conduct in-depth analyses of plant asset balances."),
      ("B", "Verify that current-year additions are physically present."),
      ("C", "Fill out the internal accounting control questionnaire's plant asset section."),
      ("D", "Further test those internal control procedures relating to processing and recording plant asset transactions.")]),
    (84, "Consideration of Internal Control", "To support the operational efficacy of internal controls, an auditor is likely to apply four types of procedures. Which of the following would generally not be used?",
     [("A", "Examine documents, records, and reports."), ("B", "Reperform client procedures."), ("C", "Inspect the design of documents."), ("D", "Make inquiries of appropriate client personnel.")]),
    (85, "Consideration of Internal Control", "The auditor concludes that there are no major internal accounting control shortcomings based on an interim assessment and review. The records and procedures would most likely be tested again at year-end if:",
     [("A", "The auditor's inquiries and observations lead him to assume that circumstances have changed."),
      ("B", "Compliance tests were not performed by the internal auditor during the remaining period."),
      ("C", "The internal accounting control system provides a foundation on which to rely in order to reduce the scope of substantive testing."),
      ("D", "The auditor used non-statistical sampling during the interim period compliance testing.")]),
    (86, "Consideration of Internal Control", "Following the assessment of control risk, an auditor wishes to reduce the degree of control risk further. At this time, the auditor would consider whether:",
     [("A", "The entity's controls pertain to any financial statement assertions."),
      ("B", "It would be efficient to obtain an understanding of the entity's information system."),
      ("C", "There is likely to be additional audit evidence available to support a further reduction."),
      ("D", "The entity's controls have been implemented.")]),
    (87, "Consideration of Internal Control", "Which of the following is a phase in an auditor's decision to evaluate control risk at less than high level?",
     [("A", "Determine which internal control policies and procedures are most likely to identify or avoid material misstatements."),
      ("B", "Document that the additional audit effort to perform tests of controls exceeds the potential reduction in substantive testing."),
      ("C", "Use analytical processes on both financial and non-financial data to identify conditions that could suggest a lack of controls."),
      ("D", "Perform tests of details of transactions and accounts balances to identify potential errors and fraud.")]),
    (88, "Consideration of Internal Control", "When the auditor finds that there are missing controls in an area of the accounting system, the audit program in that area would be modified in such a way as to:",
     [("A", "Cause the issuance of a qualified or adverse opinion."), ("B", "Eliminate the need for a test of controls."), ("C", "Increase the number of tests of controls."), ("D", "Increase the reliance on tests of controls.")]),
    (89, "Consideration of Internal Control", "Extended performance of tests of controls is most likely to occur when:",
     [("A", "The auditor is doing a \"fraud audit\"."),
      ("B", "Controls are ineffective and assessed control risk is high."),
      ("C", "It is a first-year audit."),
      ("D", "Controls are effective and assessed control risk is low.")]),
    (90, "Consideration of Internal Control", "Material weaknesses in internal control of a public company must be reported in writing to which of the following?",
     [("A", "The SEC"), ("B", "Members of management who are responsible for the related area of the company."), ("C", "Audit committee of the company's board of directors."), ("D", "The PICPA.")]),
    (91, "Consideration of Internal Control", "When a compensating control is present, the absence of a key control:",
     [("A", "Could cause a material loss, so it must be tested using substantive procedures."),
      ("B", "Is no longer a concern because there is no longer a significant deficiency or material weakness."),
      ("C", "Is still a major concern to the auditor."),
      ("D", "Is magnified and must be removed from the sampling process and examined in its entirety.")]),
    (92, "Consideration of Internal Control", "If an auditor determines that some control activities are ineffective, he or she may increase the assessed degree of control risk. The auditor would most likely increase the:",
     [("A", "Extent of tests of controls."), ("B", "Level of detection risk."), ("C", "Extent of tests of details."), ("D", "Level of inherent risk.")]),
    (93, "Consideration of Internal Control", "The reason why an auditor uses the knowledge provided by the understanding of internal control and the assessed level of the risk of material misstatement is to primarily:",
     [("A", "Determine whether procedures and records concerning the safeguarding of assets are reliable."),
      ("B", "Determine the nature, timing and extent of substantive tests for financial statement assertions."),
      ("C", "Determine whether the chances of someone bothering to commit and conceal fraud are minimized."),
      ("D", "Adjust the original estimations of inherent risk and preliminary materiality judgments.")]),
    (94, "Consideration of Internal Control", "All of the following are performed by the auditor using his knowledge of accounting and internal control systems, as well as assessments of inherent and control risks except:",
     [("A", "Design appropriate audit procedures."),
      ("B", "Evaluate the effectiveness of the accounting and control systems."),
      ("C", "Identify the types of misstatements that could occur."),
      ("D", "Consider factors that affect the risk of material misstatements.")]),
    (95, "Consideration of Internal Control", "After studying and evaluating a client's existing internal control, an auditor has concluded that the policies and procedures are well designed and functioning as intended. Under these circumstances, the auditor would most likely",
     [("A", "Perform further control tests to the extent outlined in the audit program."),
      ("B", "Determine the control policies and procedures that should prevent or detect errors and fraud."),
      ("C", "Set detection risk at a higher level than would be set under conditions of weak internal control."),
      ("D", "Set detection risk at a lower level than would be set under conditions of weak internal control.")]),
    (96, "Consideration of Internal Control", "The auditor who becomes aware of a reportable condition in internal control is required to communicate this to the:",
     [("A", "Senior management and board of directors."), ("B", "Board of directors and internal auditors."), ("C", "Internal auditors and senior management."), ("D", "Audit committee or its equivalent.")]),
    (97, "Consideration of Internal Control", "After obtaining an understanding of internal control and assessing control risk, an auditor decides to perform tests of controls. The auditor most likely decided that:",
     [("A", "It would be efficient to perform tests of controls that would result in a reduction in planned substantive tests."),
      ("B", "There were many internal control structure weaknesses that could cause errors in the accounting systems."),
      ("C", "Additional evidence to support a further reduction in control risk is not available."),
      ("D", "An increase in the assessed level of control risk is justified for certain financial statement assertions.")]),
    (98, "Consideration of Internal Control", "An auditor uses the assessed level of control risk to:",
     [("A", "Determine the acceptable level of detection risk for financial statement assertions."),
      ("B", "Evaluate the effectiveness of the entity's internal control policies and procedures."),
      ("C", "Identify transactions and account balances where inherent risk is at the maximum."),
      ("D", "Indicate whether materiality thresholds for planning and evaluation purposes are sufficiently high.")]),
    (99, "Consideration of Internal Control", "When control risk is assessed at a high level, the auditor should document his:\nUnderstanding of internal control components | Conclusion that control risk is at a high level | Basis for concluding that control risk is at a high level\nA. Yes | Yes | Yes\nB. Yes | Yes | No\nC. Yes | No | No\nD. No | Yes | No",
     [("A", "Yes, Yes, Yes"), ("B", "Yes, Yes, No"), ("C", "Yes, No, No"), ("D", "No, Yes, No")]),
    (100, "Consideration of Internal Control", "When control risk is assessed at less than high level, the auditor should document his:\nUnderstanding of internal control components | Conclusion that control risk is at less than high level | Basis for concluding that control risk is at less than high level\nA. Yes | Yes | Yes\nB. Yes | Yes | No\nC. Yes | No | No\nD. No | Yes | No",
     [("A", "Yes, Yes, Yes"), ("B", "Yes, Yes, No"), ("C", "Yes, No, No"), ("D", "No, Yes, No")])
]

chapter07 = {
    "id": "at-07",
    "code": "AT-07",
    "title": "Study and Evaluation of Internal Controls",
    "description": "Nature and objectives of internal control, COSO/PSA 315 components (CRIME), control environment, risk assessment, control activities (APIPS), information and communication, monitoring, understanding and documenting controls, and tests of controls.",
    "objectives": [
        "Nature of Internal Control",
        "Components of Internal Control",
        "Consideration of Internal Control"
    ],
    "totalQuestions": 100,
    "questions": []
}

for num, obj, qtext, opts in at07_raw:
    correct = at07_answers[num]
    expl = at07_explanations.get(num, f"Suggested Answer: {correct}. In accordance with PSA 315 and PSA 330 (Tests of Controls and Evaluation of Internal Control).")
    chapter07["questions"].append({
        "id": f"at07-{num}",
        "number": num,
        "chapterId": "at-07",
        "chapterCode": "AT-07",
        "chapterTitle": "Study and Evaluation of Internal Controls",
        "objective": obj,
        "question": qtext,
        "options": [{"key": k, "text": t} for k, t in opts],
        "correctAnswer": correct,
        "explanation": expl
    })

with open("src/data/chapters/at07.ts", "w", encoding="utf-8") as f:
    f.write(f"import {{ Chapter }} from '../../types/quiz';\n\nexport const chapter07: Chapter = {json.dumps(chapter07, indent=2)};\n")

print("Created at07.ts with 100 questions")
